### ISSUE TITLE
使用本地gradle版本遇到了以下问题

### ISSUE THREAD

**Issue by helloyingying** [alibaba/freeline#10]
```
Exception in thread "main" java.io.FileNotFoundException: https://downloads.gradle.org/distributions/gradle-2.13.0-all.zip
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1836)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:61)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

[ERROR] --------------------------------------------------------
[ERROR] freeline failed when read project info with script: ./gradlew -q checkBeforeCleanBuild
[ERROR] --------------------------------------------------------
```

**Comment by lomanyong** [comment]
@helloyingying 这个是你本地gradle版本配置的问题吧？我直接url访问`https://downloads.gradle.org/distributions/gradle-2.13.0-all.zip`也是404的。麻烦检查一下本地配置文件`gradle/wrapper/gradle-wrapper.properties`是否正确配置吧~
