### ISSUE TITLE
ModuleNotFoundError: No module named 'build_commands'

### ISSUE THREAD

**Issue by joegana** [alibaba/freeline#1007]
python freeline.py
Traceback (most recent call last):
  File "freeline.py", line 7, in <module>
    from freeline_core.dispatcher import Dispatcher
  File "E:\Justin\git_work_repo\as_moorgen\as_moorgen_ui3\freeline_core\__init__.py", line 1, in <module>
    import build_commands
ModuleNotFoundError: No module named 'build_commands'

**Comment by xflcx1991** [comment]
换成python2.x
