### ISSUE TITLE
Install Freeline Automatically 时出现 java.lang.AssertionError 的错误

### ISSUE THREAD

**Issue by Jinni6012** [alibaba/freeline#1008]
通过插件安装的Freeline，AS 3.2.1
第一次运行时提示安装Freeline 在下一步时IDEA报出以下错误信息
请问该如何解决这个问题呢，JDK和Python的环境变量都已经配置好？

null
java.lang.AssertionError
at org.xmlpull.v1.XmlPullParserFactory.<init>(XmlPullParserFactory.java:43)
at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:221)
at com.antfortune.freeline.idea.models.GradleDependencyEntity.parse(GradleDependencyEntity.java:79)
at com.antfortune.freeline.idea.actions.UpdateAction$GetServerVersion.run(UpdateAction.java:189)
at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

**Comment by micadalee** [comment]
同样的问题，现在这个项目是没人维护了吗？

**Comment by ApolloXiao** [comment]
出现同样的错误
