### ISSUE TITLE
initFreeline failed

### ISSUE THREAD

**Issue by ArcherQi** [alibaba/freeline#1010]
未添加freeline, 项目正常编译运行； 第一次使用命令./gradlew initFreeline, 报错如下：

localhost:android_newcar qichunjie$ gradlew initFreeline -Pmirror
Downloading https://services.gradle.org/distributions/gradle-4.1-all.zip

Exception in thread "main" java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 400 Bad Request"
        at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2085)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:61)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

请问这是什么问题？ 看着像gradle下载连接失败， 但是g ra d le一直可以正常使用，本地也有4.1-all. 看着像代理问题， 但是关闭了所有代理还是这样， 感谢神们支持！

**Comment by dede1314** [comment]
这个不是freeline的问题，请先使用gradlew.bat assembleDebug 这个命令成功后再来使用freeline。
Freeline实际上是使用上述命令进行编译的。
