### ISSUE TITLE
freeline提示No module named 'build_commands'无法运行

### ISSUE THREAD

**Issue by CodeWorder-xu** [alibaba/freeline#1031]
网上搜的是python版本低,我的python版本是2.7.4,android Studio是3.0,这个是有什么问题吗

**Comment by CodeWorder-xu** [comment]
D:\jinyingjie\MyDemo>python freeline.py
Traceback (most recent call last):
  File "freeline.py", line 7, in <module>
    from freeline_core.dispatcher import Dispatcher
  File "D:\jinyingjie\MyDemo\freeline_core\__init__.py", line 1, in <module>
    import build_commands
ModuleNotFoundError: No module named 'build_commands'
