### ISSUE TITLE
1+手机/CM系统存在资源加载的兼容性问题

### ISSUE THREAD

**Issue by maclaylq** [alibaba/freeline#106]
第一次运行时ok的，虽然速度特别慢，修改代码，第二次执行python freeline.py，速度很快，但是手机启动的时候的直接就崩溃了，每次都是第二次会崩溃。
````
`09-08 11:29:51.533 15274-15274/cn.cnr.cloudfm E/System: java.util.zip.ZipException: Not a zip archive
                                                            at java.util.zip.ZipFile.readCentralDir(ZipFile.java:397)
                                                            at java.util.zip.ZipFile.<init>(ZipFile.java:175)
                                                            at java.util.zip.ZipFile.<init>(ZipFile.java:131)
                                                            at dalvik.system.DexPathList$Element.maybeInit(DexPathList.java:452)
                                                            at dalvik.system.DexPathList$Element.findResource(DexPathList.java:499)
                                                            at dalvik.system.DexPathList.findResources(DexPathList.java:378)
                                                            at dalvik.system.BaseDexClassLoader.findResources(BaseDexClassLoader.java:72)
                                                            at java.lang.ClassLoader.getResources(ClassLoader.java:425)
                                                            at org.jivesoftware.smack.SmackConfiguration.<clinit>(Unknown Source)
                                                            at org.jivesoftware.smack.SmackConfiguration.getVersion(Unknown Source)
                                                            at org.jivesoftware.smack.Connection.<clinit>(Unknown Source)
                                                            at org.jivesoftware.smack.Connection.addConnectionCreationListener(Unknown Source)
                                                            at org.jivesoftware.smackx.ServiceDiscoveryManager.<clinit>(Unknown Source)
                                                            at java.lang.Class.classForName(Native Method)
                                                            at java.lang.Class.forName(Class.java:324)
                                                            at com.easemob.chat.InitSmackStaticCode.initStaticCode(Unknown Source)
                                                            at com.easemob.chat.EMChat.init(Unknown Source)
                                                            at cn.cnr.cloudfm.lib.AnyRadioApplication.onCreate(AnyRadioApplication.java:137)
                                                            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                                            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4756)
                                                            at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                            at android.os.Looper.loop(Looper.java:148)
                                                            at android.app.ActivityThread.main(ActivityThread.java:5466)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`
````
错误的地方代码是EMChat.getInstance().init(mContext);

**Comment by lomanyong** [comment]
@maclaylq 测试机型的Android系统版本是多少的？

**Comment by maclaylq** [comment]
系统是6.0.1，编译的sdk版本是5.0

**Comment by lomanyong** [comment]
@maclaylq 机型是？

**Comment by maclaylq** [comment]
1+  1，系统是cm 的。

**Comment by charvenhe** [comment]
@maclaylq 换台机器也这样吗

**Comment by maclaylq** [comment]
刚试了nexus 5,原生6.0.1，是ok的，改点代码，第二次执行 5s搞定。是跟cm系统 有关系还是跟手机有关系？
[DEBUG] -------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 4.7s
[DEBUG] Total time: 5.0s
[DEBUG] -------------------------------------

**Comment by lomanyong** [comment]
@maclaylq 1+手机是自己刷的cm系统呢？还是自带的系统？

之前也遇见过1+手机上的资源crash的问题。

**Comment by maclaylq** [comment]
@lomanyong 是自己刷的

**Comment by maclaylq** [comment]
@lomanyong 你们测试比较稳定的机子是什么，准备推荐下这个给同事。

**Comment by lomanyong** [comment]
@maclaylq 目前已经有很多团队试用过，大部分机型都还蛮稳定的，我们自测时主要是模拟器 + Nexus 6P + 锤子..

1+ or CM 是目前已知的可能会存在增量资源加载导致crash

**Comment by maclaylq** [comment]
0.6.3在1+手机上没有问题。

**Comment by lomanyong** [comment]
@maclaylq 也是CM系统吗？
