### ISSUE TITLE
我先执行python freeline.py -f 然后随便找个类修改一点代码，在执行python freeline.py，报错

### ISSUE THREAD

**Issue by fearlesstrek** [alibaba/freeline#107]
````
[options] 未与 -source 1.7 一起设置引导类路径
/Users/Fearless/Downloads/svn/android-zingchat/NewsApp-MVP/app/src/main/java/com/mingjun/news/ui/module/news/NewsDetailActivity.java:6: 错误: 程序包android.support.annotation不存在
import android.support.annotation.NonNull;
                                 ^
/Users/Fearless/Downloads/svn/android-zingchat/NewsApp-MVP/app/src/main/java/com/mingjun/news/ui/module/news/NewsDetailActivity.java:19: 错误: 程序包butterknife不存在
import butterknife.BindView;
                  ^
/Users/Fearless/Downloads/svn/android-zingchat/NewsApp-MVP/app/src/main/java/com/mingjun/news/ui/module/news/NewsDetailActivity.java:20: 错误: 程序包butterknife不存在
import butterknife.ButterKnife;
                  ^
/Users/Fearless/Downloads/svn/android-zingchat/NewsApp-MVP/app/src/main/java/com/mingjun/news/ui/module/news/NewsDetailActivity.java:22: 错误: 无法访问AppCompatActivity
public class NewsDetailActivity extends MvpActivity implements LceView<NewsDetail> {
       ^
  找不到android.support.v7.app.AppCompatActivity的类文件
/Users/Fearless/Downloads/svn/android-zingchat/NewsApp-MVP/app/build/intermediates/classes/debug/com/mingjun/news/data/model/News.class: 警告: 无法找到类型 'SerializedName' 的注释方法 'value()': 找不到com.google.gson.annotations.SerializedName的类文件
/Users/Fearless/Downloads/svn/android-zingchat/NewsApp-MVP/app/src/main/java/com/mingjun/news/ui/module/news/NewsDetailActivity.java:24: 错误: 找不到符号
    @BindView(R.id.web_view)
     ^
  符号:   类 BindView
  位置: 类 NewsDetailActivity
/Users/Fearless/Downloads/svn/android-zingchat/NewsApp-MVP/app/src/main/java/com/mingjun/news/ui/module/news/NewsDetailActivity.java:47: 错误: 找不到符号
    @NonNull
     ^
  符号:   类 NonNull
  位置: 类 NewsDetailActivity

[ERROR] --------------------------------------------------------
[ERROR] incremental javac compile failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 1.0s
[DEBUG] Total time: 1.2s
[DEBUG] --------------------------------------------------------
````

**Comment by lomanyong** [comment]
@fearlesstrek 可以检查下`${main_module}/build/freeline/jar_dependencies.json`这个文件是否存在，以及里面的内容是否正确。

**Comment by fearlesstrek** [comment]
@lomanyong 怎么确定是否正确，文件是存在的

**Comment by lomanyong** [comment]
@fearlesstrek 文件是否有内容？

**Comment by BlackMagicHappy** [comment]
@fearlesstrek @lomanyong 我也遇到这个问题，随便改了一点代码，就编译不过：
报一些类型找不到，但是用python freeline.py -f脚本是可以的。

${main_module}/build/freeline/jar_dependencies.json没有这个文件。

.json的文件只有：project_info_cache.json

**Comment by lomanyong** [comment]
@BlackMagicHappy 这个问题你的`build.gradle`中，是否设置了`hack true`呢？

如果还有问题的话，即`jar_dependencies.json`这个文件找不到，可以terminal手动执行一下`./gradlew assembleDebug --PfreelineBuild=true`，然后将日志贴出来看下。

**Comment by BlackMagicHappy** [comment]
@lomanyong
build.gradle里已经设置了hack true
android {
      *******
      freeline {
        hack true
    }
}

________________________________________________________________________

执行gradlew assembleDebug --PfreelineBuild=true的结果如下:
F:\17.MusicClient\Android\Music\MusicUI\Music>gradlew assembleDebug --PfreelineBuild=true
find variant debug start hack process...                                                         
variant release is not debug, skip hack process.
                            
FAILURE: Build failed with an exception.
                            
* What went wrong:          
Problem configuring task :Music:assembleDebug from command line.
> Unknown command-line option '--PfreelineBuild'.
                            
* Try:                      
Run gradlew help --task :Music:assembleDebug to get task usage details. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
                            
BUILD FAILED                
                            
Total time: 5.573 secs

**Comment by lomanyong** [comment]
@BlackMagicHappy 我的错..打错了命令`./gradlew assembleDebug -PfreelineBuild=true`

**Comment by BlackMagicHappy** [comment]
@lomanyong 还是报错啊：

————————————————————————————————————————————
:MusicUI_MTN:hackClassesBeforeDexDebug FAILED          
              
FAILURE: Build failed with an exception.
              
* What went wrong:
Execution failed for task ':Music:hackClassesBeforeDexDebug'.
> Illegal/unsupported escape sequence near index 3
  .*\R\$?\w*.class
     ^        
              
* Try:        
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
              
BUILD FAILED  
              
Total time: 29.974 secs

**Comment by lomanyong** [comment]
@BlackMagicHappy 找到原因了，在你们工程上全量打包应该没有成功。可以执行`gradlew assembleDebug -PfreelineBuild=true --stacktrace`，然后贴出stacktrace来看下报错的地方在哪里。

**Comment by BlackMagicHappy** [comment]
@lomanyong 我采用python freeline.py -f全量编译是可以的呢。

运行脚本gradlew assembleDebug -PfreelineBuild=true --stacktrace确实报错：

————————————————————————————————————————————
* What went wrong:
Execution failed for task ':Music:hackClassesBeforeDexDebug'.
> Illegal/unsupported escape sequence near index 3
  .*\R\$?\w*.class
     ^        
              
* Try:        
Run with --info or --debug option to get more log output.
              
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':MusicUI_MTN:hackClassesBeforeDexDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 3
.*\R\$?\w*.class
   ^          
        at com.antfortune.freeline.FreelinePlugin.isNeedBackUp(FreelinePlugin.groovy:341)
        at com.antfortune.freeline.FreelinePlugin.backUpClass(FreelinePlugin.groovy:332)
        at com.antfortune.freeline.FreelinePlugin$_apply_closure3_closure7_closure17_closure22_closure23.doCall(FreelinePlugin.groovy:195)
        at com.antfortune.freeline.FreelinePlugin$_apply_closure3_closure7_closure17_closure22.doCall(FreelinePlugin.groovy:194)
        at com.antfortune.freeline.FreelinePlugin$_apply_closure3_closure7_closure17.doCall(FreelinePlugin.groovy:192)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 60 more
              
              
BUILD FAILED  
              
Total time: 13.817 secs

**Comment by lomanyong** [comment]
@BlackMagicHappy 这个应该是正则在win上的bug，我今天一并修复，多谢case~这个问题导致了你没有看到`jar_dependencies.json`这个文件。

**Comment by BlackMagicHappy** [comment]
@lomanyong 不用谢，非常感谢你的开源精神以及耐心的指导，对于Freeline我是很想把它用起来，并在身边推广起来，期待你们更加完善的版本。

**Comment by BlackMagicHappy** [comment]
@lomanyong 我现在连之前的python freeline.py -f 都跑不起来了，之前还是能跑起来的，这个要怎么修改呢？

**Comment by lomanyong** [comment]
@BlackMagicHappy 使用这个版本的gradle插件试试看`com.antfortune.freeline:gradle:0.6.1.1609091648`

替换插件版本即可，其他不用修改，直接用freeline重新打包。

**Comment by BlackMagicHappy** [comment]
@lomanyong 我这边可以跑起来了。

**Comment by lomanyong** [comment]
@BlackMagicHappy  `jar_dependencies.json`这个文件不是保存你修改的文件的，里面主要是你的工程依赖的jar包。你可以看下是否正确。

以及，你描述的现象我不是很清楚，是`python freeline.py -f`打包后，你的修改没有进入？

**Comment by BlackMagicHappy** [comment]
@lomanyong 里面的依赖都是正确的，那这样的话jar_dependencies.json文件就没有问题了。
gradlew assembleDebug -PfreelineBuild=true --stacktrace这个运行也没有问题了。

目前的问题：我修改了某个文件的日志输出，例如：本来应该输出：aaa, 我改成了：bbb.
然后运行python freeline.py，程序也起来了，但是打印的日志还是aaa,好像我的修改没有体现出来。

**Comment by lomanyong** [comment]
@BlackMagicHappy 你修改的这个类是否在Application类中有引用呢？如果有引用的话，有可能会出现改动不生效的情况

**Comment by BlackMagicHappy** [comment]
@lomanyong 我检查了一下，我修改的类在Application类中没有引用啊

**Comment by lomanyong** [comment]
@BlackMagicHappy 改任何的Java类都不会生效吗？在几个页面加个Toast，弹出信息看看呢？

**Comment by BlackMagicHappy** [comment]
@lomanyong 我试了修改按钮的标题，是可以生效的，修改日志是不行的。我的问题算是解决了。但是Instant Run无论修改资源文件还是修改日志内容都是可以的。

**Comment by lomanyong** [comment]
@BlackMagicHappy 修改日志是指修改`Log.x(TAG, message);`类似这样的代码吗？这里有final或者abstract之类的特殊修饰吗？

**Comment by BlackMagicHappy** [comment]
@lomanyong 就是Log的日志，在控制台打印的，日志里的内容是写死的String，不涉及final或者abstract啊。

**Comment by lomanyong** [comment]
@BlackMagicHappy get，我们这边也试试看，有点奇怪的现象，修改string啥的我们也试过挺多的，还没发现这个问题。

**Comment by lomanyong** [comment]
@fearlesstrek `jar_dependencies.json`这个文件应该包含了你所有的jar包依赖，可以看是是否有，或者是一个空文件？

**Comment by renxiaoys1** [comment]
我的mac本，出现的问题同楼主一致，到现在也没有解决

**Comment by Guangxingtianxia** [comment]
Please make sure your application is properly running in your device.
        Check follow steps:
        1. Make sure the versions `python freeline.py -v`, freeline-gradle and freeline-runtime are the same;
        2. Make sure there is no network proxy.


這是因爲啥啊？

**Comment by Guangxingtianxia** [comment]
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':zhou_test_v25:transformClassesWithMultidexlistForDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.NoSuchMethodError: proguard.KeepClassSpecification.<init>(ZZZZZZLproguard/ClassSpecification;)V
        at com.android.build.gradle.internal.transforms.BaseProguardAction.keep(BaseProguardAction.java:75)
        at com.android.build.gradle.internal.transforms.MultiDexTransform.shrinkWithProguard(MultiDexTransform.java:223)
        at com.android.build.gradle.internal.transforms.MultiDexTransform.transform(MultiDexTransform.java:185)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:178)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:174)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:173)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more


[ERROR] --------------------------------------------------------
[ERROR] build failed with script: gradlew.bat :zhou_test_v25:assembleDebug -P freelineBuild=true --stacktrace
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 164.3s
[DEBUG] Total time: 164.5s
[DEBUG] --------------------------------------------------------


試了好多次，一直是這個bug。。。。是混淆的原因嗎？ 我現在是debug版本啊！
