### ISSUE TITLE
清除缓存app崩溃

### ISSUE THREAD

**Issue by qsyj** [alibaba/freeline#118]
当清理app的缓存时，app就崩溃，而且无法再次打开！应该是你们这插件在缓存中存放了东西吧，运行是找不到，就会崩溃！

**Comment by lomanyong** [comment]
@qsyj 可以贴一下crash的日志吗？

**Comment by qsyj** [comment]
@lomanyong 
不是每次都会!
具体操作:
1.第一安装freeline.py -f 
2.打开app缓存界面!
3.修改项目代码
4:执行freeline.py,发现app缓存一下增加到40M
5.清理缓存,成功(这时候不会崩溃),界面返回,当至首页界面时就崩溃
日志:
java.lang.IllegalStateException: java.lang.IllegalStateException: Could not create new AssetManager
at com.antfortune.freeline.resources.MonkeyPatcher.monkeyPatchExistingResources(MonkeyPatcher.java:394)
at com.antfortune.freeline.gradle.GradleDynamic.applyDynamicRes(GradleDynamic.java:32)
at com.antfortune.freeline.FreelineCore.applyDynamicRes(FreelineCore.java:304)
at com.antfortune.freeline.FreelineCore.injectResources(FreelineCore.java:248)
at com.antfortune.freeline.FreelineCore.init(FreelineCore.java:84)
at com.antfortune.freeline.FreelineCore.init(FreelineCore.java:58)
at cn.msh.mobilebank.android.user.u.BaseApplication.onCreate(BaseApplication.java:72)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
at android.app.ActivityThread.-wrap1(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalStateException: Could not create new AssetManager
at com.antfortune.freeline.resources.MonkeyPatcher.monkeyPatchExistingResources(MonkeyPatcher.java:286)
at com.antfortune.freeline.gradle.GradleDynamic.applyDynamicRes(GradleDynamic.java:32) 
at com.antfortune.freeline.FreelineCore.applyDynamicRes(FreelineCore.java:304) 
at com.antfortune.freeline.FreelineCore.injectResources(FreelineCore.java:248) 
at com.antfortune.freeline.FreelineCore.init(FreelineCore.java:84) 
at cn.msh.mobilebank.android.user.u.BaseApplication.onCreate(BaseApplication.java:72) 
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013) 
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707) 
at android.app.ActivityThread.-wrap1(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:148) 
at android.app.ActivityThread.main(ActivityThread.java:5417) 

6.无法再次打开app,会崩溃
日志:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.res.Resources.getBoolean(int)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.res.Resources.getBoolean(int)' on a null object reference
at android.view.Window.getDefaultFeatures(Window.java:1337)
at android.view.Window.<init>(Window.java:480)
at com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:305)
at android.app.Activity.attach(Activity.java:6179)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2350)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
at android.app.ActivityThread.-wrap11(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:148) 
at android.app.ActivityThread.main(ActivityThread.java:5417) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by lomanyong** [comment]
@qsyj 收到，我会排查这个问题，感谢提供case与日志。

**Comment by charvenhe** [comment]
@qsyj 清空缓存，是相当于把freeline的增量数据全部清空，会出现异常是正常的，这种操作freeline无法支撑哈
