### ISSUE TITLE
freeline编译出错，导致每次都全量编译

### ISSUE THREAD

**Issue by hexi** [alibaba/freeline#140]
````
Traceback (most recent call last):
  File "/Users/hexi/Documents/AndroidStudioProjects/android/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/Users/hexi/Documents/AndroidStudioProjects/android/freeline/freeline_core/gradle_tools.py", line 566, in execute
    self.run_aapt()
  File "/Users/hexi/Documents/AndroidStudioProjects/android/freeline/freeline_core/gradle_tools.py", line 585, in run_aapt
    '-M', fix_package_name(self._config, self._finder.get_dst_manifest_path())]
  File "/Users/hexi/Documents/AndroidStudioProjects/android/freeline/freeline_core/gradle_tools.py", line 666, in fix_package_name
    if config and config['package'] != config['debug_package']:
KeyError: 'debug_package'
````

**Comment by lomanyong** [comment]
@hexi `python freeline.py -v`版本是多少的？如果比较低的话，可以升级一下，`./gradlew initFreeline -Pmirror`

**Comment by krmao** [comment]
没有解决该问题

**Comment by junyuecao** [comment]
0.8.2 依然有问题

**Comment by lomanyong** [comment]
@krmao @junyuecao 提示同样的报错？

**Comment by junyuecao** [comment]
是的，完全一样堆栈信息

**Comment by lomanyong** [comment]
@junyuecao 确定使用的是最新版本吗...`KeyError: 'debug_package'`是一个默认都有的key...一般不会出现key_error的问题...
