### ISSUE TITLE
gradle deamon进程常驻，静态的sBackupMap导致多工程编译失败

### ISSUE THREAD

**Issue by tbruceyu** [alibaba/freeline#142]
![wechatimg2](https://cloud.githubusercontent.com/assets/1342575/18623495/6756355e-7e70-11e6-8c76-38e48959ea27.jpeg)
这个地方的sBackupMap定义为了static类型，导致在Gradle deamon启动的情况下，前一次编译的backup结果依然存在。

````
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:assembleDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.io.FileNotFoundException: /Users/yutao/Projects/works/everphoto_backup/app/build/freeline/freeline-backup/1474256212973 (No such file or directory)
        at com.antfortune.freeline.FreelineUtils.copyFile(FreelineUtils.groovy:129)
        at com.antfortune.freeline.FreelineUtils$copyFile$10.call(Unknown Source)
        at com.antfortune.freeline.FreelinePlugin$_rollBackClasses_closure7.doCall(FreelinePlugin.groovy:358)
        at com.antfortune.freeline.FreelinePlugin.rollBackClasses(FreelinePlugin.groovy:357)
        at com.antfortune.freeline.FreelinePlugin$_apply_closure4_closure8_closure19.doCall(FreelinePlugin.groovy:233)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:590)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:571)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more


BUILD FAILED

Total time: 1 mins 29.919 secs
````

**Comment by lomanyong** [comment]
@tbruceyu 已做修改，下个升级版本解决~
