### ISSUE TITLE
Freeline "try to connect device/ connect_device_task failed." 排查方法

### ISSUE THREAD

**Issue by lomanyong** [alibaba/freeline#152]
排查方法如下：

1. 确定`FreelineCore.init(this);`加入到Application类中，且在`onCreate()`下的第一行，不要根据是否在主进程做特殊处理，否则可能导致`FreelineService`无法正常启动；
2. 确定`FreelineService`以及freeline相关组件是否正常merge到最终的minifest中，最终的manifest路径在`${module}/build/intermediates/manifests`中；
3. 确定`python freeline.py -v`与定义在build.gradle中的freeline的版本是否一致；
4. 确定是否刚刚执行了清空app数据的操作，freeline缓存数据在`/data/data`路径，清空app数据也会导致连接不上的问题；
5. 确定是否开启了网络代理导致`127.0.0.1`被重定向？

当上述问题都无法解决时，有个终极的解决方案就是**重启试试**...不少人通过重启顺利解决连接不上的问题。。。

后续会通过自动化的方式，尽量避免手工排查上述问题。有遇见相关的问题可以具体描述一下，在issue中进行回复，可以帮忙排查。

**Comment by moonljt521** [comment]
我的只是偶尔能运行成功，错误的时候日志：
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
	Please make sure your application is properly running in your device.
	Check follow steps:
	1. Make sure the versions `python freeline.py -v`, freeline-gradle and freeline-runtime are the same;
	2. Make sure there is no network proxy.
	3.
	More about this can see: https://github.com/alibaba/freeline/issues/152
[ERROR] --------------------------------------------------------
[ERROR] Freeline server in app “包名” not found. Please make sure your application is properly running in your device.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.5s
[DEBUG] Task engine running time: 16.7s
[DEBUG] Total time: 17.1s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@moonljt521 需要先执行`python freeline.py -f`打全量包安装到设备上，再使用`python freeline.py`来增量编译。而不是使用android-studio的run，不知是否是这个问题产生的？

以及，issue里提到的那几条是否检查过了呢？

**Comment by moonljt521** [comment]
@lomanyong    按您的方式全量和增量编译了， as的freeline 控制台没有报错
不过logcat 报错
java.lang.ClassCastException: com.antfortune.freeline.FreelineApplication cannot be cast to 我的app包名.CrmApp

导致app无法启动

**Comment by lomanyong** [comment]
@moonljt521 参考一下#159 这个issue可以解决你的问题。

**Comment by moonljt521** [comment]
@lomanyong   谢谢回复， #159 么有解决我的问题~

**Comment by lomanyong** [comment]
@moonljt521 没有解决？

**Comment by moonljt521** [comment]
@lomanyong  嗯呢   按照159那条做了配置  仍然是application 类型转换异常

**Comment by lomanyong** [comment]
@moonljt521 先`clean`，然后再重新打包...manifest估计还是旧的，所以问题仍然存在。

**Comment by moonljt521** [comment]
@lomanyong  你好，我把配置流程重新做了一遍，现在成功了，除了第一次python.py 需要一分钟外，再次修改都是一两秒就编译好了，多谢

**Comment by ifaint** [comment]
我现在用的是0.7.3.1(不过其他更新的版本一样有这个问题)。全量可以，如果希望增量，则会报如下错误。之前一直可以，然后就不行了。

[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
        Please make sure your application is properly running in your device.
        Check follow steps:
        1. Make sure the versions `python freeline.py -v`, freeline-gradle and freeline-runtime are the same;
        2. Make sure there is no network proxy.
        3.
        More about this can see: https://github.com/alibaba/freeline/issues/152
[ERROR] -------------


日志反复打印如下：
freeline D/Freeline.LongLinkServer: Freeline.increment server is already running
freeline I/Freeline.Service: onStartCommand Received start id 11, intent: Intent。。。

**Comment by lomanyong** [comment]
@ifaint 尝试把手机上的 apk 卸载了，然后重新安装试试看

**Comment by ManbasJi** [comment]
按照上面的操作后还是会出现这个问题
 build failed with script: gradlew.bat :app:assembleDebug -P freelineBuild=true --stacktrace

**Comment by lomanyong** [comment]
@ManbasJi `build failed with script: gradlew.bat :app:assembleDebug -P freelineBuild=true --stacktrace`出现这个错误就是编译出错了，不是这个问题....往上看看日志，会提示你出错在哪里...

**Comment by ManbasJi** [comment]
在上面出现了这个
是代码的问题吗
inject: E:\ASproject\TaoDuoDuo\app\build\intermediates\classes\debug\com\qunyu\taoduoduo\mvpview\ZoneView.class
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:167)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:191)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:522)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:344)
        at com.android.dx.command.dexer.Main.run(Main.java:292)
        at com.android.builder.internal.compiler.DexWrapper.run(DexWrapper.java:54)
        at com.android.builder.core.DexByteCodeConverter.lambda$dexInProcess$0(DexByteCodeConverter.java:173)

**Comment by lomanyong** [comment]
@ManbasJi 恩，就是正常的 gradle 编译出错...按照平时解决 gradle 编译出错的方法去解决就行了...

**Comment by ManbasJi** [comment]
好的，谢谢

**Comment by ifaint** [comment]
@lomanyong 删除app之后，-f来一次，然后增量还是一样的结果,日志也一样还是那两行。。。

**Comment by lomanyong** [comment]
@ifaint 上面提到的方法麻烦再检查一下，以及电脑上不要同时连接多台设备，或者连接一台设备 + 模拟器...

**Comment by ifaint** [comment]
Make sure the versions `python freeline.py -v`, freeline-gradle and freeline-runtime are the same;

请问如何检查freeline-gradle 和freeline-runtime? 我在mac上，build.gradle配置的版本和`python freeline.py -v`得到的版本号是一致的

**Comment by lomanyong** [comment]
@ifaint runtime 现在不需要检查了...版本默认跟你的 freeline gradle 插件是一致的..

**Comment by WJRye** [comment]
我的第一次运行能够连接设备且提示安装应用程序，但第二次运行就连接不上设备了（上面的都排查了）。日志如下：
[DEBUG] [sync_client] try to connect device 1 times...
[DEBUG] [sync_client] wake up Service: D:\SDK\sdk\platform-tools\adb.exe shell a
m startservice -n com.youku.phone/com.antfortune.freeline.FreelineService -e wak
eup marker
[DEBUG] [Youku_Mobile] Youku_Mobile finish in 6.5s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 6.5s
[DEBUG] [merge_dex_task] just 1 dex need to sync, copy D:\SDK\workplace\YouKu\Yo
uku_Mobile\build\freeline\Youku_Mobile\dex\classes.dex to D:\SDK\workplace\YouKu
\Youku_Mobile\build\freeline\freeline-dexes\merged.dex
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s
[DEBUG] [sync_client] try to connect device 2 times...
[DEBUG] [sync_client] wake up Service: D:\SDK\sdk\platform-tools\adb.exe shell a
m startservice -n com.youku.phone/com.antfortune.freeline.FreelineService -e wak
eup marker
[DEBUG] [sync_client] try to connect device 3 times...
[DEBUG] [sync_client] wake up Service: D:\SDK\sdk\platform-tools\adb.exe shell a
m startservice -n com.youku.phone/com.antfortune.freeline.FreelineService -e wak
eup marker
[DEBUG] [sync_client] try to connect device 4 times...
[DEBUG] [sync_client] wake up Service: D:\SDK\sdk\platform-tools\adb.exe shell a
m startservice -n com.youku.phone/com.antfortune.freeline.FreelineService -e wak
eup marker
[DEBUG] [sync_client] try to connect device 5 times...
[DEBUG] [sync_client] wake up Service: D:\SDK\sdk\platform-tools\adb.exe shell a
m startservice -n com.youku.phone/com.antfortune.freeline.FreelineService -e wak
eup marker
[DEBUG] [sync_client] try to connect device 6 times...
[DEBUG] [sync_client] wake up Service: D:\SDK\sdk\platform-tools\adb.exe shell a
m startservice -n com.youku.phone/com.antfortune.freeline.FreelineService -e wak
eup marker
[DEBUG] [sync_client] try to connect device 7 times...
[DEBUG] [sync_client] wake up Service: D:\SDK\sdk\platform-tools\adb.exe shell a
m startservice -n com.youku.phone/com.antfortune.freeline.FreelineService -e wak
eup marker
[DEBUG] [sync_client] try to connect device 8 times...
[DEBUG] [sync_client] wake up Service: D:\SDK\sdk\platform-tools\adb.exe shell a
m startservice -n com.youku.phone/com.antfortune.freeline.FreelineService -e wak
eup marker
[DEBUG] [sync_client] try to connect device 9 times...
[DEBUG] [sync_client] wake up Service: D:\SDK\sdk\platform-tools\adb.exe shell a
m startservice -n com.youku.phone/com.antfortune.freeline.FreelineService -e wak
eup marker
[DEBUG] [sync_client] try to connect device 10 times...

[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
        Please make sure your application is properly running in your device.
        Check follow steps:
        1. Make sure the versions `python freeline.py -v`, freeline-gradle and f
reeline-runtime are the same;
        2. Make sure there is no network proxy.

        More about this can see: https://github.com/alibaba/freeline/issues/152
[ERROR] --------------------------------------------------------

**Comment by WJRye** [comment]
我的第一次能够连接上设备且提示安装应用程序，但第二次就连接不上了（上面的都排查了）。

**Comment by bjzhou** [comment]
换手机的时候会出现这情况，希望能够自动执行python freeline.py -f

**Comment by zigang** [comment]
只有第一次python freeline.py -f可以连上设备
以后执行python freeline.py就一直提示 [sync_client] try to connect device 10 times...
最后出错，无法连接设备，请问这是怎么回事呢？

**Comment by Dragon-Boat** [comment]
> 确定python freeline.py -v与定义在build.gradle中的freeline的版本是否一致；
定义版本是0.8.4，python freeline -v 是0.8.3 这个怎么处理

**Comment by lomanyong** [comment]
@Dragon-Boat 升级一下版本，执行`gradlew initFreeline -Pmirror`

**Comment by lomanyong** [comment]
@zigang 对照一下上面的方案先检查一下...

**Comment by Dragon-Boat** [comment]
@lomanyong ok，另外就算版本不同，运行也没问题。目前macOS和window均已成功；
希望：某些情况下，自动执行-f 全量编译；
偶尔更新代码增量编译后（如pull代码），会出现一些布局文件xml不能正确inflate的错误；全量编译后又正常。

**Comment by lomanyong** [comment]
@Dragon-Boat 目前其实是有自动全量的，比如说你修改了 build.gradle 或者修改了 AndroidManifest.xml 的情况。在你有超过 20 个文件的改动（通常是 pull 代码的时候），也会自动执行全量编译...

**Comment by ifaint** [comment]
@lomanyong 发现有些手机用不了。我用的moto x style可以。而用的一款华为和小米，就总是不行，运行不起来，提示找不到Application类，这个有办法吗？

**Comment by lomanyong** [comment]
@ifaint 找不到 application 类的情况可以参考 #273 做下改造

**Comment by ligongzixing** [comment]
请问freeLine可以用来跑单元测试吗？还有我发现不能将一个Project下的两个应用同时配置成freeline,会出现initFreeline as a task with that name already exists.

**Comment by ligongzixing** [comment]
请问freeLine可以用来运行单元测试吗？还有我发现不能将一个Project下的两个应用同时配置成freeline,会出现initFreeline as a task with that name already exists.

**Comment by OOM9527** [comment]
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
nothing matches overlay file push.png, for flavor xhdpi-v4
nothing matches overlay file push.png, for flavor xxhdpi-v4
Freeline trace:: makeFileResources all resource. Time Elapsed: 3745.255000 ms 
Freeline trace:: compile values. Time Elapsed: 429.150000 ms 
Freeline trace:: makeFileResources for color and menu. Time Elapsed: 0.554000 ms 

-ignore-ids = avd_hide_password_1:avd_hide_password_2:avd_hide_password_3:avd_show_password_1:avd_show_password_2:avd_show_password_3
Freeline trace:: custom package NULL
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
warning: overwriting '/Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.antfortune.freeline/runtime/0.8.5/assets/apktime' with '/Users/Mac/bihu_android/app/build/freeline/freeline-assets/apktime'
/Users/Mac/bihu_android/app/build/freeline/app/backup/res/values/freeline_id_keeper_public.xml:4793: error: Public symbol string/build_id declared here is not defined.

[ERROR] --------------------------------------------------------
[ERROR] build base resources failed with: freeline/release-tools/FreelineAapt package -f -I /Users/Mac/Library/Android/sdk/platforms/android-24/android.jar -M /Users/Mac/bihu_android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /Users/Mac/bihu_android/app/build/freeline/freeline-databinding/app/a276559c072f2e694566c824a8fb1bd1/res -S /Users/Mac/bihu_android/app/build/freeline/freeline-databinding/app/09b69e7b6c3f0ad805858a4be7074f89/res -S /Users/Mac/bihu_android/app/build/freeline/freeline-databinding/app/88fdbdf735a2d038848bdd59c14ab90b/res -S /Users/Mac/bihu_android/app/build/freeline/freeline-databinding/app/21a6523ff4746d610cf772e4f07a267c/res -S /Users/Mac/bihu_android/app/build/freeline/freeline-databinding/app/e165344673e5380b933d08c88c5e77c3/res -S /Users/Mac/bihu_android/weixin/src/main/res -S /Users/Mac/bihu_android/multiimageselector/res -S /Users/Mac/bihu_android/app/build/generated/res/rs/debug -S /Users/Mac/bihu_android/app/build/generated/res/resValues/debug -S /Users/Mac/bihu_android/location/src/main/res -S /Users/Mac/bihu_android/common/res -S /Users/Mac/bihu_android/common/res-datetimepicker -S /Users/Mac/bihu_android/umeng/src/main/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.squareup.leakcanary/leakcanary-android-no-op/1.4-beta2/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.antfortune.freeline/runtime/0.8.5/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/support-compat/24.2.1/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/support-core-utils/24.2.1/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/support-core-ui/24.2.1/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/support-media-compat/24.2.1/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/support-fragment/24.2.1/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/support-v4/24.2.1/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.databinding/library/1.2.1/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.databinding/adapters/1.2.1/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.github.captain-miao/autofittextview/0.2.2/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.github.captain-miao/optroundcardview/1.0.0/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.github.captain-miao/multisizetextview/1.0.0/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/24.2.1/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.github.captain-miao/recyclerviewutils/1.2.5/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.soundcloud.android/android-crop/1.0.1/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/de.hdodenhof/circleimageview/2.1.0/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/support-vector-drawable/24.2.1/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/animated-vector-drawable/24.2.1/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/24.2.1/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.github.jd-alexander/LikeButton/0.2.0/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.daimajia.easing/library/1.0.1/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.google.android.agera/agera/1.1.0/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/cardview-v7/24.2.1/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.github.captain-miao/MaterialSpinner/1.1.3-SNAPSHOT/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.getui/ext/2.0.3/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.getui/sdk/2.9.0.0/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/fr.avianey.com.viewpagerindicator/library/2.4.1/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/support-v13/24.2.1/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.github.captain-miao/chinacitypicker/1.0.0/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.squareup.picasso/picasso/2.6.0-SNAPSHOT/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/multidex/1.0.1/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.tencent.bugly/nativecrashreport/3.1.2/res -S /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.tencent.bugly/crashreport_upgrade/1.2.2.0/res -S /Users/Mac/bihu_android/app/build/freeline/app/backup/res -A /Users/Mac/bihu_android/app/build/freeline/freeline-assets -A /Users/Mac/bihu_android/app/assets -A /Users/Mac/bihu_android/app/build/generated/assets/shaders/debug -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.squareup.leakcanary/leakcanary-android-no-op/1.4-beta2/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.antfortune.freeline/runtime/0.8.5/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/support-compat/24.2.1/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/support-core-utils/24.2.1/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/support-core-ui/24.2.1/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/support-media-compat/24.2.1/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/support-fragment/24.2.1/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/support-v4/24.2.1/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.databinding/library/1.2.1/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.databinding/adapters/1.2.1/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.github.captain-miao/autofittextview/0.2.2/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.github.captain-miao/optroundcardview/1.0.0/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.github.captain-miao/multisizetextview/1.0.0/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/24.2.1/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.github.captain-miao/recyclerviewutils/1.2.5/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.soundcloud.android/android-crop/1.0.1/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/de.hdodenhof/circleimageview/2.1.0/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/support-vector-drawable/24.2.1/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/animated-vector-drawable/24.2.1/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/24.2.1/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.github.jd-alexander/LikeButton/0.2.0/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.daimajia.easing/library/1.0.1/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.google.android.agera/agera/1.1.0/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/cardview-v7/24.2.1/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.github.captain-miao/MaterialSpinner/1.1.3-SNAPSHOT/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.getui/ext/2.0.3/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.getui/sdk/2.9.0.0/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/support-v13/24.2.1/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.github.captain-miao/chinacitypicker/1.0.0/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.squareup.picasso/picasso/2.6.0-SNAPSHOT/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.android.support/multidex/1.0.1/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.tencent.bugly/nativecrashreport/3.1.2/assets -A /Users/Mac/bihu_android/app/build/intermediates/exploded-aar/com.tencent.bugly/crashreport_upgrade/1.2.2.0/assets -m -J /Users/Mac/bihu_android/app/build/freeline/app/backup --auto-add-overlay -F /Users/Mac/bihu_android/app/build/freeline/base-res.so --debug-mode --no-version-vectors --resoucres-md5-cache-path /Users/Mac/bihu_android/app/build/freeline/arsc_cache.dat --ignore-assets public_id.xml:public.xml:*.bak:.* --ignore-ids avd_hide_password_1:avd_hide_password_2:avd_hide_password_3:avd_show_password_1:avd_show_password_2:avd_show_password_3
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.4s
[DEBUG] Task engine running time: 106.5s
[DEBUG] Total time: 106.9s
[DEBUG] --------------------------------------------------------


请问一下,这个问题该如何解决呢?

**Comment by jk2K** [comment]
我 `Clean Project` 后，再运行 freeline 就可以了

**Comment by 704480904** [comment]
Freeline 的時候 ，安裝上去之後，白屏的  ,版本號是0.8.6

**Comment by lizheng98** [comment]
目前使用0.8.7版本
freeline全量编译是每次都可以正常安装；但是增量编译就报错。

错误日志如下：
[DEBUG] [sync_client] try to connect device 1 times...
[DEBUG] [sync_client] wake up Service: d:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe shell am startservice -n com.guojiang.meitu.boys/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 2 times...
[DEBUG] [sync_client] wake up Service: d:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe shell am startservice -n com.guojiang.meitu.boys/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 3 times...
[DEBUG] [sync_client] wake up Service: d:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe shell am startservice -n com.guojiang.meitu.boys/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 4 times...
[DEBUG] [sync_client] wake up Service: d:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe shell am startservice -n com.guojiang.meitu.boys/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 5 times...
[DEBUG] [sync_client] wake up Service: d:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe shell am startservice -n com.guojiang.meitu.boys/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 6 times...
[DEBUG] [sync_client] wake up Service: d:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe shell am startservice -n com.guojiang.meitu.boys/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 7 times...
[DEBUG] [sync_client] wake up Service: d:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe shell am startservice -n com.guojiang.meitu.boys/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 8 times...
[DEBUG] [sync_client] wake up Service: d:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe shell am startservice -n com.guojiang.meitu.boys/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 9 times...
[DEBUG] [sync_client] wake up Service: d:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe shell am startservice -n com.guojiang.meitu.boys/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 10 times...
[DEBUG] [sync_client] Freeline server in app com.guojiang.meitu.boys not found. Please make sure your application is properly running in your device.
[DEBUG] [connect_device_task] connect_device_task finish in 16.9s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 16.9s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 16.9s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 16.9s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 16.93s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
        Please make sure your application is properly running in your device.
        Check follow steps:
        1. Make sure the versions `python freeline.py -v`, freeline-gradle and freeline-runtime are the same;
        2. Make sure there is no network proxy.

        More about this can see: https://github.com/alibaba/freeline/issues/152
[ERROR] --------------------------------------------------------
[ERROR] Freeline server in app com.guojiang.meitu.boys not found. Please make sure your application is properly running in your device.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 16.9s
[DEBUG] Total time: 17.2s
[DEBUG] --------------------------------------------------------


已做了以下排查：
1、确定python freeline.py -v与定义在build.gradle中的freeline的版本一致
2、执行gradlew initFreeline -Pmirror
3、卸载手机上应用，重新全量打包，再增量打包还是出错
4、“”确定FreelineService以及freeline相关组件是否正常merge到最终的minifest中，最终的manifest路径在${module}/build/intermediates/manifests中”  这个怎么检查？

**Comment by moonljt521** [comment]
因为问题多多，暂时放弃了使用，回归instant run~

**Comment by alonelyshepherd** [comment]
> 确定FreelineService以及freeline相关组件是否正常merge到最终的minifest中，最终的manifest路径在${module}/build/intermediates/manifests中；

现在确认是这个原因，请问如何解决呢？

**Comment by yahier** [comment]
第一次可以运行，然后修改两个文件，再运行就出现这个错误了 
Please make sure your application is properly running in your device.
        Check follow steps:
        1. Make sure the versions `python freeline.py -v`, freeline-gradle and freeline-runtime are the same;
        2. Make sure there is no network proxy.

**Comment by z447924375** [comment]
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------

Error: Unable to access jarfile freeline\release-tools\databinding-cli8.jar

[ERROR] --------------------------------------------------------
[ERROR] process module databinding failed: java -jar freeline\release-tools\databinding-cli8.jar -p com.hubert.hxh -i D:\Androidprojects\WYBN\app\src\main\res -o D:\Androidprojects\WYBN\app\build\freeline\freeline-databinding\app\4dad97da7e097c7fdf84ca39b5beec27\res -d D:\
Androidprojects\WYBN\app\build\freeline\freeline-databinding\merged_layoutinfo -c D:\Androidprojects\WYBN\app\build\freeline\freeline-databinding\app\4dad97da7e097c7fdf84ca39b5beec27\java -l false -v 14 -s D:\adsdk
[ERROR] --------------------------------------------------------
总是报关于databing的错误

**Comment by goadsth** [comment]
0.8.7版本和lizheng98的问题一样，但是昨天用的时候还是能增量编译的，今天各种方法都试过，就是不行。只能暂时回到instant run去了，希望能给出解决方法。

**Comment by YanHuiLi** [comment]
请问一下一直是
server result is -1
怎么解决，

**Comment by zhouyou123** [comment]
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "/Users/zhouyou/Documents/gitProject/odunsmart-android/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/Users/zhouyou/Documents/gitProject/odunsmart-android/freeline/freeline_core/gradle_clean_build.py", line 74, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "/Users/zhouyou/Documents/gitProject/odunsmart-android/freeline/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 0.1s

这个怎么解决？

**Comment by jinsen47** [comment]
如果改了freeline{productFlavor ''} 的值, 要重新 ./gradlew checkBCB
不然就不能inc build

**Comment by YanHuiLi** [comment]
看下是不是有中文的文件夹，不要使用中文的文件夹

**Comment by feisher** [comment]
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "freeline_core/android_tools.py", line 44, in execute
    self._install_apk()
  File "freeline_core/android_tools.py", line 69, in _install_apk
    self.debug('start to install apk to device: {}'.format(' '.join(install_args)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 86-89: ordinal not in range(128)
这种报错怎么处理啊？？全量打包安装失败

**Comment by FivredSeven** [comment]
很奇怪，我每天都用freeline跑的好好的 ，结果今天突然遇到这个问题，不能用了。  楼主提到的这些措施我也都用了，并没有解决，我换了两个手机跑都是这样。
现在我该怎么办？
