### ISSUE TITLE
buildtools 2.2.0 Cannot get property 'outputs' on null object

### ISSUE THREAD

**Issue by gaoxuxu** [alibaba/freeline#167]
我用的0.7.0 build tools版本是2.2.0

```
Caused by: java.lang.NullPointerException: Cannot get property 'outputs' on null object
	at com.antfortune.freeline.FreelinePlugin$_apply_closure4_closure8.doCall(FreelinePlugin.groovy:116)
	at com.antfortune.freeline.FreelinePlugin$_apply_closure4.doCall(FreelinePlugin.groovy:52)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy10.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
	... 52 more
```

**Comment by lomanyong** [comment]
fixed in 0.7.1
