### ISSUE TITLE
工程为settings.gradle，单一module目录结构报错

### ISSUE THREAD

**Issue by wogaizenme** [alibaba/freeline#169]
````
Traceback (most recent call last):
  File "E:\SVN\MEYQHC\TZYJ_Android_V5.6.1.3_20160824\freeline_core\dispatcher.py", line 88, in _exec_command
    command.execute()
  File "E:\SVN\MEYQHC\TZYJ_Android_V5.6.1.3_20160824\freeline_core\freeline_build.py", line 21, in execute
    file_changed_dict = self._scan_command.execute()
  File "E:\SVN\MEYQHC\TZYJ_Android_V5.6.1.3_20160824\freeline_core\gradle_tools.py", line 40, in execute
    build_info = self._get_build_info()
  File "E:\SVN\MEYQHC\TZYJ_Android_V5.6.1.3_20160824\freeline_core\gradle_tools.py", line 66, in _get_build_info
    is_root_config_changed = os.path.getmtime(os.path.join('settings.gradle')) > last_clean_build_time
  File "C:\Python27\lib\genericpath.py", line 62, in getmtime
    return os.stat(filename).st_mtime
WindowsError: [Error 2] : 'settings.gradle'
````

**Comment by lomanyong** [comment]
@wogaizenme 目录下没有settings.gradle这个文件吗？

**Comment by wogaizenme** [comment]
我们的项目是Eclipse 转的studio 整个项目只有一个gradle文件

**Comment by lomanyong** [comment]
@wogaizenme 没有分多个module吗？

**Comment by wogaizenme** [comment]
不好意思 没有

**Comment by lomanyong** [comment]
@wogaizenme 这样的工程结构现在还没有支持...估计得后续再看下了...

**Comment by wogaizenme** [comment]
哇!看样子我还挺幸运的,这样就发现了一个问题!还有老大 你不觉得你们的介绍写的太简单了吗!我看了一天才成功的在项目上运行起来

**Comment by lomanyong** [comment]
@wogaizenme 目前项目还在完善阶段，后续会出中文文档~更方便接入。
