### ISSUE TITLE
【兼容性】java.lang.IllegalStateException: Can only be called on top-level activity

### ISSUE THREAD

**Issue by lovexujh** [alibaba/freeline#171]
Log如下：
[WARNING] check sync status failed, a clean build will be automatically executed.
[-][read_project_info_task] finished. in 2.2s
[-][generate_file_stat_task] finished. in 0.2s
[-][gradle_clean_build_task] finished. in 123.3s
[-][clean_all_cache_task] finished. in 0.0s
[-][install_apk_task] finished. in 20.9s
[-][build_base_resource_task] finished. in 10.1s
[-][generate_project_info_task] finished. in 0.0s
[-][append_file_stat_task] finished. in 0.0s
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 3.5s
[DEBUG] Task engine running time: 146.4s
[DEBUG] Total time: 149.9s
[DEBUG] --------------------------------------------------------
为什么每次修改drawable, layout之类的文件编译很慢啊？有的时候达到300S，没有使用Freeline的时候编译也就不到1分钟多一点啊，麻烦回复一下，谢谢！

**Comment by lomanyong** [comment]
@lovexujh  `[WARNING] check sync status failed, a clean build will be automatically executed.`，因为出现了这句log了。请问你现在使用的是哪个版本的freeline？手机上是否安装了其他依赖了旧版freeline的app？

**Comment by lovexujh** [comment]
classpath 'com.antfortune.freeline:gradle:0.6.2'
手机上没有其他的依赖的APP

**Comment by lovexujh** [comment]
@lomanyong   根据这个使用的http://www.jianshu.com/p/f9d3431ddd71

**Comment by lomanyong** [comment]
@lovexujh 升级到0.7.0再试试看吧。

**Comment by lovexujh** [comment]
@lomanyong 根据这个链接http://www.jianshu.com/p/f9d3431ddd71使用freeline，升级到0.7.0后报错。Caused by: java.lang.ClassCastException: com.antfortune.freeline.FreelineApplication cannot be cast to

**Comment by lomanyong** [comment]
@lovexujh 暂时关掉applicationProxy，方法是加入一个配置项：

````gradle
freeline {
    ......
    applicationProxy false
}
````

**Comment by lovexujh** [comment]
@lomanyong 按照你的方法使用0.7.0版本，修改xml后，APP会crash。杀掉APP进程后重新打开，会ANR。
LOG:
Process: com.hundsun.winner.pazq, PID: 14081
                                                                         java.lang.RuntimeException: java.lang.IllegalStateException: Can only be called on top-level activity
                                                                             at com.antfortune.freeline.util.ActivityManager$4.run(ActivityManager.java:150)
                                                                             at android.os.Handler.handleCallback(Handler.java:743)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                          Caused by: java.lang.IllegalStateException: Can only be called on top-level activity
                                                                             at android.app.Activity.recreate(Activity.java:4882)
                                                                             at com.antfortune.freeline.util.ActivityManager$4.run(ActivityManager.java:142)
                                                                             at android.os.Handler.handleCallback(Handler.java:743) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by lomanyong** [comment]
@lovexujh 改java会出现类似的问题吗？以及，这个问题是否是必现的呢？

顺便可以提供一下你使用的测试机型的信息。

**Comment by lovexujh** [comment]
@lomanyong 对于这个crash在0.7.0版本的freeline中，只有在修改drawable, layout之类必现的，修改java文件不会的。机型：ZTE A2015

**Comment by lomanyong** [comment]
@lovexujh 可以确认一下换机器是否会重现吗？

**Comment by lovexujh** [comment]
@lomanyong 稍等

**Comment by lovexujh** [comment]
@lomanyong crash必现
AS 2.2版本，Log:
java.lang.RuntimeException: java.lang.IllegalStateException: Can only be called on top-level activity
                                                                             at com.antfortune.freeline.util.ActivityManager$4.run(ActivityManager.java:150)
                                                                             at android.os.Handler.handleCallback(Handler.java:743)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                          Caused by: java.lang.IllegalStateException: Can only be called on top-level activity
                                                                             at android.app.Activity.recreate(Activity.java:4882)
                                                                             at com.antfortune.freeline.util.ActivityManager$4.run(ActivityManager.java:142)
                                                                             at android.os.Handler.handleCallback(Handler.java:743) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by lomanyong** [comment]
@lovexujh 这个异常我这边重复多种情况一直没复现出来，请问你那里可以尝试调用一下`Activity#recreate()`的API吗？不知道是否你们应用特殊的情况导致的crash？

**Comment by lovexujh** [comment]
@lomanyong 问题已经解决了，拷贝的同事的项目重新编译可以了，谢谢！
