### ISSUE TITLE
FreelineConfig 下的 applicationClass 字段为空，如下图

### ISSUE THREAD

**Issue by whistlexie** [alibaba/freeline#174]
不好意思，我又来提问了。谢谢！！
![image](https://cloud.githubusercontent.com/assets/10007354/18869784/709cb0a4-84e0-11e6-9a28-aaec377e399f.png)

不太懂 groovy，所以能麻烦提示一下吗？感激感激！！！

**Comment by whistlexie** [comment]
public static String getApplication(String manifestPath, String packageName) {
        def application = ""
        def manifestFile = new File(manifestPath)
        if (manifestFile.exists() && manifestFile.isFile()) {
            def manifest = new XmlSlurper(false, false).parse(manifestFile)
            application = manifest.application."@android:name".text()
            if (application != null && application.startsWith(".")) {
                application = packageName + application
            }
        }
        return application
    }
// 大概是这段代码把。不知道为什么就获取不了 Application 类名了

**Comment by lomanyong** [comment]
@whistlexie 暂时加入一个配置项：

````gradle
freeline {
    ...
    applicationProxy false
}
````

记得在你的Application类中加入：`FreelineCore.init(this);`，即可暂时绕过这个问题。

**Comment by whistlexie** [comment]
好的，感谢，我试一下先。 @lomanyong

**Comment by whistlexie** [comment]
@lomanyong 感谢，问题已经解决，但是出现了新的报错 O_O....

E/Freeline: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.app.Application.getAssets()' on a null object reference
                                                                        at com.antfortune.freeline.FreelineCore.getApkBuildFlag(FreelineCore.java:136)
                                                                        at com.antfortune.freeline.router.schema.CheckSyncSchema.handle(CheckSyncSchema.java:28)
                                                                        at com.antfortune.freeline.router.Router.dispatch(Router.java:48)
                                                                        at com.antfortune.freeline.server.LongLinkServer.handle(LongLinkServer.java:55)
                                                                        at com.antfortune.freeline.server.EmbedHttpServer.run(EmbedHttpServer.java:95)
                                                                        at java.lang.Thread.run(Thread.java:818)

**Comment by whistlexie** [comment]
@lomanyong 感谢，问题已经完美解决，但是还是新的问题，设备连接不上。log日志报错如下：

E/Freeline: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.app.Application.getAssets()' on a null object reference
                                                                        at com.antfortune.freeline.FreelineCore.getApkBuildFlag(FreelineCore.java:136)
                                                                        at com.antfortune.freeline.router.schema.CheckSyncSchema.handle(CheckSyncSchema.java:28)
                                                                        at com.antfortune.freeline.router.Router.dispatch(Router.java:48)
                                                                        at com.antfortune.freeline.server.LongLinkServer.handle(LongLinkServer.java:55)
                                                                        at com.antfortune.freeline.server.EmbedHttpServer.run(EmbedHttpServer.java:95)
                                                                        at java.lang.Thread.run(Thread.java:818)


确认过 Application 类的 onCreate()里面是调用过 FreelineCore.init(this)方法了。

**Comment by lomanyong** [comment]
@whistlexie `FreelineCore.init(this);`放在onCreate()下的第一行，不要对这个逻辑做是否在主线程的判断...

**Comment by whistlexie** [comment]
好的，感谢，正在试。非常感谢你的热心解答！！！

**Comment by whistlexie** [comment]
@lomanyong  非常感谢，问题已经完美解决，再次感谢！！！！！！！
