### ISSUE TITLE
机型兼容问题，部分手机就打不开App

### ISSUE THREAD

**Issue by zhoujianhanyu** [alibaba/freeline#175]
java.lang.NoClassDefFoundError: com.antfortune.freeline.gradle.GradleDynamic
at com.antfortune.freeline.FreelineCore.init(FreelineCore.java:58)
at com.antfortune.freeline.FreelineApplication.onCreate(FreelineApplication.java:28)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1065)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4692)
at android.app.ActivityThread.access$1300(ActivityThread.java:167)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1435)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5450)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)
calling UncaughtExceptionHandler
FATAL EXCEPTION: main
java.lang.NoClassDefFoundError: com.antfortune.freeline.gradle.GradleDynamic
at com.antfortune.freeline.FreelineCore.init(FreelineCore.java:58)
at com.antfortune.freeline.FreelineApplication.onCreate(FreelineApplication.java:28)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1065)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4692)
at android.app.ActivityThread.access$1300(ActivityThread.java:167)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1435)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5450)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)

**Comment by lomanyong** [comment]
@zhoujianhanyu 目前解决的办法：

````Gradle
freeline {
    ....
    applicationProxy false
}
````

可以暂时用上面的方法绕过，或者等待今天稍后发布的0.7.1，会解决这个问题。
