### ISSUE TITLE
执行python freeline.py报错

### ISSUE THREAD

**Issue by paozhuanyinyu** [alibaba/freeline#180]
````
Traceback (most recent call last):
  File "/Users/kay/Documents/workspace_as/zhibo_android/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/Users/kay/Documents/workspace_as/zhibo_android/freeline/freeline_core/gradle_inc_build.py", line 162, in execute
    self._invoker.check_other_modules_resources()
  File "/Users/kay/Documents/workspace_as/zhibo_android/freeline/freeline_core/gradle_inc_build.py", line 348, in check_other_modules_resources
    self.__modify_main_r()
  File "/Users/kay/Documents/workspace_as/zhibo_android/freeline/freeline_core/gradle_inc_build.py", line 361, in __modify_main_r
    write_file_content(main_r_fpath, buf)
  File "/Users/kay/Documents/workspace_as/zhibo_android/freeline/freeline_core/utils.py", line 118, in write_file_content
    with open(target_path, 'w') as fp:
IOError: [Errno 2] No such file or directory: u'/Users/kay/Documents/workspace_as/zhibo_android/app/build/freeline/app/backup/com/zhanyou/kay/youchat/R.java'
````

**Comment by lomanyong** [comment]
@paozhuanyinyu 必现吗？是否可以给出具体的复现路径？

**Comment by paozhuanyinyu** [comment]
必现，就是我改layout下面的xml之后，再增量编译就会报这个错。是因为我的R文件的路径跟我的ApplicationId不一致吗？

**Comment by evan0502** [comment]
[INFO] preparing for tasks...
[-][read_project_info_task] failed. in 0.0s
[-][generate_file_stat_task] finished. in 0.2s
[-][gradle_clean_build_task] failed. in 0s
[-][clean_all_cache_task] failed. in 0s
[-][install_apk_task] failed. in 0s
[-][build_base_resource_task] failed. in 0s
[-][generate_project_info_task] failed. in 0s
[-][append_file_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Evan/AndroidStudioProjects/Welltang/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/Users/Evan/AndroidStudioProjects/Welltang/freeline/freeline_core/gradle_clean_build.py", line 71, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "/Users/Evan/AndroidStudioProjects/Welltang/freeline/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 0.2s
[DEBUG] Total time: 0.4s
[DEBUG] --------------------------------------------------------

我这边也出现这样的问题，麻烦确认下呢。

**Comment by lomanyong** [comment]
@paozhuanyinyu 应该是这个问题导致的。你们是如何定义的导致的applicationId和文件夹路径不一致呢？
