### ISSUE TITLE
python freeline.py error: Operation not permitted

### ISSUE THREAD

**Issue by pphdsny** [alibaba/freeline#186]
Traceback (most recent call last):
  File "/Users/wangpeng/Document/git/DocRabPro/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/Users/wangpeng/Document/git/DocRabPro/freeline/freeline_core/gradle_clean_build.py", line 69, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "/Users/wangpeng/Document/git/DocRabPro/freeline/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 1] Operation not permitted

**Comment by lomanyong** [comment]
@pphdsny  手动执行`./gradlew -q checkBeforeCleanBuild`，是否会报错？

**Comment by pphdsny** [comment]
@lomanyong 不报错的，正常的

**Comment by lomanyong** [comment]
@pphdsny 麻烦google一下`OSError: [Errno 1] Operation not permitted`，看下提及的原因，是否跟你本地的环境有关，目前来看应该是你本地的环境导致的问题。

**Comment by lomanyong** [comment]
@pphdsny 问题如何了？
