### ISSUE TITLE
 运行 python freeline.py报错

### ISSUE THREAD

**Issue by permission-denied** [alibaba/freeline#193]
提示如下:

[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanB
uild=False, debug=False, init=False, version=False)
[DEBUG] collecting project info, please wait a while...
[DEBUG] [scan_changed_files_command] find D:\android\txpro\txdiao_android\TXFish
ing\build.gradle has modification.
[DEBUG] final apk not found, need a clean build.
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: D:\android\txpro\txdiao_android\TXFishing\build\fr
eeline\freeline-assets\apktime
[DEBUG] new clean build flag value: 140000
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiti
ng 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after wai
ting 0.0s
[DEBUG] [generate_file_stat_task] save TXFishing module file stat
[DEBUG] [generate_file_stat_task] save SmartTabLibrary module file stat
[DEBUG] [generate_file_stat_task] save IMKitWithVoIP1 module file stat
[DEBUG] [generate_file_stat_task] save ShareSDK module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.2s
[DEBUG] [read_project_info_task] read_project_info_task finish in 9.0s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after wai
ting 9.0s
[DEBUG] [gradle_clean_build_task] gradlew.bat assembleDebug --stacktrace -P free
lineBuild=true
[DEBUG] [gradle_clean_build_task] Gradle build task is running, please wait a mi
nute...
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task finish in 8.3s
[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 1
7.2s
[DEBUG] [install_apk_task] install_apk_task start to run after waiting 17.2s
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after w
aiting 17.2s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run aft
er waiting 17.0s
[DEBUG] [append_file_stat_task] append_file_stat_task start to run after waiting
 8.3s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 17.26s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
freeline auto add runtime dependencies: 0.7.2
find variant debug start hack process...
find default apk path: D:\android\txpro\txdiao_android\TXFishing\build\outputs\a
pk\TXFishing-debug.apk
Old file C:\Users\Administrator\.freeline\cache\359a2d9f63263b71108daa426254850b
\project_description.json removed.
Save to C:\Users\Administrator\.freeline\cache\359a2d9f63263b71108daa426254850b\
project_description.json

BUILD FAILED

Total time: 4.547 secs

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':TXFishing'.
> Could not find method additionalParameters() for arguments [-P, D:\android\txp
ro\txdiao_android\TXFishing\build\freeline\public_keeper.xml] on com.android.bui
ld.gradle.internal.dsl.AaptOptions_Decorated@65d6640.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring pro
ject ':TXFishing'.
        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigu
rationFailure(LifecycleProjectEvaluator.java:91)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfte
rEvaluate(LifecycleProjectEvaluator.java:86)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(L
ifecycleProjectEvaluator.java:65)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProj
ect.java:504)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProj
ect.java:83)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(Task
PathProjectEvaluator.java:47)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuil
dConfigurer.java:35)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
GradleLauncher.java:129)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle
Launcher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun
cher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildCon
troller.run(InProcessBuildActionExecuter.java:80)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.jav
a:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.jav
a:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:36)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:26)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.jav
a:171)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
meValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
meValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
ortingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
ortingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBoots
trap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.j
ava:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.ja
va:33)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: org.gradle.api.internal.MissingMethodException: Could not find method
 additionalParameters() for arguments [-P, D:\android\txpro\txdiao_android\TXFis
hing\build\freeline\public_keeper.xml] on com.android.build.gradle.internal.dsl.
AaptOptions_Decorated@65d6640.
        at org.gradle.api.internal.AbstractDynamicObject.methodMissingException(
AbstractDynamicObject.java:68)
        at org.gradle.api.internal.AbstractDynamicObject.invokeMethod(AbstractDy
namicObject.java:56)
        at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(Composite
DynamicObject.java:172)
        at com.android.build.gradle.internal.dsl.AaptOptions_Decorated.invokeMet
hod(Unknown Source)
        at com.antfortune.freeline.FreelinePlugin$_apply_closure4_closure10.doCa
ll(FreelinePlugin.groovy:95)
        at com.antfortune.freeline.FreelinePlugin$_apply_closure4.doCall(Freelin
ePlugin.groovy:50)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(Cl
osureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(Cl
osureBackedMethodInvocationDispatch.java:25)
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java
:83)
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java
:31)
        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocat
ionHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy12.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfte
rEvaluate(LifecycleProjectEvaluator.java:79)
        ... 31 more

[ERROR] --------------------------------------------------------
[ERROR] build failed with script: gradlew.bat assembleDebug
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 17.3s
[DEBUG] Total time: 17.5s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@permission-denied 你们使用的android-gradle的版本是多少呢？是否是2.0以下的？

**Comment by permission-denied** [comment]
@lomanyong  Gradle version 2.2.1     Android plugin version 1.2.3

**Comment by lomanyong** [comment]
@permission-denied  `Android plugin version 1.2.3`这个版本太低了，Freeline支持的至少得1.3+的...
