### ISSUE TITLE
改动自定义Application onCreate 里面相关类似乎会奔溃

### ISSUE THREAD

**Issue by eritpchy** [alibaba/freeline#203]
RT~

**Comment by lomanyong** [comment]
@eritpchy crash的话，麻烦贴下日志？

**Comment by eritpchy** [comment]
这么晚了 竟然还在上班.., 我没记录 等等我重现试试..

**Comment by lomanyong** [comment]
@eritpchy 额..只是看到issue了，先回复看看...有问题还是可以帮忙解决一下的..

**Comment by eritpchy** [comment]
必现~
10-15 14:49:39.865 1521-1521/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: cn.gov.hsxxxx.app, PID: 1521
                                                 java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
                                                     at cn.gov.hsxxxx.app.MyApplication.onCreate(MyApplication.java:45)
                                                     at com.antfortune.freeline.FreelineApplication.startRealApplication(FreelineApplication.java:44)
                                                     at com.antfortune.freeline.FreelineApplication.onCreate(FreelineApplication.java:31)
                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4372)
                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5045)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by eritpchy** [comment]
另外我发现一个现象  xml 里面的值 一下子改太大 也会crash
比如我一下子加了个marginTop 900

**Comment by eritpchy** [comment]
一点一点的加就没事~

**Comment by lomanyong** [comment]
@eritpchy 使用的机型的是什么？系统版本是？

**Comment by eritpchy** [comment]
夜神模拟器

**Comment by lomanyong** [comment]
@eritpchy xml crash的log有吗？

**Comment by eritpchy** [comment]
log等等全量编译了..
另外mac版本和win版本日志不一样, mac版本的日志看着很赞
FreeLine Console 那个stop好像在windows无效

**Comment by lomanyong** [comment]
@eritpchy win下日志不一样的原因是，win的控制台的api貌似没有比较好的python库来支持...所以暂时只能打全量的debug日志了...这里的优化可能会放到比较后面再来进行哈

**Comment by eritpchy** [comment]
理解~

log来了, 这个重现步骤比较奇葩
夜神模拟器 分辨率 480x800 dpi 160
用adb wm dpi 改成320 再次热部署就会出现
--------------------

10-15 15:01:58.845 10404-10421/cn.gov.hsxxxx.app:freeline I/Freeline.CheckSync: devUuid: 161000
10-15 15:01:58.845 10404-10421/cn.gov.hsxxxx.app:freeline I/Freeline.CheckSync: dev apkflag:161000, last sync is:161001, current sync is:161001
10-15 15:01:59.841 10404-10421/cn.gov.hsxxxx.app:freeline D/Freeline.PushResource: receive res /pushResource?mode=full&bundleId=base-res
10-15 15:01:59.841 10404-10421/cn.gov.hsxxxx.app:freeline D/Freeline.PushResource: receive full res pck command
10-15 15:01:59.841 10404-10421/cn.gov.hsxxxx.app:freeline D/Freeline.PushResource: bundle id base-res
10-15 15:01:59.841 10404-10421/cn.gov.hsxxxx.app:freeline I/Freeline.PushResource: bundle last time :0
10-15 15:02:00.013 10404-10421/cn.gov.hsxxxx.app:freeline D/Freeline.PushResource: delete pending file rename rst :true
10-15 15:02:00.017 10404-10421/cn.gov.hsxxxx.app:freeline D/Freeline.PushResource: increment resources file received (1056470 bytes)
10-15 15:02:00.037 10404-10421/cn.gov.hsxxxx.app:freeline D/dalvikvm: GC_FOR_ALLOC freed 1308K, 30% free 3326K/4716K, paused 7ms, total 7ms
10-15 15:02:00.041 10404-10421/cn.gov.hsxxxx.app:freeline I/Freeline.CloseLongLink: save last sync value: 2
10-15 15:02:00.041 10390-10390/cn.gov.hsxxxx.app D/FreelineApplication: FreelineApplication#onCreate()
10-15 15:02:00.041 10390-10390/cn.gov.hsxxxx.app I/Freeline: freeline start initial process...
10-15 15:02:00.041 10390-10390/cn.gov.hsxxxx.app I/Freeline: freeline init application
10-15 15:02:00.041 10390-10390/cn.gov.hsxxxx.app I/Freeline: start to inject dex...
10-15 15:02:00.041 10390-10390/cn.gov.hsxxxx.app I/Freeline: start to inject resources...
10-15 15:02:00.041 10390-10390/cn.gov.hsxxxx.app I/Freeline: dynamicInfoSp: {base-res.key=/data/data/cn.gov.hsxxxx.app/cache/temp/base-res.jar, dynamicTime=1476543653747}
10-15 15:02:00.041 10390-10390/cn.gov.hsxxxx.app I/Freeline: resMap: {base-res.key=/data/data/cn.gov.hsxxxx.app/cache/temp/base-res.jar}
10-15 15:02:00.041 10390-10390/cn.gov.hsxxxx.app I/Freeline.GradleDynamic: dynamicResPath: /data/data/cn.gov.hsxxxx.app/cache/temp/base-res.jar
10-15 15:02:00.045 10390-10390/cn.gov.hsxxxx.app I/Freeline.GradleDynamic: GradleDynamic apply dynamic resource successfully
10-15 15:02:00.045 10390-10390/cn.gov.hsxxxx.app I/Freeline: start to load hackload.dex...
10-15 15:02:00.045 10390-10390/cn.gov.hsxxxx.app I/Freeline.hackDex: /data/data/cn.gov.hsxxxx.app/cache/hack/hackload.dex dex length: 848
10-15 15:02:00.045 10390-10390/cn.gov.hsxxxx.app I/Freeline.hackDex: /data/data/cn.gov.hsxxxx.app/cache/hack/opt opt length: 4096
10-15 15:02:00.045 10390-10390/cn.gov.hsxxxx.app I/Freeline.hackDex: after opt, dex len:848; opt len:4096
10-15 15:02:00.045 10390-10390/cn.gov.hsxxxx.app I/Freeline: load hackload，dex size:848
10-15 15:02:00.045 10390-10390/cn.gov.hsxxxx.app I/Freeline: start to inject native lib...
10-15 15:02:00.045 10390-10390/cn.gov.hsxxxx.app I/Freeline.hackNative: native lib inject process start...
10-15 15:02:00.045 10390-10390/cn.gov.hsxxxx.app I/Freeline.hackNative: inject native lib success [Ljava.io.File;@4a9094f4
10-15 15:02:00.045 10390-10390/cn.gov.hsxxxx.app I/Freeline: freeline init server
10-15 15:02:00.045 10404-10404/cn.gov.hsxxxx.app:freeline I/Freeline.Service: onStartCommand Received start id 3, intent: Intent { cmp=cn.gov.hsxxxx.app/com.antfortune.freeline.FreelineService }
10-15 15:02:00.045 10404-10404/cn.gov.hsxxxx.app:freeline D/Freeline.LongLinkServer: Freeline.increment server is already running
10-15 15:02:00.049 10404-10404/cn.gov.hsxxxx.app:freeline I/Freeline.Service$Inner: onStartCommand Received start id 1, intent: Intent { cmp=cn.gov.hsxxxx.app/com.antfortune.freeline.FreelineService$InnerService }
10-15 15:02:00.061 10390-10390/cn.gov.hsxxxx.app D/FreelineApplication: create application: cn.gov.hsxxxx.app.MyApplication
10-15 15:02:00.065 10390-10390/cn.gov.hsxxxx.app D/FreelineApplication: realApplication#attach(Context)
10-15 15:02:00.065 10390-10390/cn.gov.hsxxxx.app I/Freeline: freeline start initial process...
10-15 15:02:00.065 10390-10390/cn.gov.hsxxxx.app I/Freeline: freeline init application
10-15 15:02:00.065 10390-10390/cn.gov.hsxxxx.app I/Freeline: the apk has recover, delete cache
10-15 15:02:00.065 10404-10421/cn.gov.hsxxxx.app:freeline I/Freeline.CloseLongLink: with only res changes, just recreate the running activity.
10-15 15:02:00.065 10390-10390/cn.gov.hsxxxx.app I/Freeline: clear dynamic info sp cache
10-15 15:02:00.069 10390-10390/cn.gov.hsxxxx.app I/Freeline: clear sync info sp cache
10-15 15:02:00.069 10390-10390/cn.gov.hsxxxx.app I/Freeline: start to load hackload.dex...
10-15 15:02:00.069 10390-10390/cn.gov.hsxxxx.app I/Freeline.hackDex: /data/data/cn.gov.hsxxxx.app/cache/hack/hackload.dex dex length: 848
10-15 15:02:00.069 10390-10390/cn.gov.hsxxxx.app I/Freeline.hackDex: /data/data/cn.gov.hsxxxx.app/cache/hack/opt opt length: 4096
10-15 15:02:00.069 10390-10390/cn.gov.hsxxxx.app I/Freeline.hackDex: after opt, dex len:848; opt len:4096
10-15 15:02:00.069 10390-10390/cn.gov.hsxxxx.app I/Freeline: load hackload，dex size:848
10-15 15:02:00.069 10390-10390/cn.gov.hsxxxx.app I/Freeline: start to inject native lib...
10-15 15:02:00.069 10390-10390/cn.gov.hsxxxx.app I/Freeline.hackNative: native lib inject process start...
10-15 15:02:00.069 10390-10390/cn.gov.hsxxxx.app I/Freeline.hackNative: inject native lib success [Ljava.io.File;@4a912ac4
10-15 15:02:00.069 10390-10390/cn.gov.hsxxxx.app I/Freeline: freeline init server
10-15 15:02:00.073 10404-10404/cn.gov.hsxxxx.app:freeline I/Freeline.Service: onStartCommand Received start id 4, intent: Intent { cmp=cn.gov.hsxxxx.app/com.antfortune.freeline.FreelineService }
10-15 15:02:00.073 10404-10404/cn.gov.hsxxxx.app:freeline D/Freeline.LongLinkServer: Freeline.increment server is already running
10-15 15:02:00.077 10404-10404/cn.gov.hsxxxx.app:freeline I/Freeline.Service$Inner: onStartCommand Received start id 1, intent: Intent { cmp=cn.gov.hsxxxx.app/com.antfortune.freeline.FreelineService$InnerService }
10-15 15:02:00.089 10390-10390/cn.gov.hsxxxx.app D/FreelineApplication: realApplication#onCreate()
10-15 15:02:00.089 10390-10390/cn.gov.hsxxxx.app I/Freeline.Receiver: receive action type: 1
10-15 15:02:00.089 10390-10390/cn.gov.hsxxxx.app D/Freeline.Receiver: destPath :/data/data/cn.gov.hsxxxx.app/cache/temp/base-res.jar
10-15 15:02:00.093 10390-10390/cn.gov.hsxxxx.app I/Freeline: apply res :{base-res=/data/data/cn.gov.hsxxxx.app/cache/temp/base-res.jar}
10-15 15:02:00.093 10390-10390/cn.gov.hsxxxx.app I/Freeline: dynamicInfoSp: {base-res.key=/data/data/cn.gov.hsxxxx.app/cache/temp/base-res.jar}
10-15 15:02:00.093 10390-10390/cn.gov.hsxxxx.app I/Freeline: resMap: {base-res.key=/data/data/cn.gov.hsxxxx.app/cache/temp/base-res.jar}
10-15 15:02:00.093 10390-10390/cn.gov.hsxxxx.app I/Freeline.GradleDynamic: dynamicResPath: /data/data/cn.gov.hsxxxx.app/cache/temp/base-res.jar
10-15 15:02:00.093 10390-10390/cn.gov.hsxxxx.app W/asset: Asset path /data/data/cn.gov.hsxxxx.app/cache/temp/base-res.jar is neither a directory nor file (type=1).
10-15 15:02:00.097 10390-10390/cn.gov.hsxxxx.app D/AndroidRuntime: Shutting down VM
10-15 15:02:00.097 10390-10390/cn.gov.hsxxxx.app W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x94d5bb20)
10-15 15:02:00.097 10390-10390/cn.gov.hsxxxx.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: cn.gov.hsxxxx.app, PID: 10390
                                                                   java.lang.RuntimeException: Unable to start receiver com.antfortune.freeline.FreelineReceiver: java.lang.IllegalStateException: java.lang.IllegalStateException: Could not create new AssetManager
                                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2450)
                                                                       at android.app.ActivityThread.access$1700(ActivityThread.java:135)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5045)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                       at dalvik.system.NativeStart.main(Native Method)
                                                                    Caused by: java.lang.IllegalStateException: java.lang.IllegalStateException: Could not create new AssetManager
                                                                       at com.antfortune.freeline.resources.MonkeyPatcher.monkeyPatchExistingResources(MonkeyPatcher.java:394)
                                                                       at com.antfortune.freeline.gradle.GradleDynamic.applyDynamicRes(GradleDynamic.java:32)
                                                                       at com.antfortune.freeline.FreelineCore.applyDynamicRes(FreelineCore.java:304)
                                                                       at com.antfortune.freeline.FreelineCore.injectResources(FreelineCore.java:248)
                                                                       at com.antfortune.freeline.FreelineCore.saveDynamicResInfo(FreelineCore.java:330)
                                                                       at com.antfortune.freeline.FreelineReceiver.saveDynamicResInfo(FreelineReceiver.java:59)
                                                                       at com.antfortune.freeline.FreelineReceiver.onReceive(FreelineReceiver.java:40)
                                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2443)
                                                                       at android.app.ActivityThread.access$1700(ActivityThread.java:135) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5045) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                                    Caused by: java.lang.IllegalStateException: Could not create new AssetManager
                                                                       at com.antfortune.freeline.resources.MonkeyPatcher.monkeyPatchExistingResources(MonkeyPatcher.java:286)
                                                                       at com.antfortune.freeline.gradle.GradleDynamic.applyDynamicRes(GradleDynamic.java:32) 
                                                                       at com.antfortune.freeline.FreelineCore.applyDynamicRes(FreelineCore.java:304) 
                                                                       at com.antfortune.freeline.FreelineCore.injectResources(FreelineCore.java:248) 
                                                                       at com.antfortune.freeline.FreelineCore.saveDynamicResInfo(FreelineCore.java:330) 
                                                                       at com.antfortune.freeline.FreelineReceiver.saveDynamicResInfo(FreelineReceiver.java:59) 
                                                                       at com.antfortune.freeline.FreelineReceiver.onReceive(FreelineReceiver.java:40) 
                                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2443) 
                                                                       at android.app.ActivityThread.access$1700(ActivityThread.java:135) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5045) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                       at dalvik.system.NativeStart.main(Native Method) 
10-15 15:02:00.101 400-558/? W/ActivityManager:   Force finishing activity cn.gov.hsxxxx.app/.activity.MemoireActivity
10-15 15:02:00.117 504-504/? D/dalvikvm: GC_FOR_ALLOC freed 157K, 80% free 5098K/24820K, paused 5ms, total 31ms
10-15 15:02:00.137 400-418/? W/WindowManager: updateFocusedWindowLocked, focusedAppToken is null.
10-15 15:02:00.137 504-504/? D/dalvikvm: GC_FOR_ALLOC freed 15K, 77% free 5844K/24820K, paused 6ms, total 6ms
10-15 15:02:00.197 849-11716/? D/dalvikvm: GC_FOR_ALLOC freed 1029K, 18% free 6136K/7432K, paused 13ms, total 13ms
10-15 15:02:00.213 849-11716/? D/DropBoxEntryAddedChimeraService: User is not opted-in to Usage & Diagnostics or Lockbox.

**Comment by eritpchy** [comment]
还有个..ReadMe似乎没有写要装python, 而且还是2.7 而且还不能是cygwin的python 坑死我了

**Comment by lomanyong** [comment]
@eritpchy 大概知道原因了，貌似是触发了类似清缓存的操作，导致freeline在运行期出错。

另外python 2.7的问题，现在如果是python 3+的话，执行命令会报错并提示降级的，所以README里去掉了关于python版本的一些说明。

Win下的测试主要是cmd，因为在win下Android Studio的terminal实际上也是cmd，而不是cygwin。freeline目前还没有支持cygwin的计划，没准以后用的人多了会有...

我们这两天在整理中文文档，到时就会发出来，如果有不完善的地方也欢迎指正或者帮我们完善哈。

**Comment by eritpchy** [comment]
Ok

**Comment by lomanyong** [comment]
@eritpchy 尽量不要清除缓存~

**Comment by eritpchy** [comment]
好的
