### ISSUE TITLE
freeline 和reactnative冲突这个能解决吗，freeline修改了application类，导致reactnative无法运行

### ISSUE THREAD

**Issue by shuifengYu** [alibaba/freeline#205]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.abc360.tool/com.abc360.MyReact2Activity}: java.lang.ClassCastException: com.antfortune.freeline.FreelineApplication cannot be cast to com.facebook.react.ReactApplication
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2314)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2386)
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:148)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5310)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
                                                                       Caused by: java.lang.ClassCastException: com.antfortune.freeline.FreelineApplication cannot be cast to com.facebook.react.ReactApplication
                                                                          at com.facebook.react.ReactActivityDelegate.getReactNativeHost(ReactActivityDelegate.java:72)
                                                                          at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:80)
                                                                          at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54)
                                                                          at android.app.Activity.performCreate(Activity.java:5953)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2386) 
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:148) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:135) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5310) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696) 
                                                                      java.lang.ClassCastException: com.antfortune.freeline.FreelineApplication cannot be cast to com.facebook.react.ReactApplication
                                                                          at com.facebook.react.ReactActivityDelegate.getReactNativeHost(ReactActivityDelegate.java:72)
                                                                          at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:80)
                                                                          at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54)
                                                                          at android.app.Activity.performCreate(Activity.java:5953)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2386)
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:148)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5310)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
10-18 10:54:56.581 21715-21715/com.abc360.tool E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.abc360.tool, PID: 21715
                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.abc360.tool/com.abc360.MyReact2Activity}: java.lang.ClassCastException: com.antfortune.freeline.FreelineApplication cannot be cast to com.facebook.react.ReactApplication
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2314)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2386)
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:148)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5310)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
                                                                  Caused by: java.lang.ClassCastException: com.antfortune.freeline.FreelineApplication cannot be cast to com.facebook.react.ReactApplication
                                                                     at com.facebook.react.ReactActivityDelegate.getReactNativeHost(ReactActivityDelegate.java:72)
                                                                     at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:80)
                                                                     at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54)
                                                                     at android.app.Activity.performCreate(Activity.java:5953)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2386) 
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:148) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5310) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Comment by lomanyong** [comment]
@shuifengYu 在build.gradle中加入：

````
freeline {
    ...
    applicationProxy false
}
````

在你的Application类中加入：
````
FreelineCore.init(this);
````

即可解决你的问题。

**Comment by shuifengYu** [comment]
@lomanyong 还是不行啊，同样的错误，applicationProxy false 是加在主module下的android{}里面的

**Comment by lomanyong** [comment]
@shuifengYu 缓存没清？clean一下，在编译呢？

**Comment by shuifengYu** [comment]
@lomanyong 哈哈，果然好了，所以说默认是application被代理了，如果有用到一些三方的库需要使用application就去掉代理，手动init
