### ISSUE TITLE
在酷派4.4版本的机器上必现启动crash

### ISSUE THREAD

**Issue by hicomein** [alibaba/freeline#213]
其他6.0手机上使用正常。

Exception Stack如下：

````
10-19 11:00:49.586 14186-14186/com.dengtacj.stock E/Freeline: java.lang.IllegalStateException: java.lang.IllegalStateException: Could not create new AssetManager
                                                                  at com.antfortune.freeline.resources.MonkeyPatcher.monkeyPatchExistingResources(MonkeyPatcher.java:394)
                                                                  at com.antfortune.freeline.gradle.GradleDynamic.applyDynamicRes(GradleDynamic.java:32)
                                                                  at com.antfortune.freeline.FreelineCore.applyDynamicRes(FreelineCore.java:325)
                                                                  at com.antfortune.freeline.FreelineCore.injectResources(FreelineCore.java:268)
                                                                  at com.antfortune.freeline.FreelineCore.init(FreelineCore.java:89)
                                                                  at com.antfortune.freeline.FreelineCore.init(FreelineCore.java:63)
                                                                  at com.dengtacj.stock.main.DengtaApplication.onCreate(DengtaApplication.java:189)
                                                                  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4610)
                                                                  at android.app.ActivityThread.access$1500(ActivityThread.java:159)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1389)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                  at android.os.Looper.loop(Looper.java:193)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5367)
````

**Comment by lomanyong** [comment]
@hicomein 能贴出增量编译时 freeline tag 相关的所有日志吗？

**Comment by hicomein** [comment]
正好今天更新了0.7.3版本之后就没问题了

**Comment by lomanyong** [comment]
@hicomein 应该是`0.7.3.1`吧..0.7.3有个比较明显的bug，临时发了个修复版本。

**Comment by hicomein** [comment]
是的，是0.7.3.1
