### ISSUE TITLE
windows环境下存在unicode编码错误

### ISSUE THREAD

**Issue by pcyan** [alibaba/freeline#22]
使用全量编译没问题，但是在5.0.1的手机上增量编译一直报错
修改Java文件和资源文件增量编译均会出现同个错误

```
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "D:\workspace\TestLibrary_open\freeline_core\android_tools.py", line 298, in e
xecute
    self._command.execute()
  File "D:\workspace\TestLibrary_open\freeline_core\gradle_inc_build.py", line 159, i
n execute
    map(lambda command: command.execute(), self.command_list)
  File "D:\workspace\TestLibrary_open\freeline_core\gradle_inc_build.py", line 159, i
n <lambda>
    map(lambda command: command.execute(), self.command_list)
  File "D:\workspace\TestLibrary_open\freeline_core\gradle_inc_build.py", line 210, i
n execute
    self._invoker.run_dex_task()
  File "D:\workspace\TestLibrary_open\freeline_core\android_tools.py", line 561, in r
un_dex_task
    output, err, code = cexec(dex_args, add_path=add_path)
  File "D:\workspace\TestLibrary_open\freeline_core\utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "C:\tools\python2\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\tools\python2\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
TypeError: environment can only contain strings

[ERROR] --------------------------------------------------------
[ERROR] incremental build task failed.
[ERROR] --------------------------------------------------------
```

`gradle` 配置是
```
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "io.pcyan.testapplication"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
```

**Comment by lomanyong** [comment]
@pcyan 经过收集windows用户的反馈，这个应该是0.5.3版本上windows环境存在的兼容问题，我今天会尽快修复这个问题

**Comment by lomanyong** [comment]
@pcyan 现在可以重新执行一下`gradlew.bat initFreeline`，这个编码问题目前已经解决

**Comment by pcyan** [comment]
@lomanyong 修改资源文件增量编译没问题了，但是修改java还是报同样的错误

**Comment by lomanyong** [comment]
@pcyan 可以尝试删掉工程目录下的freeline/以及freeline_core/这两个文件夹，重新执行initFreeline命令。感觉改动没有生效的样子...

**Comment by pcyan** [comment]
@lomanyong 搞定了，撒花撒花
