### ISSUE TITLE
freeline E/Freeline: java.lang.NumberFormatException: Invalid long: "${placeholder}"

### ISSUE THREAD

**Issue by BruceHurrican** [alibaba/freeline#224]
增加编译时报错，请问怎样解决？
错误日志：

```

10-24 16:26:23.009 24791-24848/com.kk.bhdemo:freeline I/Freeline: ext:${placeholder}
10-24 16:26:23.009 24791-24848/com.kk.bhdemo:freeline E/Freeline: java.lang.NumberFormatException: Invalid long: "${placeholder}"
                                                                                  at java.lang.Long.invalidLong(Long.java:124)
                                                                                  at java.lang.Long.parse(Long.java:361)
                                                                                  at java.lang.Long.parseLong(Long.java:352)
                                                                                  at java.lang.Long.parseLong(Long.java:318)
                                                                                  at com.antfortune.freeline.FreelineCore.getApkBuildFlag(FreelineCore.java:146)
                                                                                  at com.antfortune.freeline.router.schema.CheckSyncSchema.handle(CheckSyncSchema.java:28)
                                                                                  at com.antfortune.freeline.router.Router.dispatch(Router.java:48)
                                                                                  at com.antfortune.freeline.server.LongLinkServer.handle(LongLinkServer.java:55)
                                                                                  at com.antfortune.freeline.server.EmbedHttpServer.run(EmbedHttpServer.java:95)

```

**Comment by lomanyong** [comment]
@BruceHurrican 要使用freeline的时候不用使用android studio来做全量编译。这是先使用android stuido全量编译，然后再使用freeline增量编译导致的...

重新用freeline全量编译一下可以解决这个问题。

**Comment by BruceHurrican** [comment]
没有用AS 来做全量编译，我的操作步骤如下：
打开 AS-当前工程-在 freeline 终端界面 输入 python freeline.py -f 做全量编译，app 部署到终端上-修改文件，freeline 终端上输入 python freeline.py 结果：
logcat 提示上述错误信息，同时 freeline 终端上提示如下报错信息：

```

kkdeMacBook-Pro:KK kk$ python freeline.py  
[INFO] preparing for tasks...
[-][connect_device_task] finished. in 0.3s
[-][gradle_aapt_task] finished. in 0.0s
[-][ILoanLibrary] finished. in 0.0s
[-][PingAnSYBLibrary] finished. in 0.0s
[-][PingAnWifiSYB] failed. in 2.2s
[-][merge_dex_task] failed. in 0s
[-][gradle_sync_task] failed. in 0s
[-][clean_cache_task] failed. in 0s
[-][update_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kk/KK/freeline_core/android_tools.py", line 318, in execute
    self._command.execute()
  File "/Users/kk/KK/freeline_core/gradle_inc_build.py", line 176, in execute
    map(lambda command: command.execute(), self.command_list)
  File "/Users/kk/KK/freeline_core/gradle_inc_build.py", line 176, in <lambda>
    map(lambda command: command.execute(), self.command_list)
  File "/Users/kk/KK/freeline_core/gradle_inc_build.py", line 229, in execute
    self._invoker.run_dex_task()
  File "/Users/kk/demos/freeline_core/android_tools.py", line 592, in run_dex_task
    output, err, code = cexec(dex_args, add_path=add_path)
  File "/Users/kk/KK/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

[ERROR] --------------------------------------------------------
[ERROR] incremental build task failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 2.2s
[DEBUG] Total time: 2.5s
[DEBUG] --------------------------------------------------------

```

**Comment by lomanyong** [comment]
@BruceHurrican 执行freeline脚本的时候可以使用`python freeline.py -d`，可以输出详细的日志，方便我们帮助你排查一下问题~

`not such file`比较好发现，`${your-path}/freeline/release-tools/dx`这个文件可以看下是否存在。

上面的那个报错，如果是正常使用freeline编译出现的话，不知道是否在全量编译的流程中是否就出错了...需要`./gradlew assembleDebug -PfreelineBuild=true`输出的日志来辅助判断一下...

**Comment by BruceHurrican** [comment]
release-tools文件夹下 有 dx,dx.bat,dx.jar 之类的文件都有。日志太多，我将上述问题，重新写了个 demo，[地址](https://github.com/BruceHurrican/BruceDaily.git) freelineDemo 分支，上述场景可以复现。

复现步骤：
卸载 app，freeline 全量编译，部署 app，修改文件，freeline 增量编译，复现上述信息

**Comment by lomanyong** [comment]
@BruceHurrican 我把项目pull下来，能够增量编译的。你那边编译不过的原因是因为你好像不是正常初始化的？拉下代码后没有`freeline`文件夹，我重新`initFreeline`后，`freeline`文件夹出现。

dx找不到的问题，dx的路径应该是`freeline/release-tools/dx`，而你之前是`release-tools/dx`。

我还对app做了点小修改，我去掉了`applicationProxy false`，不去掉的话，需要在你的application加上`FreelineCore.init(this);`

**Comment by BruceHurrican** [comment]
谢谢我再试下
