### ISSUE TITLE
使用 Freeline 无法运行应用

### ISSUE THREAD

**Issue by sivan67** [alibaba/freeline#234]
错误日志：
````
10-27 10:37:50.663 31606-31606/cc.kaipao.dongjia E/Freeline: java.lang.reflect.InvocationTargetException
                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                 at com.antfortune.freeline.util.ReflectUtil.invokeMethod(ReflectUtil.java:39)
                                                                 at com.antfortune.freeline.FreelineApplication.startRealApplication(FreelineApplication.java:44)
                                                                 at com.antfortune.freeline.FreelineApplication.onCreate(FreelineApplication.java:32)
                                                                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1016)
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4590)
                                                                 at android.app.ActivityThread.access$1500(ActivityThread.java:157)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                 at android.os.Looper.loop(Looper.java:193)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5348)
                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                              Caused by: java.lang.NoClassDefFoundError: android.support.multidex.MultiDex
                                                                 at cc.kaipao.dongjia.app.KaiPaoApplication.attachBaseContext(KaiPaoApplication.java:357)
                                                                 at android.app.Application.attach(Application.java:181)
                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                 at com.antfortune.freeline.util.ReflectUtil.invokeMethod(ReflectUtil.java:39) 
                                                                 at com.antfortune.freeline.FreelineApplication.startRealApplication(FreelineApplication.java:44) 
                                                                 at com.antfortune.freeline.FreelineApplication.onCreate(FreelineApplication.java:32) 
                                                                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1016) 
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4590) 
                                                                 at android.app.ActivityThread.access$1500(ActivityThread.java:157) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                 at android.os.Looper.loop(Looper.java:193) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5348) 
                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645) 
                                                                 at dalvik.system.NativeStart.main(Native Method) 
10-27 10:37:50.663 31606-31606/cc.kaipao.dongjia E/FreelineApplication: attach with realApplication error
                                                                        
                                                                        [ 10-27 10:37:50.664   212:0xd4 I/         ]
                                                                        [BWC INFO](212): get_bwc_mm_property success
10-27 10:37:50.665 31606-31606/cc.kaipao.dongjia I/Freeline: freeline start initial process...
10-27 10:37:50.665 31606-31606/cc.kaipao.dongjia I/Freeline: freeline init application
10-27 10:37:50.666 31606-31606/cc.kaipao.dongjia I/Freeline: start to inject dex...
10-27 10:37:50.666 31606-31606/cc.kaipao.dongjia I/Freeline: start to inject resources...
10-27 10:37:50.666 31606-31606/cc.kaipao.dongjia I/Freeline: dynamicInfoSp: {}
10-27 10:37:50.666 31606-31606/cc.kaipao.dongjia I/Freeline: resMap: {}
10-27 10:37:50.666 31606-31606/cc.kaipao.dongjia I/Freeline: start to load hackload.dex...
10-27 10:37:50.666 31606-31606/cc.kaipao.dongjia I/Freeline.hackDex: /data/data/cc.kaipao.dongjia/cache/hack/hackload.dex dex length: 848
10-27 10:37:50.666 31606-31606/cc.kaipao.dongjia I/Freeline.hackDex: /data/data/cc.kaipao.dongjia/cache/hack/opt opt length: 4096
10-27 10:37:50.667 31606-31606/cc.kaipao.dongjia D/dalvikvm: open_cached_dex_file : /data/data/cc.kaipao.dongjia/cache/hack/hackload.dex /data/data/cc.kaipao.dongjia/cache/hack/opt/hackload.dex
10-27 10:37:50.668 31606-31606/cc.kaipao.dongjia I/Freeline.hackDex: after opt, dex len:848; opt len:4096
10-27 10:37:50.668 31606-31606/cc.kaipao.dongjia I/Freeline: load hackload，dex size:848
10-27 10:37:50.668 31606-31606/cc.kaipao.dongjia I/Freeline: start to inject native lib...
10-27 10:37:50.668 31606-31606/cc.kaipao.dongjia I/Freeline.hackNative: native lib inject process start...
10-27 10:37:50.669 31606-31606/cc.kaipao.dongjia I/Freeline.hackNative: inject native lib success [Ljava.io.File;@4225b708
10-27 10:37:50.669 31606-31606/cc.kaipao.dongjia I/Freeline: freeline init server
10-27 10:37:50.671 31606-31606/cc.kaipao.dongjia D/dongjia: freeline launched success
10-27 10:37:50.671 31606-31606/cc.kaipao.dongjia D/dalvikvm: create interp thread : stack size=128KB
10-27 10:37:50.671 31606-31606/cc.kaipao.dongjia D/dalvikvm: create new thread
10-27 10:37:50.671 31606-31606/cc.kaipao.dongjia D/dalvikvm: new thread created
10-27 10:37:50.671 31606-31606/cc.kaipao.dongjia D/dalvikvm: update thread list
10-27 10:37:50.671 31606-31636/cc.kaipao.dongjia D/dalvikvm: threadid=10: interp stack at 0x642df000
10-27 10:37:50.671 31606-31636/cc.kaipao.dongjia D/dalvikvm: threadid=10: created from interp
10-27 10:37:50.673 31606-31606/cc.kaipao.dongjia D/dalvikvm: start new thread
10-27 10:37:50.673 31606-31636/cc.kaipao.dongjia D/dalvikvm: threadid=10: notify debugger
10-27 10:37:50.673 31606-31636/cc.kaipao.dongjia D/dalvikvm: threadid=10 (SharedPreferencesImpl-load): calling run()
10-27 10:37:50.673 31606-31606/cc.kaipao.dongjia D/dalvikvm: create interp thread : stack size=128KB
10-27 10:37:50.673 31606-31606/cc.kaipao.dongjia D/dalvikvm: create new thread
10-27 10:37:50.673 31606-31606/cc.kaipao.dongjia D/dalvikvm: new thread created
10-27 10:37:50.673 31606-31606/cc.kaipao.dongjia D/dalvikvm: update thread list
10-27 10:37:50.673 31606-31638/cc.kaipao.dongjia D/dalvikvm: threadid=11: interp stack at 0x643fd000
10-27 10:37:50.673 31606-31638/cc.kaipao.dongjia D/dalvikvm: threadid=11: created from interp
10-27 10:37:50.673 31606-31606/cc.kaipao.dongjia D/dalvikvm: start new thread
10-27 10:37:50.674 31606-31638/cc.kaipao.dongjia D/dalvikvm: threadid=11: notify debugger
10-27 10:37:50.674 31606-31638/cc.kaipao.dongjia D/dalvikvm: threadid=11 (SharedPreferencesImpl-load): calling run()
10-27 10:37:50.674 31606-31638/cc.kaipao.dongjia D/dalvikvm: threadid=11: exiting
10-27 10:37:50.674 31606-31638/cc.kaipao.dongjia D/dalvikvm: threadid=11: bye!
10-27 10:37:50.676 31606-31606/cc.kaipao.dongjia D/AndroidRuntime: Shutting down VM
10-27 10:37:50.676 31606-31606/cc.kaipao.dongjia W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41d49ce0)
10-27 10:37:50.676 31606-31606/cc.kaipao.dongjia W/dalvikvm: threadid=1: uncaught exception occurred
10-27 10:37:50.676 31606-31606/cc.kaipao.dongjia W/System.err: java.lang.NoClassDefFoundError: com.cyou.mobile.common.DeviceUtil
10-27 10:37:50.676 31606-31606/cc.kaipao.dongjia W/System.err:     at cc.kaipao.dongjia.app.KaiPaoApplication.onCreate(KaiPaoApplication.java:101)
10-27 10:37:50.676 31606-31606/cc.kaipao.dongjia W/System.err:     at com.antfortune.freeline.FreelineApplication.startRealApplication(FreelineApplication.java:51)
10-27 10:37:50.676 31606-31606/cc.kaipao.dongjia W/System.err:     at com.antfortune.freeline.FreelineApplication.onCreate(FreelineApplication.java:32)
10-27 10:37:50.676 31606-31606/cc.kaipao.dongjia W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1016)
10-27 10:37:50.676 31606-31606/cc.kaipao.dongjia W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4590)
10-27 10:37:50.677 31606-31606/cc.kaipao.dongjia W/System.err:     at android.app.ActivityThread.access$1500(ActivityThread.java:157)
10-27 10:37:50.677 31606-31606/cc.kaipao.dongjia W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
10-27 10:37:50.677 31606-31606/cc.kaipao.dongjia W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
10-27 10:37:50.677 31606-31606/cc.kaipao.dongjia W/System.err:     at android.os.Looper.loop(Looper.java:193)
10-27 10:37:50.677 31606-31606/cc.kaipao.dongjia W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5348)
10-27 10:37:50.677 31606-31606/cc.kaipao.dongjia W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
10-27 10:37:50.677 31606-31606/cc.kaipao.dongjia W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
10-27 10:37:50.677 31606-31606/cc.kaipao.dongjia W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
10-27 10:37:50.677 31606-31606/cc.kaipao.dongjia W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
10-27 10:37:50.677 31606-31606/cc.kaipao.dongjia W/System.err:     at dalvik.system.NativeStart.main(Native Method)
10-27 10:37:50.677 31606-31606/cc.kaipao.dongjia W/dalvikvm: threadid=1: calling UncaughtExceptionHandler
10-27 10:37:50.677 31606-31606/cc.kaipao.dongjia I/dalvikvm: +++ calling Ljava/lang/ThreadGroup;.uncaughtException
10-27 10:37:50.678 31606-31636/cc.kaipao.dongjia D/dalvikvm: threadid=10: exiting
10-27 10:37:50.678 31606-31636/cc.kaipao.dongjia D/dalvikvm: threadid=10: bye!
10-27 10:37:50.678 31606-31606/cc.kaipao.dongjia E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: cc.kaipao.dongjia, PID: 31606
                                                                   java.lang.NoClassDefFoundError: com.cyou.mobile.common.DeviceUtil
                                                                       at cc.kaipao.dongjia.app.KaiPaoApplication.onCreate(KaiPaoApplication.java:101)
                                                                       at com.antfortune.freeline.FreelineApplication.startRealApplication(FreelineApplication.java:51)
                                                                       at com.antfortune.freeline.FreelineApplication.onCreate(FreelineApplication.java:32)
                                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1016)
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4590)
                                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:157)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                       at android.os.Looper.loop(Looper.java:193)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5348)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
                                                                       at dalvik.system.NativeStart.main(Native Method)
````

**Comment by lomanyong** [comment]
Caused by: java.lang.NoClassDefFoundError: android.support.multidex.MultiDex

看报错的内容，是否加入MultiDex的依赖了呢？

**Comment by sivan67** [comment]
加入了的。正常运行程序没问题。使用 Freeline 就会挂掉

**Comment by lomanyong** [comment]
@sivan67 加入一个配置：
````
freeline {
    ....
    applicationProxy false
}
````

在你的Application类的onCreate()中，加入`FreelineCore.init(this);`

clean一下，重新编译..应该可以解决你的问题

**Comment by mianamiana** [comment]
噗，我跟你出现了一模一样的问题，连日志报错都一样（包名不同）。
环境： Freeline-0.7.3.1 ;    Android Studio-2.2;    android.tools.build:gradle-2.1.3
@lomanyong  按你的方法可以了

**Comment by sivan67** [comment]
@lomanyong 加了 applicationProxy false 好了。thx

**Comment by sivan67** [comment]
@mianamiana 哈哈  好了就行

**Comment by mianamiana** [comment]
@lomanyong @sivan67  
另一个解决方式：我升级了下as和tool   Android Studio-2.2.2  ,android.tools.build:gradle-2.2.2  
这样不需要在application里init也不需要   applicationProxy false就可以了

**Comment by sivan67** [comment]
@mianamiana 试了可以
