### ISSUE TITLE
Didn't find class "com.antfortune.freeline.FreelineConfig" 有用到MultiDex分包

### ISSUE THREAD

**Issue by weixiaowu** [alibaba/freeline#238]
````
10-27 14:47:07.051 5292-5292/? E/Freeline: java.lang.ClassNotFoundException: com.antfortune.freeline.FreelineConfig
                                               at java.lang.Class.classForName(Native Method)
                                               at java.lang.Class.forName(Class.java:251)
                                               at java.lang.Class.forName(Class.java:216)
                                               at com.antfortune.freeline.FreelineApplication.initFreelineConfig(FreelineApplication.java:58)
                                               at com.antfortune.freeline.FreelineApplication.onCreate(FreelineApplication.java:29)
                                               at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4359)
                                               at android.app.ActivityThread.access$1500(ActivityThread.java:136)
                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1279)
                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                               at android.os.Looper.loop(Looper.java:136)
                                               at android.app.ActivityThread.main(ActivityThread.java:5032)
                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                               at dalvik.system.NativeStart.main(Native Method)
                                            Caused by: java.lang.NoClassDefFoundError: com/antfortune/freeline/FreelineConfig
                                               at java.lang.Class.classForName(Native Method) 
                                               at java.lang.Class.forName(Class.java:251) 
                                               at java.lang.Class.forName(Class.java:216) 
                                               at com.antfortune.freeline.FreelineApplication.initFreelineConfig(FreelineApplication.java:58) 
                                               at com.antfortune.freeline.FreelineApplication.onCreate(FreelineApplication.java:29) 
                                               at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014) 
                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4359) 
                                               at android.app.ActivityThread.access$1500(ActivityThread.java:136) 
                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1279) 
                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                               at android.os.Looper.loop(Looper.java:136) 
                                               at android.app.ActivityThread.main(ActivityThread.java:5032) 
                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                               at dalvik.system.NativeStart.main(Native Method) 
                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "com.antfortune.freeline.FreelineConfig" on path: DexPathList[[zip file "/data/app/com.xxx.xxx-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.xxx.xxx-2, /vendor/lib, /system/lib]]
                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                               at java.lang.Class.classForName(Native Method) 
                                               at java.lang.Class.forName(Class.java:251) 
                                               at java.lang.Class.forName(Class.java:216) 
                                               at com.antfortune.freeline.FreelineApplication.initFreelineConfig(FreelineApplication.java:58) 
                                               at com.antfortune.freeline.FreelineApplication.onCreate(FreelineApplication.java:29) 
                                               at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014) 
                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4359) 
                                               at android.app.ActivityThread.access$1500(ActivityThread.java:136) 
                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1279) 
                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                               at android.os.Looper.loop(Looper.java:136) 
                                               at android.app.ActivityThread.main(ActivityThread.java:5032) 
                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                               at dalvik.system.NativeStart.main(Native Method) 
10-27 14:47:07.051 5292-5292/? E/FreelineApplication: initFreelineConfig error
10-27 14:47:07.056 5292-5292/? E/Freeline: java.lang.NullPointerException
                                               at com.antfortune.freeline.util.ReflectUtil.getStaticFieldValue(ReflectUtil.java:84)
                                               at com.antfortune.freeline.FreelineApplication.getConfigValue(FreelineApplication.java:67)
                                               at com.antfortune.freeline.FreelineApplication.createRealApplication(FreelineApplication.java:76)
                                               at com.antfortune.freeline.FreelineApplication.onCreate(FreelineApplication.java:30)
                                               at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4359)
                                               at android.app.ActivityThread.access$1500(ActivityThread.java:136)
                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1279)
                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                               at android.os.Looper.loop(Looper.java:136)
                                               at android.app.ActivityThread.main(ActivityThread.java:5032)
                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                               at dalvik.system.NativeStart.main(Native Method)
````

**Comment by lomanyong** [comment]
@weixiaowu 是否配置了`applicationProxy false`呢？

可以看下`${main_module}/build/generated/freeline/com/antfortune/freeline/FreelineConfig.java`这个文件是否存在。

**Comment by weixiaowu** [comment]
我加了applicationProxy false，  再clean工程就好了，但是出现编译不通过，项目混淆是关闭的，错误日志如下
D:\workspace\trunk\Sources\Security\xxxx_Android\xxxx_app\build\freeline\xxxx_app\backup\res\values\freeline_id_keeper_public.xml:11648: error: Public symbol style/colligate_view_divide declared here is not defined.
D:\workspace\trunk\Sources\Security\xxxx_Android\xxxx_app\build\freeline\xxxx_app\backup\res\values\freeline_id_keeper_public.xml:11774: error: Public symbol style/winners_list_department_name declared here is not defined.
D:\workspace\trunk\Sources\Security\xxxx_Android\xxxx_app\build\freeline\xxxx_app\backup\res\values\freeline_id_keeper_public.xml:11776: error: Public symbol style/winners_list_department_value declared here is not defined.

[ERROR] --------------------------------------------------------
[ERROR] build base resources failed with: freeline\release-tools\FreelineAapt.exe package -f -I D:\adt-bundle-windows-x86-20140702\sdk\platforms\android-15\android.jar -M D:\workspace\trunk\Sources\Security\xxxx_Android\xxxx_app\build\intermediates\manifests\full\debug\AndroidManifest.xml -S D:\workspace\trunk\Sources\Security\xxxx_Android\xxxx_app\res -S D:\workspace\trunk\Sources\Security\xxxx_Android\xxxx_app\build\intermediates\exploded-aar\com.antfortune.freeline\runtime\0.7.3.1\res -S D:\workspace\trunk\Sources\Security\xxxx_Android\xxxx_app\build\intermediates\exploded-aar\com.android.support\support-v4\23.1.1\res -S D:\workspace\trunk\Sources\Security\xxxx_Android\xxxx_app\build\intermediates\exploded-aar\com.android.support\multidex\1.0.1\res -S D:\workspace\trunk\Sources\Security\xxxx_Android\xxxx_app\build\intermediates\exploded-aar\pulltorefresh-lib\res -S D:\workspace\trunk\Sources\Security\xxxx_Android\xxxx_app\build\freeline\xxxx_app\backup\res -A D:\workspace\trunk\Sources\Security\xxxx_Android\xxxx_app\build\freeline\freeline-assets -A D:\workspace\trunk\Sources\Security\xxxx_Android\xxxx_app\assets -A D:\workspace\trunk\Sources\Security\xxxx_Android\xxxx_app\build\intermediates\exploded-aar\com.antfortune.freeline\runtime\0.7.3.1\assets -A D:\workspace\trunk\Sources\Security\xxxx_Android\xxxx_app\build\intermediates\exploded-aar\com.android.support\support-v4\23.1.1\assets -A D:\workspace\trunk\Sources\Security\xxxx_Android\xxxx_app\build\intermediates\exploded-aar\com.android.support\multidex\1.0.1\assets -A D:\workspace\trunk\Sources\Security\xxxx_Android\xxxx_app\build\intermediates\exploded-aar\pulltorefresh-lib\assets -m -J D:\workspace\trunk\Sources\Security\xxxx_Android\xxxx_app\build\freeline\xxxx_app\backup --auto-add-overlay -F D:\workspace\trunk\Sources\Security\xxxx_Android\xxxx_app\build\freeline\base-res.so --debug-mode --no-version-vectors --resoucres-md5-cache-path D:\workspace\trunk\Sources\Security\xxxx_Android\xxxx_app\build\freeline\arsc_cache.dat --ignore-assets public_id.xml:public.xml:*.bak:.*
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.4s
[DEBUG] Task engine running time: 81.5s
[DEBUG] Total time: 81.8s
[DEBUG] ----------

\build\freeline\jar_dependencies.json 的内容是这样的
[
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\libs\\locSDK_4.2.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\libs\\cordova-2.9.0.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\libs\\miniLZO.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\libs\\open_sdk_r5509.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\libs\\cairh_sjkhapp_framework4other.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\libs\\hybrid-lib.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\libs\\nineoldandroids-2.2.0.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\libs\\Volley.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\libs\\eno_net.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\libs\\MCAndroidAPI.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\libs\\tmmssuitesdk.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\libs\\libammsdk.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\libs\\gson-2.2.1.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\libs\\mta-sdk-1.6.2.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\libs\\hybrid-plugins.jar",
    "D:\\adt-bundle-windows-x86-20140702\\sdk\\extras\\android\\m2repository\\com\\android\\support\\support-annotations\\23.1.1\\support-annotations-23.1.1.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\build\\intermediates\\exploded-aar\\pulltorefresh-lib\\jars\\classes.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\build\\intermediates\\exploded-aar\\com.android.support\\multidex\\1.0.1\\jars\\classes.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\build\\intermediates\\exploded-aar\\com.android.support\\support-v4\\23.1.1\\jars\\classes.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\build\\intermediates\\exploded-aar\\com.android.support\\support-v4\\23.1.1\\jars\\libs\\internal_impl-23.1.1.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\build\\intermediates\\exploded-aar\\com.antfortune.freeline\\runtime\\0.7.3.1\\jars\\classes.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\build\\intermediates\\exploded-aar\\xxxx_Android\\trade_module\\unspecified\\jars\\classes.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\build\\intermediates\\exploded-aar\\xxxx_Android\\common_module\\unspecified\\jars\\classes.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\build\\intermediates\\exploded-aar\\xxxx_Android\\trade_module\\unspecified\\jars\\libs\\adf_v1.2.4.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\build\\intermediates\\exploded-aar\\xxxx_Android\\trade_module\\unspecified\\jars\\libs\\android-async-http-1.4.4.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\build\\intermediates\\exploded-aar\\xxxx_Android\\trade_module\\unspecified\\jars\\libs\\httpmime-4.2.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\build\\intermediates\\exploded-aar\\xxxx_Android\\trade_module\\unspecified\\jars\\libs\\mframework.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\build\\intermediates\\exploded-aar\\xxxx_Android\\trade_module\\unspecified\\jars\\libs\\thinkive_gszq.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\build\\intermediates\\exploded-aar\\xxxx_Android\\common_module\\unspecified\\jars\\libs\\android-dtk-packet.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\build\\intermediates\\exploded-aar\\xxxx_Android\\common_module\\unspecified\\jars\\libs\\android-dtk.jar",
    "D:\\workspace\\trunk\\Sources\\Security\\xxxx_Android\\xxxx_app\\build\\intermediates\\exploded-aar\\xxxx_Android\\common_module\\unspecified\\jars\\libs\\sun.misc.BASE64Decoder.jar"
]

**Comment by lomanyong** [comment]
@weixiaowu 一般来说没理由出现两次资源编译出现不同的结果...可以再`python freeline.py -f`看下。

**Comment by weixiaowu** [comment]
@lomanyong 我这个项目分成main_module， trade_module(这是个library, 都是这个module下的资源找不到) ， common_module(也是个library, 这下面没资源)

**Comment by weixiaowu** [comment]
@lomanyong 现在是全量编译可以通过，但增量编译就报找不到module 下的资源就找不到，导致编译失败

**Comment by lomanyong** [comment]
@weixiaowu 恩，我记得你发过你的详细日志给我...我用你的日志尝试复现过，没能复现出问题来。一个快速解决的办法，你可以知道你们模块的资源文件夹路径的，比如`trade_module/src/main/res`，可以把这种路径加入到配置中，比如：
````gradle
freeline {
    ...
    extraResourceDependencyPaths = ["path-prefix/trade_module/src/main/res", "second-path",  ...]
}
````

然后，重新编译看看是否能够暂时解决你的问题。

你那边具体的问题原因可能还需要进一步的日志和分析才能找到原因，我会邮件给你哈~

**Comment by weixiaowu** [comment]
@lomanyong 这个方法完美解决了我的问题，非常感谢您这么及时的帮助

**Comment by weixiaowu** [comment]
@lomanyong 这个方法完美解决了我的问题，非常感谢您这么及时的帮助

**Comment by weixiaowu** [comment]
@lomanyong 这个方法完美解决了我的问题，非常感谢您这么及时的帮助

**Comment by lomanyong** [comment]
@weixiaowu 好的，有问题可以继续提issue哈
