### ISSUE TITLE
art/runtime/check_jni.cc:70 报错而崩溃

### ISSUE THREAD

**Issue by msdx** [alibaba/freeline#242]
使用到了地图界面，有时会出现下面的异常导致崩溃退出：

```
10-28 11:24:11.209 21937-23137/com.parkingwang.app A/art: art/runtime/check_jni.cc:70] JNI DETECTED ERROR IN APPLICATION: jarray was NULL
10-28 11:24:11.209 21937-23137/com.parkingwang.app A/art: art/runtime/check_jni.cc:70]     in call to GetByteArrayElements
10-28 11:24:11.209 21937-23137/com.parkingwang.app A/art: art/runtime/check_jni.cc:70]     from void com.autonavi.amap.mapcore.MapCore.nativeSetInternaltexture(long, byte[], int)
10-28 11:24:11.209 21937-23137/com.parkingwang.app A/art: art/runtime/check_jni.cc:70] "GLThread 3381" prio=5 tid=47 Runnable
10-28 11:24:11.209 21937-23137/com.parkingwang.app A/art: art/runtime/check_jni.cc:70]   | group="main" sCount=0 dsCount=0 obj=0x12c19770 self=0xd5116800
10-28 11:24:11.209 21937-23137/com.parkingwang.app A/art: art/runtime/check_jni.cc:70]   | sysTid=23137 nice=0 cgrp=default sched=0/0 handle=0xeec3c000
10-28 11:24:11.209 21937-23137/com.parkingwang.app A/art: art/runtime/check_jni.cc:70]   | state=R schedstat=( 8239462 1661765 39 ) utm=0 stm=0 core=3 HZ=100
10-28 11:24:11.209 21937-23137/com.parkingwang.app A/art: art/runtime/check_jni.cc:70]   | stack=0xdd54f000-0xdd551000 stackSize=1036KB
10-28 11:24:11.209 21937-23137/com.parkingwang.app A/art: art/runtime/check_jni.cc:70]   | held mutexes= "mutator lock"(shared held)
10-28 11:24:11.209 21937-23137/com.parkingwang.app A/art: art/runtime/check_jni.cc:70]   at com.autonavi.amap.mapcore.MapCore.nativeSetInternaltexture(Native method)
10-28 11:24:11.209 21937-23137/com.parkingwang.app A/art: art/runtime/check_jni.cc:70]   at com.autonavi.amap.mapcore.MapCore.setInternaltexture(MapCore.java:135)
10-28 11:24:11.209 21937-23137/com.parkingwang.app A/art: art/runtime/check_jni.cc:70]   at com.amap.api.col.s.e(GLMapResManager.java:462)
10-28 11:24:11.209 21937-23137/com.parkingwang.app A/art: art/runtime/check_jni.cc:70]   at com.amap.api.col.h.s(AMapDelegateImp.java:1122)
10-28 11:24:11.209 21937-23137/com.parkingwang.app A/art: art/runtime/check_jni.cc:70]   - locked <0x01f46fc7> (a com.amap.api.col.h)
10-28 11:24:11.209 21937-23137/com.parkingwang.app A/art: art/runtime/check_jni.cc:70]   at com.amap.api.col.h.onSurfaceCreated(AMapDelegateImp.java:4328)
10-28 11:24:11.209 21937-23137/com.parkingwang.app A/art: art/runtime/check_jni.cc:70]   at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1548)
10-28 11:24:11.209 21937-23137/com.parkingwang.app A/art: art/runtime/check_jni.cc:70]   at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)
10-28 11:24:11.209 21937-23137/com.parkingwang.app A/art: art/runtime/check_jni.cc:70] 
```

**Comment by lomanyong** [comment]
@msdx 这个日志还真没办法看出是freeline在哪里引起了crash了...可能跟第三方sdk的某些生命周期相关？可能需要更加详细的日志来辅助判断看看...

**Comment by msdx** [comment]
@lomanyong 之前在使用instant run的时候也是有报这个问题，然后我改用freeline试了一下，昨天一直没出现这个问题，能正常开发，到今晚就发现也跟着报这个问题了。

**Comment by msdx** [comment]
`python freeline.py -f`后能正常。而且这个问题在instant run中是必现，在freeline中有时不会出现，出现之后可以使用-f。
目前这个问题我也在高德开发者后台中提交了工单了。

**Comment by lomanyong** [comment]
@msdx get，感谢提供case
