### ISSUE TITLE
执行报错

### ISSUE THREAD

**Issue by msdx** [alibaba/freeline#245]
日志如下：
```
[INFO] preparing for tasks...
[-][connect_device_task] finished. in 0.1s
[-][gradle_aapt_task] finished. in 0.7s
[-][api] failed. in 0.0s
[-][app] failed. in 0s
[-][merge_dex_task] failed. in 0s
[-][gradle_sync_task] failed. in 0s
[-][clean_cache_task] failed. in 0s
[-][update_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/project/park-here-android/freeline/freeline_core/android_tools.py", line 318, in execute
    self._command.execute()
  File "/workspace/project/park-here-android/freeline/freeline_core/gradle_inc_build.py", line 176, in execute
    map(lambda command: command.execute(), self.command_list)
  File "/workspace/project/park-here-android/freeline/freeline_core/gradle_inc_build.py", line 176, in <lambda>
    map(lambda command: command.execute(), self.command_list)
  File "/workspace/project/park-here-android/freeline/freeline_core/gradle_inc_build.py", line 210, in execute
    self._invoker.append_r_file()
  File "/workspace/project/park-here-android/freeline/freeline_core/gradle_inc_build.py", line 395, in append_r_file
    if os.path.exists(fpath):
  File "/usr/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

[ERROR] --------------------------------------------------------
[ERROR] incremental build task failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.1s
[DEBUG] Task engine running time: 0.7s
[DEBUG] Total time: 0.8s
[DEBUG] --------------------------------------------------------
```

**Comment by lomanyong** [comment]
@msdx 貌似用的不是新版本的？在某个版本中已经fix了这个问题了...

**Comment by msdx** [comment]
@lomanyong 前几天刚用的，0.7.3.1。只出现过一次。

**Comment by lomanyong** [comment]
@msdx 报错的那行代码在某个较早的版本里已经加了判空处理...如果用的新版本的话通常不会报错才对..

````python
if fpath and os.path.exists(fpath):
    self._changed_files['src'].append(fpath)
    self.debug('add R.java to changed list: ' + fpath)
````

**Comment by msdx** [comment]
@lomanyong 这个我就不清楚了，这个问题只出现过一次，重新编译之后正常了我也没注意。

**Comment by lomanyong** [comment]
@msdx issue我先close了，应该是已经修复过的问题。下次如果出现的话，麻烦可以打开指定的文件看下crash的地方，是否代码是错误的哈~

**Comment by msdx** [comment]
@lomanyong 今天又发生了这个错误。
你说的加判空处理的不知道是指哪一行

**Comment by msdx** [comment]
版本如下：
```
haohang@haohang-desktop:/workspace/project/park-here-android$ python freeline.py -v
v0.7.3
```

**Comment by lomanyong** [comment]
@msdx `freeline_core/gradle_inc_build.py`这个文件。直接搜索关键字`if fpath and os.path.exists(fpath):`或者`self.debug('add R.java to changed list: ' + fpath)`

**Comment by msdx** [comment]
我稍后更新到0.8看看。

**Comment by lomanyong** [comment]
@msdx `freeline_core/gradle_inc_build.py`，这个可以搜索看看~

**Comment by lomanyong** [comment]
@msdx 我知道问题在哪了= =...0.7.3.1加入的fix，但是你用的是0.7.3。。

**Comment by msdx** [comment]
嗯，我刚才也发现了。
