### ISSUE TITLE
collecting project info, please wait a while...一直在这个状态，不动了

### ISSUE THREAD

**Issue by junjle** [alibaba/freeline#255]
C:\code\trunk>python freeline.py
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=False, init=False, version=False)
[DEBUG] collecting project info, please wait a while...

**Comment by lomanyong** [comment]
@junjle 用的是哪个版本的？

**Comment by junjle** [comment]
0.8.0

**Comment by junjle** [comment]
另外我问一下，freeline的不同版本和AndroidStudio版本，python版本，还有windows版本有什么关系吗，会出现版本不一致导致不能使用得情况吗

**Comment by lomanyong** [comment]
@junjle python版本2.7就行...跟windows版本无关。可以clean一下重新编译吗？

**Comment by junjle** [comment]
[dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=True, debug=False, init=False, version=False)
collecting project info, please wait a while...

[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "C:\code\trunk\freeline_core\dispatcher.py", line 87, in _exec_command
    command.execute()
  File "C:\code\trunk\freeline_core\build_commands.py", line 11, in execute
    map(lambda command: command.execute(), self.command_list)
  File "C:\code\trunk\freeline_core\build_commands.py", line 11, in <lambda>
    map(lambda command: command.execute(), self.command_list)
  File "C:\code\trunk\freeline_core\build_commands.py", line 40, in execute
    self._builder.check_build_environment()
  File "C:\code\trunk\freeline_core\gradle_clean_build.py", line 27, in check_build_environment
    self._project_info = get_project_info(self._config)
  File "C:\code\trunk\freeline_core\gradle_tools.py", line 1062, in get_project_info
    get_local_resources_dependencies('assets', config, module, project_info)
  File "C:\code\trunk\freeline_core\gradle_tools.py", line 1085, in get_local_resources_dependencies
    local_res_deps.extend(dep['local_resources'])
MemoryError

[ERROR] --------------------------------------------------------
[ERROR]

**Comment by junjle** [comment]
很长时间之后报了这个错误

**Comment by lomanyong** [comment]
@junjle 看样子是死循环了。

想起来你之前给我发过邮件，有重复的10w行的cache生成...

把你这次生成的`project_info_cache.json`跟`project_description.json`文件上传一下吧，我之前用你的这两份缓存文件没有跑出异常来，我在试试看。

**Comment by junjle** [comment]
@lomanyong 完美的解决了我的问题，阿里的工程师果然是大牛，支持freeline
