### ISSUE TITLE
 python freeline.py 后报OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ChenLingxiu** [alibaba/freeline#257]
➜  wangxin git:(dev-wx-xplugin-201611) ✗ python freeline.py  
[INFO] preparing for tasks...
[-][read_project_info_task] finished. in 11.9s
[-][generate_file_stat_task] finished. in 0.2s
[-][gradle_clean_build_task] failed. in 0.0s
[-][clean_all_cache_task] failed. in 0s
[-][install_apk_task] failed. in 0s
[-][build_base_resource_task] failed. in 0s
[-][generate_project_info_task] failed. in 0s
[-][append_file_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mayongge/gitlab/wangxin/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/Users/mayongge/gitlab/wangxin/freeline/freeline_core/gradle_clean_build.py", line 112, in execute
    output, err, code = cexec(command.split(' '), callback=None, cwd=cwd)
  File "/Users/mayongge/gitlab/wangxin/freeline/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

出错的IDE的环境是
Android studio 2.2.1， jdk 8 ，freeline 版本是0.7.3.1.
android {
    freeline {
        productFlavor 'normal'
        applicationProxy false
        apkPath "$project.buildDir/outputs/apk/wangxin_android-normal-debug.apk"
        buildScript "gradle :wangxin_android:assembleNormalDebug -Puse_wxlib_jnilibs=false"
    }
application.onCreate()已添加FreelineCore.init()。

已尝试过重新initFreeline和 chgmod +x ./gradlew，并没有修正这个错误，但是在两一台使用Android studio 2.1.1 jdk 7 的机器执行python freeline.py  没有报错。请问如何排查错误原因和修复错误？

**Comment by ChenLingxiu** [comment]
已经发现原因了，是我设置buildScript不够通用。 "gradle :wangxin_android:assembleNormalDebug -Puse_wxlib_jnilibs=false"这句要求有系统变量gradle，改成./gradlew 后就没报错了。麻烦了～多谢提供优秀的工具，100个赞
