### ISSUE TITLE
使用android studio自带build方式启动应用crash

### ISSUE THREAD

**Issue by vipjinxiao** [alibaba/freeline#265]
接入freeline后，全量编译和增量编译都没有问题。但我今天偶然点了一次android studio自带的“Run”，发现应用启动后会crash，其中和freeline相关的log为：
E/FreelineApplication: initFreelineConfig error
E/Freeline: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.reflect.Field java.lang.Class.getDeclaredField(java.lang.String)' on a null object reference
                                                                   at com.antfortune.freeline.util.ReflectUtil.getStaticFieldValue(ReflectUtil.java:84)
                                                                   at com.antfortune.freeline.FreelineApplication.getConfigValue(FreelineApplication.java:67)
                                                                   at com.antfortune.freeline.FreelineApplication.createRealApplication(FreelineApplication.java:76)
                                                                   at com.antfortune.freeline.FreelineApplication.onCreate(FreelineApplication.java:30)
                                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
                                                                   at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

之后重新使用freeline全量编译发现又好用了，请问这是设计如此吗？还是有哪里设置不对

**Comment by lomanyong** [comment]
@vipjinxiao 不是额，其实你如果clean一下，再使用as的run的话是没有问题的。出现问题的原因是因为缓存manifest没有更新导致启动时仍然启动了FreelineApplication，但是不是使用Freeline来build的话，不会生成FreelineConfig类，所以会出现上面的crash。

如果你要正常使用as的build的话，记得在使用完freeline后，先clean一下。
