### ISSUE TITLE
无法找到R.java

### ISSUE THREAD

**Issue by yangxuecheng** [alibaba/freeline#267]
1）第一步
````
 ~/w/A/banma_android_crowdsource on cs-2.3.0 ⨯ python2 freeline.py -f                                                                                                                  14:51:09
[INFO] preparing for tasks...
[-][read_project_info_task] finished. in 7.3s
[-][generate_file_stat_task] finished. in 0.1s
[-][gradle_clean_build_task] finished. in 48.4s
[-][clean_all_cache_task] finished. in 0.0s
[-][install_apk_task] finished. in 14.1s
[-][build_base_resource_task] finished. in 5.0s
[-][generate_project_info_task] finished. in 0.0s
[-][generate_apt_files_task] finished. in 0.0s
[-][append_file_stat_task] finished. in 0.0s
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.1s
[DEBUG] Task engine running time: 69.8s
[DEBUG] Total time: 69.9s
[DEBUG] --------------------------------------------------------
````

2)第二步
````
~/w/A/banma_android_crowdsource on cs-2.3.0 ⨯ python2 freeline.py                                                                                                                                   14:52:24
[INFO] preparing for tasks...
[-][connect_device_task] finished. in 0.2s
[-][gradle_aapt_task] failed. in 0.9s
[-][network] failed. in 0s
[-][amap] failed. in 0s
[-][model] failed. in 0s
[-][meituanpai] failed. in 0s
[-][crowdsource] failed. in 0s
[-][merge_dex_task] failed. in 0s
[-][gradle_sync_task] failed. in 0s
[-][clean_cache_task] failed. in 0s
[-][update_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yangxuecheng/workspace/Android Projects/banma_android_crowdsource/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/Users/****/workspace/Android Projects/banma_android_crowdsource/freeline/freeline_core/gradle_inc_build.py", line 170, in execute
    self._invoker.check_other_modules_resources()
  File "/Users/****/workspace/Android Projects/banma_android_crowdsource/freeline/freeline_core/gradle_inc_build.py", line 447, in check_other_modules_resources
    self.__modify_main_r()
  File "/Users/****/workspace/Android Projects/banma_android_crowdsource/freeline/freeline_core/gradle_inc_build.py", line 460, in __modify_main_r
    write_file_content(main_r_fpath, buf)
  File "/Users/****/workspace/Android Projects/banma_android_crowdsource/freeline/freeline_core/utils.py", line 118, in write_file_content
    with open(target_path, 'w') as fp:
IOError: [Errno 2] No such file or directory: u'/Users/****/workspace/Android Projects/banma_android_crowdsource/crowdsource/build/freeline/crowdsource/backup/com/****/banma/R.java'
````

3）freeline的build的文件夹，freeline-backup文件夹为空

**Comment by yangxuecheng** [comment]
Solved

**Comment by lomanyong** [comment]
@yangxuecheng hi，回晚了，什么问题导致的呢？

**Comment by yangxuecheng** [comment]
@lomanyong  因为我们的applicationId和manifest里面的packagename不同，导致生成的主模块的backup的R.java路径不对造成的。

我看了下源码

`class FreelineParser {

    public static String getPackageName(String applicationId, String manifestPath) {
        if (!FreelineUtils.isEmpty(applicationId) && !"null".equals(applicationId)) {
            return applicationId
        }
        return getPackage(manifestPath)
    }
}`

这里packagneme直接是拿的applicationId，而这两者是有可能不同的。

我是通过直接在gradle_tools里面把self._package_name替换为我的项目的packagename解决的。

` def get_backup_r_path(self):
        return os.path.join(self.get_backup_dir(), self._package_name.replace('.', os.sep), 'R.java')
`

getPackageName是不是可以改为直接从manifest里取，对其他功能有没有影响这个我就不太清楚了。

**Comment by lomanyong** [comment]
@yangxuecheng 应该是可以直接加配置解决的：

````gradle
freeline {
    ....
    packageName "your-package-name"
}
````
