### ISSUE TITLE
Application 类没有被初始化

### ISSUE THREAD

**Issue by chenzhong13** [alibaba/freeline#273]
在我们的应用中使用 freeline 后，能否正常打包和安装，但是一运行就 crash，原因是一些需要在 Application#onCreate 方法中进行初始化的东西没有被初始化。
我在 Application#onCreate 中进行了日志打印，发现没有在控制台输入日志，所以怀疑是我们的 Application 类没有被正常调用。

我写的 demo 小程序是可以的，Application 也可以正常调用。

请问是什么原因呢？

我使用 productFlavor 指定了 flavor，应用开启了 multidex，其它和你们的官方教程一致，使用的版本是最新的 0.8.1

**Comment by lomanyong** [comment]
@chenzhong13 简单的解决方法，加入一个配置项：

````gradle
freeline {
    applicationProxy false
}
````

在你的Application类中加入：
````java
public class YourApplication extends Application {
    
    public onCreate() {
         super.onCreate();
         FreelineCore.init(this);
    }
}
````

然后clean，重新打包即可解决你的问题了。

**Comment by candledragle** [comment]
06-29 12:23:48.659 12808-12808/com.longfor.property:freeline E/Freeline: java.net.BindException: bind failed: EADDRINUSE (Address already in use)
                                                                             at libcore.io.IoBridge.bind(IoBridge.java:99)
                                                                             at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:132)
                                                                             at java.net.ServerSocket.<init>(ServerSocket.java:105)
                                                                             at java.net.ServerSocket.<init>(ServerSocket.java:74)
                                                                             at com.antfortune.freeline.server.EmbedHttpServer.start(EmbedHttpServer.java:25)
                                                                             at com.antfortune.freeline.server.LongLinkServer.start(LongLinkServer.java:154)
                                                                             at com.antfortune.freeline.FreelineService.onStartCommand(FreelineService.java:40)
                                                                             at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2864)
                                                                             at android.app.ActivityThread.access$2100(ActivityThread.java:144)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
                                                                          Caused by: android.system.ErrnoException: bind failed: EADDRINUSE (Address already in use)
                                                                             at libcore.io.Posix.bind(Native Method)
                                                                             at libcore.io.ForwardingOs.bind(ForwardingOs.java:56)
                                                                             at libcore.io.IoBridge.bind(IoBridge.java:97)
                                                                             at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:132) 
                                                                             at java.net.ServerSocket.<init>(ServerSocket.java:105) 
                                                                             at java.net.ServerSocket.<init>(ServerSocket.java:74) 
                                                                             at com.antfortune.freeline.server.EmbedHttpServer.start(EmbedHttpServer.java:25) 
                                                                             at com.antfortune.freeline.server.LongLinkServer.start(LongLinkServer.java:154) 
                                                                             at com.antfortune.freeline.FreelineService.onStartCommand(FreelineService.java:40) 
                                                                             at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2864) 
                                                                             at android.app.ActivityThread.access$2100(ActivityThread.java:144) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5221) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
