### ISSUE TITLE
华为联想手机都会出现java.util.zip.ZipException: Not a zip archive崩溃

### ISSUE THREAD

**Issue by zhanfangzxc** [alibaba/freeline#275]
第一次执行python freeline.py -f 没有问题，但是第二次执行python freeline.py就会直接闪退:
 Unable to open zip file: /data/user/0/com.yingshibao.gsee/cache/temp/dex/merged.apk
11-09 16:05:02.570 9350-9350/? E/System: java.util.zip.ZipException: Not a zip archive
                                             at java.util.zip.ZipFile.readCentralDir(ZipFile.java:397)
                                             at java.util.zip.ZipFile.<init>(ZipFile.java:175)
                                             at java.util.zip.ZipFile.<init>(ZipFile.java:131)
                                             at dalvik.system.DexPathList$Element.maybeInit(DexPathList.java:452)
                                             at dalvik.system.DexPathList$Element.findResource(DexPathList.java:499)
                                             at dalvik.system.DexPathList.findResources(DexPathList.java:378)
                                             at dalvik.system.BaseDexClassLoader.findResources(BaseDexClassLoader.java:72)
                                             at java.lang.ClassLoader.getResources(ClassLoader.java:425)
                                             at org.jivesoftware.smack.SmackConfiguration.<clinit>(Unknown Source)
                                             at org.jivesoftware.smack.SmackConfiguration.getVersion(Unknown Source)
                                             at org.jivesoftware.smack.Connection.<clinit>(Unknown Source)
                                             at org.jivesoftware.smack.Connection.addConnectionCreationListener(Unknown Source)
                                             at org.jivesoftware.smackx.ServiceDiscoveryManager.<clinit>(Unknown Source)
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.Class.forName(Class.java:324)
                                             at com.easemob.chat.InitSmackStaticCode.initStaticCode(Unknown Source)
                                             at com.easemob.chat.EMChat.init(Unknown Source)
                                             at com.easemob.easeui.controller.EaseUI.init(EaseUI.java:120)
                                             at com.yingshibao.gsee.utils.DemoHelper.init(DemoHelper.java:93)
                                             at com.yingshibao.gsee.AppContext.onCreate(AppContext.java:150)
                                             at com.antfortune.freeline.FreelineApplication.startRealApplication(FreelineApplication.java:51)
                                             at com.antfortune.freeline.FreelineApplication.onCreate(FreelineApplication.java:32)
                                             at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1015)
                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                                             at android.app.ActivityThread.access$1600(ActivityThread.java:150)
                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                             at android.os.Looper.loop(Looper.java:148)
                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                             at java.lang.reflect.Method.invoke(Native Method)
                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by lomanyong** [comment]
@zhanfangzxc 可以给下具体的手机型号以及系统版本吗？

在5.0+的设备上测试过吗？

**Comment by zhanfangzxc** [comment]
@lomanyong  我的这个是在联想zuk z1和华为荣耀8，Android版本都是6.0

**Comment by lomanyong** [comment]
@zhanfangzxc 应该是机型兼容性问题，我再看下原因。

**Comment by zhanfangzxc** [comment]
@lomanyong 找出原因了吗，还是很希望能用上的，现在的编译速度却是是龟速

**Comment by lomanyong** [comment]
@zhanfangzxc 你那里还有其他机型或者模拟器可以验证一下吗？

**Comment by lomanyong** [comment]
@zhanfangzxc 能麻烦把`${main_module}\build\freeline\freeline-dexes\merged.dex`这个文件邮件发给我一下吗？

至少增量一次后会出现这个文件

**Comment by shaolimin** [comment]
请问这个问题解决了吗

**Comment by lomanyong** [comment]
@shaolimin 你也遇见了类似的情况了吗？

**Comment by shanyezhihe** [comment]
遇到同样问题了

**Comment by shanyezhihe** [comment]
华为荣耀8，6.0系统

**Comment by lwh4616** [comment]
魅族没蓝note 2也是一直出现这样的问题 使用了fastjson 经常crash

**Comment by HywTony** [comment]
魅族 pro 5  版本号 Flyme 6.0.1  android 版本5.1 同样的crash提示
