### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by Heart2009** [alibaba/freeline#282]
Suppressed: java.lang.ClassNotFoundException: com.antfortune.freeline.FreelineApplication
                                                                               at java.lang.Class.classForName(Native Method)
                                                                               at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                               at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                               		... 13 more
                                                                            Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by lomanyong** [comment]
@Heart2009  `FreelineApplication`如果你是用freeline来打包的话不会找不到的...出现这个错误的原因很可能是你用正常的打包命令或者使用了AS的run导致的...麻烦检查一下。

或者直接使用`python freeline.py -f`
