### ISSUE TITLE
执行 gradlew initFreeline报错（最后Building过程）

### ISSUE THREAD

**Issue by shoxive** [alibaba/freeline#300]
报错日志如下:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':initFreeline'.
> Cannot get property 'main_manifest_path' on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
麻烦看下什么原因，感谢！

**Comment by lomanyong** [comment]
@shoxive 麻烦加上`--stacktrace`重新运行一下，看下具体的错误栈

**Comment by shoxive** [comment]
@lomanyong   
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':initFreeline'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.NullPointerException: Cannot get property 'main_manifest_path' on null object
        at com.antfortune.freeline.FreelineInitializer$_generateProjectDescription_closure7.doCall(FreelineInitializer.groovy:261)
        at com.antfortune.freeline.FreelineInitializer.generateProjectDescription(FreelineInitializer.groovy:257)
        at com.antfortune.freeline.FreelineInitializer$generateProjectDescription$0.callStatic(Unknown Source)
        at com.antfortune.freeline.FreelineInitializer.initFreeline(FreelineInitializer.groovy:99)
        at com.antfortune.freeline.FreelineInitializer$initFreeline.call(Unknown Source)
        at com.antfortune.freeline.FreelinePlugin$_apply_closure2.doCall(FreelinePlugin.groovy:37)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:590)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:571)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more


BUILD FAILED

**Comment by lomanyong** [comment]
@shoxive 你的工程里存在没有manifest的library module吗？

**Comment by shoxive** [comment]
@lomanyong  刚确认了一下  所有module都有Manifest

**Comment by shoxive** [comment]
@lomanyong 不过我们项目有几个module是以组件化的方式提供，可能是这方面的问题

**Comment by lomanyong** [comment]
@shoxive 有可能是组件化的原因，都是aar依赖了吗？

具体的原因我再分析一下，下个版本我在这个crash的地方加个保护...

**Comment by shoxive** [comment]
@lomanyong  我们只是分离了几个功能模块的组件化，因为还要在不同模块做开发，不是aar依赖

**Comment by lomanyong** [comment]
@shoxive 那你指的组件化的方式提供是？

**Comment by shoxive** [comment]
@lomanyong 就是每一个组件相当于一个可独立运行的APP，组件之间用URL Schema实现页面跳转和数据交互的实现。但是每个moudle都是有menifest的，这个可以确认。

**Comment by lomanyong** [comment]
@shoxive 恩，这个我理解，主要还是build.gradle中配置的依赖方式。是类似 https://github.com/oasisfeng/nevolution 这样的吗？

**Comment by shoxive** [comment]
@laijiandong 恩，类似，也是通过property来判断是用library还是application。

**Comment by shoxive** [comment]
@lomanyong 我们把做到一半的组件化搁下了(反正都是为了提高编译速度)，0.8.1也能编译通过
还是非常感谢，这个issue先关掉了。
