### ISSUE TITLE
NullPointerException(com.antfortune.freeline.FreelineService.onStartCommand(FreelineService.java:42))

### ISSUE THREAD

**Issue by Rflyee** [alibaba/freeline#301]
经常出现以下异常：
`com.xxx.xxx:freeline E/AndroidRuntime: FATAL EXCEPTION: main
		Process: com.xxx.xxx:freeline, PID: 16914
		java.lang.RuntimeException: Unable to start service com.antfortune.freeline.FreelineService@424e8250 with null: java.lang.NullPointerException
			at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2934)
			at android.app.ActivityThread.access$2400(ActivityThread.java:139)
			at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
			at android.os.Handler.dispatchMessage(Handler.java:102)
			at android.os.Looper.loop(Looper.java:136)
			at android.app.ActivityThread.main(ActivityThread.java:5314)
			at java.lang.reflect.Method.invokeNative(Native Method)
			at java.lang.reflect.Method.invoke(Method.java:515)
			at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
			at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
			at dalvik.system.NativeStart.main(Native Method)
		 Caused by: java.lang.NullPointerException
			at com.antfortune.freeline.FreelineService.onStartCommand(FreelineService.java:42)
			at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2897)
			at android.app.ActivityThread.access$2400(ActivityThread.java:139) 
			at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378) 
			at android.os.Handler.dispatchMessage(Handler.java:102) 
			at android.os.Looper.loop(Looper.java:136) 
			at android.app.ActivityThread.main(ActivityThread.java:5314) 
			at java.lang.reflect.Method.invokeNative(Native Method) 
			at java.lang.reflect.Method.invoke(Method.java:515) 
			at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864) 
			at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680) 
			at dalvik.system.NativeStart.main(Native Method) `

**Comment by lomanyong** [comment]
@Rflyee logcat里过滤一下`Freeline.Service`相关的日志有什么呢？或者`Freeline`的日志..

**Comment by Rflyee** [comment]
这个呢？
`Caused by: java.lang.NullPointerException
                                                                                at com.antfortune.freeline.FreelineService.onStartCommand(FreelineService.java:42)`

**Comment by Rflyee** [comment]
哦明白了   你想要上下文信息是吧？这次没全保存，下次出现我过滤下

**Comment by lomanyong** [comment]
@Rflyee 会有这么一行log打出来：`Log.i(LOG_TAG, "onStartCommand Received start id " + startId + ", intent: " + intent);`

**Comment by Rflyee** [comment]
@lomanyong 又出现了，还是上边的错误，但是没有你提到的那个日志，tag过滤为Freeline.Service或者Freeline没有;内容过滤你说的那个“onStartCommand Received” 也没有。和Freeline相关的主要就是上面贴的runtime信息。还有几个重启FreelineService相关的：比如
`ActivityManager: Scheduling restart of crashed service com.xxx.xxx/com.antfortune.freeline.FreelineService in 1000ms`
`ActivityManager: Start proc com.xxx.xxx:freeline for service com.xxx.xxx/com.antfortune.freeline.FreelineService:`

**Comment by lomanyong** [comment]
@Rflyee 昨天忘了回复，你没有找到log的原因应该是因为过滤错进程了，那个Service在一个独立的进程里，所以你在logcat里选错了的话，会找不到日志，你可以选择不按进程过滤，让手机输出全部的日志，或者单独选择`:freeline`进程来过滤日志...

**Comment by Rflyee** [comment]
ok，解决了就好。当时过滤条件选择的确实是No Filters，并且也试过直接命令抓取全部log。还需要日志吗？如果需要我稍后再试试

**Comment by lomanyong** [comment]
@Rflyee 我先加入了判空处理了，应该不影响正常使用，如果之后还出现的话再继续看下日志~
