### ISSUE TITLE
拆包之后使用freeline报错

### ISSUE THREAD

**Issue by Huyamin150** [alibaba/freeline#306]
我使用拆Dex之后使用freeline编译出现了错误，执行的编译方法：报出来Error:Execution failed for task ':app:transformClassesWithDexForPftestinDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
然而我切换到没有使用freeline的分支之后正常安装。我的gradle是3.1版本的
依赖classpath 'com.android.tools.build:gradle:2.2.2'
Freeline版本是0.81

**Comment by lomanyong** [comment]
@Huyamin150 麻烦使用`python freeline.py -d -f`，看下详细的stacktrace...现在发出来的这部分日志看不出问题在哪里...

**Comment by Huyamin150** [comment]
@lomanyong 
完整日志如下：
* What went wrong:
Execution failed for task ':app:transformClassesWithDexForPftestinDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurr
ent.ExecutionException: java.lang.UnsupportedOperationException

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDexForPftestinDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.
java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46
)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskEx
ecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExec
uter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.j
ava:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.j
ava:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecute
r.java:233)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecute
r.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecut
or.java:74)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:
55)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: com.android.ide.common.proces
s.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
        at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:54)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:158)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:173)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(Default
TaskClassInfoStore.java:158)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskC
lassInfoStore.java:129)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskC
lassInfoStore.java:118)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.j
ava:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.
java:61)
        ... 14 more
Caused by: com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.uti
l.concurrent.ExecutionException: java.lang.UnsupportedOperationException
        at com.android.build.gradle.internal.transforms.DexTransform.transform(DexTransform.java:443)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:178)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:174)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        ... 21 more
Caused by: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.Unsupport
edOperationException
        at com.android.builder.core.DexByteCodeConverter.dexOutOfProcess(DexByteCodeConverter.java:210)
        at com.android.builder.core.DexByteCodeConverter.runDexer(DexByteCodeConverter.java:159)
        at com.android.builder.core.DexByteCodeConverter.convertByteCode(DexByteCodeConverter.java:146)
        at com.android.builder.core.AndroidBuilder.convertByteCode(AndroidBuilder.java:1386)
        at com.android.build.gradle.internal.transforms.DexTransform.transform(DexTransform.java:272)
        ... 24 more
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
        at com.android.builder.core.DexByteCodeConverter.dexOutOfProcess(DexByteCodeConverter.java:206)
        ... 28 more
Caused by: java.lang.UnsupportedOperationException
        at com.android.ide.common.process.ProcessInfoBuilder$JavaProcessInfoImpl.getExecutable(ProcessInfoBuilder.java:3
49)
        at com.android.build.gradle.internal.process.GradleProcessResult.buildProcessException(GradleProcessResult.java:
74)
        at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:
49)
        at com.android.builder.core.DexByteCodeConverter.lambda$dexOutOfProcess$1(DexByteCodeConverter.java:196)


[ERROR] --------------------------------------------------------
[ERROR] build failed with script: gradlew.bat :app:assemblePftestinDebug -P freelineBuild=true --stacktrace
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 158.1s
[DEBUG] Total time: 158.3s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@Huyamin150 看了stacktrace貌似不是出在freeline植入的task里，普通打包能够打包通过吗？麻烦确认一下...

**Comment by Huyamin150** [comment]
在配置了freeline的情况下直接run也通不过，只有去除freeline在项目里配置之后打包方可成功，我是用cmd命令行cd到项目根目录下进行init命令的，然后显示buildsuccess的，在studio的Terminal或者Freeline的命令行工具里面init全部失败 报错：* What went wrong:
Task 'initFreeline' not found in project ':app'.
studio插件显示freeline没有安装，我这个build是在cmd命令行进行build的

**Comment by lomanyong** [comment]
@Huyamin150 直接run（不要使用freeline）的话是不会执行freeline相关的task的，或者你手动执行`./gradlew :{main_module}:assembleDebug`，不需要去掉freeline的配置应该也可以执行才对...

找不多`initFreeline`也很正常...因为你去掉了freeline的配置依赖了...

**Comment by Huyamin150** [comment]
@lomanyong 我没有去除依赖，区别在于我在CMD窗口进入的时候可以init成功，在studio里面就不可以，直接run在不去除freeline的时候按道理是用自带的编译，但是也是会出错，一定要去除 app plugin 和project level的 gradle 的依赖才能跑。这也是奇怪的问题。我用命令行进入项目根目录执行init也是没错的吧，项目里面生成了对应的文件夹，但是studio里面就是不行

**Comment by a124779683** [comment]
国内为了避免出问题一定要用镜像 gradlew initFeeline -Pmirror试一下

**Comment by Huyamin150** [comment]
是用的国内的镜像，回头我用0.73试试吧~，一脸懵逼



huyamin150@sohu.com
 
发件人： a124779683
发送时间： 2016-11-17 14:51
收件人： alibaba/freeline
抄送： Nick.Hu; Mention
主题： Re: [alibaba/freeline] 拆包之后使用freeline报错 (#306)
国内为了避免出问题一定要用镜像 gradlew initFeeline -Pmirror试一下
