### ISSUE TITLE
永远都报同一个错误，实在是搞不懂，贴上app的gradle配置，求原因

### ISSUE THREAD

**Issue by Huyamin150** [alibaba/freeline#315]
首先，还是一样的报错，Caused by: java.lang.UnsupportedOperationException，不管是命令行执行python freeline.py还是直接run，均会抛出此错误。移除掉freeline的gradle的配置之后立刻run恢复正常。

其次，我是在项目根目录里执行gradlew initFreeline -Pmirror 并非app文件夹下，这个应该是对的。build success也是没有问题的，现在我项目里为了freeline就更改了根目录的配件配置文件和app的gradle配置文件，没有在application里执行init，改动就这么多，流程也是很简单，执行python freeline.py显示wait a min 之后一段时间之后就会显示Caused by: java.lang.UnsupportedOperationException，我实在是没有办法解决了，特此贴上我的gradle配置，求作者看下问题出在哪。

gradle：版本 2.14.1   studio：2.3Canary (以前2.2也是同样的错误)
# **根目录的build.gradle**
````
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.2'
        classpath 'com.antfortune.freeline:gradle:0.8.2'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}
````

# **app目录的gradle：**
````
apply plugin: 'com.android.application'
apply plugin: 'com.antfortune.freeline'
def RELEASE_HOST = "\"api.yonghuivip.com\""
def INTERNAL_HOST = "\"apitest.yonghuivip.com\""
def TESTIN_HOST = "\"test.yonghuivip.com\""
def PRESSURE_HOST = "\"api-qa.yonghuivip.com\""
def PRERELEASE_HOST = "\"api-prelaunch.yonghuivip.com\""

def getDate() {
    def date = new Date()
    def formattedDate = date.format('yyyyMMdd')
    return formattedDate
}

def getBuildNum() {
    def vcFile = file("../../script/yhstore/build.ver")
    def buildNum = vcFile.readLines().get(0)
    return Integer.parseInt(buildNum)
}

ext {
    storeFilePath = ""
    keystorePasswordValue = ""
    keyPasswordValue = ""
    appReleaseDir = ""
    publish=false
    publishDir=""
    dev = false
}

def loadProperties() {
    def proFile = file("../local.properties")
    Properties p = new Properties()
    proFile.withInputStream { stream->
        p.load(stream)
    }
    storeFilePath = p.storePath
    keystorePasswordValue = p.storePassword
    keyPasswordValue = p.keyPassword
    appReleaseDir = p.appReleaseDir
    publish = p.publish
    publishDir = p.publishDir
    dev = p.dev;
}

loadProperties()

def versionCodeValue
if (publish.equals('true')) {
    versionCodeValue = getBuildNum();
} else {
    versionCodeValue = Integer.parseInt(getDate()) * 100;
}

def versionNameValue = "2.5.0"

android {

    freeline {
        hack true
        productFlavor 'internal' // 渠道名
    }
    signingConfigs {
        release {
            keyAlias 'YHO2O'
            keyPassword keyPasswordValue
            storeFile file(storeFilePath)
            storePassword keystorePasswordValue
        }
    }
    compileSdkVersion 23
    buildToolsVersion "23.0.2"
    sourceSets.main {
        jni.srcDirs = ['src/main']
    }
    defaultConfig {
        applicationId "cn.yonghui.hyd"
        minSdkVersion 14
        targetSdkVersion 23
        versionCode versionCodeValue
        if (dev.equals('true')) {
            versionName versionNameValue + "-dev"
        } else {
            versionName versionNameValue
        }
        ndk {
            moduleName "YhJni"
        }
        signingConfig signingConfigs.release
        // Enabling multidex support.
        multiDexEnabled true
    }
    lintOptions {
        abortOnError false
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            zipAlignEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    productFlavors {
        /*************** test ***************/
        // internal
        internal {}
        // testin
        pftestin {}
        // pressure
        pressure {}
        // prelaunch
        prelaunch {}

        /************* release **************/
        //  official
        official {}
        // 360
        pf360 {}
    }

    productFlavors.all { flavor->
        manifestPlaceholders = [CHANNEL_VALUE: name, TD_CHANNEL_VALUE: "YHO2O-"+name, HF_CHANNEL_VALUE: "yho2o."+name]
        ndk {
            abiFilters "armeabi","armeabi-v7a","x86"
        }
        if (name.equals('internal')) {
            buildConfigField "String", "API_HOST", INTERNAL_HOST
        } else if (name.equals('pftestin')) {
            buildConfigField "String", "API_HOST", TESTIN_HOST
        } else if (name.equals('pressure')) {
            buildConfigField "String", "API_HOST", PRESSURE_HOST
        } else if (name.equals('prerelease')) {
            buildConfigField "String", "API_HOST", PRERELEASE_HOST
        } else {
            buildConfigField "String", "API_HOST", RELEASE_HOST
        }
        buildConfigField "String", "RELEASE_HOST", RELEASE_HOST
        buildConfigField "String", "INTERNAL_HOST", INTERNAL_HOST
        buildConfigField "String", "TESTIN_HOST", TESTIN_HOST
        buildConfigField "String", "PRESURE_HOST", PRESSURE_HOST
        buildConfigField "String", "PRERELEASE_HOST", PRERELEASE_HOST
    }

    // empty the output file list
    def publicConf
    if (publish.equals('true')) {
        publicConf = new File(publishDir, "publish.conf")
        publicConf.write("")
    }

    // apk output setting
    applicationVariants.all{ variant->
        variant.outputs.each { output->
            if(variant.buildType.name.equals('release') && !dev) {
                def releaseApkName = 'yhstore-' + variant.productFlavors[0].name + '-v' + versionName + '-' + versionCode + '.apk'
                output.outputFile = new File(appReleaseDir, releaseApkName)

                if (publish.equals('true')) {
                    publicConf.append("" + output.outputFile, 'UTF-8')
                    publicConf.append("\n")
                }
            }
            if(variant.buildType.name.equals('beta')){
            }
            if(variant.buildType.name.equals('debug')){
                if (variant.flavorName.equals('internal')) {
                    def releaseApkName = 'yhstore-' + variant.productFlavors[0].name + '-v' + versionName + '-' + versionCode + '.apk'
                    output.outputFile = new File(appReleaseDir, releaseApkName)

                    if (publish.equals('true')) {
                        publicConf.append("" + output.outputFile, 'UTF-8')
                        publicConf.append("\n")
                    }
                }
            }
        }
    }
}

repositories {
    mavenCentral()
    flatDir {
        dirs project(':yhpay-center').file('libs')
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')


    compile 'com.android.support:support-v4:23.4.0'
    compile 'de.greenrobot:eventbus:2.4.0'
    compile 'org.jbundle.util.osgi.wrapped:org.jbundle.util.osgi.wrapped.org.apache.http.client:4.1.2'
    compile 'com.android.support:recyclerview-v7:23.4.0'
    compile (project(':yhpay-center')) {
//        exclude module: 'libammsdk.jar'
    }
    compile project(':upgrade')
    compile project(':http')
    compile project(':utils')

    compile 'de.greenrobot:greendao:2.0.0'
    //fresco相关
    compile 'com.facebook.fresco:fresco:0.12.0'
    compile 'com.facebook.fresco:animated-base-support:0.12.0'
    compile 'com.facebook.fresco:webpsupport:0.12.0'

    compile 'com.android.support:multidex:1.0.0'


}
````

**Comment by lomanyong** [comment]
@Huyamin150 麻烦贴出详细的错误堆栈看下...

**Comment by Huyamin150** [comment]
python freeline.py -d -f 命令之后的错误信息：上次也给您看过，说过看不出来什么

 What went wrong:
Execution failed for task ':app:transformClassesWithDexForInternalDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.E
xecutionException: java.lang.UnsupportedOperationException

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDexForInternalDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:
69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecute
r.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.
java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:5
2)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:4
3)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.jav
a:233)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.jav
a:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.ja
va:74)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:55)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: com.android.ide.common.process.Pro
cessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
        at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:54)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:158)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:173)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskC
lassInfoStore.java:158)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassI
nfoStore.java:129)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassI
nfoStore.java:118)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:8
0)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:
61)
        ... 14 more
Caused by: com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.con
current.ExecutionException: java.lang.UnsupportedOperationException
        at com.android.build.gradle.internal.transforms.DexTransform.transform(DexTransform.java:443)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:178)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:174)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        ... 21 more
Caused by: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOpe
rationException
        at com.android.builder.core.DexByteCodeConverter.dexOutOfProcess(DexByteCodeConverter.java:210)
        at com.android.builder.core.DexByteCodeConverter.runDexer(DexByteCodeConverter.java:159)
        at com.android.builder.core.DexByteCodeConverter.convertByteCode(DexByteCodeConverter.java:146)
        at com.android.builder.core.AndroidBuilder.convertByteCode(AndroidBuilder.java:1386)
        at com.android.build.gradle.internal.transforms.DexTransform.transform(DexTransform.java:272)
        ... 24 more
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
        at com.android.builder.core.DexByteCodeConverter.dexOutOfProcess(DexByteCodeConverter.java:206)
        ... 28 more
Caused by: java.lang.UnsupportedOperationException
        at com.android.ide.common.process.ProcessInfoBuilder$JavaProcessInfoImpl.getExecutable(ProcessInfoBuilder.java:349)
        at com.android.build.gradle.internal.process.GradleProcessResult.buildProcessException(GradleProcessResult.java:74)
        at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:49)
        at com.android.builder.core.DexByteCodeConverter.lambda$dexOutOfProcess$1(DexByteCodeConverter.java:196)


[ERROR] --------------------------------------------------------
[ERROR] build failed with script: gradlew.bat :app:assembleInternalDebug -P freelineBuild=true --stacktrace
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 115.5s
[DEBUG] Total time: 115.7s
[DEBUG] --------------------------------------------------------

**Comment by Huyamin150** [comment]
@lomanyong

**Comment by Huyamin150** [comment]
@lomanyong 

在这段日志之后报的错
F:\Android\AndroidSourceCode\Studio2.2+\YHStore>python freeline.py
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=False, init=False, version=
False, wait=False)
[DEBUG] [WARNING] some important file missed, a clean build will be automatically executed.
[DEBUG] collecting project info, please wait a while...
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: F:\Android\AndroidSourceCode\Studio2.2+\YHStore\app\build\freeline\freeline-assets\apktime
[DEBUG] new clean build flag value: 659000
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save app module file stat
[DEBUG] [generate_file_stat_task] save yhpay-center module file stat
[DEBUG] [generate_file_stat_task] save upgrade module file stat
[DEBUG] [generate_file_stat_task] save http module file stat
[DEBUG] [generate_file_stat_task] save utils module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.2s
[DEBUG] [read_project_info_task] read_project_info_task finish in 2.7s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 2.7s
[DEBUG] [gradle_clean_build_task] gradlew.bat :app:assembleInternalDebug -P freelineBuild=true --stacktrace
[DEBUG] [gradle_clean_build_task] Gradle build task is running, please wait a minute...

**Comment by lomanyong** [comment]
@Huyamin150 加入这个试试看

````gradle
dependencies {
    sourceCompatibility = 1.7
    targetCompatibility = 1.7

    .....your dependencies...
}
````

如果还不行的话，你看下是否可以提供一个可以复现这个问题的简单sample，我来build看下..

**Comment by Huyamin150** [comment]
@lomanyong 我下午弄个sample出来看看

**Comment by Huyamin150** [comment]
@lomanyong 我昨天准备把项目的业务代码删除打一个阉割版的sample 发过来，突然发现删除掉业务代码奇迹般的可以安装了，实在是找不到原因，这些业务代码也就是普通的代码，而且application的初始化代码全部删除我以为是这个原因后来发现也不是，实在是没办法重现了，抱歉，这个issue您关掉吧。可能是其中某个东西影响到了，等之后我研究出来了是什么原因影响到了，我再来告诉你们

**Comment by lomanyong** [comment]
@Huyamin150 恩，麻烦了。
