### ISSUE TITLE
IncompatibleClassChangeError

### ISSUE THREAD

**Issue by Davion8948** [alibaba/freeline#32]
Hello：
Is it must rebuild the whole project after delete some `public static final String` fields?
Because after I deleted a filed my app crashed by: 

    `java.lang.IncompatibleClassChangeError: com.xxx.rc.example.view.ExampleActivity
                          at dalvik.system.DexFile.defineClassNative(Native Method)
                          at dalvik.system.DexFile.defineClass(DexFile.java:226)
                          at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                          at dalvik.system.DexPathList.findClass(DexPathList.java:322)
                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                          at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                          at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                          at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2515)
                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2697)
                          at android.app.ActivityThread.access$800(ActivityThread.java:179)
                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1540)
                          at android.os.Handler.dispatchMessage(Handler.java:111)
                          at android.os.Looper.loop(Looper.java:194)
                          at android.app.ActivityThread.main(ActivityThread.java:5796)
                          at java.lang.reflect.Method.invoke(Native Method)
                          at java.lang.reflect.Method.invoke(Method.java:372)
                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1010)
                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)`

**Comment by lomanyong** [comment]
@Davion8948 Is this case can be recurrent? I have repeated this case in sample project but didn't find a crash.

**Comment by Davion8948** [comment]
@lomanyong 
Yes. I can recurrent this.

After I created a new sample project, I created a super Activity like this:

    public abstract class BaseActivity extends AppCompatActivity{
      //Delete this or add this
      public static final String TAG = "BaseActivity";
    }

Then let Activity extends this and run `python freeline.py`, it's ok now.
Next I deleted the `TAG` field and rerun `python freeline.py` the app will crash with that error.

**Comment by charvenhe** [comment]
@Davion8948 it may be abstract class change ，winch cause sub class does not match with the parent class,you can remove "abstract" in BaseActivity and try again .

**Comment by Davion8948** [comment]
@charvenhe 

好的，谢谢。主页上和Wiki上好像没有关于目前有哪些情况可能导致问题，希望有时间能加一下，这样在使用的时候可以避开相应的问题。

**Comment by lomanyong** [comment]
@Davion8948 嗯，我们也在整理这部分内容，尽快都完善起来，感谢提议～
