### ISSUE TITLE
编译通过，但是运行的时候报错：android.view.InflateException: Binary XML file line #32: Error inflating class android.support.v7.widget.RecyclerView

### ISSUE THREAD

**Issue by wuhaowen** [alibaba/freeline#320]
````
11-21 22:01:44.923 26901-26901/com.mealkey.mealtime E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.mealkey.mealtime, PID: 26901
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mealkey.mealtime/com.mealkey.mealtime.view.ChoosePadActivity}: android.view.InflateException: Binary XML file line #32: Error inflating class android.support.v7.widget.RecyclerView
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5258)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:735)
                                                                       Caused by: android.view.InflateException: Binary XML file line #32: Error inflating class android.support.v7.widget.RecyclerView
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                          at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                          at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                          at com.mealkey.mealtime.view.ChoosePadActivity.onCreate(ChoosePadActivity.java:54)
                                                                          at android.app.Activity.performCreate(Activity.java:6005)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:135) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5258) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:735) 
                                                                       Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.RecyclerView" on path: DexPathList[[dex file "/data/data/com.mealkey.mealtime/cache/hack/hackload.dex", zip file "/data/app/com.mealkey.mealtime-1/base.apk"],nativeLibraryDirectories=[/data/data/com.mealkey.mealtime/cache/temp/native, /data/app/com.mealkey.mealtime-1/lib/arm, /vendor/lib, /system/lib]]
                                                                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:571)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                          at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                          at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                          at com.mealkey.mealtime.view.ChoosePadActivity.onCreate(ChoosePadActivity.java:54) 
                                                                          at android.app.Activity.performCreate(Activity.java:6005) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:135) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5258) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:735) 
                                                                      	Suppressed: java.lang.ClassNotFoundException: android.support.v7.widget.RecyclerView
                                                                          at java.lang.Class.classForName(Native Method)
                                                                          at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                          at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                          		... 24 more
                                                                       Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
````

**Comment by wuhaowen** [comment]
file changed list:
{
    "build_info": {
        "last_clean_build_time": 1479700626.679266,
        "is_root_config_changed": false
    },
    "projects": {
        "lib-nfcreader": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "clienttransfer": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "lib-printer": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "clientwaiter": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "app": {
            "src": [
                "E:\\WorkSpace\\MealTime\\app\\src\\main\\java\\com\\mealkey\\mealtime\\AppContext.java"
            ],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "lib-push": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "clientreserve": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "clientorder": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "base": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "common": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "clientsnackorder": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "clientgreeter": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "lib-vguang": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "clientchef": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        }
    }
}

**Comment by lomanyong** [comment]
@wuhaowen `java.lang.ClassNotFoundException: android.support.v7.widget.RecyclerView`这个错误是分包的时候`RecyclerView`被分到后面的dex导致的吧？你可以尝试取消 Application 代理看看是否可以解决这个问题

解决方式：
加入一个配置项：

````gradle
freeline {
    applicationProxy false
}
````

在你的Application类中加入：
````java
public class YourApplication extends Application {
    
    public onCreate() {
         super.onCreate();
         FreelineCore.init(this);
    }
}
````

然后clean，重新打包后看下是否还有同样的问题。

**Comment by wuhaowen** [comment]
# @lomanyong 已经参照设置了，问题依旧

**Comment by lomanyong** [comment]
@wuhaowen 不用freeline打包就没问题？RecyclerView的类找不到不像是freeline导致的问题...添加我上述的配置后，最好能够clean一下，再build...

**Comment by lomanyong** [comment]
确认了一下在替换完 application 的情况下，freeline 不会导致 recyclerview 的类 Not Found..
