### ISSUE TITLE
用studio的运行项目没问题，但用freeline运行就报NoClassDefFoundError

### ISSUE THREAD

**Issue by adminLiu-s** [alibaba/freeline#325]
java.lang.NoClassDefFoundError: com.dandan.ui.rongyun.RongCloudEvent
                                                      at com.dandan.base.AppUser.onCreate(AppUser.java:29)
                                                      at com.antfortune.freeline.FreelineApplication.startRealApplication(FreelineApplication.java:51)
                                                      at com.antfortune.freeline.FreelineApplication.onCreate(FreelineApplication.java:32)
                                                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4587)
                                                      at android.app.ActivityThread.access$1800(ActivityThread.java:141)
                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)
                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                      at android.os.Looper.loop(Looper.java:136)
                                                      at android.app.ActivityThread.main(ActivityThread.java:5288)
                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883)
                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                      at dalvik.system.NativeStart.main(Native Method)

**Comment by lomanyong** [comment]
@adminLiu-s 参考#273 可以解决你的问题。

**Comment by adminLiu-s** [comment]
我这样操作完后NoClassDefFoundError是解决了，但又出现一个问题，每次点freeline都是全量编译了，不能增量编译...

[WARNING] check sync status failed, a clean build will be automatically executed.
[-][read_project_info_task] finished. in 6.5s
[-][generate_file_stat_task] finished. in 0.1s
[-][gradle_clean_build_task] finished. in 74.6s

**Comment by lomanyong** [comment]
@adminLiu-s 先把手机上的apk卸载了再运行...

**Comment by adminLiu-s** [comment]
终于好了....感谢作者，还能再完善
