### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by r17171709** [alibaba/freeline#331]
``` xml
* What went wrong:
Execution failed for task ':app:processDevelopDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
```

**Comment by lomanyong** [comment]
@r17171709 麻烦给出更详细的日志..

**Comment by r17171709** [comment]
``` xml
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processDebugResources'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:239)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:212)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Failed to execute aapt
        at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:185)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:82)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 60 more
Caused by: com.android.ide.common.process.ProcessException: Failed to execute aapt
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:873)
        at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:178)
        ... 68 more
Caused by: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing 'E:\android-sdk-windows\build-tools\24.0.3\aapt.exe' with arguments {package -f --no-crunch -I E:\android-sdk-windows\platforms\android-24\android.jar -M E:\workspace\HouseButler\app
\build\intermediates\manifests\full\debug\AndroidManifest.xml -S E:\workspace\HouseButler\app\build\intermediates\res\merged\debug -m -J E:\workspace\HouseButler\app\build\generated\source\r\debug -F E:\workspace\HouseButler\app\build\intermediates\res\resources-debug.ap_ -D E:\workspace\HouseButler\app\
build\intermediates\multi-dex\debug\manifest_keep.txt --debug-mode --custom-package com.house365.housebutler -0 apk -P E:\workspace\HouseButler\app\build\freeline\public_keeper.xml --output-text-symbols E:\workspace\HouseButler\app\build\intermediates\symbols\debug --no-version-vectors}
        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:871)
        ... 69 more
Caused by: com.android.ide.common.process.ProcessException: Error while executing 'E:\android-sdk-windows\build-tools\24.0.3\aapt.exe' with arguments {package -f --no-crunch -I E:\android-sdk-windows\platforms\android-24\android.jar -M E:\workspace\HouseButler\app\build\intermediates\manifests\full\debug
\AndroidManifest.xml -S E:\workspace\HouseButler\app\build\intermediates\res\merged\debug -m -J E:\workspace\HouseButler\app\build\generated\source\r\debug -F E:\workspace\HouseButler\app\build\intermediates\res\resources-debug.ap_ -D E:\workspace\HouseButler\app\build\intermediates\multi-dex\debug\manif
est_keep.txt --debug-mode --custom-package com.house365.housebutler -0 apk -P E:\workspace\HouseButler\app\build\freeline\public_keeper.xml --output-text-symbols E:\workspace\HouseButler\app\build\intermediates\symbols\debug --no-version-vectors}
        at com.android.build.gradle.internal.process.GradleProcessResult.buildProcessException(GradleProcessResult.java:75)
        at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:49)
        at com.android.builder.internal.aapt.AbstractProcessExecutionAapt$1.onSuccess(AbstractProcessExecutionAapt.java:78)
        at com.android.builder.internal.aapt.AbstractProcessExecutionAapt$1.onSuccess(AbstractProcessExecutionAapt.java:74)
        at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
        at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:53)
        at com.android.build.gradle.internal.process.GradleProcessExecutor$1.run(GradleProcessExecutor.java:58)
Caused by: org.gradle.process.internal.ExecException: Process 'command 'E:\android-sdk-windows\build-tools\24.0.3\aapt.exe'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:367)
        at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:47)
        ... 9 more


```

**Comment by lomanyong** [comment]
@r17171709 漏了回复了...

从日志上看就是gradle aapt执行出错，具体的出错原因在日志输出里应该有...应该是可以找到的...你截取的这部分日志没有截取到...

**Comment by r17171709** [comment]
@lomanyong 那个问题解决了，是因为manifest有硬编码，写了中文字了，所以freeline解析就变成乱码了。这个你们应该看一下吧？现在又遇到新的问题了，就是全量编译通过了，但是增量编译又出问题了
``` xml
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "E:\workspace\HouseButler\freeline_core\task.py", line 123, in execute
    self.task.execute()
  File "E:\workspace\HouseButler\freeline_core\gradle_inc_build.py", line 170, in execute
    self._invoker.check_other_modules_resources()
  File "E:\workspace\HouseButler\freeline_core\gradle_inc_build.py", line 447, in check_other_modules_resources
    self.__modify_main_r()
  File "E:\workspace\HouseButler\freeline_core\gradle_inc_build.py", line 460, in __modify_main_r
    write_file_content(main_r_fpath, buf)
  File "E:\workspace\HouseButler\freeline_core\utils.py", line 118, in write_file_content
    with open(target_path, 'w') as fp:
IOError: [Errno 2] No such file or directory: u'E:\\workspace\\HouseButler\\app\\build\\freeline\\app\\backup\\com\\house365\\housebutler\\R.java'

```

**Comment by lomanyong** [comment]
@r17171709 你们是否 manifest 定义的包名跟 applicationId 不一致呢？

**Comment by lomanyong** [comment]
@r17171709 中文硬编码的问题也不是吧？我看报错的日志是 Gradle task 执行失败...stacktrace里没有看到freeline相关的，具体是什么样的中文硬编码？

**Comment by r17171709** [comment]
@lomanyong 确实manifest里面的包名与applicationId的包名是不一致的，这个如何解决呢？中文硬编码就是meta-data里面的value是中文汉字而已，我把他挪到@sting里面就没问题了

**Comment by lomanyong** [comment]
@r17171709 不一致的问题是个特殊case，这周验证完后，会发版解决，已有相关issue #284

**Comment by r17171709** [comment]
@lomanyong 包名不一致，但是现在升级到0.8.3全量更新OK，增量更新还是有问题
``` xml
Traceback (most recent call last):
  File "E:\workspace\HouseButler\freeline_core\task.py", line 123, in execute
    self.task.execute()
  File "E:\workspace\HouseButler\freeline_core\gradle_inc_build.py", line 170, in execute
    self._invoker.check_other_modules_resources()
  File "E:\workspace\HouseButler\freeline_core\gradle_inc_build.py", line 447, in check_other_modules_resources
    self.__modify_main_r()
  File "E:\workspace\HouseButler\freeline_core\gradle_inc_build.py", line 460, in __modify_main_r
    write_file_content(main_r_fpath, buf)
  File "E:\workspace\HouseButler\freeline_core\utils.py", line 118, in write_file_content
    with open(target_path, 'w') as fp:
IOError: [Errno 2] No such file or directory: u'E:\\workspace\\HouseButler\\app\\build\\freeline\\app\\backup\\com\\house365\\housebutler\\R.java'

```
