### ISSUE TITLE
execute gradlew checkBeforeCleanBuild first

### ISSUE THREAD

**Issue by ss518926** [alibaba/freeline#348]
因为AS内部下载总是
```
Error:Execution failed for task ':initFreeline'.
> Can't get http://obr0ndq7a.bkt.clouddn.com/freeline/freeline-v0.8.2.zip to E:\Android\demo\TestLib\freeline.zip.tmp
```
所以用迅雷下载的压缩包，然后解压到工程。

然后执行报错

```
E:\Android\demo\TestLib>python freeline.py
Traceback (most recent call last):
  File "freeline.py", line 49, in <module>
    main()
  File "freeline.py", line 45, in main
    freeline.call(args=args)
  File "freeline.py", line 20, in call
    self.dispatcher.call_command(args)
  File "E:\Android\demo\TestLib\freeline_core\dispatcher.py", line 31, in call_command
    self._config = read_freeline_config()
  File "E:\Android\demo\TestLib\freeline_core\dispatcher.py", line 161, in read_freeline_config
    raise NoConfigFoundException(config_path)
freeline_core.exceptions.NoConfigFoundException: C:\Users\Administrator\.freeline\cache\3ba3c049350dc6b991a71a7cc40d2814\project_description.json not found, please execute gradlew checkBeforeCleanBuild first.
```

是不是少了什么步骤orz？

**Comment by lomanyong** [comment]
@ss518926 参考 #345

**Comment by ss518926** [comment]
系统Win7 第3步不懂啥意识，第4部 大概意思复制文件，删除压缩包这些做了

**Comment by ss518926** [comment]
project_description.json not found 我现在的问题是这个。。。

**Comment by ss518926** [comment]
@lomanyong

**Comment by lomanyong** [comment]
@ss518926 再执行一下`gradlew checkBeforeCleanBuild`应该就可以了..

**Comment by ss518926** [comment]
java环境变量错误？(╯‵□′)╯︵┻━┻
感觉自己还没上小学了Orz

```
[DEBUG] [ERROR] Builder.get_javac() return None.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
JAVA_HOME not found in env.
[ERROR] --------------------------------------------------------
[ERROR] Please declares your JAVA_HOME to system env!
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.1s
[DEBUG] Task engine running time: 0.0s
[DEBUG] Total time: 0.1s
[DEBUG] --------------------------------------------------------
```

但是看了下配置。。没啥问题呀
![java环境配置](http://7xlw2m.com1.z0.glb.clouddn.com/java%E9%85%8D%E7%BD%AE.png)

@lomanyong

**Comment by ss518926** [comment]
好吧，看了 #91 解决了

**Comment by ss518926** [comment]
成了，速度的确杠杠的。
不过切回AS自带的Run App会报错
```
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Unable to find source java class: 'E:\Android\demo\TestLib\app\build\generated\freeline\com\antfortune\freeline\FreelineConfig.java' because it does not belong to any of the source dirs: '[E:\Android\demo\TestLib\app\src\main\java, E:\Android\demo\TestLib\app\src\debug\java, E:\Android\demo\TestLib\app\build\generated\source\r\debug, E:\Android\demo\TestLib\app\build\generated\source\buildConfig\debug, E:\Android\demo\TestLib\app\build\generated\source\aidl\debug, E:\Android\demo\TestLib\app\build\generated\source\rs\debug]'
```

不过 clean project 就可以了。

谢谢

**Comment by lomanyong** [comment]
@ss518926 切换回 AS 会报错是正常的…clean一下即可。
