### ISSUE TITLE
org.gradle.api.ProjectConfigurationException: A problem occurred configuring pro

### ISSUE THREAD

**Issue by zx98cv12** [alibaba/freeline#349]
* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring pro
        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigu
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfte
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(L
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProj
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProj
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProje
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:82)
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:75)
        at org.gradle.execution.commandline.CommandLineTaskParser.parseTasks(Com
        at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.config
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configur
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$0
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.procee
        at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(Defau
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configur
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$0
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.procee
        at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.co
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configur
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.select(D
        at org.gradle.initialization.DefaultGradleLauncher$3.run(DefaultGradleLa
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGra
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradl
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradl
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildCon
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(Exe
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildA
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(Contin
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(Contin
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBu
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(Forw
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(Forw
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(For
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClien
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBu
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(Hin
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(Daemon
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableE
Caused by: java.lang.RuntimeException: Freeline doesn't support proguard now, pl
        at com.antfortune.freeline.FreelinePlugin$_apply_closure4$_closure11.doC
        at com.antfortune.freeline.FreelinePlugin$_apply_closure4.doCall(Freelin
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(Cl
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(Cl
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(Abstract
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatc
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatc
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocati
        at com.sun.proxy.$Proxy12.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfte
        ... 65 more

[ERROR] --------------------------------------------------------
[ERROR] build failed with script: gradlew.bat :RfProperties:assembleDebug -P fre
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 5.6s
[DEBUG] Total time: 5.8s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@zx98cv12 `Caused by: java.lang.RuntimeException: Freeline doesn't support proguard now, pl...`这部分日志上面应该还有一句比较明显的提示...在debug模式下把proguard关掉就行了...
