### ISSUE TITLE
freeline 卡住了，编译了43分钟了还没好

### ISSUE THREAD

**Issue by corleoneJ** [alibaba/freeline#358]
E:\GitProject\owner>python freeline.py
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=False, init=False, version=False, wait=False)
[DEBUG] final apk not found, need a clean build.
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: E:\GitProject\owner\app\build\freeline\freeline-assets\apktime
[DEBUG] new clean build flag value: 658000
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save app module file stat
[DEBUG] [generate_file_stat_task] save barcode module file stat
[DEBUG] [generate_file_stat_task] save share module file stat
[DEBUG] [generate_file_stat_task] save map module file stat
[DEBUG] [generate_file_stat_task] save common module file stat
[DEBUG] [generate_file_stat_task] save push module file stat
[DEBUG] [generate_file_stat_task] save image module file stat
[DEBUG] [generate_file_stat_task] save slidedatetimepicker module file stat
[DEBUG] [generate_file_stat_task] save repository module file stat
[DEBUG] [generate_file_stat_task] save util module file stat
[DEBUG] [generate_file_stat_task] save wenda module file stat
[DEBUG] [generate_file_stat_task] save http module file stat
[DEBUG] [generate_file_stat_task] save chat module file stat
[DEBUG] [generate_file_stat_task] save wendahttp module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.1s
[DEBUG] [read_project_info_task] read_project_info_task finish in 13.5s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 13.5s
[DEBUG] [gradle_clean_build_task] gradlew.bat :app:assembleDebug -P freelineBuild=true --stacktrace
[DEBUG] [gradle_clean_build_task] Gradle build task is running, please wait a minute...

dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0'
//        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
        classpath 'com.antfortune.freeline:gradle:0.8.1'
    }

androidstudio 2.2.0版本
jdk 1.8.77

请问这是为什么？还要继续等吗

**Comment by lomanyong** [comment]
@corleoneJ 应该是因为网络问题卡在下载的地方了...正常编译不可能这么久。

你可以手动执行一下`gradlew.bat :app:assembleDebug -P freelineBuild=true --stacktrace`检查具体是卡在哪个地方。

**Comment by corleoneJ** [comment]
> Building 97% > :app:transformClassesWithPreJackPackagedLibrariesForInternalDebug
A larger heap for the Gradle daemon is recommended for running jack.

It currently has 247 MB.
For faster builds, increase the maximum heap size for the Gradle daemon to at least 1536 MB.
To do this set org.gradle.jvmargs=-Xmx1536M in the project gradle.properties.
        at com.android.jack.backend.dex.rop.CodeItemBuilder.run(CodeItemBuilder.java:381)
        at com.android.jack.backend.dex.rop.CodeItemBuilder.run(CodeItemBuilder.java:116)
        at com.android.sched.scheduler.ScheduleInstance.runWithLog(ScheduleInstance.java:203)
        ... 2 more

*****************************************************************************************
# **我继续执行你了说的那条命令，然后报上边的错，

然后，我把这句代码写到了项目根目录的gradle.properties里，
org.gradle.jvmargs=-Xmx1536M**，报下边的错
****************************************************************************************

Error occurred during initialization of _VM_
Could not reserve enough space for 1572864KB object heap

        at org.gradle.launcher.daemon.bootstrap.DaemonGreeter.parseDaemonOutput(DaemonGreeter.java:34)
        at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startProcess(DefaultDaemonStarter.java:153)
        at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startDaemon(DefaultDaemonStarter.java:136)
        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.startDaemon(DefaultDaemonConnector.java:111)
        at org.gradle.launcher.daemon.client.SingleUseDaemonClient.execute(SingleUseDaemonClient.java:52)
        at org.gradle.launcher.daemon.client.SingleUseDaemonClient.execute(SingleUseDaemonClient.java:37)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:239)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:212)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by lomanyong** [comment]
@corleoneJ 看了下日志，跟 freeline 应该没有太多关系。从日志来看，你应该是开启了 Jack？freeline 不支持同 Jack 一起使用...

**Comment by corleoneJ** [comment]
感谢您的宝贵时间来回答我的问题，请问这个异常是什么引起的？

Caused by: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
        at com.antfortune.freeline.FreelinePlugin.addFreelineGeneratedFiles(FreelinePlugin.groovy:389)
        at com.antfortune.freeline.FreelinePlugin$_apply_closure4$_closure11$_closure15.doCall(FreelinePlugin.groovy:127)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:590)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:571)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
        at com.antfortune.freeline.FreelinePlugin.addFreelineGeneratedFiles(FreelinePlugin.groovy:389)
        at com.antfortune.freeline.FreelinePlugin$_apply_closure4$_closure11$_closure15.doCall(FreelinePlugin.groovy:127)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:590)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:571)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more

**Comment by lomanyong** [comment]
@corleoneJ 可以参考#315 #335 ，这个错误通常也是你本地的某些环境的问题导致的。可以看下后台进程是否还有 gradle 在占用，把那些后台进程结束掉..然后重新编译看看...

**Comment by corleoneJ** [comment]
WARNING: Ignoring Android API artifact com.google.android:android:2.1_r1 for xiucher_webRelease
WARNING: WARNING: Dependency org.apache.httpcomponents:httpclient:4.3.5 is ignored for xiucher_webRelease as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
find variant xiucher_webDebug start hack process...
variant xiucher_webRelease is not debug, skip hack process.

FAILURE: Build failed with an exception.

* What went wrong:
Task 'intiFreeline' not found in root project 'owner2'. Some candidates are: 'initFreeline'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Gradle文件：
apply plugin: 'com.android.application'
apply plugin: 'com.neenbedankt.android-apt'
apply plugin: 'com.antfortune.freeline'

android {
    def globalConfiguration = rootProject.extensions.getByName("ext")

    compileSdkVersion globalConfiguration.getAt("androidCompileSdkVersion")
    buildToolsVersion globalConfiguration.getAt("androidBuildToolsVersion")

    defaultConfig {
        minSdkVersion globalConfiguration.getAt("androidMinSdkVersion")
        targetSdkVersion globalConfiguration.getAt("androidTargetSdkVersion")

        applicationId globalConfiguration.getAt("androidApplicationId")
        versionCode globalConfiguration.getAt("androidVersionCode")
        versionName globalConfiguration.getAt("androidVersionName")
        testInstrumentationRunner globalConfiguration.getAt("testInstrumentationRunner")
        testApplicationId globalConfiguration.getAt("testApplicationId")

        manifestPlaceholders = [UMENG_CHANNEL_VALUE: "default_channel"]
        multiDexEnabled true
    }

    signingConfigs {
        myConfigs {
            storeFile file("../buildsystem/xiucheren.jks")
            keyAlias "修车人"
            keyPassword "xiucheren"
            storePassword "xiucheren"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.myConfigs
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.myConfigs
        }
    }

    freeline {
        hack true
    }

    productFlavors {

//        production {
//            manifestPlaceholders = [UMENG_CHANNEL_VALUE: "ceshi"]
//        }
//        internal {
//            manifestPlaceholders = [UMENG_CHANNEL_VALUE: "internal"]
//        }

        xiucher_web {
            manifestPlaceholders = [UMENG_CHANNEL_VALUE: "xiucher_web"]
        }
//        yingyongbao {
//            manifestPlaceholders = [UMENG_CHANNEL_VALUE: "yingyongbao"]
//        }
//        baiduzhushou {
//            manifestPlaceholders = [UMENG_CHANNEL_VALUE: "baiduzhushou"]
//        }
//        wandoujia {
//            manifestPlaceholders = [UMENG_CHANNEL_VALUE: "wandoujia"]
//        }
//        _360 {
//            manifestPlaceholders = [UMENG_CHANNEL_VALUE: "_360zhushou"]
//        }

//        ceshi {
//            manifestPlaceholders = [UMENG_CHANNEL_VALUE: "ceshi"]
//        }
    }

    lintOptions {
        abortOnError false
    }

    packagingOptions {
        exclude 'META-INF/ASL2.0'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/MANIFEST.MF'
        exclude 'META-INF/DEPENDENCIES'
    }

    dexOptions {
        jumboMode true
        incremental true
        javaMaxHeapSize "2g"
    }

//    compileOptions {
//        sourceCompatibility JavaVersion.VERSION_1_8
//        targetCompatibility JavaVersion.VERSION_1_8
//    }
    buildToolsVersion '24'
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile project(':barcode')
    compile project(':share')
    compile project(':map')
    compile project(':common')
    compile project(':push')
    compile project(':image')
    compile project(':slidedatetimepicker')
    compile project(':repository')
    compile project(':util')
    compile project(':wenda')

    // 展示层
    def presentationDependencies = rootProject.ext.presentationDependencies
    compile presentationDependencies.appcompatV7
    compile presentationDependencies.supportV4
    compile presentationDependencies.cardView
    compile presentationDependencies.butterKnife
    compile presentationDependencies.circleImageView
    compile presentationDependencies.otto
    compile('cn.trinea.android.view.autoscrollviewpager:android-auto-scroll-view-pager:1.1.2') {
        exclude module: 'support-v4'
    }

    // 数据
    def dataDependencies = rootProject.ext.dataDependencies
    compile dataDependencies.greenDao
    compile dataDependencies.dagger
    apt dataDependencies.daggerCompiler
    provided dataDependencies.javaxAnnotation
    compile dataDependencies.percentLayout
    compile dataDependencies.httpmime
    compile dataDependencies.httpcore

    def depenDencies = rootProject.ext.dependencies
    compile depenDencies.jackson
    compile depenDencies.cropper
    compile depenDencies.multidex
    compile depenDencies.mpermission
    apt depenDencies.mpermissiondpt
    compile depenDencies.constraintLayout
}

请问这个如何解决？

**Comment by lomanyong** [comment]
@corleoneJ 额...这不很明显吗。。。

`* What went wrong:
Task 'intiFreeline' not found in root project 'owner2'. Some candidates are: 'initFreeline'.`

已经给出提示了...命令错了...是`initFreeline`，而不是`intiFreeline`

**Comment by corleoneJ** [comment]
呃。。。不好意思，已经改过来了。。。

**Comment by corleoneJ** [comment]
我每次执行完 python freeline.py 命令之后，经常会出现一个对话框：

++++++++++++++++++++++++++++++++++++++++++++++++++++++
File Cache Conflict

Load File System Changes      Keep Memory Changes    Show different     Help  

++++++++++++++++++++++++++++++++++++++++++++++++++++++

每次都要点 Keep Memory Changes ， 有没有什么办法让freeline 永远执行第二个选项？

**Comment by lomanyong** [comment]
@corleoneJ 你是点了`ctrl+z`之类的才会有这种提示吧...

**Comment by corleoneJ** [comment]
没有撤销之类的操作，具体流程比如：
当我对a文件做了一次修改，然后运行freeline 。
当我第二次对a文件做了修改，然后运行freeline的时候，会弹出来一个对话框：
![qq 20161202151148](https://cloud.githubusercontent.com/assets/10388277/20825835/cdd43964-b8a1-11e6-93ff-be81a65530a6.png)

我必须选择之后他才会执行编译。

**Comment by lomanyong** [comment]
@corleoneJ strange issue... 通常是 AS 的文件缓存发现与本地的文件也存在修改的时候才会出这个提示...没搞清楚你本地是否有什么特殊的环境因素导致的，目前的反馈来看，其他的项目似乎没有这个问题..

**Comment by corleoneJ** [comment]
找到解决方案了，出处：http://stackoverflow.com/questions/6621166/how-to-prevent-phpstorm-to-reload-file-without-prompt-when-file-on-disk-is-chang。

![22221](https://cloud.githubusercontent.com/assets/10388277/20826511/6e51eae0-b8a6-11e6-9be7-1de0309f2a13.png)

上述是PHPstorm的解决方案，因为都是intellij  idea，所以我感觉AS应该也通用。

以下是我的AS的设置：
![111](https://cloud.githubusercontent.com/assets/10388277/20826538/9a8bdd8c-b8a6-11e6-80f8-c3dd40248a5a.png)

希望能帮到其他也遇到类似问题的人。

同时感谢 freeline 。

**Comment by lomanyong** [comment]
@corleoneJ 好的~感谢提供 case~

喜欢 freeline 的话欢迎向身边的朋友推荐哈~

**Comment by weiyanjie** [comment]
![image](https://cloud.githubusercontent.com/assets/11783776/21479532/191ca7ca-cb90-11e6-9683-7761dcea3c4f.png)
一直卡在这个位置  会是什么原因导致的呢

**Comment by QGB** [comment]
sudo apt install vim autopoint
