### ISSUE TITLE
第一次运行出错，不懂Python就没法进行下去了

### ISSUE THREAD

**Issue by shizhangbiao** [alibaba/freeline#368]
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "D:\项目地址\freeline_core\task.py", line 123, in execute
    self.task.execute()
  File "D:\项目地址\freeline_core\gradle_clean_build.py", line 75, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "D:\项目地址\freeline_core\utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "D:\Program Files\Python\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "D:\Program Files\Python\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2]

**Comment by lomanyong** [comment]
@shizhangbiao 这日志截取得不完整....怎么帮你看问题....

你可以先看下目录下有没有`gradlew.bat`这个文件...从这个不完整的日志只能猜测了..

**Comment by shizhangbiao** [comment]
好像是缺少了，直接从其他项目下拷贝一个可以吗

**Comment by lomanyong** [comment]
@shizhangbiao 可以...随便新建一个 Android 工程都会自动生成这个文件...
