### ISSUE TITLE
集成了GrowingIO的app第二次编译启动crash

### ISSUE THREAD

**Issue by wankey** [alibaba/freeline#374]
java.lang.RuntimeException: Unable to create application com.antfortune.freeline.FreelineApplication: android.content.res.Resources$NotFoundException: String resource ID #0x0
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
                                                       at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
                                                       at android.content.res.Resources.getText(Resources.java:312)
                                                       at android.content.res.Resources.getString(Resources.java:400)
                                                       at com.growingio.android.sdk.collection.GrowingIO.startWithConfiguration(Unknown Source)
                                                       at package.Application.initStatistic(ArenaGameApplication.java:68)
                                                       at package.setupDependency(ArenaGameApplication.java:37)
                                                       at framework.BaseApp.onCreate(BaseApp.java:31)
                                                       at package.Application.onCreate(ArenaGameApplication.java:27)
                                                       at com.antfortune.freeline.FreelineApplication.startRealApplication(FreelineApplication.java:51)
                                                       at com.antfortune.freeline.FreelineApplication.onCreate(FreelineApplication.java:32)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                                                       at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by lomanyong** [comment]
@wankey 参考 #273 来解决这个问题
