### ISSUE TITLE
编译遇到错误 task.py", line 123, in execute self.task.execute()

### ISSUE THREAD

**Issue by xiebudong** [alibaba/freeline#400]
两个工程目录A和B， 属于同一个项目只是分支不同，之前在A上配置的freeline，一切运行良好，后面建立B工程导入后编译出现错误， 尝试clean  然后执行freeline -f也还是不行，B是基于A建立的分支所以freeline的配置完全一样，A工程一直没有问题， 怀疑是不是多工程冲突了。  

freeline版本 0.8.2

 错误如下：
`[INFO] preparing for tasks...
[-][read_project_info_task] finished. in 27.7s
[-][generate_file_stat_task] finished. in 0.6s
[-][gradle_clean_build_task] failed. in 0.0s
[-][clean_all_cache_task] failed. in 0s
[-][install_apk_task] failed. in 0s
[-][build_base_resource_task] failed. in 0s
[-][generate_project_info_task] failed. in 0s
[-][generate_apt_files_task] failed. in 0s
[-][append_file_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "/Users/BMR/Work_IN/Git_SmallProj/Git_InAR/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/Users/BMR/Work_IN/Git_SmallProj/Git_InAR/freeline/freeline_core/gradle_clean_build.py", line 116, in execute
    output, err, code = cexec(command.split(' '), callback=None, cwd=cwd)
  File "/Users/BMR/Work_IN/Git_SmallProj/Git_InAR/freeline/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.1s
[DEBUG] Task engine running time: 27.7s
[DEBUG] Total time: 27.8s
[DEBUG] --------------------------------------------------------`

**Comment by lomanyong** [comment]
@xiebudong 目录下缺少`gradlew`这个文件导致的...拷贝过来即可，记得加上可执行权限。
