### ISSUE TITLE
java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.baiyin.baiud.services.GoldPriceService$GoldPriceBinder

### ISSUE THREAD

**Issue by huangbom** [alibaba/freeline#415]
`➜  goldandroid ✗ python freeline.py -v`
`v0.8.3`

我在application里面bind service，在下面的时候报错

```
Process: com.fuqi.gold:freeline, PID: 11731
                                                                            java.lang.ClassCastException: android.os.BinderProxycannot be cast to com.baiyin.baiud.services.GoldPriceService$GoldPriceBinder
                                                                            at com.baiyin.baiud.GoldApp$GoldPriceServiceConnection.onServiceConnected(GoldApp.java:503)
                                                                            at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1339)
                                                                            at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1356)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7326)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

```
 public class GoldPriceServiceConnection implements ServiceConnection {
        @Override
        public void onServiceDisconnected(ComponentName name) {
        }

        @Override
        public void onServiceConnected(ComponentName name, IBinder service) {
            // 这里报错
            GoldPriceBinder binder = (GoldPriceBinder) service;
            binder.start();
        }
    }
```

我配置了这个属性clean 之后也没有用

```
 freeline {
       applicationProxy false
}
```

```

@Override
public void onCreate() {
        super.onCreate(); 
        FreelineCore.init(this);

  
```

**Comment by lomanyong** [comment]
@huangbom 是参考了 #273 做的吗？clean 后重新使用 freeline 编译的吗？

这个 cast 出问题的是否使用了某些三方库？

**Comment by huangbom** [comment]
@lomanyong 我把这些去掉了

```
freeline {
       applicationProxy false
}

@Override
public void onCreate() {
        super.onCreate(); 
        FreelineCore.init(this);
        ...
}
```

然后我打了log发现是这样的：

> com.xxx.xxx I/onServiceConnected: AdDownloadBinder
> com.xxx.xxx:freeline I/onServiceConnected: BinderProxy

有一个freeline的也执行到了这里，那个IBinder service就变成了BinderProxy。
然后我这样就没问题了：
```
if (service instanceof AdDownloadService.AdDownloadBinder) {
         Log.i("instanceof","hahahahahah");
         AdDownloadService.AdDownloadBinder binder = (AdDownloadService.AdDownloadBinder) service;
         binder.start();
}
```

> 非常感谢🙏

>
