### ISSUE TITLE
Error when initialize freeline.

### ISSUE THREAD

**Issue by pollyfat** [alibaba/freeline#420]
[INFO] preparing for tasks...
[-][read_project_info_task] failed. in 0.1s
[-][generate_file_stat_task] finished. in 0.0s
[-][gradle_clean_build_task] failed. in 0s
[-][clean_all_cache_task] failed. in 0s
[-][install_apk_task] failed. in 0s
[-][build_base_resource_task] failed. in 0s
[-][generate_project_info_task] failed. in 0s
[-][generate_apt_files_task] failed. in 0s
[-][append_file_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Hmei/StudioProjects/36g-ls-android/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/Users/Hmei/StudioProjects/36g-ls-android/freeline/freeline_core/gradle_clean_build.py", line 75, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "/Users/Hmei/StudioProjects/36g-ls-android/freeline/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 0.1s
[DEBUG] Total time: 0.4s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@pollyfat 项目根目录下缺少了 gradlew 文件，从别的项目复制一个过来即可..记得加上可执行权限...

提问前可以搜索一下已有的 issue...

**Comment by pollyfat** [comment]
谢谢。

大概看了下没找到，下次注意。
