### ISSUE TITLE
Exception in thread "main" java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by bailibaili** [alibaba/freeline#434]
localhost:XiaoWei liushuai$ python freeline.py  
[INFO] preparing for tasks...
[-][read_project_info_task] failed. in 0.5s
[-][generate_file_stat_task] finished. in 0.0s
[-][gradle_clean_build_task] failed. in 0s
[-][clean_all_cache_task] failed. in 0s
[-][install_apk_task] failed. in 0s
[-][build_base_resource_task] failed. in 0s
[-][generate_project_info_task] failed. in 0s
[-][generate_apt_files_task] failed. in 0s
[-][append_file_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)
        at org.gradle.wrapper.Install.unzip(Install.java:214)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

[ERROR] --------------------------------------------------------
[ERROR] freeline failed when read project info with script: ./gradlew -q checkBeforeCleanBuild

在issue中也没有找到类似问题的答案，请问一下这个是什么原因？

**Comment by lomanyong** [comment]
@bailibaili gradle.zip 下载有问题...你随便在命令行执行一下 `./gradlew tasks`应该也会报错...或者重新自动下载..

**Comment by bailibaili** [comment]
如果我使用这个指令就会报另一个错误
localhost:XiaoWei liushuai$ ./gradlew initFreeline
Unzipping /Users/liushuai/.gradle/wrapper/dists/gradle-2.14.1-all/8bnwg5hd3w55iofp58khbp6yv/gradle-2.14.1-all.zip to /Users/liushuai/.gradle/wrapper/dists/gradle-2.14.1-all/8bnwg5hd3w55iofp58khbp6yv
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)
        at org.gradle.wrapper.Install.unzip(Install.java:214)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
localhost:XiaoWei liushuai$

**Comment by lomanyong** [comment]
@bailibaili 额。。。把这个文件给删了`/Users/liushuai/.gradle/wrapper/dists/gradle-2.14.1-all/8bnwg5hd3w55iofp58khbp6yv/gradle-2.14.1-all.zip`，让他重新下载，或者你搜索下 gradle.zip 离线下载的方法...不然太慢了...

**Comment by bailibaili** [comment]
好的，谢谢

**Comment by LeeWiHong** [comment]
通过删除gradle-2.14.1-all.zip再到webstorm中运行一次他会自动下载，搞定了。。。
