### ISSUE TITLE
编译的时候 挂了

### ISSUE THREAD

**Issue by stevenchans** [alibaba/freeline#436]
log 日志
 What went wrong:
Execution failed for task ':app:mergeAjmdDebugAssets'.
> /Users/ajmd/ajmide_android_studio_new/app/build/intermediates/assets/debug/apktime file not found. 
  Missing the `productFlavor` configuration?
  You can try to add `productFlavor` to freeline DSL, for example: 
  
    freeline { 
        hack true 
        productFlavor 'your-flavor' 
    }
  
  Then re-run `python freeline.py` again.

**Comment by stevenchans** [comment]
java.lang.NoClassDefFoundError:   
 编译过了  
我的project  使用了 谷歌官方的分包机制   这个会有冲突吗

**Comment by WJRye** [comment]
我的也能够成功编译，但是运行应用程序就报错。这个与 谷歌的multiDex兼容吗?

**Comment by huangbom** [comment]
@stevenchans @WJRye 我使用了multiDex没问题
```
    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(base);
    }
```

**Comment by lomanyong** [comment]
@stevenchans @WJRye 参考 #273 的做法可以解决你们的问题，兼容是没有问题的

**Comment by stevenchans** [comment]
@lomanyong
我已经使用了 这个官方的 解决方案   还是有这个问题  
我还有使用阿里的andfix 热修复框架  会有冲突吗

**Comment by stevenchans** [comment]
@lomanyong 
log 日志
java.lang.reflect.InvocationTargetException
                                                 at java.lang.reflect.Constructor.constructNative(Native Method)
                                                 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                 at com.antfortune.freeline.FreelineApplication.createRealApplication(FreelineApplication.java:84)
                                                 at com.antfortune.freeline.FreelineApplication.onCreate(FreelineApplication.java:30)
                                                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4430)
                                                 at android.app.ActivityThread.access$1500(ActivityThread.java:142)
                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1263)
                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                 at android.os.Looper.loop(Looper.java:136)
                                                 at android.app.ActivityThread.main(ActivityThread.java:5118)
                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
                                                 at dalvik.system.NativeStart.main(Native Method)

**Comment by lomanyong** [comment]
@stevenchans 不会有任何冲突...你确认你使用 #273 提供的解决方案吗？从日志来看并没有...

你需要的是，先 clean 一下，再编译...
