### ISSUE TITLE
编码问题UnicodeEncodeError: 'ascii' codec can't encode character u'\u8f6f'

### ISSUE THREAD

**Issue by xialei92** [alibaba/freeline#437]
````
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=True, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.2.2
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.3
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.3
[DEBUG] find app has 0 java files modified.
[DEBUG] project just need a incremental build.
[DEBUG] file changed list:
{
    "build_info": {
        "last_clean_build_time": 1481022613.8854754,
        "is_root_config_changed": false
    },
    "projects": {
        "app": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        }
    }
}
[DEBUG] [task_engine] depth: 1, task: [connect_device_task]
[DEBUG] [task_engine] depth: 1, task: [gradle_aapt_task]
[DEBUG] [task_engine] depth: 2, task: [app]
[DEBUG] [task_engine] depth: 3, task: [merge_dex_task]
[DEBUG] [task_engine] depth: 5, task: [gradle_sync_task]
[DEBUG] [task_engine] depth: 6, task: [clean_cache_task]
[DEBUG] [task_engine] depth: 7, task: [update_stat_task]
[DEBUG] [connect_device_task] connect_device_task start to run after waiting 0.0s
[DEBUG] [gradle_aapt_task] gradle_aapt_task start to run after waiting 0.0s
[DEBUG] [sync_client] start to connect device...
[DEBUG] [sync_client] apktime path: C:\Demo\coolchat\app\build\freeline\freeline-assets\apktime
[DEBUG] [gradle_aapt_task] no need to execute
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 0.0s
[DEBUG] [app] app start to run after waiting 0.0s
[DEBUG] [sync_client] your local sync value is: 925000
[DEBUG] [sync_client] your local uuid value is: 925000
[DEBUG] [app_inc_invoker] app old R.java path: C:\Demo\coolchat\app\build\generated\source\r\debug\com\coolchat\aha\R.java
[DEBUG] [app_inc_invoker] app new R.java path: C:\Demo\coolchat\app\build\freeline\app\backup\com\coolchat\aha\R.java
[DEBUG] avoid windows unicode error for C:\Demo\coolchat\app\build\freeline\app\backup\com\coolchat\aha\R.java
[DEBUG] [app_inc_invoker] find R.java changed (md5 value is different from origin R.java)
[DEBUG] [app_inc_invoker] src changed files:
[DEBUG] [app_inc_invoker] [u'C:\\Demo\\coolchat\\app\\build\\freeline\\app\\backup\\com\\coolchat\\aha\\R.java']
[DEBUG] [app_inc_invoker] find R.java modified in src list
[DEBUG] [app_inc_invoker] app code only change R.java, need not go ahead
[DEBUG] [app_inc_javac_compile] no need to execute
[DEBUG] [app_inc_dex_compile] no need to execute
[DEBUG] [app] app finish in 0.1s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 0.1s
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s
[DEBUG] [sync_client] server result is 1
[DEBUG] [sync_client] find device port: 41128
[DEBUG] [connect_device_task] connect_device_task finish in 0.3s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 0.3s
C:\Demo\coolchat>python freeline.py
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=False, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.2.2
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.3
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.3
[DEBUG] [scan_changed_files_command] find C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\widget\ScrollEdgeViewPager.java has modification.
[DEBUG] find app has 1 java files modified.
[DEBUG] project just need a incremental build.
[DEBUG] file changed list:
{
    "build_info": {
        "last_clean_build_time": 1481022613.8854754,
        "is_root_config_changed": false
    },
    "projects": {
        "app": {
            "src": [
                "C:\\Demo\\coolchat\\app\\src\\main\\java\\com\\coolchat\\aha\\widget\\ScrollEdgeViewPager.java"
            ],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        }
    }
}
[DEBUG] [task_engine] depth: 1, task: [connect_device_task]
[DEBUG] [task_engine] depth: 1, task: [gradle_aapt_task]
[DEBUG] [task_engine] depth: 2, task: [app]
[DEBUG] [task_engine] depth: 3, task: [merge_dex_task]
[DEBUG] [task_engine] depth: 5, task: [gradle_sync_task]
[DEBUG] [task_engine] depth: 6, task: [clean_cache_task]
[DEBUG] [task_engine] depth: 7, task: [update_stat_task]
[DEBUG] [connect_device_task] connect_device_task start to run after waiting 0.0s
[DEBUG] [gradle_aapt_task] gradle_aapt_task start to run after waiting 0.0s
[DEBUG] [sync_client] start to connect device...
[DEBUG] [gradle_aapt_task] no need to execute
[DEBUG] [sync_client] apktime path: C:\Demo\coolchat\app\build\freeline\freeline-assets\apktime
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 0.0s
[DEBUG] [app] app start to run after waiting 0.0s
[DEBUG] [sync_client] your local sync value is: 925000
[DEBUG] [sync_client] your local uuid value is: 925000
[DEBUG] [app_inc_invoker] app old R.java path: C:\Demo\coolchat\app\build\generated\source\r\debug\com\coolchat\aha\R.java
[DEBUG] [app_inc_invoker] app new R.java path: C:\Demo\coolchat\app\build\freeline\app\backup\com\coolchat\aha\R.java
[DEBUG] avoid windows unicode error for C:\Demo\coolchat\app\build\freeline\app\backup\com\coolchat\aha\R.java
[DEBUG] [app_inc_invoker] find R.java changed (md5 value is different from origin R.java)
[DEBUG] [app_inc_invoker] src changed files:
[DEBUG] [app_inc_invoker] [u'C:\\Demo\\coolchat\\app\\src\\main\\java\\com\\coolchat\\aha\\widget\\ScrollEdgeViewPager.java', u'C:\\Demo\\coolchat\\app\\build\\freeline\\
app\\backup\\com\\coolchat\\aha\\R.java']
[DEBUG] [app_inc_invoker] find R.java modified in src list
[DEBUG] [app_inc_javac_compile] start to execute javac command...
[DEBUG] avoid windows unicode error for C:\Demo\coolchat\app\build\freeline\app\backup\com\coolchat\aha\R.java
[DEBUG] [sync_client] server result is 1
[DEBUG] [app_inc_invoker] find R.java modified in src list
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\easemob\widget\AudioMsgView.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\easemob\widget\FriendlyMsgView.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\easemob\widget\PicMsgView.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\easemob\widget\TextMsgView.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\easemob\widget\VideoMsgView.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\chat\ChatFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\chat\DriftBottleFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\chat\helper\ChatItemViewHelper.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\chat\MsgFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\common\BlackListFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\common\ChooseVideoFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\common\DisclaimerFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\common\FAndQFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\common\MainFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\common\PersonalDynamicFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\common\RewardFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\common\SettingFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\common\UserPageFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\dialog\DemoDialog.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\dialog\LoginDialog.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\dialog\PayDialog.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\dialog\ReportDialog.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\dialog\ResponseDialog.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\dialog\SetPasswordDialog.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\dialog\TextWarnDialog.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\dialog\UpdateAppDialog.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\discovery\ApplyStep1Fragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\discovery\ApplyStep2Fragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\discovery\BeautyFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\discovery\ChoosePublishFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\discovery\CommentDetailFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\discovery\DiscoveryFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\discovery\InterestingFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\discovery\LocationFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\discovery\PublishDynamicFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\me\BaseInfoFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\me\ChooseCityFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\me\EditPersonalInfoFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\me\FeedBackFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\me\FriendsFatherFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\me\FriendsFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\me\IncomeDetailFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\me\MeFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\me\ModifyBaseInfoFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\me\MyImageFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\me\MyMessageFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\me\MyWalletFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\me\PublishRewardFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\me\SecretPicOrVideoFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\me\VisitorFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\popwindow\ChatFilterPop.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\ui\popwindow\ChatFunctionsPop.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\video_selector\VideoSelectorFragment.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\widget\AuthCodeView.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\widget\AvatarView.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\widget\ChatBottomBar.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\widget\ChatRecordView.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\widget\EditInformationView.java
[DEBUG] [app_inc_invoker] add apt related file: C:\Demo\coolchat\app\src\main\java\com\coolchat\aha\widget\GenderAgeView.java
[DEBUG] [app_inc_invoker] arguments length: 29724 > 8000, save args to C:\Demo\coolchat\app\build\freeline\app\javac_args_file
[DEBUG] [app] app finish in 0.1s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 0.1s
[DEBUG] [sync_client] find device port: 41128
[DEBUG] [connect_device_task] connect_device_task finish in 0.4s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 0.4s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 0.4s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 0.4s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 0.36s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "C:\Demo\coolchat\freeline_core\android_tools.py", line 334, in execute
    self._command.execute()
  File "C:\Demo\coolchat\freeline_core\gradle_inc_build.py", line 186, in execute
    map(lambda command: command.execute(), self.command_list)
  File "C:\Demo\coolchat\freeline_core\gradle_inc_build.py", line 186, in <lambda>
    map(lambda command: command.execute(), self.command_list)
  File "C:\Demo\coolchat\freeline_core\gradle_inc_build.py", line 225, in execute
    self._invoker.run_javac_task()
  File "C:\Demo\coolchat\freeline_core\gradle_inc_build.py", line 615, in run_javac_task
    javacargs = self._generate_java_compile_args(extra_javac_args_enabled=extra_javac_args_enabled)
  File "C:\Demo\coolchat\freeline_core\gradle_inc_build.py", line 685, in _generate_java_compile_args
    self.debug('javac arguments: ' + arguments_content)
  File "C:\Demo\coolchat\freeline_core\android_tools.py", line 374, in debug
    Logger.debug('[{}_inc_invoker] {}'.format(self._name, message))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u8f6f' in position 1629: ordinal not in range(128)

[ERROR] --------------------------------------------------------
[ERROR] incremental build task failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 0.4s
[DEBUG] Total time: 0.6s
[DEBUG] --------------------------------------------------------
````

**Comment by jp1017** [comment]
linux 16.04, 升级到0.8.3后，全量编译出错：

>Traceback (most recent call last):
  File "***/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "***/freeline/freeline_core/android_tools.py", line 44, in execute
    self._install_apk()
  File "***/freeline/freeline_core/android_tools.py", line 69, in _install_apk
    self.debug('start to install apk to device: {}'.format(' '.join(install_args)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 119-122: ordinal not in range(128)

**Comment by lomanyong** [comment]
@jp1017 这个编码的问题应该是出现了中文字符导致的...确认下路径是否有中文吗？

**Comment by jp1017** [comment]
@lomanyong 刚删了0.8.3, 换回0.8.2, 一切正常的呀。。路径没有中文

**Comment by jp1017** [comment]
又删除0.8.2, 下载0.8.3，还是报上面错误。。。 @lomanyong :disappointed:

**Comment by lomanyong** [comment]
@jp1017 `adb`的路径有中文吗？

**Comment by jp1017** [comment]
@lomanyong 没有中文。。

sdk里面的是路径:

>~/Android/Sdk/platform-tools/adb

linux系统路径:

>/usr/bin/adb

**Comment by lomanyong** [comment]
@jp1017 基本就是 adb 路径有中文，或者 apk 的路径或者名字含有中文导致的了...

````python
install_args = [self._adb, 'install', '-r', self._apk_path]
self.debug('start to install apk to device: {}'.format(' '.join(install_args)))
````

Python 出现字符编码的问题一直比较头疼...得找下有什么比较好的根治的手段...

**Comment by jp1017** [comment]
@lomanyong apk包名我自定义的有中文。。 :cry: 坑了

**Comment by hzz9600** [comment]
你好，我也出现了这个错误，排查了工程所有路径和jdk路径，实在找不到包含中文的地方，修改xml编译没问题，修改代码就出现了UnicodeEncodeError: 'ascii' codec can't encode character u'\u3001' in position 1629: ordinal not in range(128)

**Comment by xialei92** [comment]
@hzz9600 你是不是用的Windows 然后你的用户名是中文的 我当时的问题就出在这
