### ISSUE TITLE
Unsupported major.minor version  52.0

### ISSUE THREAD

**Issue by Bvin** [alibaba/freeline#441]
java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version
 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Exception in thread "main"

asVersion 2.2.3
compileSdkVersion 23
buildToolsVersion "25.0.1"
minSdkVersion 14
targetSdkVersion 25
classpath 'com.android.tools.build:gradle:2.1.2'
classpath 'com.antfortune.freeline:gradle:0.8.3'

**Comment by pengwei1024** [comment]
你好，这是Freeline插件报错吗？ @Bvin

**Comment by lomanyong** [comment]
@Bvin 需要完整一点的呀...以及在什么情况下出现...

**Comment by Bvin** [comment]
可以了，targetSdkVersion降低为23就可以了
