### ISSUE TITLE
正常运行项目，但是会造成我手机的生日管家应用崩溃

### ISSUE THREAD

**Issue by oneapp1e** [alibaba/freeline#445]
Process: com.octinn.birthdayplus, PID: 26786
                                                   java.lang.RuntimeException: Unable to start receiver com.antfortune.freeline.FreelineReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.app.Application.getPackageName()' on a null object reference
                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2748)
                                                       at android.app.ActivityThread.access$1800(ActivityThread.java:153)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5458)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.app.Application.getPackageName()' on a null object reference
                                                       at com.antfortune.freeline.a.g(FreelineCore.java:362)
                                                       at com.antfortune.freeline.FreelineReceiver.onReceive(FreelineReceiver.java:36)
                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2741)
                                                       at android.app.ActivityThread.access$1800(ActivityThread.java:153) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5458) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628) 
12-07 14:21:06.748 3549-3560/? E/ANDR-PERF-OPTSHANDLER: perf_lock_rel: updated /sys/class/scsi_host/host0/../../../clkscale_enable with 1
                                                         return value 2

**Comment by lomanyong** [comment]
@oneapp1e 。。。生日管家是第三方的app吗？还是你的开发项目？

**Comment by oneapp1e** [comment]
第三方app，与我的项目无关，我用自己的手机做测试遇到的，小米手机正常运行项目了，但是每次都会报这个异常。我把生日管家的进程杀掉也不行，运行项目还是会报。

**Comment by oneapp1e** [comment]
第三方app，与我的项目无关，我用自己的手机做测试遇到的，小米手机正常运行项目了，但是每次都会报这个异常。我把生日管家的进程杀掉也不行，运行项目还是会报。

**Comment by lomanyong** [comment]
@oneapp1e 那还生日管家打包的问题。。。解决的方式只有一个。。把它从你的测试手机上先卸载了...
