### ISSUE TITLE
在部分5.0以下手机上，使用freeline运行会崩溃

### ISSUE THREAD

**Issue by bjzhou** [alibaba/freeline#479]
```
12-13 21:51:51.350 1628-1628/mobi.supo.cleaner E/dalvikvm: Could not find class 'com.google.android.gms.common.util.zza', referenced from method com.google.firebase.FirebaseApp.zzNW
12-13 21:51:51.396 1628-1628/mobi.supo.cleaner E/dalvikvm: Could not find class 'com.google.android.gms.common.internal.zzah', referenced from method com.google.firebase.FirebaseOptions.fromResource
12-13 21:51:51.423 1628-1628/mobi.supo.cleaner E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 java.lang.NoClassDefFoundError: com.google.android.gms.common.internal.zzah
                                                                     at com.google.firebase.FirebaseOptions.fromResource(Unknown Source)
                                                                     at com.google.firebase.FirebaseApp.zzbu(Unknown Source)
                                                                     at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
                                                                     at android.content.ContentProvider.attachInfo(ContentProvider.java:1058)
                                                                     at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:5127)
                                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4711)
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4651)
                                                                     at android.app.ActivityThread.access$1300(ActivityThread.java:165)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1433)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                     at android.os.Looper.loop(Looper.java:194)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5400)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:525)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by lomanyong** [comment]
@bjzhou 参考 #273 的方案应该可以解决你的问题
