### ISSUE TITLE
Android 7.0 增量资源兼容性问题

### ISSUE THREAD

**Issue by gdky005** [alibaba/freeline#48]
操作步骤：
1. Activity 里面套了 四个 fragment， 修改第一个里面的东西，点击第二个 tab 的时候崩溃，提示如下：

````
309 E/Freeline.ResPatcher: Failed to update existing theme for activity com.jm.android.jumei.home.activity.HomeActivity@86885df
                                          java.lang.NoSuchFieldException: No field mTheme in class Landroid/content/res/Resources$Theme; (declaration of 'android.content.res.Resources$Theme' appears in /system/framework/framework.jar)
                                              at java.lang.Class.getDeclaredField(Native Method)
                                              at com.android.tools.fd.runtime.MonkeyPatcher.monkeyPatchExistingResources(MonkeyPatcher.java:330)
                                              at com.antfortune.freeline.gradle.GradleDynamic.applyDynamicRes(GradleDynamic.java:32)
elineCore.applyDynamicRes(FreelineCore.java:297)
                                              at com.antfortune.freeline.FreelineCore.injectResources(FreelineCore.java:240)
                                              at com.antfortune.freeline.FreelineCore.saveDynamicResInfo(FreelineCore.java:322)
                                              at com.antfortune.freeline.FreelineReceiver.saveDynamicResInfo(FreelineReceiver.java:52)
                                              at com.antfortune.freeline.FreelineReceiver.onReceive(FreelineReceiver.java:39)
                                              at android.app.ActivityThread.handleReceiver(ActivityThread.java:3011)
                                              at android.app.ActivityThread.-wrap18(ActivityThread.java)
                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1544)
                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                              at android.os.Looper.loop(Looper.java:154)
                                              at android.app.ActivityThread.main(ActivityThread.java:6077)
                                              at java.lang.reflect.Method.invoke(Native Method)
                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
````

**Comment by lomanyong** [comment]
related commit (85b9b7c)[https://github.com/alibaba/freeline/commit/85b9b7cdfb11c0fe455d12058420b67994863b45]

**Comment by lomanyong** [comment]
@gdky005 可以试一下`0.5.5`的版本，看下在7.0上是否还会出现同样的crash
