### ISSUE TITLE
点击Android studio中的Freeline的图标就出现这个

### ISSUE THREAD

**Issue by YuJunKui1995** [alibaba/freeline#480]
python freeline.py
Traceback (most recent call last):
  File "freeline.py", line 7, in <module>
    from freeline_core.dispatcher import Dispatcher
  File "D:\shidexian\ShiDeXianAPPAndroid\freeline_core\__init__.py", line 1, in <module>
    import build_commands
ImportError: No module named 'build_commands'

**Comment by lomanyong** [comment]
@YuJunKui1995 不支持 Python 3 目前，麻烦使用 Python 2.7+的版本
