### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by cwjfeifei** [alibaba/freeline#490]
F:\test>gradlew.bat initFreeline
Exception in thread "main" java.lang.NullPointerException
        at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:34)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:25)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by lomanyong** [comment]
@cwjfeifei Google it. 跟 freeline 没有关系...本地的 gradle 环境的问题...
