### ISSUE TITLE
第一次使用的时候报  You can try to add `productFlavor` to freeline DSL

### ISSUE THREAD

**Issue by sight-wxc** [alibaba/freeline#497]
我在build.gradle配置下是有的啊
freeline {
        hack true
        productFlavor "develop"
        autoDependency false
    }
productFlavors {
..
develop {}
}
这样配置 有错么？

**Comment by lomanyong** [comment]
@sight-wxc 重新 clean 编译一下？没日志看不出问题...如果配置真的跟你发的一致的话，应该是没问题的...

**Comment by sight-wxc** [comment]
重新build 之后 
* What went wrong:
Execution failed for task ':app:mergeDevelopDebugAssets'.
> D:\working-svn\YuMeiRen\app\build\intermediates\assets\develop\debug\apktime file not found.
Missing the `productFlavor` configuration?
You can try to add `productFlavor` to freeline DSL, for example:

  freeline {
      hack true
      productFlavor 'your-flavor'
  }

Then re-run `python freeline.py` again.


* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:mergeDevelopDebugAssets'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.GradleException: D:\working-svn\YuMeiRen\app\build\intermediates\assets\develop\debug\apktime file not found.
Missing the `productFlavor` configuration?
You can try to add `productFlavor` to freeline DSL, for example:

  freeline {
      hack true
      productFlavor 'your-flavor'
  }

Then re-run `python freeline.py` again.

        at com.antfortune.freeline.FreelinePlugin$_addFreelineGeneratedFiles_closure5.doCall(FreelinePlugin.groovy:424)
        at com.antfortune.freeline.FreelinePlugin.addFreelineGeneratedFiles(FreelinePlugin.groovy:419)
        at com.antfortune.freeline.FreelinePlugin$_apply_closure4$_closure11$_closure15.doCall(FreelinePlugin.groovy:142)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more


[ERROR] --------------------------------------------------------
[ERROR] build failed with script: gradlew.bat :app:assembleDevelopDebug -P freelineBuild=true -PdisableAutoDependency=true --stacktrace
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.4s
[DEBUG] Task engine running time: 7.0s
[DEBUG] Total time: 7.4s
[DEBUG] --------------------------------------------------------

这是日志 ，会不会跟Androidannotations 这个注解 有冲突？

**Comment by lomanyong** [comment]
@sight-wxc 删掉`autoDependency false`这一行...重新编译应该就好了...
