### ISSUE TITLE
修改布局文件后增量编译，会引发崩溃，全量编译后正常

### ISSUE THREAD

**Issue by EndSmile** [alibaba/freeline#512]
```
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                      
 at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:124)
                                                       at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:146)
                                                       at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:59)
                                                       at com.xdja.auxiliaryPoliceSys.common.base.BaseActivity.onCreate(BaseActivity.java:38)
                                                       at android.app.Activity.performCreate(Activity.java:6323)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:165) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:150) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5546) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682) 
```

**Comment by lomanyong** [comment]
@EndSmile 崩溃后再点击app是否可以恢复正常？

**Comment by EndSmile** [comment]
不会，点击启动app都会报这个错误

**Comment by lomanyong** [comment]
@EndSmile 麻烦提供一个必现的 sample 吧，否则我这里也无法测试并修复...

**Comment by EndSmile** [comment]
@lomanyong 
找到问题了，主module引用的两个子module(common,push)里面都有一个叫AppTheme的主题，主module引用了这个主题，正常情况下其使用的是common里的AppTheme，但是修改布局文件后的增量编译后其引用了push里的AppTheme，就报出了这个错误
