### ISSUE TITLE
ImportError: No module named 'command'

### ISSUE THREAD

**Issue by waitinghc** [alibaba/freeline#514]
`D:\AndroidStudioProjects\CustomizeKeyboard>python freeline.py
Traceback (most recent call last):
  File "freeline.py", line 7, in <module>
    from freeline_core.dispatcher import Dispatcher
  File "D:\AndroidStudioProjects\CustomizeKeyboard\freeline_core\dispatcher.py", line 8, in <module>
    from command import AbstractCommand
ImportError: No module named 'command'
` 请问还需要配置什么东西吗

**Comment by lomanyong** [comment]
@waitinghc 不支持 Python3，切换为 Python2.7+即可。

**Comment by waitinghc** [comment]
谢谢，完美解决
