### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 141-142ordinal not in range(128)

### ISSUE THREAD

**Issue by Goheadfor** [alibaba/freeline#515]
Traceback (most recent call last):
  File "freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "freeline/freeline_core/gradle_inc_build.py", line 170, in execute
    self._invoker.check_other_modules_resources()
  File "freeline/freeline_core/gradle_inc_build.py", line 448, in check_other_modules_resources
    self.__modify_main_r()
  File "freeline/freeline_core/gradle_inc_build.py", line 458, in __modify_main_r
    self.debug('modify {}'.format(main_r_fpath))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 141-142: ordinal not in range(128)

就改了布局文件的一个显示文本，然后在增量编译就报这个错误，在 ./gradlew clean 之后再编译就编译正常

**Comment by lomanyong** [comment]
@Goheadfor 路径中包含有中文的原因导致的...

**Comment by Goheadfor** [comment]
@lomanyong 怎么查看是哪个路径包含有中文，我的项目地址没有中文额
