### ISSUE TITLE
initFreeline的时候出现错误

### ISSUE THREAD

**Issue by 550609334** [alibaba/freeline#520]
在执行initFreeline的时候出现这个错误，之后无法再次尝试 报同样的错误

liuzipengdeMacBook-Pro:~ liuzipeng$ cd /Users/liuzipeng/Documents/android-cb01/CB01
liuzipengdeMacBook-Pro:CB01 liuzipeng$ ./gradlew initFreeline -Pmirror
Unzipping /Users/liuzipeng/.gradle/wrapper/dists/gradle-2.14.1-all/8bnwg5hd3w55iofp58khbp6yv/gradle-2.14.1-all.zip to /Users/liuzipeng/.gradle/wrapper/dists/gradle-2.14.1-all/8bnwg5hd3w55iofp58khbp6yv
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.zip.ZipFile.<init>(ZipFile.java:164)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by lomanyong** [comment]
@550609334 。。。gradle 初始化的问题，把相关的文件删掉`/Users/liuzipeng/.gradle/wrapper/dists/gradle-2.14.1-all/8bnwg5hd3w55iofp58khbp6yv/gradle-2.14.1-all.zip`，重新执行
