### ISSUE TITLE
[ERROR] build failed with script: gradlew.bat :quanzhouparking:assembleDebug -P freelineBuild=true --stacktrace

### ISSUE THREAD

**Issue by weibinguo** [alibaba/freeline#527]
运行 FreeRun就报这个错
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':quanzhouparking:mergeBaiduDebugAssets'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.GradleException: D:\AndroidStudioProjects\QuanZhouParking\quanzhouparking\build\intermediates\assets\debug\apktime file not found.
Missing the `productFlavor` configuration?
You can try to add `productFlavor` to freeline DSL, for example:

  freeline {
      hack true
      productFlavor 'your-flavor'
  }

Then re-run `python freeline.py` again.

        at com.antfortune.freeline.FreelinePlugin$_addFreelineGeneratedFiles_closure5.doCall(FreelinePlugin.groovy:386)
        at com.antfortune.freeline.FreelinePlugin.addFreelineGeneratedFiles(FreelinePlugin.groovy:381)
        at com.antfortune.freeline.FreelinePlugin$_apply_closure4$_closure13$_closure17.doCall(FreelinePlugin.groovy:142)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:590)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:571)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more

[ERROR] build failed with script: gradlew.bat :quanzhouparking:assembleDebug -P freelineBuild=true --stacktrace

**Comment by lomanyong** [comment]
@weibinguo 日志中已有相应的提示：
````
Missing the productFlavor configuration?
You can try to add productFlavor to freeline DSL, for example:

freeline {
hack true
productFlavor 'your-flavor'
}

Then re-run python freeline.py again.
````

**Comment by weibinguo** [comment]
your-flavor 要怎么填写，能举个例子吗

**Comment by lomanyong** [comment]
@weibinguo 你工程相关的 flavor，看你们平时主要适用哪个来进行开发，配置哪个即可。
