### ISSUE TITLE
Attempt to invoke virtual method 'android.content.res.AssetManager android.content.ContextWrapper.getAssets()' on a null object reference

### ISSUE THREAD

**Issue by zmingchun** [alibaba/freeline#531]
如下：
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.content.ContextWrapper.getAssets()' on a null object reference
                                                                          at com.antfortune.freeline.FreelineCore.getApkBuildFlag(FreelineCore.java:156)
                                                                          at com.antfortune.freeline.router.schema.CheckSyncSchema.handle(CheckSyncSchema.java:28)
                                                                          at com.antfortune.freeline.router.Router.dispatch(Router.java:48)
                                                                          at com.antfortune.freeline.server.LongLinkServer.handle(LongLinkServer.java:55)
                                                                          at com.antfortune.freeline.server.EmbedHttpServer.run(EmbedHttpServer.java:95)
                                                                          at java.lang.Thread.run(Thread.java:833)
```

**Comment by zmingchun** [comment]
freeline执行一次全量编译安装后，再次执行，常出现以下异常（只有一台设备连线、只开一个Android Studio）：
```
[DEBUG] [sync_client] try to connect device 9 times...
[DEBUG] [sync_client] wake up Service: D:\software\Android\android_sdk\platform-tools\adb.exe shell am startservice -n com.****.***/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 10 times...
[DEBUG] [sync_client] Freeline server in app com.****.*** not found. Please make sure your application is properly running in your device.
[DEBUG] [connect_device_task] connect_device_task finish in 15.7s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 15.7s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 15.7s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 15.7s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 15.66s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
        Please make sure your application is properly running in your device.
        Check follow steps:
        1. Make sure the versions `python freeline.py -v`, freeline-gradle and freeline-runtime are the same;
        2. Make sure there is no network proxy.

        More about this can see: https://github.com/alibaba/freeline/issues/152
[ERROR] --------------------------------------------------------
[ERROR] Freeline server in app com.****.*** not found. Please make sure your application is properly running in your device.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 15.7s
[DEBUG] Total time: 15.9s
[DEBUG] --------------------------------------------------------

```

**Comment by lomanyong** [comment]
@zmingchun 抱歉回复晚了...卸载一下 apk 然后重新安装试试看..

**Comment by zmingchun** [comment]
@lomanyong 有试过重新安装的，但就是会反复出现。

**Comment by lomanyong** [comment]
@zmingchun 你们是否在自己在 Application 中调用了`FreelineCore.init(this);`呢？

**Comment by zmingchun** [comment]
@lomanyong 没有的，只在```build.gradle```配置了
```
freeline{
    productFlavor '渠道标识'
}
```

**Comment by lomanyong** [comment]
@zmingchun 可以参考一下#273 ，修改一下配置，看下是否可以解决你的问题

**Comment by mrldroid** [comment]
@lomanyong  Freeline 0.7.0+开始，默认开启了Application替换，这条可以不用检查.这句话的意思是不用加FreelineCore.init(this)吗

**Comment by lomanyong** [comment]
@mrldroid 是的，如果你有其他需求的话，也可以自己手动替换...

**Comment by mrldroid** [comment]
@lomanyong  我现在用0.8.4 如果不加FreelineCore.init(this)这行的话，第一次全编译没问题，但第二次增量编译就出错，提示找不到device，而且logcat也报这个issue

**Comment by lomanyong** [comment]
@mrldroid 可以参考#153 ，找不到 device 的情况挺多种的...可以先排除一下。

**Comment by zmingchun** [comment]
@lomanyong 不好意思，确认晚了。按照[#273 ](https://github.com/alibaba/freeline/issues/273) 配置是可以解决现在的问题的。但是在手动导出apk，会报“Error:(14, 31) 错误: 程序包com.antfortune.freeline不存在”。

**Comment by lomanyong** [comment]
@zmingchun 确实是正常依赖了freeline吗？如果每次都有`apply plugin: "com.antfortune.freeline"`的话，那么会自动给你添加`com.antfortune.freeline:runtime-no-op`的依赖的，不会找不到这个程序包...

**Comment by zmingchun** [comment]
@lomanyong 依赖是正常的。补充下，导出debug包是正常的，非debug包才报异常。PS: applicationProxy=false 的方式。

**Comment by lomanyong** [comment]
@zmingchun 一个临时的解决方案，手动添加到主工程的依赖：`releaseCompile "com.antfortune.freeline:runtime-no-op:0.8.4"`，根治的方案你得检查一下工程，依赖添加肯定存在问题...这个`releaseCompile`插件自动给你隐形添加了的...

**Comment by zmingchun** [comment]
@lomanyong 这种临时方案有点不友好，我这边的buildType 和 flavor比较多。
另外，我这边的依赖添加一共就两个地方：
1）根目录build.gradle
```
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0'
        //引用增量编译插件https://github.com/alibaba/freeline/blob/master/README-zh.md
        //配置好环境后，使用前，可以执行task：gradlew checkBeforeCleanBuild，检查配置是否完整
        classpath 'com.antfortune.freeline:gradle:0.8.4'
    }
}
```

2）app module 的build.gradle 
```
/**应用增量编译插件，支持Android5.0+*/
apply plugin: 'com.antfortune.freeline'

/**配置参数*/
freeline {
    productFlavor 'kid'
}
```
还有哪里的配置？

**Comment by lomanyong** [comment]
@zmingchun 你按照你的需求配置就可以了，保证打release包的时候能够有依赖。

plugin 里会自动给你挂载 no-op 版本，你可以手动执行一下`./gradlew :{your-main-module}:dependencies`检查一下依赖..

**Comment by candledragle** [comment]
我也遇到这个问题 @lomanyong
