### ISSUE TITLE
freeline内部出现空指针

### ISSUE THREAD

**Issue by xiebudong** [alibaba/freeline#532]
修改文件后执行python freeline.py，程序启动后闪退，错误如下

freeline版本：0.8.4
gradle版本： 2.2.2

`E/Freeline: java.lang.NullPointerException
                                                                         at com.antfortune.freeline.FreelineCore.getApkBuildFlag(FreelineCore.java:156)
                                                                         at com.antfortune.freeline.FreelineCore.getUuid(FreelineCore.java:406)
                                                                         at com.antfortune.freeline.FreelineReceiver.onReceive(FreelineReceiver.java:36)
                                                                         at android.app.ActivityThread.handleReceiver(ActivityThread.java:2533)
                                                                         at android.app.ActivityThread.access$2000(ActivityThread.java:139)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1337)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5314)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                                         at dalvik.system.NativeStart.main(Native Method)

com.jiuyan.app.friend E/Freeline: java.lang.NullPointerException
                                                                     at com.antfortune.freeline.FreelineCore.getApkBuildFlag(FreelineCore.java:156)
                                                                     at com.antfortune.freeline.FreelineCore.getUuid(FreelineCore.java:406)
                                                                     at com.antfortune.freeline.FreelineReceiver.onReceive(FreelineReceiver.java:36)
                                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2533)
                                                                     at android.app.ActivityThread.access$2000(ActivityThread.java:139)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1337)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5314)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                                     at dalvik.system.NativeStart.main(Native Method)`

**Comment by lomanyong** [comment]
@xiebudong 操作步骤是否是对使用 AS 打出的 apk 使用了 freeline 增量编译呢？或者你是否在自己的 Application 类中添加了 `FreelineCore.init(this);`？

这个问题的原因通常是非正常操作导致的...

**Comment by xiebudong** [comment]
第三次执行freeline
第一次带 -f 执行，运行没问题
第二次不带参数执行，提示some important file missed..   又执行了clean build, 但是运行没有问题
第三次改了一行代码，然后执行就报了这个错误

Application没有添加FreelineCore.init(this);  第一次运行是没有问题的。

gradle配置的确是和正常的项目有点不同。
一，application插件是在beforeEvaluate里动态添加的，如下
project.beforEvaluate {
     if (some condition ...) {
          project.apply plugin: 'com.android.application'
     } else {
          project.apply plugin: 'com.android.library'
     }
}

可以确定执行freeline的时候apply的是application插件。

二， 有用productFlavor，并且是动态对freeline配置的flavor, 如下：
project.afterEvaluate {
          def freelineExt = project.getExtensions().findByName('freeline')
                    if (freelineExt != null) {
                        freelineExt.productFlavor = 'singleton'
           }
}

**Comment by lomanyong** [comment]
@xiebudong 类似插件化开发的工程？

可以解开工程 apk 看下是否有 apktime 文件？

**Comment by xiebudong** [comment]
是的  用的small ,  assets下有apktime的， 我看NPT那一行应该是sApplication为空了

**Comment by lomanyong** [comment]
@xiebudong 我看了下 156 在 0.8.4 版本应该对应的是这一行：

![](http://ww2.sinaimg.cn/large/006tNc79gw1fb40impnhgj30x60m877e.jpg)

apktime 应该是没有拿到，空指针了...

**Comment by xiebudong** [comment]
apk解压跟目录的asstes下是有这个apktime的， 里面是一串数字，什么情况下会拿不到呢

**Comment by lomanyong** [comment]
@xiebudong 只要打进 apk 里正常情况下都可以拿到，会不会是因为 Small 的插件化的原因影响到了...

**Comment by xiebudong** [comment]
有可能的   我再研究看看

**Comment by msdx** [comment]
The problem:

```
E/Freeline: java.lang.NullPointerException: Attempt to invoke a virtual method on a null object reference
                                                                 at com.antfortune.freeline.FreelineCore.getApkBuildFlag(FreelineCore.java:156)
                                                                 at com.antfortune.freeline.FreelineCore.getUuid(FreelineCore.java:406)
                                                                 at com.antfortune.freeline.FreelineReceiver.onReceive(FreelineReceiver.java:36)
                                                                 at android.app.ActivityThread.handleReceiver(ActivityThread.java:2749)
                                                                 at android.app.ActivityThread.access$1700(ActivityThread.java:169)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1500)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                 at android.os.Looper.loop(Looper.java:194)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```
