### ISSUE TITLE
修改主Module外的Module运行时报错

### ISSUE THREAD

**Issue by nixionglin** [alibaba/freeline#543]
假设有2两Module，分别是ParentModule与ChildModule，App运行是以ChildModule为主Module。因此相关的依赖是在ChildModule中。ChildModule中的Application为MyApplication继续于ParentModule中的Application。修改ChildModule下面相关内容均正常，但是修改ParentModule就会运行报错。大概原因是通过FreelineApplication找到的realApplication为ChildModule中的Application，而通过ChildParent对应的MyApplication又找不到ParentModule中对应的修改点。ParentModule中的Application与对应Module耦合度很高又不方便往ChildModuel中迁移。如下面的报错信息：
     Caused by: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
        at com.partent.common.constant.ClientConfig$ClientConfigInstance.<clinit>(ClientConfig.java:15)
        at com.partent.common.constant.ClientConfig.getInstance(ClientConfig.java:19)
        at com.partent.common.constant.ClientConfig.<clinit>(ClientConfig.java:46)
        at com.child.home.MyApplication.attachBaseContext(MyApplication.java:191)
        at android.app.Application.attach(Application.java:181)
        at java.lang.reflect.Method.invokeNative(Native Method)?
        at java.lang.reflect.Method.invoke(Method.java:525)?
        at com.antfortune.freeline.util.ReflectUtil.invokeMethod(ReflectUtil.java:39)?
        at com.antfortune.freeline.FreelineApplication.startRealApplication(FreelineApplication.java:44)?
        at com.antfortune.freeline.FreelineApplication.onCreate(FreelineApplication.java:32)?
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)?
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4570)?
        at android.app.ActivityThread.access$1300(ActivityThread.java:147)?
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)?
        at android.os.Handler.dispatchMessage(Handler.java:99)?
        at android.os.Looper.loop(Looper.java:137)?
        at android.app.ActivityThread.main(ActivityThread.java:5265)?
        at java.lang.reflect.Method.invokeNative(Native Method)?
        at java.lang.reflect.Method.invoke(Method.java:525)?
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:760)?
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)?
        at dalvik.system.NativeStart.main(Native Method)?

其中：
com.partent.common.constant是ParentModule；
com.child.home是ChildModule；
ClientConfig是ParentModule中的代码文件；
MyApplication是ChildModule中的Application。
尝试修改python脚本文件加载ParentModule中的Application为RealApplication，但是ChildModule中的MyApplication又找不到。请问像我这种情况如何解决？

**Comment by lomanyong** [comment]
@nixionglin 参考 #273 做下修改，然后重新 clean 编译看下是否恢复正常。

**Comment by nixionglin** [comment]
你好，我这个问题有些不一样。按照那个方式尝试过了不生效。另外尝试在主MyApplication onCreate()方法中使用 FreelineCore.init(applicaio, realApplication) 的方式，即 FreelineCore.init(this, ParentApplication)，其效果与  FreelineCore.init(this)是一样的，暂时还没想到有什么好的方法。

**Comment by nixionglin** [comment]
报这个错是因为将app module中的build.gradle中的applicationProxy配置为true，采用了FreelineApplication代理，在查找修改的时候从MyApplication找不到MyApplication父类ParentApplication对应module下的修改文件，所以会报错。后来尝试将applicationProxy配置为false,同时在MyApplication的onCreate()的**首行**（非首行增量编译不生效）后。parent module下的修改不崩溃，但是修改无效果。

**Comment by lomanyong** [comment]
@nixionglin 你们是插件化的工程？听着像是有两个 Application 的样子？不是很明白你具体的描述...

可以提供一些示例代码吗？

**Comment by nixionglin** [comment]
lomanyong 你好，不好意思。最近在忙其他项目了一直没抽出空回复。我将这个现象写了一个demo工程。
针对这个工程出的问题大概罗列了一下：
1、本issue提的运行崩溃，后来修改build .gradle取消代码，通过在Application添加Freeline init方法。但是此时一部分代码修改不生效。（示例工程的mylibrary，rootlibrary下的文件）
2、修改主模块的activity_main.xml一些View属性只有第一次生效，后现再修改（如调整背景色等）也不生效，但是退出应用再次进入时才出现修改后的效果。
运行demo项目很容易复现（具体修改rootlibrary下的config文件及activity_main.xml属性）。

**Comment by nixionglin** [comment]
@lomanyong demo 示例代码地址：
https://github.com/nixionglin/FreelineDemo
非常谢谢

**Comment by lomanyong** [comment]
@nixionglin 修改 `public static final`修饰的变量时实际上已经生效，但是因为没有重新加载导致看到了不生效的情况，如果连同引用类一起修改的话，是可以看到修改结果的。

资源修改背景颜色不生效的情况我没有遇见额，修改的都可以正常生效。

**Comment by nixionglin** [comment]
@lomanyong 修改activity_main.xml中资源第一次会生效，但是后面的修改没有生效。但是如果退出应用再进的话才看到生效后的效果。至于修改public static final变量的问题，在这个仿实际项目架构的demo工程中确实是生效的，但是在实际项目中却没有生效，目前还没定位到是什么原因。

**Comment by nixionglin** [comment]
@lomanyong 崩溃没有复现么？

**Comment by lomanyong** [comment]
@nixionglin `public static final`的问题是已知的，需要立刻生效的话，需要把引用类也一起加入增量编译即可。奔溃的问题可以通过`applicationProxy false`来解决。

资源修改我这边一直没有失效额...

**Comment by nixionglin** [comment]
@lomanyong 谢谢您的解答 崩溃的问题在实际项目中遇到过，官方文档中说这个值默认是true，当时的解决方法是将applicationProxy 设置成false，并且这个demo 中 applicationProxy 这个值配的就是false。如下： 
    freeline {
        applicationProxy false
    }
但是还是发生了崩溃。至于说修改activity_main.xml资源的一些属性，如大小、背景色、text文本第一次是没有问题的，之后就一直不生效，并且我测试了其他几台手机现象也是如此。
现象与https://github.com/alibaba/freeline/issues/615一样，但是按上面的解决方法仍然如此，现在根据其过程了0.8.5了，也是如此。现象是界面闪一下并未生效。详细过程见log
非常感谢！
[log.txt](https://github.com/alibaba/freeline/files/710251/log.txt)
