### ISSUE TITLE
出现 NoSuchMethodError的错误

### ISSUE THREAD

**Issue by tuzhenyu** [alibaba/freeline#544]
点击freeline插件的图标进行全量编译时 出现 这个错误：
NoSuchMethodError:com.android.tools.idea.gradle.dsl.model.GradleBuildModel.parseBuildFile(Lcom/intellij/openapi/vfs/VirtualFile;Lcom/intellij/openapi/project/Project;)Lcom/android/tools/idea/gradle/dsl/model/GradleBuildModel;
我尝试直接执行：python freeline.py -f
结果错误日志是这样的：
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=True, debug=False, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 1.1.3
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.4
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.4
               [DEBUG] collecting project info, please wait a while...
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: D:\***\app\build\freeline\freeline-assets\apktime
[DEBUG] new clean build flag value: 410000
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save app module file stat
[DEBUG] [generate_file_stat_task] save common module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.5s
[DEBUG] [read_project_info_task] read_project_info_task finish in 5.9s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 5.9s
[DEBUG] [gradle_clean_build_task] gradlew.bat :app:assembleDebug -P freelineBuild=true --stacktrace
[DEBUG] [gradle_clean_build_task] Gradle build task is running, please wait a minute...
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task finish in 5.8s
[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 11.7s
[DEBUG] [install_apk_task] install_apk_task start to run after waiting 11.7s
[DEBUG] [append_file_stat_task] append_file_stat_task start to run after waiting 0.0s
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after waiting 11.7s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run after waiting 11.2s
[DEBUG] [generate_apt_files_task] generate_apt_files_task start to run after waiting 5.8s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 11.71s to execute tasks.
[DEBUG] [task_engine] it takes task engine 11.71s to execute tasks.
[DEBUG] [task_engine] it takes task engine 11.71s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
freeline auto add runtime dependencies: 0.8.4
KEEP_SPECS patched: removed 'activity' root
find variant prodDebug start hack process...
find default apk path: D:\***\app\build\outputs\apk\app-prod-debug.apk
Old file D:\***\freeline_project_description.json removed.
Save to D:\***\freeline_project_description.json

BUILD FAILED

Total time: 5.267 secs

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not find method additionalParameters() for arguments [-P, D:\***\app\build\freeline\public_keeper.xml] on com.android.build.gradle.internal.d
sl.AaptOptions_Decorated@1d3546f9.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.
        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:91)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:86)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:65)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:504)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:83)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: org.gradle.api.internal.MissingMethodException: Could not find method additionalParameters() for arguments [-P, D:\***\app\build\freeline\
public_keeper.xml] on com.android.build.gradle.internal.dsl.AaptOptions_Decorated@1d3546f9.
        at org.gradle.api.internal.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:68)
        at org.gradle.api.internal.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:56)
        at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:172)
        at com.android.build.gradle.internal.dsl.AaptOptions_Decorated.invokeMethod(Unknown Source)
        at com.antfortune.freeline.FreelinePlugin$_apply_closure4$_closure13.doCall(FreelinePlugin.groovy:111)
        at com.antfortune.freeline.FreelinePlugin$_apply_closure4.doCall(FreelinePlugin.groovy:51)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy12.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:79)
        ... 31 more

[ERROR] --------------------------------------------------------
[ERROR] build failed with script: gradlew.bat :app:assembleDebug -P freelineBuild=true --stacktrace
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 4.3s
[DEBUG] Task engine running time: 11.7s
[DEBUG] Total time: 16.0s
[DEBUG] --------------------------------------------------------

请问下我是不是哪里没配置好，我的 Gradle Version : 2.2, Android Plugin Version :1.1.3.

**Comment by lomanyong** [comment]
@tuzhenyu 升级一下gradle的版本，目前的版本太低了...

**Comment by tuzhenyu** [comment]
好的，我试下，谢谢！
