### ISSUE TITLE
小米5s上百度地图sdk初始化失败

### ISSUE THREAD

**Issue by callmepeanut** [alibaba/freeline#545]
Log如下，其他手机没这个问题：                                                               
 java.lang.UnsatisfiedLinkError: No implementation found for int com.baidu.platform.comjni.engine.JNIEngine.initClass(java.lang.Object, int) (tried Java_com_baidu_platform_comjni_engine_JNIEngine_initClass and Java_com_baidu_platform_comjni_engine_JNIEngine_initClass__Ljava_lang_Object_2I)
                                                                    at com.baidu.platform.comjni.engine.JNIEngine.initClass(Native Method)
                                                                    at com.baidu.platform.comjni.engine.AppEngine.InitClass(Unknown Source)
                                                                    at com.baidu.platform.comapi.a.<clinit>(Unknown Source)
                                                                    at com.baidu.platform.comapi.a.a(Unknown Source)
                                                                    at com.baidu.platform.comapi.c.a(Unknown Source)
                                                                    at com.baidu.mapapi.SDKInitializer.initialize(Unknown Source)
                                                                    at com.baidu.mapapi.SDKInitializer.initialize(Unknown Source)

**Comment by lomanyong** [comment]
@callmepeanut 是否可以确认一下使用instant-run的话也有同样的问题呢？

这个可能属于手机的兼容性问题或者库本身的兼容性问题....
