### ISSUE TITLE
'#' 不是内部或外部命令，也不是可运行的程序   

### ISSUE THREAD

**Issue by AndroidCrazyBoy** [alibaba/freeline#550]
Traceback (most recent call last):
  File "freeline.py", line 7, in <module>
    from freeline_core.dispatcher import Dispatcher
  File "E:\Android\FumerVaper\android\truck\FumerVaper-master\freeline_core\dispatcher.py", line 8, in <module>
    from exceptions import CheckSyncStateException, FreelineException, NoInstallationException, \
ImportError: No module named 'exceptions'

**Comment by lomanyong** [comment]
@AndroidCrazyBoy 请使用 Python 2.7 的版本，目前不支持 Python 3
