### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by shizhongyu** [alibaba/freeline#555]
Traceback (most recent call last):
  File "freeline.py", line 7, in <module>
    from freeline_core.dispatcher import Dispatcher
  File "G:\AndroidDemo\Freeline\freeline_core\dispatcher.py", line 8, in <module>
    from command import AbstractCommand
ModuleNotFoundError: No module named 'command'

**Comment by lomanyong** [comment]
@shizhongyu 请使用 `Python 2.7`版本
