### ISSUE TITLE
运行说无法实例化应用

### ISSUE THREAD

**Issue by a449139686** [alibaba/freeline#557]
01-03 09:10:32.063 23299-23299/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.viroyal.royalcar, PID: 23299
                                                   java.lang.RuntimeException: Unable to instantiate application com.antfortune.freeline.FreelineApplication: java.lang.ClassNotFoundException: Didn't find class "com.antfortune.freeline.FreelineApplication" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.viroyal.royalcar-1/base.apk"],nativeLibraryDirectories=[/data/app/com.viroyal.royalcar-1/lib/arm, /data/app/com.viroyal.royalcar-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, system/vendor/lib, system/vendor/lib/egl, system/lib/hw]]
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:591)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5037)
                                                       at android.app.ActivityThread.access$1600(ActivityThread.java:150)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1459)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:168)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5845)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.antfortune.freeline.FreelineApplication" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.viroyal.royalcar-1/base.apk"],nativeLibraryDirectories=[/data/app/com.viroyal.royalcar-1/lib/arm, /data/app/com.viroyal.royalcar-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, system/vendor/lib, system/vendor/lib/egl, system/lib/hw]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:988)
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:577)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5037) 
                                                       at android.app.ActivityThread.access$1600(ActivityThread.java:150) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1459) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:168) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5845) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
                                                   	Suppressed: java.lang.ClassNotFoundException: com.antfortune.freeline.FreelineApplication
                                                       at java.lang.Class.classForName(Native Method)
                                                       at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                       at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                       		... 12 more
                                                    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by a449139686** [comment]
application导致的联动问题
