### ISSUE TITLE
运行的时候还有一个权限问题？ 6.0手机

### ISSUE THREAD

**Issue by a449139686** [alibaba/freeline#558]
01-03 09:10:35.311 1209-2420/? E/DatabaseUtils: Writing exception to parcel
                                                java.lang.SecurityException: com.neusoft.td.android.wo116114 was not granted  this permission: android.permission.WRITE_SETTINGS.
                                                    at android.provider.Settings.isCallingPackageAllowedToPerformAppOpsProtectedOperation(Settings.java:9260)
                                                    at android.provider.Settings.checkAndNoteWriteSettingsOperation(Settings.java:9133)
                                                    at com.android.providers.settings.SettingsProvider.mutateSystemSetting(SettingsProvider.java:1189)
                                                    at com.android.providers.settings.SettingsProvider.insertSystemSetting(SettingsProvider.java:1164)
                                                    at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:276)
                                                    at android.content.ContentProvider$Transport.call(ContentProvider.java:403)
                                                    at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:283)
                                                    at android.os.Binder.execTransact(Binder.java:461)

**Comment by hhhaiai** [comment]
明显你的app没有声明权限啊android.permission.WRITE_SETTINGS

**Comment by a449139686** [comment]
我正常 run可以的。 没报错啊

**Comment by a449139686** [comment]
可以了 还是application 的问题

**Comment by dengbing0907** [comment]
请问你是怎么解决的？我也碰到这个问题了

**Comment by faywong** [comment]
感觉三星的 6.0 手机上比较容易出这个问题。
