### ISSUE TITLE
Failed to read uid_cputime

### ISSUE THREAD

**Issue by a449139686** [alibaba/freeline#559]
java.io.FileNotFoundException: /proc/uid_cputime/show_uid_stat: open failed: ENOENT (No such file or directory)
                                                             at libcore.io.IoBridge.open(IoBridge.java:452)
                                                             at java.io.FileInputStream.<init>(FileInputStream.java:76)
                                                             at java.io.FileInputStream.<init>(FileInputStream.java:103)
                                                             at java.io.FileReader.<init>(FileReader.java:66)
                                                             at com.android.internal.os.KernelUidCpuTimeReader.readDelta(KernelUidCpuTimeReader.java:71)
                                                             at com.android.internal.os.BatteryStatsImpl.updateCpuTimeLocked(BatteryStatsImpl.java:8862)
                                                             at com.android.server.am.BatteryStatsService.updateExternalStats(BatteryStatsService.java:1685)
                                                             at com.android.server.am.BatteryStatsService.getStatisticsStream(BatteryStatsService.java:476)
                                                             at com.android.internal.app.IBatteryStats$Stub.onTransact(IBatteryStats.java:178)
                                                             at android.os.Binder.execTransact(Binder.java:461)
                                                          Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                             at libcore.io.Posix.open(Native Method)
                                                             at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                             at libcore.io.IoBridge.open(IoBridge.java:438)
                                                             at java.io.FileInputStream.<init>(FileInputStream.java:76) 
                                                             at java.io.FileInputStream.<init>(FileInputStream.java:103) 
                                                             at java.io.FileReader.<init>(FileReader.java:66) 
                                                             at com.android.internal.os.KernelUidCpuTimeReader.readDelta(KernelUidCpuTimeReader.java:71) 
                                                             at com.android.internal.os.BatteryStatsImpl.updateCpuTimeLocked(BatteryStatsImpl.java:8862) 
                                                             at com.android.server.am.BatteryStatsService.updateExternalStats(BatteryStatsService.java:1685) 
                                                             at com.android.server.am.BatteryStatsService.getStatisticsStream(BatteryStatsService.java:476) 
                                                             at com.android.internal.app.IBatteryStats$Stub.onTransact(IBatteryStats.java:178) 
                                                             at android.os.Binder.execTransact(Binder.java:461)

**Comment by a449139686** [comment]
application导致的联动问题

**Comment by durzoflint** [comment]
I have the same error, can anyone guide me as to why this is happening?
