### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by strongmanb** [alibaba/freeline#565]
ine\freeline-backup\AccountSettingFragment.class-1483496289457
        at com.android.dx.command.dexer.Main.run(Main.java:292)
        at com.android.builder.internal.compiler.DexWrapper.run(DexWrapper.java:54)
        at com.android.builder.core.DexByteCodeConverter.lambda$dexInProcess$0(DexByteCodeConverter.java:173)

**Comment by lomanyong** [comment]
@strongmanb 没有具体的日志？

**Comment by strongmanb** [comment]
@lomanyong back up D:\work\workspace\android\company\test\app\build\intermediates\classes\debug\com\gsmc\php\longba\ui\module\usercenter\accountsetting\AccountSettingContract$View.class to D:\work\workspace\android\company\\test\app\build\
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more
Caused by: com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 655
36
        at com.android.build.gradle.internal.transforms.DexTransform.transform(DexTransform.java:443)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:178)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:174)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        ... 76 more
Caused by: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
        at com.android.builder.core.DexByteCodeConverter.dexInProcess(DexByteCodeConverter.java:179)
        at com.android.builder.core.DexByteCodeConverter.runDexer(DexByteCodeConverter.java:157)
        at com.android.builder.core.DexByteCodeConverter.convertByteCode(DexByteCodeConverter.java:146)
        at com.android.builder.core.AndroidBuilder.convertByteCode(AndroidBuilder.java:1386)
        at com.android.build.gradle.internal.transforms.DexTransform.transform(DexTransform.java:432)
        ... 79 more
Caused by: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
        at com.android.builder.core.DexByteCodeConverter.dexInProcess(DexByteCodeConverter.java:177)
        ... 83 more
Caused by: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
        at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:488)
        at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:264)
        at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:497)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:191)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:522)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:344)
        at com.android.dx.command.dexer.Main.run(Main.java:292)
        at com.android.builder.internal.compiler.DexWrapper.run(DexWrapper.java:54)
        at com.android.builder.core.DexByteCodeConverter.lambda$dexInProcess$0(DexByteCodeConverter.java:173)

**Comment by strongmanb** [comment]
@lomanyong 解决了，是我的问题，今天开始在项目中用Freeline，之后有什么问题我再留言给你，谢谢你
