### ISSUE TITLE
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by zhairui** [alibaba/freeline#573]
执行完python freeline.py命令之后，报了如下错误，不知道是什么原因
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
        at com.android.builder.core.DexByteCodeConverter.dexOutOfProcess(DexByteCodeConverter.java:206)
        ... 75 more
Caused by: java.lang.UnsupportedOperationException
        at com.android.ide.common.process.ProcessInfoBuilder$JavaProcessInfoImpl.getExecutable(ProcessInfoBuilder.java:349)
        at com.android.ide.common.process.ProcessInfoBuilder$JavaProcessInfoImpl.getExecutable(ProcessInfoBuilder.java:349)
        at com.android.build.gradle.internal.process.GradleProcessResult.buildProcessException(GradleProcessResult.java:74)
        at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:49)
        at com.android.builder.core.DexByteCodeConverter.lambda$dexOutOfProcess$1(DexByteCodeConverter.java:196)

**Comment by lomanyong** [comment]
@zhairui 没有开multidex导致的？

**Comment by zhairui** [comment]
multiDexEnabled true 
已经设置成了true

**Comment by lomanyong** [comment]
@zhairui #335 #315 基本都是工程本身的问题...抱歉无法帮你进行解决...
