### ISSUE TITLE
执行python freeline.py 命令报错

### ISSUE THREAD

**Issue by Alex-Linrk** [alibaba/freeline#575]
> `Traceback (most recent call last):
  File "freeline.py", line 7, in <module>
    from freeline_core.dispatcher import Dispatcher
  File "F:\teletomproject\LocalSVN\LHWXproject\0_Androidstudio\NetIntellisenseLiteStrengthen\freeline_core\dispatcher.py", line 8, in <module>
    from command import AbstractCommand
ImportError: No module named 'command'`
Android studio 插件已安装，并且gradlew initFreeline BUILD SUCCESSFUL 但是执行 python freeline.py就报错

**Comment by Alex-Linrk** [comment]
找到问题原因了， 不支持Python 3+
