### ISSUE TITLE
编译失败。

### ISSUE THREAD

**Issue by shizhongyu** [alibaba/freeline#584]
C:\Work\tulipsport\android\client>python freeline.py
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=False, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.2.2
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.4
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.4
[DEBUG] final apk not found, need a clean build.
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: C:\Work\tulipsport\android\client\app\build\freeline\freeline-assets\apktime
[DEBUG] new clean build flag value: 108000
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save app module file stat
[DEBUG] [generate_file_stat_task] save appguide module file stat
[DEBUG] [generate_file_stat_task] save map module file stat
[DEBUG] [generate_file_stat_task] save wearlib module file stat
[DEBUG] [generate_file_stat_task] save util module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 1.7s
[DEBUG] [read_project_info_task] read_project_info_task finish in 258.3s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 258.2s[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Downloading https://services.gradle.org/distributions/gradle-2.14.1-all.zip
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
....................................................................................

Exception in thread "main" java.lang.RuntimeException: javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketExc
eption: Software caused connection abort: recv failed
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
        at org.gradle.wrapper.Install.createDist(Install.java:47)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException: Software caused connection abort: re
cv failed
        at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1541)
        at sun.security.ssl.AppInputStream.available(AppInputStream.java:60)
        at java.io.BufferedInputStream.available(BufferedInputStream.java:410)
        at sun.net.www.MeteredStream.available(MeteredStream.java:170)
        at sun.net.www.http.KeepAliveStream.close(KeepAliveStream.java:85)
        at java.io.FilterInputStream.close(FilterInputStream.java:181)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.close(HttpURLConnection.java:3409)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:74)
        at org.gradle.wrapper.Download.download(Download.java:45)
        at org.gradle.wrapper.Install$1.call(Install.java:60)
        at org.gradle.wrapper.Install$1.call(Install.java:47)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        ... 3 more
Caused by: javax.net.ssl.SSLException: java.net.SocketException: Software caused connection abort: recv failed
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1870)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1815)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:116)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.MeteredStream.read(MeteredStream.java:134)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3336)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3329)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:63)
        ... 7 more
Caused by: java.net.SocketException: Software caused connection abort: recv failed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:170)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
        at sun.security.ssl.InputRecord.read(InputRecord.java:532)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        ... 14 more

[ERROR] --------------------------------------------------------
[ERROR] freeline failed when read project info with script: gradlew.bat -q checkBeforeCleanBuild
[ERROR] --------------------------------------------------------

[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 258.2s[DEBUG] Prepare tasks time: 2.0s
[DEBUG] Task engine running time: 258.3s
[DEBUG] Total time: 260.3s
[DEBUG] --------------------------------------------------------

[DEBUG] [install_apk_task] install_apk_task start to run after waiting 258.2s
close failed in file object destructor:
Error in sys.excepthook:

Original exception was:

**Comment by lomanyong** [comment]
@shizhongyu 网络问题...卡在下载 gradle.zip 上了..
