### ISSUE TITLE
WindowsError: [Error 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by imknown** [alibaba/freeline#588]
> `Python 2.7.13 x86` on `Windows 10 64bit` shows the fatal error below:

```
D:\project\AndroidStudioProjects\XXX>python freeline.py
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=False, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.2.3
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.4
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.4
[DEBUG] final apk not found, need a clean build.
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: D:\project\AndroidStudioProjects\XXX\ZMain\yyy\build\freeline\freeline-assets\apktime
[DEBUG] new clean build flag value: 901000
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save smarterCity module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.1s
[DEBUG] [read_project_info_task] read_project_info_task finish in 2.4s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 2.4s
[DEBUG] [gradle_clean_build_task] ./gradlew :ZMain:yyy:assembleAOfficialDebug -P freelineBuild=true --stacktrace
[DEBUG] [gradle_clean_build_task] Gradle build task is running, please wait a minute...
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task finish in 0.0s
[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 2.5s
[DEBUG] [install_apk_task] install_apk_task start to run after waiting 2.5s
[DEBUG] [append_file_stat_task] append_file_stat_task start to run after waiting 0.0s
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after waiting 2.5s
[DEBUG] [generate_apt_files_task] generate_apt_files_task start to run after waiting 0.0s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run after waiting 2.4s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 2.45s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "D:\project\AndroidStudioProjects\XXX\freeline_core\task.py", line 123, in execute
    self.task.execute()
  File "D:\project\AndroidStudioProjects\XXX\freeline_core\gradle_clean_build.py", line 116, in execute
    output, err, code = cexec(command.split(' '), callback=None, cwd=cwd)
  File "D:\project\AndroidStudioProjects\XXX\freeline_core\utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "E:\A32\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "E:\A32\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 2.5s
[DEBUG] Total time: 2.7s
[DEBUG] --------------------------------------------------------
```

What i configured in `module build.gradle`:
``` gradle
android {
    freeline {
        // https://www.freelinebuild.com/docs/zh_cn/#Freeline%20DSL
        buildScript "./gradlew :ZMain:yyy:assembleAOfficialDebug"

        productFlavor "AOfficial"
    }
}
```

**Comment by lomanyong** [comment]
@imknow 在windows下不要这样定义= =，执行了 Linux 的命令了...

按照下面修改下再试试看

````gradle
freeline {
        // https://www.freelinebuild.com/docs/zh_cn/#Freeline%20DSL
        buildScript "gradlew :ZMain:yyy:assembleAOfficialDebug"

        productFlavor "AOfficial"
    }
````

**Comment by imknown** [comment]
@lomanyong 啊! 确实没注意, 我这里是 有人用 `Windows Android Studio`, 有人用 `Linux Android Studio` 开发, 这个 `buildScript` 没法统一 一下吗?

此外, `Windows` 改成 `buildScript "gradlew :ZMain:yyy:assembleAOfficialDebug"` 之后 还是报错:
```
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "D:\project\AndroidStudioProjects\XXX\freeline_core\task.py", line 123, in execute
    self.task.execute()
  File "D:\project\AndroidStudioProjects\XXX\freeline_core\gradle_clean_build.py", line 116, in execute
    output, err, code = cexec(command.split(' '), callback=None, cwd=cwd)
  File "D:\project\AndroidStudioProjects\XXX\freeline_core\utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "E:\A32\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "E:\A32\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 2.4s
[DEBUG] Total time: 2.7s
[DEBUG] --------------------------------------------------------
```

**Comment by lomanyong** [comment]
@imknown 可以统一呀，你们自己简单写下 groovy，根据系统来切换就可以了...不用几行代码...

这个问题，你目录下没有`gradlew.bat`这个文件？没有的话拷贝一个过来...

**Comment by imknown** [comment]
@lomanyong 嗯, 谢谢思路, 平台的问题一会儿我研究一下.

------

`gradlew.bat` 一直是 有的, 我终端里 单纯用 `gradle` 的 `gradlew` 是可以的.

**Comment by imknow** [comment]
你们是不是发错地方了？🤣
发自网易邮箱大师
在2017年01月09日 17:50，imknown J. Kimu 写道:

@lomanyong 嗯, 谢谢思路, 平台的问题一会儿我研究一下.

gradlew.bat 一直是 有的, 我终端里 单纯用 gradle 的 gradlew 是可以的.

**Comment by imknown** [comment]
@imknow ......
