### ISSUE TITLE
点击Freeline按钮报错

### ISSUE THREAD

**Issue by Aplombs** [alibaba/freeline#590]
Traceback (most recent call last):
  File "freeline.py", line 7, in <module>
    from freeline_core.dispatcher import Dispatcher
  File "F:\application\ICBC\imappcandroid_1703\IMAPP_C_ANDROID\freeline_core\dispatcher.py", line 8, in <module>
    from command import AbstractCommand
ModuleNotFoundError: No module named 'command'

**Comment by lomanyong** [comment]
@Aplombs 请使用 Python 2.7+版本
