### ISSUE TITLE
AS 运行freeline 错误

### ISSUE THREAD

**Issue by grins2193285007** [alibaba/freeline#595]
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "e:\JXB\freeline_core\task.py", line 123, in execute
    self.task.execute()
  File "e:\JXB\freeline_core\gradle_clean_build.py", line 75, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "e:\JXB\freeline_core\utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "D:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "D:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 不是有效的 Win32                                                                                                                                                              

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------

我是win10 64位系统，python 2.7.13  32位  ，之前安装64位python也不行才换成32位
我同事win7 安装起就可以用了，我折腾了一天还是不行。
请大神帮我解决一下，谢谢!

**Comment by lomanyong** [comment]
@grins2193285007 麻烦贴全日志...应该是配置问题，不是程序问题。
