### ISSUE TITLE
gradlew initFreeline 出错

### ISSUE THREAD

**Issue by ice45571** [alibaba/freeline#598]
C:\Users\ice\Desktop\MVPTest\Test>gradlew initFreeline
Unzipping C:\Users\ice\.gradle\wrapper\dists\gradle-2.14.1-all\8bnwg5hd3w55iofp58khbp6yv\gradle-2.14.1-all.zip to C:\Users\ice\.gradle\wrapper\dists\gradle-2.14.1-all\8bnwg5hd3w55iofp
58khbp6yv
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at org.gradle.wrapper.Install.unzip(Install.java:214)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by lomanyong** [comment]
@ice45571 网络问题，你本地下载 gradle.zip 文件出错了，以及推荐你使用`gradlew initFreeline -Pmirror`命令
