### ISSUE TITLE
执行“python freeline.py”报错

### ISSUE THREAD

**Issue by Misayanice** [alibaba/freeline#600]
Traceback (most recent call last):
  File "freeline.py", line 7, in <module>
    from freeline_core.dispatcher import Dispatcher
  File "E:\android\android_developer_project\experiments\LatestExperiment\freeline_core\dispatcher.py", line 8, in <module>
    from command import AbstractCommand
ModuleNotFoundError: No module named 'command'

**Comment by lomanyong** [comment]
@Misayanice 请用Python2.7+

**Comment by Misayanice** [comment]
恩。是的。我用的python 3.6.0报错的。
