### ISSUE TITLE
存在layout和layout-sw480，全量编译后不改动任何内容增量编译，编译成功，运行时异常

### ISSUE THREAD

**Issue by bulletProofCat** [alibaba/freeline#618]
项目中存在layout和layout-sw480两个文件夹分别存放同一界面的不同布局用于做特殊界面在不同大小手机屏幕的适配，初次运行freeline无异常，不改动任何东西，再次运行增量编译，编译成功，app启动，用到layout-sw480和layout都定义的布局xml文件时报错crash。

如果删除layout-sw480文件夹则freeline增量编译能够正常运行。

异常log：
android.content.res.Resources$NotFoundException: File res/layout-sw480dp-v13/ask_fragment_slider_text.xml from xml type layout resource ID #0x7f030034
at android.content.res.Resources.loadXmlResourceParser(Resources.java:2720)
at android.content.res.Resources.loadXmlResourceParser(Resources.java:2675)
at android.content.res.Resources.getLayout(Resources.java:1096)
at android.view.LayoutInflater.parseInclude(LayoutInflater.java:889)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:828)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:828)
....
Caused by: java.io.FileNotFoundException: Corrupt XML binary file
at android.content.res.AssetManager.openXmlAssetNative(Native Method)
at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:485)
at android.content.res.Resources.loadXmlResourceParser(Resources.java:2702)
at android.content.res.Resources.loadXmlResourceParser(Resources.java:2675) 
at android.content.res.Resources.getLayout(Resources.java:1096) 
at android.view.LayoutInflater.parseInclude(LayoutInflater.java:889) 
at android.view.LayoutInflater.rInflate(LayoutInflater.java:821) 
....

**Comment by lomanyong** [comment]
@bulletProofCat 能否提供一个可以复现问题的sample工程？
