### ISSUE TITLE
stack size 1036KB

### ISSUE THREAD

**Issue by sqc0720** [alibaba/freeline#621]
In thread: Thread[Thread-2762,5,main]
                                                                              UncaughtException detected: java.lang.StackOverflowError: stack size 1036KB
                                                                                  at com.easemob.chat.EMChat.getVersion(Unknown Source)
                                                                                  at com.easemob.cloud.HttpClientConfig.getDefaultUserAgent(Unknown Source)
                                                                                  at com.easemob.cloud.HttpClientConfig.getDefaultHttpClient(Unknown Source)
                                                                                  at com.easemob.cloud.HttpClientManager.httpExecute(Unknown Source)
                                                                                  at com.easemob.cloud.EMHttpClient.httpExecute(Unknown Source)
                                                                                  at com.easemob.chat.core.j.p(Unknown Source)
                                                                                  at com.easemob.chat.core.j.o(Unknown Source)
                                                                                  at com.easemob.chat.core.l.c(Unknown Source)
                                                                                  at com.easemob.chat.core.n.h(Unknown Source)
                                                                                  at com.easemob.chat.core.j.p(Unknown Source)
                                                                                  at com.easemob.chat.core.j.o(Unknown Source)
                                                                                  at com.easemob.chat.core.l.c(Unknown Source)
                                                                                  at com.easemob.chat.core.n.h(Unknown Source)
                                                                                  at com.easemob.chat.core.j.p(Unknown Source)
                                                                                  at com.easemob.chat.core.j.o(Unknown Source)
                                                                                  at com.easemob.chat.core.l.c(Unknown Source)
                                                                                  at com.easemob.chat.core.n.h(Unknown Source)
                                                                                  at com.easemob.chat.core.j.p(Unknown Source)
                                                                                  at com.easemob.chat.core.j.o(Unknown Source)
                                                                                  at com.easemob.chat.core.l.c(Unknown Source)
                                                                                  at com.easemob.chat.core.n.h(Unknown Source)
                                                                                  at com.easemob.chat.core.j.p(Unknown Source)
                                                                                  at com.easemob.chat.core.j.o(Unknown Source)
                                                                                  at com.easemob.chat.core.l.c(Unknown Source)
                                                                                  at com.easemob.chat.core.n.h(Unknown Source)
                                                                                  at com.easemob.chat.core.j.p(Unknown Source)
                                                                                  at com.easemob.chat.core.j.o(Unknown Source)
                                                                                  at com.easemob.chat.core.l.c(Unknown Source)
                                                                                  at com.easemob.chat.core.n.h(Unknown Source)
                                                                                  at com.easemob.chat.core.j.p(Unknown Source)
                                                                                  at com.easemob.chat.core.j.o(Unknown Source)
                                                                                  at com.easemob.chat.core.l.c(Unknown Source)
                                                                                  at com.easemob.chat.core.n.h(Unknown Source)
                                                                                  at com.easemob.chat.core.j.p(Unknown Source)
                                                                                  at com.easemob.chat.core.j.o(Unknown Source)
                                                                                  at com.easemob.chat.core.l.c(Unknown Source)
                                                                                  at com.easemob.chat.core.n.h(Unknown Source)
                                                                                  at com.easemob.chat.core.j.p(Unknown Source)
                                                                                  at com.easemob.chat.core.j.o(Unknown Source)
                                                                                  at com.easemob.chat.core.l.c(Unknown Source)
                                                                                  at com.easemob.chat.core.n.h(Unknown Source)
                                                                                  at com.easemob.chat.core.j.p(Unknown Source)
                                                                                  at com.easemob.chat.core.j.o(Unknown Source)
                                                                                  at com.easemob.chat.core.l.c(Unknown Source)
                                                                                  at com.easemob.chat.core.n.h(Unknown Source)
                                                                                  at com.easemob.chat.core.j.p(Unknown Source)
                                                                                  at com.easemob.chat.core.j.o(Unknown Source)
                                                                                  at com.easemob.chat.core.l.c(Unknown Source)
                                                                                  at com.easemob.chat.core.n.h(Unknown Source)
                                                                                  at com.easemob.chat.core.j.p(Unknown Source)
                                                                                  at com.easemob.chat.core.j.o(Unknown Source)
                                                                                  at com.easemob.chat.core.l.c(Unknown Source)
                                                                                  at com.easemob.chat.core.n.h(Unknown Source)
                                                                                  at com.easemob.chat.core.j.p(Unknown Source)
                                                                                  at com.easemob.chat.core.j.o(Unknown Source)
                                                                                  at com.easemob.chat.core.l.c(Unknown Source)
                                                                                  at com.easemob.chat.core.n.h(Unknown Source)
                                                                                  at com.easemob.chat.core.j.p(Unknown Source)
                                                                                  at com.easemob.chat.core.j.o(Unknown Source)
                                                                                  at com.easemob.chat.core.l.c(Unknown Source)
                                                                                  at com.easemob.chat.core.n.h(Unknown Source)
                                                                                  at com.easemob.chat.core.j.p(Unknown Source)
                                                                                  at com.easemob.chat.core.j.o(Unknown Source)
                                                                                  at com.easemob.chat.core.l.c(Unknown Source)
                                                                                  at com.easemob.chat.core.n.h(Unknown Source)
                                                                                  at com.easemob.chat.core.j.p(Unknown Source)
                                                                                  at com.easemob.chat.core.j.o(Unknown Source)
                                                                                  at com.easemob.chat.core.l.c(Unknown Source)
                                                                                  at com.easemob.chat.core.n.h(Unknown Source)
                                                                                  at com.easemob.chat.core.j.p(Unknown Source)
                                                                                  at com.easemob.chat.core.j.o(Unknown Source)
                                                                                  at com.easemob.chat.core.l.c(Unknown Source)
                                                                                  at com.easemob.chat.core.n.h(Unknown Source)
                                                                                  at com.easemob.chat.core.j.p(Unknown Source)
                                                                                  at com.easemob.chat.core.j.o(Unknown Source)
                                                                                  at com.easemob.chat.core.l.c(Unknown Source)
                                                                                  at com.easemob.chat.core.n.h(Unknown Source)
                                                                                  at com.easemob.chat.core.j.p(Unknown Source)
                                                                                  at com.easemob.chat.core.j.o(Unknown Source)
                                                                                  at com.easemob.chat.core.l.c(Unknown Source)
                                                                                  at com.easemob.chat.core.n.h(Unknown Source)
                                                                                  at com.easemob.chat.core.j.p(Unknown Source)
                                                                                  at com.easemob.chat.core.j.o(Unknown Source)
                                                                              	at com.easemob.chat.c

**Comment by lomanyong** [comment]
@sqc0720 freeline 导致的？错误信息都在环信的 sdk 里...

**Comment by sqc0720** [comment]
使用freeline 加载项目。报错如果把freeline 在项目中删除可以正常使用

**Comment by lomanyong** [comment]
@sqc0720 使用环信 + freeline 的工程有不少，并没有遇见别人提出类似的问题。如果可以的话，看你那边是否可以提供可以复现问题的 sample 工程？

**Comment by sqc0720** [comment]
好的， 有时间我会提供一个sample 功能，我这面也检测一下

**Comment by sqc0720** [comment]
还有一个问题。 今天使用python freeline.py -f 运行程序显示成功了但是终端没有显示应用图标。下面为截图：E:\changekdkj>python freeline.py -f
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=True, debug=False, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.0.0
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.4
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.4
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: E:\changekdkj\app\build\freeline\freeline-assets\apktime
[DEBUG] new clean build flag value: 712000
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save app module file stat
[DEBUG] [generate_file_stat_task] save library module file stat
[DEBUG] [generate_file_stat_task] save share module file stat
[DEBUG] [generate_file_stat_task] save easeui module file stat
[DEBUG] [generate_file_stat_task] save PushSDK module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.2s
[DEBUG] [read_project_info_task] read_project_info_task finish in 14.1s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 14.1s
[DEBUG] [gradle_clean_build_task] gradlew.bat :app:assembleDebug -P freelineBuild=true --stacktrace
[DEBUG] [gradle_clean_build_task] Gradle build task is running, please wait a minute...
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task finish in 101.3s
[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 115.4s
[DEBUG] [install_apk_task] install_apk_task start to run after waiting 115.4s
[DEBUG] [install_apk_task] check device' connection...
[DEBUG] [clean_all_cache_task] ignore remove: E:\changekdkj\app\build\freeline\freeline_annotation_info.json
[DEBUG] [clean_all_cache_task] ignore remove: E:\changekdkj\app\build\freeline\jar_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: E:\changekdkj\app\build\freeline\public_keeper.xml
[DEBUG] [clean_all_cache_task] ignore remove: E:\changekdkj\app\build\freeline\stat_cache.json
[DEBUG] [clean_all_cache_task] ignore remove: E:\changekdkj\app\build\freeline\app\assets_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: E:\changekdkj\app\build\freeline\app\resources_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: E:\changekdkj\app\build\freeline\freeline-assets\apktime
[DEBUG] [clean_all_cache_task] ignore remove: E:\changekdkj\app\build\freeline\library\resources_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: E:\changekdkj\app\build\freeline\PushSDK\resources_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: E:\changekdkj\app\build\freeline\share\resources_dependencies.json
[DEBUG] [clean_all_cache_task] clean_all_cache_task finish in 0.0s
[DEBUG] [append_file_stat_task] append_file_stat_task start to run after waiting 0.0s
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after waiting 115.4s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run after waiting 115.3s
[DEBUG] [generate_apt_files_task] generate_apt_files_task start to run after waiting 101.4s
[DEBUG] [append_file_stat_task] generate_file_stat_task in append mode
[DEBUG] collecting project info, please wait a while...
[DEBUG] [generate_apt_files_task] generate_apt_files_task finish in 0.0s
[DEBUG] collecting project info, please wait a while...
[DEBUG] [append_file_stat_task] no new modules found.
[DEBUG] [append_file_stat_task] append_file_stat_task finish in 0.0s
[DEBUG] [build_base_resource_task] E:\changekdkj\app\build\freeline\public_keeper.xml exists, move to dst: E:\changekdkj\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml
[DEBUG] [build_base_resource_task] generating ids.xml from public.xml...
[DEBUG] [generate_project_info_task] generate_project_info_task finish in 0.0s
[DEBUG] [install_apk_task] start to install apk to device: D:\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe install -r E:\changekdkj\app\build\outputs\apk\app-debug-2.7.7.apk
[DEBUG] [build_base_resource_task] aapt exec: freeline\release-tools\FreelineAapt.exe package -f -I D:\adt-bundle-windows-x86_64-20140702\sdk\platforms\android-22\android.jar -M E:\changekdkj\app\build\intermediates\manifests\full\debug\AndroidManifest.xml -S E
:\changekdkj\app\src\main\res\huanxin -S E:\changekdkj\app\src\main\res\umeng_community -S E:\changekdkj\app\src\main\res\imageselecter -S E:\changekdkj\app\src\main\res\main -S E:\changekdkj\app\src\main\res -S E:\changekdkj\share\build\generated\res\rs\releas
e -S E:\changekdkj\library\src\main\res -S E:\changekdkj\PushSDK\build\generated\res\rs\release -S E:\changekdkj\easeui\src\main\res -S E:\changekdkj\app\build\generated\res\rs\debug -S E:\changekdkj\share\src\main\res -S E:\changekdkj\library\build\generated\r
es\rs\release -S E:\changekdkj\PushSDK\res -S E:\changekdkj\app\build\intermediates\exploded-aar\com.antfortune.freeline\runtime\0.8.4\res -S E:\changekdkj\app\build\intermediates\exploded-aar\com.android.support\support-v4\23.0.1\res -S E:\changekdkj\app\build
\intermediates\exploded-aar\cn.leancloud.android\avoscloud-push\v3.14.6\res -S E:\changekdkj\app\build\intermediates\exploded-aar\com.github.linger1216\labelview\v1.1.1\res -S E:\changekdkj\app\build\intermediates\exploded-aar\com.zhuge.analysis\zhugeio\2.3.2\r
es -S E:\changekdkj\app\build\intermediates\exploded-aar\com.github.lecho\hellocharts-android\v1.5.8\res -S E:\changekdkj\app\build\intermediates\exploded-aar\com.alipay.euler\andfix\0.4.0\res -S E:\changekdkj\app\build\intermediates\exploded-aar\com.baoyz.swip
emenulistview\library\1.3.0\res -S E:\changekdkj\app\build\intermediates\exploded-aar\com.android.support\multidex\1.0.1\res -S E:\changekdkj\app\build\intermediates\exploded-aar\in.srain.cube\ultra-ptr\1.0.11\res -S E:\changekdkj\app\build\intermediates\explod
ed-aar\SMSSDK-2.0.2\res -S E:\changekdkj\app\build\intermediates\exploded-aar\com.commit451\PhotoView\1.2.4\res -S E:\changekdkj\app\build\intermediates\exploded-aar\com.android.support\recyclerview-v7\22.2.0\res -S E:\changekdkj\app\build\intermediates\explode
d-aar\com.android.support\appcompat-v7\22.2.0\res -S E:\changekdkj\app\build\intermediates\exploded-aar\com.android.support\design\22.2.0\res -S E:\changekdkj\app\build\freeline\app\backup\res -A E:\changekdkj\app\build\freeline\freeline-assets -A E:\changekdkj
\app\src\main\assets -A E:\changekdkj\app\build\intermediates\exploded-aar\com.antfortune.freeline\runtime\0.8.4\assets -A E:\changekdkj\app\build\intermediates\exploded-aar\com.android.support\support-v4\23.0.1\assets -A E:\changekdkj\app\build\intermediates\e
xploded-aar\cn.leancloud.android\avoscloud-push\v3.14.6\assets -A E:\changekdkj\app\build\intermediates\exploded-aar\com.github.linger1216\labelview\v1.1.1\assets -A E:\changekdkj\app\build\intermediates\exploded-aar\com.zhuge.analysis\zhugeio\2.3.2\assets -A E
:\changekdkj\app\build\intermediates\exploded-aar\com.github.lecho\hellocharts-android\v1.5.8\assets -A E:\changekdkj\app\build\intermediates\exploded-aar\com.alipay.euler\andfix\0.4.0\assets -A E:\changekdkj\app\build\intermediates\exploded-aar\com.baoyz.swipe
menulistview\library\1.3.0\assets -A E:\changekdkj\app\build\intermediates\exploded-aar\com.android.support\multidex\1.0.1\assets -A E:\changekdkj\app\build\intermediates\exploded-aar\in.srain.cube\ultra-ptr\1.0.11\assets -A E:\changekdkj\app\build\intermediate
s\exploded-aar\SMSSDK-2.0.2\assets -A E:\changekdkj\app\build\intermediates\exploded-aar\com.commit451\PhotoView\1.2.4\assets -A E:\changekdkj\app\build\intermediates\exploded-aar\com.android.support\recyclerview-v7\22.2.0\assets -A E:\changekdkj\app\build\inte
rmediates\exploded-aar\com.android.support\appcompat-v7\22.2.0\assets -A E:\changekdkj\app\build\intermediates\exploded-aar\com.android.support\design\22.2.0\assets -m -J E:\changekdkj\app\build\freeline\app\backup --auto-add-overlay -F E:\changekdkj\app\build\
freeline\base-res.so --debug-mode --no-version-vectors --resoucres-md5-cache-path E:\changekdkj\app\build\freeline\arsc_cache.dat --ignore-assets public_id.xml:public.xml:*.bak:.*
[DEBUG] [install_apk_task] start to launch application com.haixue.android.accountlife/com.haixue.android.accountlife.ui.splash.SplashActivity
[DEBUG] [install_apk_task] D:\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe shell am start -n com.haixue.android.accountlife/com.haixue.android.accountlife.ui.splash.SplashActivity
[DEBUG] [build_base_resource_task] generate base resource success: E:\changekdkj\app\build\freeline\base-res.so
[DEBUG] [tracing] build_base_resource_aapt_task: 9692.99983978ms
[DEBUG] [build_base_resource_task] build_base_resource_task finish in 9.8s
[DEBUG] [install_apk_task] install_apk_task finish in 9.9s
[DEBUG] [task_engine] it takes task engine 125.32s to execute tasks.
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 125.3s
[DEBUG] Total time: 125.5s
[DEBUG] --------------------------------------------------------
