### ISSUE TITLE
横屏应用运行时强制转为了竖屏

### ISSUE THREAD

**Issue by zhousuqiang** [alibaba/freeline#644]
我的应用是横屏应用，修改代码再运行时强制转成了竖屏导致程序直接挂了，但在应用列表中手动点击打开反而又是正常了，请问这是什么原因？

**Comment by lomanyong** [comment]
@zhousuqiang 如果 crash 了，请提供 crash 日志...方便分析是否是因为 freeline 引起的问题...

**Comment by zhousuqiang** [comment]
@lomanyong 
另说明app是运行在机顶盒上，所以整个系统都是横屏显示的。
日志如下：
02-10 12:42:02.220 24869-24869/? D/zygote: +==========================+
02-10 12:42:02.220 24869-24869/? D/zygote: +  TVM version v3.3.63_update5  +
02-10 12:42:02.220 24869-24869/? D/zygote: +==========================+
02-10 12:42:02.220 24869-24869/? D/zygote: mountEmulatedStorage......
02-10 12:42:02.220 24869-24869/? D/zygote: source=/mnt/shell/emulated
02-10 12:42:02.220 24869-24869/? D/zygote: target=/storage/emulated
02-10 12:42:02.220 24869-24869/? D/zygote: legacy=/storage/emulated/legacy
02-10 12:42:02.230 24869-24869/? D/TVM: Prepare to start GC Daemon
02-10 12:42:02.230 24869-24869/? D/TVM: Successfully start GC Daemon
02-10 12:42:02.230 24869-24869/? D/zygote: going to init jdwp
02-10 12:42:02.230 24869-24869/? D/zygote: param.suspend is  0
02-10 12:42:02.230 24869-24869/? D/jdwp: jdwp: in function vJdwpStartup
02-10 12:42:02.230 24869-24869/? D/jdwp: prepping for JDWP over ADB
02-10 12:42:02.230 24869-24874/? D/zygote: singal catcher 24874 started
02-10 12:42:02.230 24869-24869/? D/zygote: jdwp init finished in kvmInitJDWP
02-10 12:42:02.230 24869-24869/? D/TVM: VMThread.create: new thread 24876
02-10 12:42:02.230 24869-24869/? D/TVM: VMThread.create: new thread 24877
02-10 12:42:02.230 24869-24869/? D/TVM: VMThread.create: new thread 24878
02-10 12:42:02.240 24869-24875/? W/TVM: Debugger Connected
02-10 12:42:02.260 24869-24875/? I/TVM: +++ sending up 5 features
02-10 12:42:02.340 24869-24869/com.huan.edu.lexue.frontend W/TVM: TODO: native method clearGrowthLimit not implemented, yunos/vmkid/liblemur/src/native/kernel/lemur_system_VMRuntime.cpp:242
02-10 12:42:02.350 24869-24869/com.huan.edu.lexue.frontend D/TVM: VMThread.create: new thread 24884
02-10 12:42:02.350 24869-24869/com.huan.edu.lexue.frontend D/ProviderStub: onCreate
02-10 12:42:02.350 24869-24869/com.huan.edu.lexue.frontend D/FreelineApplication: FreelineApplication#onCreate()
02-10 12:42:02.350 24869-24869/com.huan.edu.lexue.frontend E/TVM: Could not find class 'Lorg/micro/freeline/hackload/ClassVerifier;', referenced from method Lcom/antfortune/freeline/FreelineConfig;.<init>
02-10 12:42:02.360 24869-24869/com.huan.edu.lexue.frontend W/TVM: VFY: unable to resolve const-class 5751 (Lorg/micro/freeline/hackload/ClassVerifier;) in Lcom/antfortune/freeline/FreelineConfig;
02-10 12:42:02.360 24869-24869/com.huan.edu.lexue.frontend D/TVM: VFY: replacing opcode 0x1c at 0x000d
02-10 12:42:02.360 24869-24869/com.huan.edu.lexue.frontend D/FreelineApplication: create application: com.huan.edu.lexue.frontend.app.EduApp
02-10 12:42:02.360 24869-24869/com.huan.edu.lexue.frontend I/Freeline: freeline start initial process...
02-10 12:42:02.360 24869-24869/com.huan.edu.lexue.frontend I/Freeline: freeline init application
02-10 12:42:02.360 24869-24869/com.huan.edu.lexue.frontend D/TVM: VMThread.create: new thread 24889
02-10 12:42:02.360 24869-24884/com.huan.edu.lexue.frontend D/TVM: thread detach: non daemon thread 24884 num = 3
02-10 12:42:02.370 24869-24869/com.huan.edu.lexue.frontend I/Freeline: start to inject dex...
02-10 12:42:02.370 24869-24889/com.huan.edu.lexue.frontend D/TVM: thread detach: non daemon thread 24889 num = 3
02-10 12:42:02.390 24869-24869/com.huan.edu.lexue.frontend I/Freeline.hackDex: /data/data/com.huan.edu.lexue.frontend/cache/temp/dex/merged.dex dex length: 112076
02-10 12:42:02.390 24869-24869/com.huan.edu.lexue.frontend I/Freeline.hackDex: /data/data/com.huan.edu.lexue.frontend/cache/temp/opt/358dbbd7aa9afa6c83c9fc155e6ecb94 opt length: 4096
02-10 12:42:02.390 24869-24869/com.huan.edu.lexue.frontend I/TVM: DexOpt: source file mod time mismatch (589d4451 vs 589d4498)
02-10 12:42:02.390 24869-24869/com.huan.edu.lexue.frontend D/TVM: ODEX file is stale or bad; removing and retrying (/data/data/com.huan.edu.lexue.frontend/cache/temp/opt/358dbbd7aa9afa6c83c9fc155e6ecb94/merged.dex)
02-10 12:42:02.390 24869-24869/com.huan.edu.lexue.frontend D/TVM: DexOpt: --- BEGIN 'merged.dex' (bootstrap=0) ---
02-10 12:42:02.460 24869-24869/com.huan.edu.lexue.frontend D/TVM: DexOpt: --- END 'merged.dex' (success) ---
02-10 12:42:02.460 24869-24869/com.huan.edu.lexue.frontend D/TVM: DEX prep '/data/data/com.huan.edu.lexue.frontend/cache/temp/dex/merged.dex': copy in 0ms, rewrite 70ms
02-10 12:42:02.460 24869-24869/com.huan.edu.lexue.frontend I/Freeline.hackDex: after opt, dex len:112076; opt len:4096
02-10 12:42:02.460 24869-24869/com.huan.edu.lexue.frontend I/Freeline: find increment package
02-10 12:42:02.460 24869-24869/com.huan.edu.lexue.frontend I/Freeline: start to inject resources...
02-10 12:42:02.460 24869-24869/com.huan.edu.lexue.frontend I/Freeline: dynamicInfoSp: {base-res.key=/data/data/com.huan.edu.lexue.frontend/cache/temp/base-res.jar, dynamic_opt_key=/data/data/com.huan.edu.lexue.frontend/cache/temp/opt, dynamic_dex_dir_key=/data/data/com.huan.edu.lexue.frontend/cache/temp/dex, dynamicTime=1486701720598}
02-10 12:42:02.460 24869-24869/com.huan.edu.lexue.frontend I/Freeline: resMap: {base-res.key=/data/data/com.huan.edu.lexue.frontend/cache/temp/base-res.jar}
02-10 12:42:02.460 24869-24869/com.huan.edu.lexue.frontend I/Freeline.GradleDynamic: dynamicResPath: /data/data/com.huan.edu.lexue.frontend/cache/temp/base-res.jar
02-10 12:42:02.470 24869-24869/com.huan.edu.lexue.frontend I/Freeline.GradleDynamic: GradleDynamic apply dynamic resource successfully
02-10 12:42:02.470 24869-24869/com.huan.edu.lexue.frontend I/Freeline: start to load hackload.dex...
02-10 12:42:02.470 24869-24869/com.huan.edu.lexue.frontend I/Freeline.hackDex: /data/data/com.huan.edu.lexue.frontend/cache/hack/hackload.dex dex length: 848
02-10 12:42:02.470 24869-24869/com.huan.edu.lexue.frontend I/Freeline.hackDex: /data/data/com.huan.edu.lexue.frontend/cache/hack/opt opt length: 4096
02-10 12:42:02.470 24869-24869/com.huan.edu.lexue.frontend I/Freeline.hackDex: after opt, dex len:848; opt len:4096
02-10 12:42:02.470 24869-24869/com.huan.edu.lexue.frontend I/Freeline: load hackload，dex size:848
02-10 12:42:02.470 24869-24869/com.huan.edu.lexue.frontend I/Freeline: start to inject native lib...
02-10 12:42:02.470 24869-24869/com.huan.edu.lexue.frontend I/Freeline.hackNative: native lib inject process start...
02-10 12:42:02.470 24869-24869/com.huan.edu.lexue.frontend I/Freeline.hackNative: inject native lib success [Ljava.io.File;@439e7fd0
02-10 12:42:02.470 24869-24869/com.huan.edu.lexue.frontend I/Freeline: freeline init server
02-10 12:42:02.470 24869-24869/com.huan.edu.lexue.frontend D/FreelineApplication: realApplication#attach(Context)
02-10 12:42:02.480 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:EduApp.onCreate(L:38): Lexue3.0 Application onCreate...
02-10 12:42:02.480 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:EduApp.onCreate(L:39): Lexue3.0 VersionName = 3.9.0_debug
02-10 12:42:02.480 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:EduApp.onCreate(L:40): Lexue3.0 VersionCode = 391
02-10 12:42:02.490 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:EduApp.onCreate(L:41): Lexue3.0 ChannelName = DEMO
02-10 12:42:02.490 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:EduApp.onCreate(L:42): Lexue3.0 Android Mode = MagicBox2
02-10 12:42:02.490 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:EduApp.onCreate(L:43): Lexue3.0 Android SDK = 19
02-10 12:42:02.490 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:EduApp.onCreate(L:44): Lexue3.0 Android VERSION = 3.0.6-RS-20160831.0951
02-10 12:42:02.490 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:EduApp.onCreate(L:45): Lexue3.0 ScreenWidth=1920 ,ScreenHeight=1080
02-10 12:42:02.500 24869-24869/com.huan.edu.lexue.frontend D/FreelineApplication: realApplication#onCreate()
02-10 12:42:02.500 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:EduApp.onTrimMemory(L:77): onTrimMemory...level=5
02-10 12:42:02.550 24869-24869/com.huan.edu.lexue.frontend D/TVM: GC_TIME GC_ALLOC freed 437K, 17% free 5314K/6351K, objects(33751)
02-10 12:42:02.550 24869-24869/com.huan.edu.lexue.frontend D/TVM: Sending VM heap info to DDM
02-10 12:42:02.550 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onAttach(L:40): 推荐 ,onAttach...
02-10 12:42:02.560 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onCreate(L:46): 推荐 ,onCreate...
02-10 12:42:02.560 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onAttach(L:40): 儿童 ,onAttach...
02-10 12:42:02.560 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onAttach(L:40): 儿童歌谣 ,onAttach...
02-10 12:42:02.560 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onCreate(L:46): 儿童歌谣 ,onCreate...
02-10 12:42:02.560 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onCreate(L:46): 儿童 ,onCreate...
02-10 12:42:02.560 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onAttach(L:40): 小学 ,onAttach...
02-10 12:42:02.560 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onAttach(L:40): 1年级 ,onAttach...
02-10 12:42:02.560 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onCreate(L:46): 1年级 ,onCreate...
02-10 12:42:02.560 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onCreate(L:46): 小学 ,onCreate...
02-10 12:42:02.560 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onAttach(L:40): 初中 ,onAttach...
02-10 12:42:02.560 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onAttach(L:40): 初一 ,onAttach...
02-10 12:42:02.560 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onCreate(L:46): 初一 ,onCreate...
02-10 12:42:02.560 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onCreate(L:46): 初中 ,onCreate...
02-10 12:42:02.570 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onAttach(L:40): 高中 ,onAttach...
02-10 12:42:02.570 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onAttach(L:40): 高一 ,onAttach...
02-10 12:42:02.570 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onCreate(L:46): 高一 ,onCreate...
02-10 12:42:02.570 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onCreate(L:46): 高中 ,onCreate...
02-10 12:42:02.570 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onAttach(L:40): 免费 ,onAttach...
02-10 12:42:02.570 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onAttach(L:40): 最新推荐 ,onAttach...
02-10 12:42:02.570 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onCreate(L:46): 最新推荐 ,onCreate...
02-10 12:42:02.570 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onCreate(L:46): 免费 ,onCreate...
02-10 12:42:02.570 24869-24869/com.huan.edu.lexue.frontend D/TVM: try create PROXY:$Proxy0 by loader 0x439a5808
02-10 12:42:02.590 24869-24869/com.huan.edu.lexue.frontend D/TVM: GC_TIME GC_ALLOC freed 274K, 16% free 5353K/6351K, objects(34490)
02-10 12:42:02.590 24869-24869/com.huan.edu.lexue.frontend D/TVM: Sending VM heap info to DDM
02-10 12:42:02.630 24869-24869/com.huan.edu.lexue.frontend D/TVM: Alloc from exist block failed.allocatedSize = 3875808, size = 24, idealSize= 3875808.
02-10 12:42:02.640 24869-24869/com.huan.edu.lexue.frontend D/TVM: GC_TIME GC_ALLOC freed <1K, 11% free 8953K/9999K, objects(34473)
02-10 12:42:02.640 24869-24869/com.huan.edu.lexue.frontend D/TVM: Sending VM heap info to DDM
02-10 12:42:02.690 24869-24869/com.huan.edu.lexue.frontend D/TVM: try create PROXY:$Proxy1 by loader 0x439a5808
02-10 12:42:02.700 24869-24869/com.huan.edu.lexue.frontend D/TVM: VMThread.create: new thread 24901
02-10 12:42:02.700 24869-24901/com.huan.edu.lexue.frontend D/TVM: thread detach: non daemon thread 24901 num = 3
02-10 12:42:02.700 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:NetworkChangeReceiver.registerReceiver(L:63): 注册网络广播接收者...
02-10 12:42:02.710 24869-24869/com.huan.edu.lexue.frontend D/TVM: VMThread.create: new thread 24902
02-10 12:42:02.710 24869-24902/com.huan.edu.lexue.frontend D/TVM: thread detach: non daemon thread 24902 num = 3
02-10 12:42:02.740 24869-24869/com.huan.edu.lexue.frontend D/TVM: VMThread.create: new thread 24904
02-10 12:42:02.740 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onCreateView(L:51): 推荐 ,onCreateView...
02-10 12:42:02.790 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onViewCreated(L:67): 推荐 ,onViewCreated...
02-10 12:42:02.810 24869-24869/com.huan.edu.lexue.frontend D/TVM: VMThread.create: new thread 24905
02-10 12:42:02.810 24869-24869/com.huan.edu.lexue.frontend I/[lexue_log]:BaseFragment.onActivityCreated(L:73): 推荐 ,onActivityCreated...
02-10 12:42:02.830 24869-24869/com.huan.edu.lexue.frontend D/TVM: GC_TIME GC_ALLOC freed 432K, 10% free 9799K/10831K, objects(36333)
02-10 12:42:02.830 24869-24869/com.huan.edu.lexue.frontend D/TVM: Sending VM heap info to DDM
02-10 12:42:02.830 24869-24869/com.huan.edu.lexue.frontend D/AndroidRuntime: Shutting down VM
02-10 12:42:02.830 24869-24869/com.huan.edu.lexue.frontend W/TVM: try to handle uncaught exception in bootstrap frame.
02-10 12:42:02.830 24869-24869/com.huan.edu.lexue.frontend E/TVM: 0x433eca58 0x433e7cf0 0x433e83f0 0x683065f8
02-10 12:42:02.830 24869-24869/com.huan.edu.lexue.frontend E/TVM: uncaughtException Ljava/lang/ThreadGroup;
02-10 12:42:02.830 24869-24869/com.huan.edu.lexue.frontend E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.huan.edu.lexue.frontend, PID: 24869
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.huan.edu.lexue.frontend/com.huan.edu.lexue.frontend.activity.HomeActivity}: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class com.owen.tvrecyclerview.widget.TvRecyclerView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/tv_recyclerview_template. Make sure other views do not use the same id.
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2201)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2251)
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:153)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5038)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:851)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:667)
                                                                              Caused by: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class com.owen.tvrecyclerview.widget.TvRecyclerView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/tv_recyclerview_template. Make sure other views do not use the same id.
                                                                                 at android.view.View.onRestoreInstanceState(View.java:12836)
                                                                                 at android.support.v7.widget.RecyclerView.onRestoreInstanceState(RecyclerView.java:1137)
                                                                                 at com.owen.tvrecyclerview.widget.TvRecyclerView.onRestoreInstanceState(TvRecyclerView.java:898)
                                                                                 at android.view.View.dispatchRestoreInstanceState(View.java:12812)
                                                                                 at android.view.ViewGroup.dispatchThawSelfOnly(ViewGroup.java:2657)
                                                                                 at android.support.v7.widget.RecyclerView.dispatchRestoreInstanceState(RecyclerView.java:1161)
                                                                                 at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2643)
                                                                                 at android.view.View.restoreHierarchyState(View.java:12790)
                                                                                 at android.support.v4.app.Fragment.restoreViewState(Fragment.java:477)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1135)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1272)
                                                                                 at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2149)
                                                                                 at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
                                                                                 at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:600)
                                                                                 at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
                                                                                 at android.app.Activity.performStart(Activity.java:5280)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2174)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2251) 
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:153) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5038) 
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:851) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:667) 
02-10 12:42:02.840 24869-24869/com.huan.edu.lexue.frontend I/Process: Sending signal. PID: 24869 SIG: 9

**Comment by lomanyong** [comment]
@zhousuqiang 这个看着像是你的 app 自身的逻辑导致的问题...不像是 freeline 导致的...可能是 freeline 的重启功能间接触发了这个问题...
