### ISSUE TITLE
IncompatibleClassChangeError

### ISSUE THREAD

**Issue by kosiarska** [alibaba/freeline#645]
Issue:
```` 
Process: xxx.debug, PID: 13721
                                                   java.lang.IncompatibleClassChangeError: Structural change of xxx.ui.base.BaseActivity is hazardous (/data/app/xxx.debug-2/oat/x86/base.odex at compile time, /data/user/0/xxx.debug/cache/temp/opt/86a1cac5b4192c5f3d21af84ded67e3e/merged.dex at runtime): Direct method count off: 2 vs 3
                                                   Lxxx/ui/base/BaseActivity; (Compile time):
                                                    Static fields:
                                                     Ljava/lang/String; KEY_ACTIVITY_ID
                                                     Ljava/util/concurrent/atomic/AtomicLong; NEXT_ID
                                                     Ljava/util/Map; sComponentsMap
                                                    Instance fields:
                                                     Leu/xxx/injection/component/ActivityComponent; mActivityComponent
                                                     J mActivityId
                                                    Direct methods:
                                                     <clinit>()V
                                                     <init>()V
                                                    Virtual methods:
                                                     activityComponent()
Lxxx/injection/component/ActivityComponent;
                                                     onCreate(Landroid/os/Bundle;)V
                                                     onDestroy()V
                                                     onSaveInstanceState(Landroid/os/Bundle;)V
                                                   Lxxx/ui/base/BaseActivity; (Runtime):
                                                    Static fields:
                                                     Ljava/lang/String; KEY_ACTIVITY_ID
                                                     Ljava/util/concurrent/atomic/AtomicLong; NEXT_ID
                                                     Ljava/util/Map; sComponentsMap
                                                    Instance fields:
                                                     Lxxx/injection/component/ActivityComponent; mActivityComponent
                                                     J mActivityId
                                                    Direct methods:
                                                     <clinit>()V
                                                     <init>()V
                                                     injection(Landroid/os/Bundle;)V
                                                    Virtual methods:
                                                     activityComponent()Lxxx/injection/component/ActivityComponent;
                                                     onCreate(Landroid/os/Bundle;)V
                                                     onDestroy()V
                                                     onSaveInstanceState(Landroid/os/Bundle;)V
                                                    (declaration of 'xxx.ui.splash.SplashActivity' appears in /data/app/xxx.debug-2/base.apk)
                                                       at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                       at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2557)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`
````

Steps to reproduce:
1. Open this project:
https://github.com/ribot/android-boilerplate
2. Start project using freeline
3. Replace body of BaseActivity code with this (copy paste):
https://gist.github.com/kosiarska/cf67c24a07fdbd7d705a22b4223c6e14
4. Run freeline again

**Comment by lomanyong** [comment]
@kosiarska hi, this issue is caused by the method count of the basic class changed, but the child-class has the original method count. You should change SplashActivity together.
