### ISSUE TITLE
gradlew initFreeline problem?

### ISSUE THREAD

**Issue by songsh** [alibaba/freeline#646]
Execution failed for task ':initFreeline'.
> Can't get http://static.freelinebuild.com/freeline/0.8.5/all/freeline.zip

**Comment by songsh** [comment]
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':initFre
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExec
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.exec
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execut
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecu
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execut
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(Defaul
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(Defau
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTask
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExec
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecu
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildEx
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLa
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGra
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradl
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradl
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildCon
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(Exe
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildA
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(Contin
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(Contin
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBu
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(Forw
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(Forw
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(For
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClien
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBu
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(Hin
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(Daemon
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableE
Caused by: : Can't get http://static.freelinebuild.com/freeline/0.8.5/all/freeli
        at org.apache.tools.ant.taskdefs.Get$GetThread.downloadFile(Get.java:806
        at org.apache.tools.ant.taskdefs.Get$GetThread.get(Get.java:647)
        at org.apache.tools.ant.taskdefs.Get$GetThread.run(Get.java:631)

**Comment by lomanyong** [comment]
@songsh this issue is caused by your network status...

You can try to access this url directly.

**Comment by songsh** [comment]
thanks so mush, i copy the file to project root,
![image](https://cloud.githubusercontent.com/assets/2272252/22774726/5a11e6fc-eee3-11e6-971e-26b0aa645c31.png)
then run freeline ,
Error:Execution failed for task ':initFreeline'.
> Can't get http://static.freelinebuild.com/freeline/0.8.5/all/freeline.zip to C:\Users\91489\AndroidStudioProjects\Gdzx_androidv1.0\ZhiXun\freeline.zip.tmp

**Comment by songsh** [comment]
app 安装到手机上了，但还是报这个错。。。。

**Comment by lomanyong** [comment]
@songsh 你这本地的网络问题我远程也没办法帮你调试吧。。。
