### ISSUE TITLE
执行 python freeline.py -f  报错，怎么解决

### ISSUE THREAD

**Issue by shangwfa** [alibaba/freeline#648]
python freeline.py -f  
[INFO] preparing for tasks...
[-][read_project_info_task] failed. in 0.0s
[-][generate_file_stat_task] finished. in 0.1s
[-][gradle_clean_build_task] failed. in 0s
[-][clean_all_cache_task] failed. in 0s
[-][install_apk_task] failed. in 0s
[-][build_base_resource_task] failed. in 0s
[-][generate_project_info_task] failed. in 0s
[-][generate_apt_files_task] failed. in 0s
[-][append_file_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "/Users/menmen/Desktop/weex-androd/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/Users/menmen/Desktop/weex-androd/freeline/freeline_core/gradle_clean_build.py", line 75, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "/Users/menmen/Desktop/weex-androd/freeline/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

**Comment by shangwfa** [comment]
有说需要修改工程下，freeline下的release-tools文件的读写权限，修改后仍旧无效

**Comment by shangwfa** [comment]
找到原因了，修改chmod +x gradlew
