### ISSUE TITLE
Exception in thread "main" java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by cikichen** [alibaba/freeline#651]
```
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=False, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.3.0-beta4
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.5
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.5.1701181052
[DEBUG] [WARNING] some important file missed, a clean build will be automatically executed.
[DEBUG] collecting project info, please wait a while...
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: E:\client\app\build\freeline\freeline-assets\apktime
[DEBUG] new clean build flag value: 866000
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save app module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.0s
[DEBUG] [read_project_info_task] read_project_info_task finish in 1.1s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 1.1s
[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 1.1s
[DEBUG] [install_apk_task] install_apk_task start to run after waiting 1.1s
[DEBUG] [append_file_stat_task] append_file_stat_task start to run after waiting 0.0s
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after waiting 1.1s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run after waiting 1.0s
[DEBUG] [generate_apt_files_task] generate_apt_files_task start to run after waiting 0.0s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 1.06s to execute tasks.
[DEBUG] [task_engine] it takes task engine 1.06s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)
        at org.gradle.wrapper.Install.unzip(Install.java:214)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

[ERROR] --------------------------------------------------------
[ERROR] freeline failed when read project info with script: gradlew.bat -q checkBeforeCleanBuild
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.5s
[DEBUG] Task engine running time: 1.1s
[DEBUG] Total time: 1.5s
[DEBUG] --------------------------------------------------------
```

另外指定productFlavors的详细步骤能更新到文档里面去吗？

**Comment by lomanyong** [comment]
@cikichen 指定 productFlavor 在编译期会报错提示的，有给出方案的。如果觉得不够详细的话你们也可以帮忙完善哈~

这个报错的原因看着是本地的 gradle 文件有问题...跟 freeline 本身的逻辑没有太多的关联...
