### ISSUE TITLE
incremental res build failed

### ISSUE THREAD

**Issue by mabinbib** [alibaba/freeline#654]
第一次全量python freeline.py -f的时候可以运行，但是第二次，python freeline.py就出现incremental res build failed这个问题

**Comment by lomanyong** [comment]
@mabinbib 请贴出详细的日志

**Comment by mabinbib** [comment]
[ERROR] Freeline server in app com.sgcc.cs not found. Please make sure your application is properly running in your device.

**Comment by mabinbib** [comment]
现在我按照152 全部走了一遍出现这个问题，第一遍全量编译没问题，再次增量编译出现的问题。

**Comment by mabinbib** [comment]
@lomanyong

**Comment by lomanyong** [comment]
@mabinbib 这个不是 incremental res build failed 的错误吧... issue 152 的重启电脑试过吗？

**Comment by mabinbib** [comment]
是的，昨晚是incremental res build failed 错误，今天我按照流程从新走了一遍，出现了新的错误。我现在重启试试。

**Comment by mabinbib** [comment]
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
        Please make sure your application is properly running in your device.
        Check follow steps:
        1. Make sure the versions `python freeline.py -v`, freeline-gradle and freeline-runtime are the same;
        2. Make sure there is no network proxy.
        
        More about this can see: https://github.com/alibaba/freeline/issues/152
[ERROR] --------------------------------------------------------
[ERROR] Freeline server in app com.sgcc.cs not found. Please make sure your application is properly running in your device.
[ERROR] --------------------------------------------------------
重启后出现的，还是一样。

**Comment by lomanyong** [comment]
@mabinbib android studio 有开启代理吗？手机上相同的 app 是否有卸载？是否可以换个手机也试试看？

**Comment by mabinbib** [comment]
没有开代理，app已经卸载，现在换个手机测试

**Comment by mabinbib** [comment]
要说代理，只有下载sdk的时候用的腾讯的镜像。

**Comment by mabinbib** [comment]
换了手机，还是一样的问题。

**Comment by lomanyong** [comment]
@mabinbib 看下logcat的日志，freeline的server是否启动了...

**Comment by mabinbib** [comment]
E/Freeline: java.lang.NullPointerException
                 at com.antfortune.freeline.FreelineCore.getApkBuildFlag(FreelineCore.java:156)
                 at com.antfortune.freeline.router.schema.CheckSyncSchema.handle(CheckSyncSchema.java:28)
                 at com.antfortune.freeline.router.Router.dispatch(Router.java:48)
                 at com.antfortune.freeline.server.LongLinkServer.handle(LongLinkServer.java:55)
                 at com.antfortune.freeline.server.EmbedHttpServer.run(EmbedHttpServer.java:95)
                 at java.lang.Thread.run(Thread.java:856)
 I/Freeline.Service: onStartCommand Received start id 11, intent: Intent { cmp=com.sgcc.cs/com.antfortune.fre
 D/Freeline.LongLinkServer: Freeline.increment server is already running
 E/Freeline: java.lang.NullPointerException
                 at com.antfortune.freeline.FreelineCore.getApkBuildFlag(FreelineCore.java:156)
                 at com.antfortune.freeline.router.schema.CheckSyncSchema.handle(CheckSyncSchema.java:28)
                 at com.antfortune.freeline.router.Router.dispatch(Router.java:48)
                 at com.antfortune.freeline.server.LongLinkServer.handle(LongLinkServer.java:55)
                 at com.antfortune.freeline.server.EmbedHttpServer.run(EmbedHttpServer.java:95)
                 at java.lang.Thread.run(Thread.java:856)
 I/Freeline.Service: onStartCommand Received start id 12, intent: Intent { cmp=com.sgcc.cs/com.antfortune.fre
 D/Freeline.LongLinkServer: Freeline.increment server is already running
 E/Freeline: java.lang.NullPointerException
                 at com.antfortune.freeline.FreelineCore.getApkBuildFlag(FreelineCore.java:156)
                 at com.antfortune.freeline.router.schema.CheckSyncSchema.handle(CheckSyncSchema.java:28)
                 at com.antfortune.freeline.router.Router.dispatch(Router.java:48)
                 at com.antfortune.freeline.server.LongLinkServer.handle(LongLinkServer.java:55)
                 at com.antfortune.freeline.server.EmbedHttpServer.run(EmbedHttpServer.java:95)
                 at java.lang.Thread.run(Thread.java:856)
 I/Freeline.Service: onStartCommand Received start id 13, intent: Intent { cmp=com.sgcc.cs/com.antfortune.fre
 D/Freeline.LongLinkServer: Freeline.increment server is already running
 E/Freeline: java.lang.NullPointerException
                 at com.antfortune.freeline.FreelineCore.getApkBuildFlag(FreelineCore.java:156)
                 at com.antfortune.freeline.router.schema.CheckSyncSchema.handle(CheckSyncSchema.java:28)
                 at com.antfortune.freeline.router.Router.dispatch(Router.java:48)
                 at com.antfortune.freeline.server.LongLinkServer.handle(LongLinkServer.java:55)
                 at com.antfortune.freeline.server.EmbedHttpServer.run(EmbedHttpServer.java:95)
                 at java.lang.Thread.run(Thread.java:856)
 I/Freeline.Service: onStartCommand Received start id 14, intent: Intent { cmp=com.sgcc.cs/com.antfortune.fre
 D/Freeline.LongLinkServer: Freeline.increment server is already running
 E/Freeline: java.lang.NullPointerException
                 at com.antfortune.freeline.FreelineCore.getApkBuildFlag(FreelineCore.java:156)
                 at com.antfortune.freeline.router.schema.CheckSyncSchema.handle(CheckSyncSchema.java:28)
                 at com.antfortune.freeline.router.Router.dispatch(Router.java:48)
                 at com.antfortune.freeline.server.LongLinkServer.handle(LongLinkServer.java:55)
                 at com.antfortune.freeline.server.EmbedHttpServer.run(EmbedHttpServer.java:95)
                 at java.lang.Thread.run(Thread.java:856)
 I/Freeline.Service: onStartCommand Received start id 15, intent: Intent { cmp=com.sgcc.cs/com.antfortune.fre
 D/Freeline.LongLinkServer: Freeline.increment server is already running
 E/Freeline: java.lang.NullPointerException
                 at com.antfortune.freeline.FreelineCore.getApkBuildFlag(FreelineCore.java:156)
                 at com.antfortune.freeline.router.schema.CheckSyncSchema.handle(CheckSyncSchema.java:28)
                 at com.antfortune.freeline.router.Router.dispatch(Router.java:48)
                 at com.antfortune.freeline.server.LongLinkServer.handle(LongLinkServer.java:55)
                 at com.antfortune.freeline.server.EmbedHttpServer.run(EmbedHttpServer.java:95)
                 at java.lang.Thread.run(Thread.java:856)
 I/Freeline.Service: onStartCommand Received start id 16, intent: Intent { cmp=com.sgcc.cs/com.antfortune.fre
 D/Freeline.LongLinkServer: Freeline.increment server is already running
 E/Freeline: java.lang.NullPointerException
                 at com.antfortune.freeline.FreelineCore.getApkBuildFlag(FreelineCore.java:156)
                 at com.antfortune.freeline.router.schema.CheckSyncSchema.handle(CheckSyncSchema.java:28)
                 at com.antfortune.freeline.router.Router.dispatch(Router.java:48)
                 at com.antfortune.freeline.server.LongLinkServer.handle(LongLinkServer.java:55)
                 at com.antfortune.freeline.server.EmbedHttpServer.run(EmbedHttpServer.java:95)
                 at java.lang.Thread.run(Thread.java:856)
 I/Freeline.Service: onStartCommand Received start id 17, intent: Intent { cmp=com.sgcc.cs/com.antfortune.fre
 D/Freeline.LongLinkServer: Freeline.increment server is already running
 E/Freeline: java.lang.NullPointerException
                 at com.antfortune.freeline.FreelineCore.getApkBuildFlag(FreelineCore.java:156)
                 at com.antfortune.freeline.router.schema.CheckSyncSchema.handle(CheckSyncSchema.java:28)
                 at com.antfortune.freeline.router.Router.dispatch(Router.java:48)
                 at com.antfortune.freeline.server.LongLinkServer.handle(LongLinkServer.java:55)
                 at com.antfortune.freeline.server.EmbedHttpServer.run(EmbedHttpServer.java:95)
                 at java.lang.Thread.run(Thread.java:856)
 I/Freeline.Service: onStartCommand Received start id 18, intent: Intent { cmp=com.sgcc.cs/com.antfortune.fre
 D/Freeline.LongLinkServer: Freeline.increment server is already running
 E/Freeline: java.lang.NullPointerException
                 at com.antfortune.freeline.FreelineCore.getApkBuildFlag(FreelineCore.java:156)
                 at com.antfortune.freeline.router.schema.CheckSyncSchema.handle(CheckSyncSchema.java:28)
                 at com.antfortune.freeline.router.Router.dispatch(Router.java:48)
                 at com.antfortune.freeline.server.LongLinkServer.handle(LongLinkServer.java:55)
                 at com.antfortune.freeline.server.EmbedHttpServer.run(EmbedHttpServer.java:95)
                 at java.lang.Thread.run(Thread.java:856)
 I/Freeline.Service: onStartCommand Received start id 19, intent: Intent { cmp=com.sgcc.cs/com.antfortune.fre
 D/Freeline.LongLinkServer: Freeline.increment server is already running
 E/Freeline: java.lang.NullPointerException
                 at com.antfortune.freeline.FreelineCore.getApkBuildFlag(FreelineCore.java:156)
                 at com.antfortune.freeline.router.schema.CheckSyncSchema.handle(CheckSyncSchema.java:28)
                 at com.antfortune.freeline.router.Router.dispatch(Router.java:48)
                 at com.antfortune.freeline.server.LongLinkServer.handle(LongLinkServer.java:55)
                 at com.antfortune.freeline.server.EmbedHttpServer.run(EmbedHttpServer.java:95)
                 at java.lang.Thread.run(Thread.java:856)
 I/Freeline.Service: onStartCommand Received start id 20, intent: Intent { cmp=com.sgcc.cs/com.antfortune.fre
 D/Freeline.LongLinkServer: Freeline.increment server is already running
 E/Freeline: java.lang.NullPointerException
                 at com.antfortune.freeline.FreelineCore.getApkBuildFlag(FreelineCore.java:156)
                 at com.antfortune.freeline.router.schema.CheckSyncSchema.handle(CheckSyncSchema.java:28)
                 at com.antfortune.freeline.router.Router.dispatch(Router.java:48)
                 at com.antfortune.freeline.server.LongLinkServer.handle(LongLinkServer.java:55)
                 at com.antfortune.freeline.server.EmbedHttpServer.run(EmbedHttpServer.java:95)
                 at java.lang.Thread.run(Thread.java:856)

**Comment by mabinbib** [comment]
是这个吗

**Comment by mabinbib** [comment]
@lomanyong

**Comment by lomanyong** [comment]
@mabinbib right，这个问题导致的无法连接上。App 有使用什么特殊的插件化框架之类的吗？

**Comment by mabinbib** [comment]
最近多了一个内存泄漏检测 LeakCanary

**Comment by lomanyong** [comment]
@mabinbib 参考 #273 做下处理再尝试看看

**Comment by mabinbib** [comment]
incremental javac compile failed.
出现这个问题
log：
02-14 14:52:08.896 21271-21271/com.sgcc.cs I/Freeline: freeline start initial process...
02-14 14:52:08.896 21271-21271/com.sgcc.cs I/Freeline: freeline init application
02-14 14:52:08.906 21271-21271/com.sgcc.cs E/dalvikvm: Could not find class 'android.util.ArrayMap', referenced from method com.antfortune.freeline.resources.MonkeyPatcher.monkeyPatchExistingResources
02-14 14:52:08.906 21271-21271/com.sgcc.cs W/dalvikvm: VFY: unable to resolve check-cast 245 (Landroid/util/ArrayMap;) in Lcom/antfortune/freeline/resources/MonkeyPatcher;
02-14 14:52:08.906 21271-21271/com.sgcc.cs E/dalvikvm: Could not find class 'android.util.ArrayMap', referenced from method com.antfortune.freeline.resources.MonkeyPatcher.pruneResourceCache
02-14 14:52:08.906 21271-21271/com.sgcc.cs W/dalvikvm: VFY: unable to resolve const-class 245 (Landroid/util/ArrayMap;) in Lcom/antfortune/freeline/resources/MonkeyPatcher;
02-14 14:52:08.911 21271-21271/com.sgcc.cs I/Freeline: start to inject dex...
02-14 14:52:08.911 21271-21271/com.sgcc.cs I/Freeline: start to inject resources...
02-14 14:52:08.911 21271-21271/com.sgcc.cs I/Freeline: dynamicInfoSp: {}
02-14 14:52:08.911 21271-21271/com.sgcc.cs I/Freeline: resMap: {}
02-14 14:52:08.911 21271-21271/com.sgcc.cs I/Freeline: start to load hackload.dex...
02-14 14:52:08.911 21271-21271/com.sgcc.cs I/Freeline: copy hackload dex from assets success
02-14 14:52:08.911 21271-21271/com.sgcc.cs I/Freeline.hackDex: /data/data/com.sgcc.cs/cache/hack/hackload.dex dex length: 848
02-14 14:52:08.911 21271-21271/com.sgcc.cs I/Freeline.hackDex: /data/data/com.sgcc.cs/cache/hack/opt opt length: 4096
02-14 14:52:08.981 21271-21271/com.sgcc.cs I/Freeline.hackDex: after opt, dex len:848; opt len:4096
02-14 14:52:08.981 21271-21271/com.sgcc.cs I/Freeline: load hackload，dex size:848
02-14 14:52:08.981 21271-21271/com.sgcc.cs I/Freeline: start to inject native lib...
02-14 14:52:08.981 21271-21271/com.sgcc.cs I/Freeline.hackNative: native lib inject process start...
02-14 14:52:08.981 21271-21271/com.sgcc.cs I/Freeline.hackNative: inject native lib success [Ljava.io.File;@41fa97b8
02-14 14:52:08.981 21271-21271/com.sgcc.cs I/Freeline: freeline init server

**Comment by lomanyong** [comment]
@mabinbib javac compile failed 就看控制台输出的日志呀...

**Comment by mabinbib** [comment]
这个问题不应该出现，我第一次全量编译，第二次只是改变了title就编译不过。

**Comment by lomanyong** [comment]
@mabinbib 请贴出错误的日志具体的信息...

**Comment by mabinbib** [comment]
警告: [options] 未与 -source 1.7 一起设置引导类路径
/Users/mabinbin/Android/AndroidStudioProject/Marketing_cellphone_client_as/app/src/main/java/com/sgcc/cs/area/jiangsu/ChangeOfNameBusInfo.java:3: 错误: 程序包an.os不存在
import android.os.Bundle;
                 ^
/Users/mabinbin/Android/AndroidStudioProject/Marketing_cellphone_client_as/app/src/main/java/com/sgcc/cs/area/jiangsu/ChangeOfNameBusInfo.java:4: 错误: 程序包an.view不存在
import android.view.View;
                   ^
/Users/mabinbin/Android/AndroidStudioProject/Marketing_cellphone_client_as/app/src/main/java/com/sgcc/cs/area/jiangsu/ChangeOfNameBusInfo.java:13: 错误: 无法访问View
public class ChangeOfNameBusInfo extends BaseActivity{
       ^
  找不到android.view.View的类文件
/Users/mabinbin/Android/AndroidStudioProject/Marketing_cellphone_client_as/app/src/main/java/com/sgcc/cs/area/jiangsu/ChangeOfNameBusInfo.java:16: 错误: 找不到符号
    protected void onCreate(Bundle savedInstanceState) {
                            ^
  符号:   类 Bundle
  位置: 类 ChangeOfNameBusInfo
/Users/mabinbin/Android/AndroidStudioProject/Marketing_cellphone_client_as/app/src/main/java/com/sgcc/cs/area/jiangsu/ChangeOfNameBusInfo.java:31: 错误: 找不到符号
    public void onClick(View v) {
                        ^
  符号:   类 View
  位置: 类 ChangeOfNameBusInfo
/Users/mabinbin/Android/AndroidStudioProject/Marketing_cellphone_client_as/app/src/main/java/com/sgcc/cs/area/jiangsu/ChangeOfNameBusInfo.java:15: 错误: 方法不会超类型的方法
    @Override
    ^
/Users/mabinbin/Android/AndroidStudioProject/Marketing_cellphone_client_as/app/src/main/java/com/sgcc/cs/area/jiangsu/ChangeOfNameBusInfo.java:17: 错误: 找不到符号
        super.onCreate(savedInstanceState);
        ^
  符号:   变量 super
  位置: 类 ChangeOfNameBusInfo
/Users/mabinbin/Android/AndroidStudioProject/Marketing_cellphone_client_as/app/src/main/java/com/sgcc/cs/area/jiangsu/ChangeOfNameBusInfo.java:18: 错误: 找不到符号
        setContentView(R.layout.jiangsu_change_of_name_clause);
        ^
  符号:   方法 setContentView(int)
  位置: 类 ChangeOfNameBusInfo
/Users/mabinbin/Android/AndroidStudioProject/Marketing_cellphone_client_as/app/src/main/java/com/sgcc/cs/area/jiangsu/ChangeOfNameBusInfo.java:23: 错误: 方法不会超类型的方法
    @Override
    ^
/Users/mabinbin/Android/AndroidStudioProject/Marketing_cellphone_client_as/app/src/main/java/com/sgcc/cs/area/jiangsu/ChangeOfNameBusInfo.java:25: 错误: 找不到符号
        super.initTitle();
        ^
  符号:   变量 super
  位置: 类 ChangeOfNameBusInfo
/Users/mabinbin/Android/AndroidStudioProject/Marketing_cellphone_client_as/app/src/main/java/com/sgcc/cs/area/jiangsu/ChangeOfNameBusInfo.java:26: 错误: 找不到符号
        setListener();
        ^
  符号:   方法 setListener()
  位置: 类 ChangeOfNameBusInfo
/Users/mabinbin/Android/AndroidStudioProject/Marketing_cellphone_client_as/app/src/main/java/com/sgcc/cs/area/jiangsu/ChangeOfNameBusInfo.java:30: 错误: 方法不会超类型的方法
    @Override
    ^
/Users/mabinbin/Android/AndroidStudioProject/Marketing_cellphone_client_as/app/src/main/java/com/sgcc/cs/area/jiangsu/ChangeOfNameBusInfo.java:32: 错误: 找不到符号
        super.onClick(v);
        ^
  符号:   变量 super
  位置: 类 ChangeOfNameBusInfo
13 个错误
1 个警告

[ERROR] --------------------------------------------------------
[ERROR] incremental javac compile failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 0.9s
[DEBUG] Total time: 1.3s
[DEBUG] ---------------------------------------

**Comment by lomanyong** [comment]
@mabinbib 执行`python freeline.py -d`日志里会有一个 javac 命令，里面的一个参数：`android.jar`那个路径的jar应该是不存在的...你可以看下。

**Comment by mabinbib** [comment]
javac exec: /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin/javac -encoding UTF-8 -g -target 1.7 -source 1.7 -cp /Users/mabinbin/Android/AndroidStudioProject/Marketing_cellphone_client_as/app/build/freeline/app/classes:/Users/mabinbin/Android/AndroidStudioProject/Marketing_cellphone_client_as/app/build/intermediates/classes/dev/debug:/Users/mabinbin/Library/Android/sdk/platforms/Google Inc.:Google APIs:23/android.jar:/Users/mabinbin/Android/AndroidStudioProject/Marketing_cellphone_client_as/app/libs/base-support-0.0.1-SNAPSHOT.jar:

**Comment by mabinbib** [comment]
@lomanyong

**Comment by lomanyong** [comment]
@mabinbib  `/Users/mabinbin/Library/Android/sdk/platforms/Google Inc.:Google APIs:23/android.jar` 你还需要这个库？不能用非 Google API 的库吗？

**Comment by mabinbib** [comment]
可以了，非常感谢，是库的原因，原谅我问的很多问题很小白。给你带来麻烦，很抱歉。

**Comment by lomanyong** [comment]
@mabinbib 解决问题就好~
