### ISSUE TITLE
java.net.BindException: Address already in use

### ISSUE THREAD

**Issue by guangit** [alibaba/freeline#659]
E: java.net.BindException: Address already in use
       at java.net.PlainSocketImpl.socketBind(Native Method)
       at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:368)
       at java.net.ServerSocket.bind(ServerSocket.java:377)
       at java.net.ServerSocket.<init>(ServerSocket.java:237)
       at java.net.ServerSocket.<init>(ServerSocket.java:128)
       at com.antfortune.freeline.server.EmbedHttpServer.start(EmbedHttpServer.java:25)
       at com.antfortune.freeline.server.LongLinkServer.start(LongLinkServer.java:154)
       at com.antfortune.freeline.FreelineService.onStartCommand(FreelineService.java:40)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3320)
       at android.app.ActivityThread.-wrap21(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1580)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6114)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)

 incremental res build failed.
第一次运行不会报错 修改xml文件之后就不行了

**Comment by lomanyong** [comment]
@guangit 这个跟这个错误堆栈没有关系的，资源编译出错具体看python输出的日志
