### ISSUE TITLE
initFreeline Could not initialize class com.antfortune.freeline.versions.StaticVersionComparator

### ISSUE THREAD

**Issue by conncui** [alibaba/freeline#670]
```
10:42:45.917 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':initFreeline'
10:42:45.917 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':initFreeline' is up-to-date
10:42:45.917 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':initFreeline' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
10:42:45.917 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':initFreeline'.
10:42:45.917 [QUIET] [system.out] Freeline initial process start...
10:42:45.972 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@3b99ac5c5 pairs: {GET /api/versions/latest HTTP/1.1: null}{User-Agent: Java/1.8.0_122-ea}{Host: www.freelinebuild.com}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
10:42:45.998 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@6dc36a4c8 pairs: {null: HTTP/1.1 200 OK}{Server: Tengine}{Date: Mon, 20 Feb 2017 02:42:47 GMT}{Content-Type: application/json; charset=utf-8}{Content-Length: 252}{Connection: keep-alive}{x-powered-by: Express}{etag: W/"fc-833d9d12"}
10:42:45.999 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.oldresult.TransientConfigurationResultsBuilder] Loaded resolved configuration results (0.0 secs) from Binary store in /tmp/gradle2604735562755744071.bin
10:42:46.000 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':initFreeline'
10:42:46.000 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :initFreeline FAILED
10:42:46.001 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :initFreeline (Thread[Task worker,5,main]) completed. Took 0.085 secs.
10:42:46.001 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Task worker,5,main]] finished, busy: 0.085 secs, idle: 0.0 secs
10:42:46.002 [ERROR] [org.gradle.BuildExceptionReporter] 
10:42:46.002 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
10:42:46.002 [ERROR] [org.gradle.BuildExceptionReporter] 
10:42:46.002 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
10:42:46.002 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':initFreeline'.
10:42:46.003 [ERROR] [org.gradle.BuildExceptionReporter] > Could not initialize class com.antfortune.freeline.versions.StaticVersionComparator
10:42:46.003 [ERROR] [org.gradle.BuildExceptionReporter] 
10:42:46.003 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
10:42:46.079 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':initFreeline'.
10:42:46.079 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
10:42:46.079 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
10:42:46.079 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.antfortune.freeline.versions.StaticVersionComparator
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at com.antfortune.freeline.FreelineDownloader.isFreelineGradleVersionNeedToBeUpdated(FreelineDownloader.groovy:201)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at com.antfortune.freeline.FreelineDownloader.checkVersion(FreelineDownloader.groovy:182)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at com.antfortune.freeline.FreelineDownloader.fetchData(FreelineDownloader.groovy:134)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at com.antfortune.freeline.FreelineDownloader.execute(FreelineDownloader.groovy:45)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at com.antfortune.freeline.FreelineDownloader$execute.call(Unknown Source)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at com.antfortune.freeline.FreelineInitializer.initFreeline(FreelineInitializer.groovy:16)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at com.antfortune.freeline.FreelineInitializer$initFreeline.call(Unknown Source)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at com.antfortune.freeline.FreelinePlugin$_apply_closure2.doCall(FreelinePlugin.groovy:38)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:590)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:571)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        ... 14 more
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter] 
10:42:46.080 [LIFECYCLE] [org.gradle.BuildResultLogger] 
10:42:46.080 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
10:42:46.080 [LIFECYCLE] [org.gradle.BuildResultLogger] 
10:42:46.080 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 2.04 secs
10:42:46.082 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache task history cache (/home/cui/work/oschinagit/AndroidProject/.gradle/2.14.1/taskArtifacts) was closed 0 times.
10:42:46.082 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 1 (avg: 0.0 secs, total: 0.0 secs)
10:42:46.082 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 28 (avg: 0.0 secs, total: 0.007 secs)
10:42:46.082 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.ResolutionResultsStoreFactory] Deleted 2 resolution results binary files in 0.0 secs
10:42:46.082 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedRepositoryFactory] In-memory dependency metadata cache closed. Repos cached: 147, cache instances: 6, modules served from cache: 1970, artifacts: 657
10:42:46.082 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Generated Gradle JARs cache (/home/cui/.gradle/caches/2.14.1/generated-gradle-jars) was closed 0 times.
10:42:46.082 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-versions.bin (/home/cui/.gradle/caches/modules-2/metadata-2.16/module-versions.bin)
10:42:46.082 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-metadata.bin (/home/cui/.gradle/caches/modules-2/metadata-2.16/module-metadata.bin)
10:42:46.083 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-artifacts.bin (/home/cui/.gradle/caches/modules-2/metadata-2.16/module-artifacts.bin)
10:42:46.083 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache artifact-at-repository.bin (/home/cui/.gradle/caches/modules-2/metadata-2.16/artifact-at-repository.bin)
10:42:46.083 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on artifact cache (/home/cui/.gradle/caches/modules-2).
10:42:46.083 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Plugin Resolution Cache (/home/cui/.gradle/caches/2.14.1/plugin-resolution) was closed 0 times.
10:42:46.083 [DEBUG] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonManager] Stopping 0 compiler daemon(s).
10:42:46.083 [INFO] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonManager] Stopped 0 compiler daemon(s).
10:42:46.083 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has finished executing the build.
10:42:46.083 [DEBUG] [org.gradle.launcher.daemon.server.health.DaemonStatus] GC rate: 0.0/s
10:42:47.358 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientInputForwarder] Dispatching close input message: org.gradle.launcher.daemon.protocol.CloseInput@3c3d5449
10:42:47.358 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 13: dispatching class org.gradle.launcher.daemon.protocol.CloseInput
10:42:47.359 [INFO] [org.gradle.launcher.daemon.client.DaemonClient] Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':initFreeline'.] from daemon DaemonInfo{pid=16112, address=[249a1f21-c359-491c-9204-607a0061c072 port:53797, addresses:[/0:0:0:0:0:0:0:1%lo, /127.0.0.1]], idle=true, lastBusy=1487558530999, context=DefaultDaemonContext[uid=07a8b67b-7b1b-4ed7-a926-e41540ef07c1,javaHome=/home/cui/ide/java/jdk1.8.0_122,daemonRegistryDir=/home/cui/.gradle/daemon,pid=16112,idleTimeout=10800000,daemonOpts=-Xmx2048m,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant]} (build should be done).
10:42:47.359 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: dispatching class org.gradle.launcher.daemon.protocol.Finished
10:42:47.360 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: connection stop

```

**Comment by conncui** [comment]
```
10:42:45.917 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':initFreeline'
10:42:45.917 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':initFreeline' is up-to-date
10:42:45.917 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':initFreeline' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
10:42:45.917 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':initFreeline'.
10:42:45.917 [QUIET] [system.out] Freeline initial process start...
10:42:45.972 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@3b99ac5c5 pairs: {GET /api/versions/latest HTTP/1.1: null}{User-Agent: Java/1.8.0_122-ea}{Host: www.freelinebuild.com}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
10:42:45.998 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@6dc36a4c8 pairs: {null: HTTP/1.1 200 OK}{Server: Tengine}{Date: Mon, 20 Feb 2017 02:42:47 GMT}{Content-Type: application/json; charset=utf-8}{Content-Length: 252}{Connection: keep-alive}{x-powered-by: Express}{etag: W/"fc-833d9d12"}
10:42:45.999 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.oldresult.TransientConfigurationResultsBuilder] Loaded resolved configuration results (0.0 secs) from Binary store in /tmp/gradle2604735562755744071.bin
10:42:46.000 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':initFreeline'
10:42:46.000 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :initFreeline FAILED
10:42:46.001 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :initFreeline (Thread[Task worker,5,main]) completed. Took 0.085 secs.
10:42:46.001 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Task worker,5,main]] finished, busy: 0.085 secs, idle: 0.0 secs
10:42:46.002 [ERROR] [org.gradle.BuildExceptionReporter] 
10:42:46.002 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
10:42:46.002 [ERROR] [org.gradle.BuildExceptionReporter] 
10:42:46.002 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
10:42:46.002 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':initFreeline'.
10:42:46.003 [ERROR] [org.gradle.BuildExceptionReporter] > Could not initialize class com.antfortune.freeline.versions.StaticVersionComparator
10:42:46.003 [ERROR] [org.gradle.BuildExceptionReporter] 
10:42:46.003 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
10:42:46.079 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':initFreeline'.
10:42:46.079 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
10:42:46.079 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
10:42:46.079 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.antfortune.freeline.versions.StaticVersionComparator
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at com.antfortune.freeline.FreelineDownloader.isFreelineGradleVersionNeedToBeUpdated(FreelineDownloader.groovy:201)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at com.antfortune.freeline.FreelineDownloader.checkVersion(FreelineDownloader.groovy:182)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at com.antfortune.freeline.FreelineDownloader.fetchData(FreelineDownloader.groovy:134)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at com.antfortune.freeline.FreelineDownloader.execute(FreelineDownloader.groovy:45)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at com.antfortune.freeline.FreelineDownloader$execute.call(Unknown Source)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at com.antfortune.freeline.FreelineInitializer.initFreeline(FreelineInitializer.groovy:16)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at com.antfortune.freeline.FreelineInitializer$initFreeline.call(Unknown Source)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at com.antfortune.freeline.FreelinePlugin$_apply_closure2.doCall(FreelinePlugin.groovy:38)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:590)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:571)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter]        ... 14 more
10:42:46.080 [ERROR] [org.gradle.BuildExceptionReporter] 
10:42:46.080 [LIFECYCLE] [org.gradle.BuildResultLogger] 
10:42:46.080 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
10:42:46.080 [LIFECYCLE] [org.gradle.BuildResultLogger] 
10:42:46.080 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 2.04 secs
10:42:46.082 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache task history cache (/home/cui/work/oschinagit/AndroidProject/.gradle/2.14.1/taskArtifacts) was closed 0 times.
10:42:46.082 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 1 (avg: 0.0 secs, total: 0.0 secs)
10:42:46.082 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 28 (avg: 0.0 secs, total: 0.007 secs)
10:42:46.082 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.ResolutionResultsStoreFactory] Deleted 2 resolution results binary files in 0.0 secs
10:42:46.082 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedRepositoryFactory] In-memory dependency metadata cache closed. Repos cached: 147, cache instances: 6, modules served from cache: 1970, artifacts: 657
10:42:46.082 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Generated Gradle JARs cache (/home/cui/.gradle/caches/2.14.1/generated-gradle-jars) was closed 0 times.
10:42:46.082 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-versions.bin (/home/cui/.gradle/caches/modules-2/metadata-2.16/module-versions.bin)
10:42:46.082 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-metadata.bin (/home/cui/.gradle/caches/modules-2/metadata-2.16/module-metadata.bin)
10:42:46.083 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-artifacts.bin (/home/cui/.gradle/caches/modules-2/metadata-2.16/module-artifacts.bin)
10:42:46.083 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache artifact-at-repository.bin (/home/cui/.gradle/caches/modules-2/metadata-2.16/artifact-at-repository.bin)
10:42:46.083 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on artifact cache (/home/cui/.gradle/caches/modules-2).
10:42:46.083 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Plugin Resolution Cache (/home/cui/.gradle/caches/2.14.1/plugin-resolution) was closed 0 times.
10:42:46.083 [DEBUG] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonManager] Stopping 0 compiler daemon(s).
10:42:46.083 [INFO] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonManager] Stopped 0 compiler daemon(s).
10:42:46.083 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has finished executing the build.
10:42:46.083 [DEBUG] [org.gradle.launcher.daemon.server.health.DaemonStatus] GC rate: 0.0/s
10:42:47.358 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientInputForwarder] Dispatching close input message: org.gradle.launcher.daemon.protocol.CloseInput@3c3d5449
10:42:47.358 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 13: dispatching class org.gradle.launcher.daemon.protocol.CloseInput
10:42:47.359 [INFO] [org.gradle.launcher.daemon.client.DaemonClient] Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':initFreeline'.] from daemon DaemonInfo{pid=16112, address=[249a1f21-c359-491c-9204-607a0061c072 port:53797, addresses:[/0:0:0:0:0:0:0:1%lo, /127.0.0.1]], idle=true, lastBusy=1487558530999, context=DefaultDaemonContext[uid=07a8b67b-7b1b-4ed7-a926-e41540ef07c1,javaHome=/home/cui/ide/java/jdk1.8.0_122,daemonRegistryDir=/home/cui/.gradle/daemon,pid=16112,idleTimeout=10800000,daemonOpts=-Xmx2048m,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant]} (build should be done).
10:42:47.359 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: dispatching class org.gradle.launcher.daemon.protocol.Finished
10:42:47.360 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: connection stop

```
