### ISSUE TITLE
提示没有权限

### ISSUE THREAD

**Issue by lxhao** [alibaba/freeline#677]
用root用户执行也是一样的报错
```
Traceback (most recent call last):
  File "/home/lxhao/code/android/Vendor/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/home/lxhao/code/android/Vendor/freeline/freeline_core/gradle_clean_build.py", line 74, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "/home/lxhao/code/android/Vendor/freeline/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Comment by lomanyong** [comment]
@lxhao 执行`chmod +x gradlew`，是 gradlew 这个文件没有执行权限应该

**Comment by liruidong183** [comment]
windows提示这个错误怎么解决呢

**Comment by ktlsl** [comment]
windows提示这个错误怎么解决呢 +1
