### ISSUE TITLE
我修改activity_main.xml增量编译时有效的。但是修改java代码增量无效。

### ISSUE THREAD

**Issue by 2629312117** [alibaba/freeline#679]
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "I:\freelineproject\FreelineOkDemo\MyApplication\freeline_core\android_tools.py", line 344, in execute
    self._command.execute()
  File "I:\freelineproject\FreelineOkDemo\MyApplication\freeline_core\gradle_inc_build.py", line 186, in execute
    map(lambda command: command.execute(), self.command_list)
  File "I:\freelineproject\FreelineOkDemo\MyApplication\freeline_core\gradle_inc_build.py", line 186, in <lambda>
    map(lambda command: command.execute(), self.command_list)
  File "I:\freelineproject\FreelineOkDemo\MyApplication\freeline_core\gradle_inc_build.py", line 240, in execute
    self._invoker.run_dex_task()
  File "I:\freelineproject\FreelineOkDemo\MyApplication\freeline_core\android_tools.py", line 627, in run_dex_task
    self.debug('dex exec: ' + ' '.join(dex_args))
TypeError: sequence item 0: expected string, NoneType found

[ERROR] --------------------------------------------------------
[ERROR] incremental build task failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 1.3s
[DEBUG] Total time: 1.5s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@2629312117 你应该是使用了不一样的 android sdk，将sdk版本改为正常版本即可...

**Comment by 2629312117** [comment]
apply plugin: 'com.android.application'
apply plugin: 'com.antfortune.freeline'
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"
    defaultConfig {
        applicationId "com.example.ltech.myapplication"
        minSdkVersion 23
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
//    buildTypes {
//        release {
//            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
//        }
//    }

    lintOptions {
        abortOnError false
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    compile 'com.android.support:appcompat-v7:23.2.1'

    testCompile 'com.antfortune.freeline:gradle:0.8.6'


}           请问下：我已经用23的sdk，我要怎么修改修改
