### ISSUE TITLE
mac 电脑集成碰到的问题  No such file or directory

### ISSUE THREAD

**Issue by mcdonaldLiu** [alibaba/freeline#681]
[INFO] preparing for tasks...
[-][read_project_info_task] failed. in 0.0s
[-][generate_file_stat_task] finished. in 0.2s
[-][gradle_clean_build_task] failed. in 0s
[-][clean_all_cache_task] failed. in 0s
[-][install_apk_task] failed. in 0s
[-][build_base_resource_task] failed. in 0s
[-][generate_project_info_task] failed. in 0s
[-][generate_apt_files_task] failed. in 0s
[-][append_file_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "/Users/berlin/Downloads/Android/project/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/Users/berlin/Downloads/Android/project/freeline/freeline_core/gradle_clean_build.py", line 74, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "/Users/berlin/Downloads/Android/project/freeline/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
上面是命令行输入:python freeline.py -f之后输出的结果，不知道哪里出问题了，麻烦看一下，不甚感激

**Comment by lomanyong** [comment]
@mcdonaldLiu 复制一个 gradlew 文件过来即可，或者配置成使用系统的gradle命令，自己添加 buildScript

**Comment by candledragle** [comment]
I encounter the problem too ,thx very much
