### ISSUE TITLE
[ERROR] build failed with script: gradlew.bat :app:assembleDebug -P freelineBuild=true --stacktrace

### ISSUE THREAD

**Issue by zouzhenglu** [alibaba/freeline#682]
inject: D:\worksapce\code\work\hxy\Hxy\app\build\intermediates\classes\debug\com\xx\hxy\biz\gm\AppManager.class
        at com.android.dx.merge.InstructionTransformer.transform(InstructionTransformer.java:50)
        at com.android.dx.merge.DexMerger.transformCode(DexMerger.java:830)
        at com.android.dx.merge.DexMerger.transformMethods(DexMerger.java:804)
        at com.android.dx.merge.DexMerger.transformClassData(DexMerger.java:777)
        at com.android.dx.merge.DexMerger.transformClassDef(DexMerger.java:673)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:527)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:167)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:191)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:522)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:344)
        at com.android.dx.command.dexer.Main.run(Main.java:292)
        at com.android.builder.internal.compiler.DexWrapper.run(DexWrapper.java:54)
        at com.android.builder.core.DexByteCodeConverter.lambda$dexInProcess$0(DexByteCodeConverter.java:173)

有用到multidex，但是没有自己另外做处理，用as自带的运行没问题，

**Comment by zouzhenglu** [comment]
inject: D:\worksapce\code\work\Hxy2\app\build\intermediates\classes\debug\com\xx\hxy\module\main\home\ask\services\VoiceStreamPlayer.class
        at com.android.dx.merge.DexMerger.transformMethods(DexMerger.java:804)
        at com.android.dx.merge.DexMerger.transformClassData(DexMerger.java:777)
        at com.android.dx.merge.DexMerger.transformClassDef(DexMerger.java:673)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:527)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:167)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:191)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:522)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:344)
        at com.android.dx.command.dexer.Main.run(Main.java:292)
        at com.android.builder.internal.compiler.DexWrapper.run(DexWrapper.java:54)
        at com.android.builder.core.DexByteCodeConverter.lambda$dexInProcess$0(DexByteCodeConverter.java:173)

折腾了几次，都是类似这样的异常，项目本身是可以运行的。运行其他简单的项目能用
