### ISSUE TITLE
Exception in thread "main" java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by VeHan** [alibaba/freeline#689]
hanweiweideMacBook-Pro:yourenandroid hanweiwei$ python freeline.py  
[WARNING] some important file missed, a clean build will be automatically executed.
[-][read_project_info_task] failed. in 623.3s
[-][generate_file_stat_task] finished. in 0.1s
[-][gradle_clean_build_task] failed. in 0s
[-][clean_all_cache_task] failed. in 0s
[-][install_apk_task] failed. in 0s
[-][build_base_resource_task] failed. in 0s
[-][generate_project_info_task] failed. in 0s
[-][generate_apt_files_task] failed. in 0s
[-][append_file_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)
        at org.gradle.wrapper.Install.unzip(Install.java:214)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

[ERROR] --------------------------------------------------------
[ERROR] freeline failed when read project info with script: ./gradlew -q checkBeforeCleanBuild
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 2.2s
[DEBUG] Task engine running time: 623.3s
[DEBUG] Total time: 625.4s
[DEBUG] --------------------------------------------------------
hanweiweideMacBook-Pro:yourenandroid hanweiwei$ python freeline.py  

[WARNING] some important file missed, a clean build will be automatically executed.
[-][read_project_info_task] failed. in 0.4s
[-][generate_file_stat_task] finished. in 0.1s
[-][gradle_clean_build_task] failed. in 0s
[-][clean_all_cache_task] failed. in 0s
[-][install_apk_task] failed. in 0s
[-][build_base_resource_task] failed. in 0s
[-][generate_project_info_task] failed. in 0s
[-][generate_apt_files_task] failed. in 0s
[-][append_file_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)
        at org.gradle.wrapper.Install.unzip(Install.java:214)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

[ERROR] --------------------------------------------------------
[ERROR] freeline failed when read project info with script: ./gradlew -q checkBeforeCleanBuild
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 2.2s
[DEBUG] Task engine running time: 0.4s
[DEBUG] Total time: 2.6s
[DEBUG] --------------------------------------------------------
hanweiweideMacBook-Pro:yourenandroid hanweiwei$ python freeline.py  
[INFO] preparing for tasks...
[-][read_project_info_task] failed. in 0.2s
[-][generate_file_stat_task] finished. in 0.1s
[-][gradle_clean_build_task] failed. in 0s
[-][clean_all_cache_task] failed. in 0s
[-][install_apk_task] failed. in 0s
[-][build_base_resource_task] failed. in 0s
[-][generate_project_info_task] failed. in 0s
[-][generate_apt_files_task] failed. in 0s
[-][append_file_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)
        at org.gradle.wrapper.Install.unzip(Install.java:214)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

[ERROR] --------------------------------------------------------
[ERROR] freeline failed when read project info with script: ./gradlew -q checkBeforeCleanBuild
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 1.5s
[DEBUG] Task engine running time: 0.2s
[DEBUG] Total time: 1.8s
[DEBUG] --------------------------------------------------------
hanweiweideMacBook-Pro:yourenandroid hanweiwei$ python freeline.py  
[INFO] preparing for tasks...
[-][read_project_info_task] failed. in 0.7s
[-][generate_file_stat_task] finished. in 0.1s
[-][gradle_clean_build_task] failed. in 0s
[-][clean_all_cache_task] failed. in 0s
[-][install_apk_task] failed. in 0s
[-][build_base_resource_task] failed. in 0s
[-][generate_project_info_task] failed. in 0s
[-][generate_apt_files_task] failed. in 0s
[-][append_file_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)
        at org.gradle.wrapper.Install.unzip(Install.java:214)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

[ERROR] --------------------------------------------------------
[ERROR] freeline failed when read project info with script: ./gradlew -q checkBeforeCleanBuild
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.9s
[DEBUG] Task engine running time: 0.7s
[DEBUG] Total time: 1.6s
[DEBUG] --------------------------------------------------------
hanweiweideMacBook-Pro:yourenandroid hanweiwei$

**Comment by VeHan** [comment]
好吧，这是因为我的gradle环境有问题，现在已经OK了
