### ISSUE TITLE
Freeline server in app "package name" not found. Please make sure your application is properly running in your device.

### ISSUE THREAD

**Issue by mabinbib** [alibaba/freeline#691]
前提：前段时间还可以用，昨天开始无法使用。
运行条件：
1.手机上无apk
2.执行 python freeline.py -f 成功
但是之后编译执行 python freeline.py 就出现  Freeline server in app "package name" not found. Please make sure your application is properly running in your device. 这样的问题。
排除：手机连接无问题；
＃152 解决方法测试无法解决；
重启无法解决。

**Comment by lomanyong** [comment]
@mabinbib 手机尝试卸载apk看下，可以看下logcat是否有相关的错误日志，可以贴出来一看

**Comment by mabinbib** [comment]
@lomanyong   3-03 17:39:22.831 32608-32649/com.sgcc.cs:freeline E/Freeline: java.lang.NumberFormatException: Invalid long: "${placeholder}"
                                                                    at java.lang.Long.invalidLong(Long.java:124)
                                                                    at java.lang.Long.parse(Long.java:363)
                                                                    at java.lang.Long.parseLong(Long.java:353)
                                                                    at java.lang.Long.parseLong(Long.java:321)
                                                                    at com.antfortune.freeline.FreelineCore.getApkBuildFlag(FreelineCore.java:166)
                                                                    at com.antfortune.freeline.router.schema.CheckSyncSchema.handle(CheckSyncSchema.java:28)
                                                                    at com.antfortune.freeline.router.Router.dispatch(Router.java:48)
                                                                    at com.antfortune.freeline.server.LongLinkServer.handle(LongLinkServer.java:55)
                                                                    at com.antfortune.freeline.server.EmbedHttpServer.run(EmbedHttpServer.java:95)
                                                                    at java.lang.Thread.run(Thread.java:818)
03-03 17:39:22.831 32608-32649/com.sgcc.cs:freeline I/Freeline: ext:${placeholder}

**Comment by mabinbib** [comment]
@lomanyong

**Comment by lomanyong** [comment]
@mabinbib 文件没有被替换成功，`gradle clean`一下之后是否可以正常呢？是否是使用Freeline编译的呢？

这个问题在使用 AS 编译的时候可能会出现

**Comment by mabinbib** [comment]
@lomanyong  是不是应用退出后就必须重新全量编译。

**Comment by lomanyong** [comment]
@mabinbib 并没有这么一说，可能是进程被杀了导致无法连接上，你可以手动启动app也可以

**Comment by mabinbib** [comment]
@lomanyong 我测试别的应用无这个问题，单独这个有，没办法，禁用了。别的程序用freeline

**Comment by mabinbib** [comment]
先关闭问题吧，如果再遇到别的问题我再反馈。
