### ISSUE TITLE
在 Nexus5X 7.0系统的模拟器上经常报java.lang.NoSuchMethodError: No static method lambdaFactory异常

### ISSUE THREAD

**Issue by fengminchao** [alibaba/freeline#694]
用的是retroLambda,崩溃的地方我一直没修改过代码，修改其他代码增量编译运行的时候经常报这个异常，现在平均4次增量编译就会报这个异常，然后不得不重新全量编译。

```
03-03 11:48:53.560 17498-17498/net.muxi.huashiapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: net.muxi.huashiapp, PID: 17498
                                                                    java.lang.NoSuchMethodError: No static method lambdaFactory$(Lnet/muxi/huashiapp/ui/schedule/TimetableFragment;)Lrx/functions/Action1; in class Lnet/muxi/huashiapp/ui/schedule/TimetableFragment$$Lambda$4; or its super classes (declaration of 'net.muxi.huashiapp.ui.schedule.TimetableFragment$$Lambda$4' appears in /data/user/0/net.muxi.huashiapp/cache/temp/dex/merged.apk)
                                                                        at net.muxi.huashiapp.ui.schedule.TimetableFragment.initListener(TimetableFragment.java:155)
                                                                        at net.muxi.huashiapp.ui.schedule.TimetableFragment.onCreateView(TimetableFragment.java:110)
                                                                        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2184)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1298)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1523)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1585)
                                                                        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2832)
                                                                        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
                                                                        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:603)
                                                                        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:181)
                                                                        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
                                                                        at android.app.Activity.performStart(Activity.java:6681)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2609)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by lomanyong** [comment]
@fengminchao 是否可以给出可以复现问题的sample工程呢？

**Comment by fengminchao** [comment]
刚刚把 Freeline从0.8.5升级到0.8.6 又不报这个异常了。。不清楚是不是版本的原因
