### ISSUE TITLE
gradlew initFreeline -Pmirror 报错

### ISSUE THREAD

**Issue by MrHangVIP** [alibaba/freeline#701]
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: /Users/songzhihang/.gradle/wrapper/dists/gradle-2.14.1-all/8bnwg5hd3w55iofp58khbp6yv/gradle-2.14.1-all.zip
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by lomanyong** [comment]
@MrHangVIP 本地 gradle 环境的问题...可以先解决自己本地的问题..

**Comment by MrHangVIP** [comment]
已经解决了。谢谢
