### ISSUE TITLE
Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by xuchenchen** [alibaba/freeline#717]
执行python freeline.py -f后正常编译安装，修改完代码后时间稍微长一些再执行python freeline.py就报错：[DEBUG] [merge_dex_task] merge_dex_task finish in 0.4s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 18.2s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 18.2s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 16.4s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 18.2s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------

java.lang.UnsupportedClassVersionError: com/android/dx/merge/DexMerger : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(Unknown Source)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$000(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
Could not find the main class: com.android.dx.merge.DexMerger. Program will exit.
Exception in thread "main"
[ERROR] --------------------------------------------------------
[ERROR] merge dex failed: java -jar freeline\release-tools\DexMerge.jar E:\XXX\build\freeline\freeline
dexes\merged.dex E:\XXX\build\freeline\XXX\dex\classes.dex E:\XXX\build\freeline\XXX\dex\classes.dex
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.6s
[DEBUG] Task engine running time: 18.2s
[DEBUG] Total time: 18.8s
[DEBUG] --------------------------------------------------------
错误日志如上，为保护代码隐私，地址部分用XXX代替了下，使用studio为2.3版本，freeline为最新版本0.8.6，Python版本为2.7.9，希望能及时给予帮助谢谢

**Comment by lomanyong** [comment]
@xuchenchen 你使用的 java 版本是？切换一下版本是否正常？这个是java环境问题导致的...

**Comment by xuchenchen** [comment]
我考虑过可能是版本问题，但是我studioSDKLocation中JDKLocation用的是jdk1.8.0_101版本
![image](https://cloud.githubusercontent.com/assets/5358531/23928566/60bbdffc-095b-11e7-9b48-51a82ca44f4d.png)
![image](https://cloud.githubusercontent.com/assets/5358531/23928628/bd16eeae-095b-11e7-819e-92ea45844b59.png)

**Comment by lomanyong** [comment]
@xuchenchen 不是AS的java版本，是你本地的java版本，使用`java -version`输出
