### ISSUE TITLE
windows上多次（第二次开始）initFreeline就有这个错误

### ISSUE THREAD

**Issue by zhoujianhanyu** [alibaba/freeline#72]
Freeline init process start...
Downloading lastest release from https://github.com/alibaba/freeline/releases/download/0.5.5/freeline-v0.5.5.zip
Please wait a minute...      
:initFreeline FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':initFreeline'.
> java.lang.ClassCastException: org.apache.xerces.parsers.XIncludeAwareParserConfiguration cannot be cast to org.apache.xerces.xni.parser.XMLParserConfiguration

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':initFreeline'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: : java.lang.ClassCastException: org.apache.xerces.parsers.XIncludeAwareParserConfiguration cannot be cast to org.apache.xerces.xni.parser.XMLParserConfiguration
        at com.antfortune.freeline.FreelineInitializer.initFreeline(FreelineInitializer.groovy:40)
        at com.antfortune.freeline.FreelineInitializer$initFreeline.call(Unknown Source)
        at com.antfortune.freeline.FreelinePlugin$_apply_closure1.doCall(FreelinePlugin.groovy:19)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:590)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:571)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more
Caused by: java.lang.ClassCastException: org.apache.xerces.parsers.XIncludeAwareParserConfiguration cannot be cast to org.apache.xerces.xni.parser.XMLParserConfiguration
        at org.apache.xerces.parsers.SAXParser.<init>(Unknown Source)
        at org.apache.xerces.parsers.SAXParser.<init>(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.<init>(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl.<init>(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserFactoryImpl.newSAXParser(Unknown Source)
        at org.apache.tools.ant.util.JAXPUtils.newSAXParser(JAXPUtils.java:217)
        at org.apache.tools.ant.util.JAXPUtils.getNamespaceXMLReader(JAXPUtils.java:174)
        at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:245)
        at org.apache.tools.ant.helper.ProjectHelper2.parseUnknownElement(ProjectHelper2.java:131)
        at org.apache.tools.ant.helper.ProjectHelper2.parseAntlibDescriptor(ProjectHelper2.java:111)
        at org.apache.tools.ant.taskdefs.Antlib.createAntlib(Antlib.java:94)
        at org.apache.tools.ant.taskdefs.Definer.loadAntlib(Definer.java:425)
        at org.apache.tools.ant.taskdefs.Definer.execute(Definer.java:277)
        at org.apache.tools.ant.ComponentHelper.checkNamespace(ComponentHelper.java:874)
        at org.apache.tools.ant.ComponentHelper.getDefinition(ComponentHelper.java:307)
        at org.apache.tools.ant.ComponentHelper.createComponent(ComponentHelper.java:284)
        at org.apache.tools.ant.ComponentHelper.createComponent(ComponentHelper.java:263)
        at org.apache.tools.ant.UnknownElement.makeObject(UnknownElement.java:430)
        at org.apache.tools.ant.UnknownElement.maybeConfigure(UnknownElement.java:164)
        ... 23 more

BUILD FAILED

Total time: 2.467 secs

**Comment by lomanyong** [comment]
@zhoujianhanyu gradle版本是多少的呢？

**Comment by zhoujianhanyu** [comment]
@lomanyong gradle的版本是2.14.1，好像我改了版本号也没用。mac上没有问题。

**Comment by lomanyong** [comment]
@zhoujianhanyu 我这里还是没有复现，是否可以提供更多信息，或者稳定的复现步骤呢？

**Comment by zhoujianhanyu** [comment]
@lomanyong我用最新版本就没问题了，不好意思没及时告知你们。

**Comment by lomanyong** [comment]
@zhoujianhanyu 好的， 欢迎继续给我们反馈哈~

**Comment by zhoujianhanyu** [comment]
@lomanyong 嗯，好。
