### ISSUE TITLE
-f全编译报错，但是run可运行

### ISSUE THREAD

**Issue by nevergoneok** [alibaba/freeline#724]
at com.android.dx.merge.DexMerger.merge(DexMerger.java:191)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:522)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:344)
        at com.android.dx.command.dexer.Main.run(Main.java:292)
        at com.android.builder.internal.compiler.DexWrapper.run(DexWrapper.java:54)
        at com.android.builder.core.DexByteCodeConverter.lambda$dexInProcess$0(DexByteCodeConverter.java:173)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:191)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:522)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:344)
        at com.android.dx.command.dexer.Main.run(Main.java:292)
        at com.android.builder.internal.compiler.DexWrapper.run(DexWrapper.java:54)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:191)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:522)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:344)
        at com.android.dx.command.dexer.Main.run(Main.java:292)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:191)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:522)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:344)
        at com.android.dx.command.dexer.Main.run(Main.java:292)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:191)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:522)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:344)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:191)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:522)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:344)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:191)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:522)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:344)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:191)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:522)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:191)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:522)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:522)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:344)
        at com.android.builder.core.DexByteCodeConverter.lambda$dexInProcess$0(DexByteCodeConverter.java:173)

**Comment by lomanyong** [comment]
@nevergoneok 日志不完整...请提供完整一点的日志
