### ISSUE TITLE
修改了布局文件后，编译出现UnicodeDecodeError: 'utf8' codec can't decode byte 0xd5 in position 11406: invalid continuation byte

### ISSUE THREAD

**Issue by z360394624** [alibaba/freeline#728]
是否是因为布局文件中有中文字符串导致此问题。修改class文件是没有问题，正常运行编译的。
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "D:\development\workspaces\as\Pro\freeline_core\task.py", line 123, in execute
    self.task.execute()
  File "D:\development\workspaces\as\Pro\freeline_core\gradle_inc_build.py", line 164, in execute
    self._invoker.process_databinding(self._original_changed_files, self._changed_files_ref)
  File "D:\development\workspaces\as\Pro\freeline_core\gradle_inc_build.py", line 341, in process_databinding
    output_layoutinfo_dir))
  File "D:\development\workspaces\as\Pro\freeline_core\gradle_tools.py", line 839, in extract_related_java_files
    result = self.process_layout_info(fpath)
  File "D:\development\workspaces\as\Pro\freeline_core\gradle_tools.py", line 871, in process_layout_info
    tree = ET.ElementTree(ET.fromstring(remove_namespace(fpath)))
  File "D:\development\workspaces\as\Pro\freeline_core\utils.py", line 155, in remove_namespace
    content = get_file_content(path)
  File "D:\development\workspaces\as\Pro\freeline_core\utils.py", line 114, in get_file_content
    return f.read()
  File "D:\development\python\lib\codecs.py", line 686, in read
    return self.reader.read(size)
  File "D:\development\python\lib\codecs.py", line 492, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd5 in position 11406: invalid continuation byte

**Comment by lomanyong** [comment]
@z360394624 应该有存在不支持的中文/特殊字符...
