### ISSUE TITLE
win平台为啥老是报这个build failed with script: gradlew.bat :sFBestAndroid:assembleDebug -P freelineBuild=true --stacktrace？？？、试了好多次都不行

### ISSUE THREAD

**Issue by Zzzzzz123** [alibaba/freeline#729]
find resource path: D:\codecode\viewPagerIndicatorlibrary\build\intermediates\bundles\default\assets

        at com.antfortune.freeline.FreelinePlugin$_addFreelineGeneratedFiles_closure5.doCall(FreelinePlugin.groovy:386)
        at com.antfortune.freeline.FreelinePlugin.addFreelineGeneratedFiles(FreelinePlugin.groovy:381)
        at com.antfortune.freeline.FreelinePlugin$_apply_closure4$_closure13$_closure17.doCall(FreelinePlugin.groovy:142)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:596)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:577)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 70 more

[ERROR] --------------------------------------------------------
[ERROR] build failed with script: gradlew.bat :sFBestAndroid:assembleDebug -P freelineBuild=true --stacktrace

**Comment by wanyt** [comment]
在主工程的build.gradle里面添加：

`android {
    .......
    dexOptions {
        javaMaxHeapSize "4g"
    }

}`

然后再试试

**Comment by lomanyong** [comment]
@Zzzzzz123 没有具体的stacktrace？

**Comment by Zzzzzz123** [comment]
aused by: java.io.IOException: 远程主机强迫关闭了一个现有的连接。                                                                                                     
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketInputStream.read(SocketConnection.java:176)
        at com.esotericsoftware.kryo.io.Input.fill(Input.java:139)
没啊，这就是全部了，

**Comment by shitou19891006** [comment]
我也遇到相同的问题了，请问你解决了没有啊？解决了可以告诉怎么解决的吗
