### ISSUE TITLE
python脚本出错

### ISSUE THREAD

**Issue by friends110110** [alibaba/freeline#736]
0.8.5版本   gradle initFreeline -PfreelineVersion=0.8.5能成功   执行 python freeline.py -f 报以下错误， 
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "D:\Android\projects\Develop_Branch\freeline_core\task.py", line 123, in execut
e
    self.task.execute()
  File "D:\Android\projects\Develop_Branch\freeline_core\gradle_clean_build.py", line
74, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "D:\Android\projects\Develop_Branch\freeline_core\utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "D:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "D:\Python27\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2]

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------

**Comment by lxz2014** [comment]
我也报这错误！！！！！！

**Comment by lomanyong** [comment]
@friends110110 @lxz2014 这都是已有issue，可以搜索一下，跟你本地环境相关
