### ISSUE TITLE
[options] 未与 -source 1.7

### ISSUE THREAD

**Issue by HpWens** [alibaba/freeline#754]
项目中集成了微信的热修复tinker
第一次编译要10分钟，然后编译就提示以下错误：
警告: [options] 未与 -source 1.7 一起设置引导类路径
注: Creating file:/F:/MiGuProject/app/build/generated/source/apt/defaultBuild/debug/com/hisunflytone/cmdm/MgdmApplication.java

注释处理程序抛出未捕获的异常错误。
有关详细信息, 请参阅以下堆栈跟踪。
java.lang.IllegalArgumentException
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
at dagger.internal.codegen.SimpleAnnotationMirror.of(SimpleAnnotationMirror.java:55)
at dagger.internal.codegen.Scope.singletonScope(Scope.java:87)

**Comment by lomanyong** [comment]
@HpWens 最好能够贴出完整的日志...与tinker一起集成没啥问题...不少用户都用了tinker

**Comment by HpWens** [comment]
注释处理程序抛出未捕获的异常错误。
有关详细信息, 请参阅以下堆栈跟踪。
java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
        at dagger.internal.codegen.SimpleAnnotationMirror.of(SimpleAnnotationMirror.java:55)
        at dagger.internal.codegen.Scope.singletonScope(Scope.java:87)
        at dagger.internal.codegen.BindingGraphValidator$Validation.validateDependencyScopes(BindingGraphValidator.java:634)
        at dagger.internal.codegen.BindingGraphValidator$Validation.validateSubgraph(BindingGraphValidator.java:166)
        at dagger.internal.codegen.BindingGraphValidator.validate(BindingGraphValidator.java:1146)
        at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:138)
        at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:46)
        at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:318)
        at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:171)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1173)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:859)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        at com.sun.tools.javac.main.Main.compile(Main.java:381)
        at com.sun.tools.javac.main.Main.compile(Main.java:370)
        at com.sun.tools.javac.main.Main.compile(Main.java:361)
        at com.sun.tools.javac.Main.compile(Main.java:56)
        at com.sun.tools.javac.Main.main(Main.java:42)

[ERROR] --------------------------------------------------------
[ERROR] incremental javac compile failed.

**Comment by lomanyong** [comment]
@HpWens 不够完整呀...从日志来看应该跟Freeline没啥关系，主要是dagger的问题
