### ISSUE TITLE
databinding初次编译出错 使用gradle:2.3.0 freeline:0.8.7

### ISSUE THREAD

**Issue by EasonHolmes** [alibaba/freeline#757]
process databinding error: Source '/Users/cuiyang/Documents/work/works/newCompany/ddcarcompany/app/src/main/res/android/databinding' exists but is a directory

java.io.IOException: Source '/Users/cuiyang/Documents/work/works/newCompany/ddcarcompany/app/src/main/res/android/databinding' exists but is a directory
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1077)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
        at android.databinding.tool.LayoutXmlProcessor$1.processOtherFile(LayoutXmlProcessor.java:172)
        at android.databinding.tool.LayoutXmlProcessor.processAllInputFiles(LayoutXmlProcessor.java:126)
        at android.databinding.tool.LayoutXmlProcessor.processResources(LayoutXmlProcessor.java:219)
        at com.antfortune.freeline.databinding.ProcessLayouts.run(ProcessLayouts.java:23)
        at com.antfortune.freeline.databinding.CliMain.main(CliMain.java:113)

[ERROR] --------------------------------------------------------
[ERROR] process module databinding failed: java -jar freeline/release-tools/databinding-cli8.jar -p com.ddcar.company -i /Users/cuiyang/Documents/work/works/newCompany/ddcarcompany/app/src/main/res -o /Users/cuiyang/Documents/work/works/newCompany/ddcarcompany/app/build/freeline/freeline-databinding/app/76912259c3a7f6705d1b60ee186b5620/res -d /Users/cuiyang/Documents/work/works/newCompany/ddcarcompany/app/build/freeline/freeline-databinding/merged_layoutinfo -c /Users/cuiyang/Documents/work/works/newCompany/ddcarcompany/app/build/freeline/freeline-databinding/app/76912259c3a7f6705d1b60ee186b5620/java -l false -v 17 -s /Users/cuiyang/Documents/work/sdk/android-sdk-macosx

**Comment by lomanyong** [comment]
@EasonHolmes 暂不处理跟DataBinding相关的问题...
