### ISSUE TITLE
0.8.6编译正常，为何升级0.8.7后编译报错？

### ISSUE THREAD

**Issue by xingyuetianyu** [alibaba/freeline#758]
0.8.7错误 0.8.6正常
1. 
 What went wrong:
xecution failed for task ':app-android:compileDebugJavaWithJavac'.
 Compilation failed; see the compiler error output for details.

 Try:
un with --info or --debug option to get more log output.

 Exception is:
rg.gradle.api.tasks.TaskExecutionException: Execution failed for task ':xxapp-android:compileDebugJavaWithJavac'.
       at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
       at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
       at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
       at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
       at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
       at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
       at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
       at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
       at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
       at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
       at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
       at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
       at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
       at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
       at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
aused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
       at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:47)
       at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
       at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:101)
       at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
       at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
       at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
       at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
       at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:157)
       at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:139)
       at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
       at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
       at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
       at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:244)
       at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
       at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:231)
       at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
       at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
       at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
       ... 14 more

==========================================
**2.**
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: 
                  java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: 
                  org.gradle.process.internal.ExecException: Process 'command 'E:\Program Files\Java\jdk1.7.0_80\bin\java.exe''   finished with non-zero exit value 3

**Comment by lomanyong** [comment]
@xingyuetianyu `see the compiler error output for details.`这个是java编译错误吧，应该有具体的编译错误信息的...

**Comment by xingyuetianyu** [comment]
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: 
                  java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: 
                  org.gradle.process.internal.ExecException: Process 'command 'E:\Program Files\Java\jdk1.7.0_80\bin\java.exe''   finished with non-zero exit value 3

这个错误呢
升级后就报这个错误了

**Comment by lomanyong** [comment]
@xingyuetianyu 可以确认回退后正常吗？以及是否可以提供更加完整的堆栈日志呢？

**Comment by xingyuetianyu** [comment]
昨天刚回退了，回退正常，现在就是使用的0.8.6的版本，0.8.6正常使用
日志只能升级后才有，我再升级看看具体日志吧

能给个新的 微信群号吗， 之前看到的过期了，谢谢！

**Comment by lomanyong** [comment]
@xingyuetianyu 后面会建个QQ群更加方便点...可以关注一下README...

**Comment by xingyuetianyu** [comment]
好的，谢谢
我先升级下，看看0.8.7的版本日志

**Comment by xingyuetianyu** [comment]
0.8.7   
“如果第一次运行的时候出现了耗时长达十几分钟的话，需要注意一下是否卡在下载 gradle 文件了。检查的方法即手动执行 gradlew checkBeforeCleanBuild” 这个命令执行过了，很快执行好了”

但是执行  python freeline.py -f 命令时 

[DEBUG] [gradle_clean_build_task] Gradle build task is running, please wait a

卡在这里差不多一个小时了，求解

**Comment by xingyuetianyu** [comment]
0.8.7的错误日志： 求解
Caused by: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_05\bin\java.
exe'' finished with non-zero exit value 3
        at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:43)
        at com.android.builder.core.AndroidBuilder$3.call(AndroidBuilder.java:1538)
        at com.android.builder.core.AndroidBuilder$3.call(AndroidBuilder.java:1531)
Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_05\bin\java.exe'' finished with non-zero exit value 3
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:367)
        at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:41)
        ... 2 more


[ERROR] --------------------------------------------------------
[ERROR] build failed with script: gradlew.bat assembleDebug -P freelineBuild=true --stacktrace
[ERROR] --------------------------------------------------------

就这么多日志
