### ISSUE TITLE
全量编译时，报错ClassNotFoundException

### ISSUE THREAD

**Issue by xingyuetianyu** [alibaba/freeline#767]
手机        vivo X5Max L  
系统版本 4.4.4 

java.lang.RuntimeException: Unable to instantiate application com.antfortune.freeline.FreelineApplication: java.lang.ClassNotFoundException: Didn't find class "com.antfortune.freeline.FreelineApplication" on path: DexPathList[[zip file "/data/app/com.xx.app-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.xx.app-1, /vendor/lib, /system/lib]]
 at android.app.LoadedApk.makeApplication(LoadedApk.java:507)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4440)
at android.app.ActivityThread.access$1500(ActivityThread.java:140)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1262)
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5143)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
at dalvik.system.NativeStart.main(Native Method)

 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.antfortune.freeline.FreelineApplication" on path: DexPathList[[zip file "/data/app/com.xx.app-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.xx.app-1, /vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
 at android.app.Instrumentation.newApplication(Instrumentation.java:977)
 at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4440) 
 at android.app.ActivityThread.access$1500(ActivityThread.java:140) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1262) 
 at android.os.Handler.dispatchMessage(Handler.java:102) 
 at android.os.Looper.loop(Looper.java:136) 
 at android.app.ActivityThread.main(ActivityThread.java:5143) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:515) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602) 
 at dalvik.system.NativeStart.main(Native Method)

**Comment by xingyuetianyu** [comment]
同一个项目，小米手机可以是可以增长全量和增量的
但是换成 vivo 手机 就报上面的错误了

**Comment by sivan67** [comment]
我的也是差不多的错误，小米可以，魅族就报错

**Comment by lomanyong** [comment]
@sivan67 @xingyuetianyu 报这个错的话，可以参考 #273 做修改...
