### ISSUE TITLE
app运行失败，java.lang.NoClassDefFoundError按照官网的提示处理没效 

### ISSUE THREAD

**Issue by ZhongXiaoHong** [alibaba/freeline#770]
提示信息：
 Process: com.hc.flzx_v02, PID: 18103
                                                                 java.lang.NoClassDefFoundError: com.antfortune.freeline.FreelineCore
                                                                     at com.hc.flzx_v02.global.App.attachBaseContext(App.java:33)
                                                                     at android.app.Application.attach(Application.java:200)
                                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:992)
                                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:976)
                                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:532)
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4586)
                                                                     at android.app.ActivityThread.access$1800(ActivityThread.java:139)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5314)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                                     at dalvik.system.NativeStart.main(Native Method)

请问为什么呢

**Comment by lomanyong** [comment]
@ZhongXiaoHong 请确认是否正确依赖Freeline Runtime，debug包才会生效...

**Comment by ZhongXiaoHong** [comment]
我是按照官网如何接入部分来做的， 也检查过了 ，另外  freeline {
        applicationProxy false
    }这个也有加    还是不行哦

**Comment by ZhongXiaoHong** [comment]
【原因】项目里使用了分包，在maindexlist.txt加入没有found的class
