### ISSUE TITLE
MIUI报错

### ISSUE THREAD

**Issue by helloyingying** [alibaba/freeline#772]
java.lang.RuntimeException: Unable to start receiver com.antfortune.freeline.FreelineReceiver: java.lang.IllegalStateException: java.lang.NoSuchFieldException: No field mAssets in class Landroid/content/res/MiuiResourcesImpl; (declaration of 'android.content.res.MiuiResourcesImpl' appears in /system/framework/framework.jar)
  at android.app.ActivityThread.handleReceiver(ActivityThread.java:3033)
  at android.app.ActivityThread.-wrap18(ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1559)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6114)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
Caused by: java.lang.IllegalStateException: java.lang.NoSuchFieldException: No field mAssets in class Landroid/content/res/MiuiResourcesImpl; (declaration of 'android.content.res.MiuiResourcesImpl' appears in /system/framework/framework.jar)
  at com.antfortune.freeline.resources.MonkeyPatcher.monkeyPatchExistingResources(MonkeyPatcher.java:400)
  at com.antfortune.freeline.gradle.GradleDynamic.applyDynamicRes(GradleDynamic.java:33)
  at com.antfortune.freeline.FreelineCore.applyDynamicRes(FreelineCore.java:335)
  at com.antfortune.freeline.FreelineCore.injectResources(FreelineCore.java:278)
  at com.antfortune.freeline.FreelineCore.saveDynamicResInfo(FreelineCore.java:365)
  at com.antfortune.freeline.FreelineReceiver.saveDynamicResInfo(FreelineReceiver.java:59)
  at com.antfortune.freeline.FreelineReceiver.onReceive(FreelineReceiver.java:40)
  at android.app.ActivityThread.handleReceiver(ActivityThread.java:3026)
  ... 8 more
Caused by: java.lang.NoSuchFieldException: No field mAssets in class Landroid/content/res/MiuiResourcesImpl; (declaration of 'android.content.res.MiuiResourcesImpl' appears in /system/framework/framework.jar)
  at java.lang.Class.getDeclaredField(Native Method)
  at com.antfortune.freeline.resources.MonkeyPatcher.monkeyPatchExistingResources(MonkeyPatcher.java:392)
  ... 15 more

**Comment by lomanyong** [comment]
@helloyingying 应该是部分MIUI的兼容性问题...

**Comment by helloyingying** [comment]
补充下
MIUI版本：MIUI Global 8.2.2.0 
Android版本：7.0

**Comment by zpetter** [comment]
有解决办法吗，不然freeline 无法使用了

**Comment by zpetter** [comment]
小米5  7.0无法使用 更新
