### ISSUE TITLE
编译的时候报错build failed with script: gradlew.bat :app:assembleDebug -P freelineBuild=true --stacktrace

### ISSUE THREAD

**Issue by tx123456** [alibaba/freeline#782]
我这是第一次编译，编译的时候提示adb以停止运行，但是我正常启动app都可以启动，下面这是错误信息，希望有大佬能告诉我该怎么办
 at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: Manifest merger failed with multiple errors, see logs
        at com.android.builder.core.AndroidBuilder.mergeManifestsForApplication(AndroidBuilder.java:582)
        at com.android.build.gradle.tasks.MergeManifests.doFullTaskAction(MergeManifests.java:70)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:82)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more

[ERROR] --------------------------------------------------------
[ERROR] build failed with script: gradlew.bat :app:assembleDebug -P freelineBuild=true --stacktrace
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 5.7s
[DEBUG] Task engine running time: 5.2s
[DEBUG] Total time: 10.8s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@tx123456 上面的编译日志中应该有对你的出错原因给出提示的...
