### ISSUE TITLE
打开app时crash

### ISSUE THREAD

**Issue by j2j2j2j2j2j2** [alibaba/freeline#783]
利用freeline能够编译通过，但是，安装上app后，打开则直接crash。（不用freeline，能够正常运行）
报的错误：
````
04-26 12:23:22.362  9208  9208 E ActivityThread: **Failed to find provider info for com.tencent.mm.coolassist.debugprovider**
ctivityThread: Service com.google.android.location.places.service.PlaceDetectionAsyncService has leaked IntentReceiver amth@b02e0d5 that was originally registered here. Are you missing a call to unregisterReceiver()?
04-26 12:23:53.476  4018  4018 E ActivityThread: android.app.IntentReceiverLeaked: **Service com.google.android.location.places.service.PlaceDetectionAsyncService has leaked IntentReceiver amth@b02e0d5 that was originally registered here. Are you missing a call to unregisterReceiver()?**
04-26 12:23:53.476  4018  4018 E ActivityThread: 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1159)
04-26 12:23:53.476  4018  4018 E ActivityThread: 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:946)
04-26 12:23:53.476  4018  4018 E ActivityThread: 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1302)
04-26 12:23:53.476  4018  4018 E ActivityThread: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1282)
04-26 12:23:53.476  4018  4018 E ActivityThread: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:593)
04-26 12:23:53.476  4018  4018 E ActivityThread: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:593)
04-26 12:23:53.476  4018  4018 E ActivityThread: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:593)
04-26 12:23:53.476  4018  4018 E ActivityThread: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:593)
04-26 12:23:53.476  4018  4018 E ActivityThread: 	at amrb.run(:com.google.android.gms:4414)
04-26 12:23:53.476  4018  4018 E ActivityThread: 	at android.os.Handler.handleCallback(Handler.java:751)
04-26 12:23:53.476  4018  4018 E ActivityThread: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-26 12:23:53.476  4018  4018 E ActivityThread: 	at android.os.Looper.loop(Looper.java:154)
04-26 12:23:53.476  4018  4018 E ActivityThread: 	at android.os.HandlerThread.run(HandlerThread.java:61)
````

**Comment by lomanyong** [comment]
@j2j2j2j2j2j2 能否提供可以复现问题的demo？

**Comment by candledragle** [comment]
同问，我的是多module开发
