### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by magicboylinw** [alibaba/freeline#784]
Gradle 3.3
Groovy:       2.4.7
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Mac OS X 10.12.3 x86_64
python 2.7.10

运行 python ./freeline.py -f 报错：
[INFO] preparing for tasks...
[-][read_project_info_task] failed. in 0.0s
[-][generate_file_stat_task] finished. in 0.0s
[-][gradle_clean_build_task] failed. in 0s
[-][clean_all_cache_task] failed. in 0s
[-][install_apk_task] failed. in 0s
[-][build_base_resource_task] failed. in 0s
[-][generate_project_info_task] failed. in 0s
[-][generate_apt_files_task] failed. in 0s
[-][append_file_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "/Users/linwei/repo/appso-android/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/Users/linwei/repo/appso-android/freeline/freeline_core/gradle_clean_build.py", line 74, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "/Users/linwei/repo/appso-android/freeline/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by magicboylinw** [comment]
解决了
`OSError: [Errno 2] No such file or directory` 指的是没有找到 gradlew 脚本，有的项目就没有生产这个脚本，作者可以给这个加上更加明确的提示，到底是确实了哪个文件
`gradle wrapper`
生产 wrapper 脚本
