### ISSUE TITLE
ImportError: No module named 'build_commands'

### ISSUE THREAD

**Issue by zeshaoaaa** [alibaba/freeline#79]
Traceback (most recent call last):
  File "freeline.py", line 5, in <module>
    from freeline_core.dispatcher import Dispatcher
  File "/Users/mac/Documents/projects/CloudPos/freeline_core/__init__.py", line 1, in <module>
    import build_commands
ImportError: No module named 'build_commands'

------------------------

请问怎么解决这个问题？是在OS X的AS上报出的

**Comment by lomanyong** [comment]
@zeshaoaaa python版本应该不对，freeline目前只支持Python 2.7+的，不支持Python 3+
