### ISSUE TITLE
databinding 错误

### ISSUE THREAD

**Issue by njleonzhang** [alibaba/freeline#806]
```
process databinding error: Source '/Users/leon/Documents/smartCommunity/android-new/app/src/main/res/res-family/area' exists but is a directory

java.io.IOException: Source '/Users/leon/Documents/smartCommunity/android-new/app/src/main/res/res-family/area' exists but is a directory
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1077)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
        at android.databinding.tool.LayoutXmlProcessor$1.processOtherFile(LayoutXmlProcessor.java:172)
        at android.databinding.tool.LayoutXmlProcessor.processAllInputFiles(LayoutXmlProcessor.java:126)
        at android.databinding.tool.LayoutXmlProcessor.processResources(LayoutXmlProcessor.java:219)
        at com.antfortune.freeline.databinding.ProcessLayouts.run(ProcessLayouts.java:23)
        at com.antfortune.freeline.databinding.CliMain.main(CliMain.java:113)

[ERROR] --------------------------------------------------------
[ERROR] process module databinding failed: java -jar freeline/release-tools/databinding-cli8.jar -p com.zywulian.smartlife -i /Users/leon/Documents/smartCommunity/android-new/app/src/main/res -o /Users/leon/Documents/smartCommunity/android-new/app/build/freeline/freeline-databinding/app/9f865755bc03a404d76470fc3b69a697/res -d /Users/leon/Documents/smartCommunity/android-new/app/build/freeline/freeline-databinding/merged_layoutinfo -c /Users/leon/Documents/smartCommunity/android-new/app/build/freeline/freeline-databinding/app/9f865755bc03a404d76470fc3b69a697/java -l false -v 15 -s /Users/leon/Library/Android/sdk
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 155.2s
[DEBUG] Total time: 155.3s
[DEBUG] --------------------------------------------------------
```

**Comment by lomanyong** [comment]
@njleonzhang databinding的支持暂时delay了...
