### ISSUE TITLE
MAC Python2.7 无法获取相关权限 你们是怎么处理这个问题的

### ISSUE THREAD

**Issue by daiwenbo88** [alibaba/freeline#812]
Traceback (most recent call last):
  File "/Users/daiwenbo/Desktop/moshiproject/MyApplication2/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/Users/daiwenbo/Desktop/moshiproject/MyApplication2/freeline/freeline_core/gradle_clean_build.py", line 74, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "/Users/daiwenbo/Desktop/moshiproject/MyApplication2/freeline/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.0s

**Comment by lomanyong** [comment]
@daiwenbo88 chmod +x

把python文件赋予权限即可

**Comment by XinyuSimov** [comment]
chmod +x ./gradlew
