### ISSUE TITLE
使用plugin安装的jdk1.7，gradle3.3

### ISSUE THREAD

**Issue by lanaiver** [alibaba/freeline#825]
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:215)
        at java.util.zip.ZipFile.<init>(ZipFile.java:145)
        at java.util.zip.ZipFile.<init>(ZipFile.java:159)
        at org.gradle.wrapper.Install.unzip(Install.java:214)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

[ERROR] --------------------------------------------------------
[ERROR] freeline failed when read project info with script: gradlew.bat -q checkBeforeCleanBuild
[ERROR] --------------------------------------------------------

**Comment by lomanyong** [comment]
@lanaiver 这个看着是你本地的gradle环境导致的问题...可以搜索已有的issue
