### ISSUE TITLE
what this?

### ISSUE THREAD

**Issue by 110117ab** [alibaba/freeline#831]
Caused by: java.io.FileNotFoundException: D:\work\code\Android\EmployeHome\DEP_1.53.72_2017_05_11\app\src\main\java\com\antfortune\freeline\FreelineApplication.java (系统找不到指定的路径。)
        at com.tencent.bugly.build.gradle.tasks.TinkerSupportManifestTask.updateManifest(TinkerSupportManifestTask.groovy:51)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)

**Comment by lomanyong** [comment]
@110117ab 暂时先关闭tinker的集成，这是bugly的报错
