### ISSUE TITLE
集成freeline后执行python freeline.py异常

### ISSUE THREAD

**Issue by dandan9628** [alibaba/freeline#863]
执行python freeline.py时出先以下内容
Traceback (most recent call last):
  File "freeline.py", line 7, in <module>
    from freeline_core.dispatcher import Dispatcher
  File "C:\Users\sunliang\Desktop\AndroidAssistiveTouch-master\freeline_core\__init__.py", line 1, in <module>
    import build_commands
ImportError: No module named 'build_commands'

**Comment by 17050097616** [comment]
用python2.7解决
