### ISSUE TITLE
 unexpected exception within task

### ISSUE THREAD

**Issue by Cuieney** [alibaba/freeline#872]
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cuieneydemacbook/Desktop/sljr/IntelligentSecretary/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/Users/cuieneydemacbook/Desktop/sljr/IntelligentSecretary/freeline/freeline_core/gradle_clean_build.py", line 74, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "/Users/cuieneydemacbook/Desktop/sljr/IntelligentSecretary/freeline/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

**Comment by life2015** [comment]
OSError: [Errno 13] Permission denied
Log写的很清楚了 是权限问题
可能是你的Python环境配置问题 
或者试下chomd 777 freeline.py
