### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Structural change of com.example.freeline_exception.Parent is hazardous (/data/app/com.example.freeline_exception-1/oat/x86/base.odex at compile time, /data/user/0/com.example.freeline_exception/cache/temp/opt/86a1cac5b4192c5f3d21af84ded67e3e/merged.dex at runtime): Virtual method count off: 2 vs 3

### ISSUE THREAD

**Issue by tongyapeng** [alibaba/freeline#879]
android 5.1.0、6.0.0、 7.1.0 能稳定重现(art下)，弄了一个工程能重现的这个问题

[测试工程](https://pan.baidu.com/s/1jH5AUhC)

首先在master分支使用freeline全量打包，然后切换到error分支执行补丁打包，运行期oat时报错,apk中Parent.class中有两个public方法，补丁中的Parent.class有三个public方法
我试了如果把补丁dex按照classesN.dex的标准排好，在打包成apk经过安装时是没问题的(补丁dex和原有的classes.dex一起做oat)

```
09-01 01:46:58.666 19227-19227/? I/art: Late-enabling -Xcheck:jni
09-01 01:46:58.751 19227-19227/com.example.freeline_exception W/System: ClassLoader referenced unknown path: /data/app/com.example.freeline_exception-1/lib/x86
09-01 01:46:58.766 19227-19227/com.example.freeline_exception D/FreelineApplication: FreelineApplication#onCreate()
09-01 01:46:58.766 19227-19227/com.example.freeline_exception D/FreelineApplication: create empty application.
09-01 01:46:58.767 19227-19227/com.example.freeline_exception I/Freeline: freeline start initial process...
09-01 01:46:58.768 19227-19227/com.example.freeline_exception I/Freeline: freeline init application
09-01 01:46:58.782 19227-19227/com.example.freeline_exception I/Freeline: start to inject dex...
09-01 01:46:58.792 19227-19227/com.example.freeline_exception I/Freeline.hackDex: /data/user/0/com.example.freeline_exception/cache/temp/dex/merged.apk dex length: 86328
09-01 01:46:58.800 19227-19227/com.example.freeline_exception I/Freeline.hackDex: /data/user/0/com.example.freeline_exception/cache/temp/opt/86a1cac5b4192c5f3d21af84ded67e3e opt length: 4096
09-01 01:46:59.170 19227-19227/com.example.freeline_exception I/Freeline.hackDex: after opt, dex len:86328; opt len:4096
09-01 01:46:59.170 19227-19227/com.example.freeline_exception I/Freeline: find increment package
09-01 01:46:59.170 19227-19227/com.example.freeline_exception I/Freeline: start to inject resources...
09-01 01:46:59.170 19227-19227/com.example.freeline_exception I/Freeline: dynamicInfoSp: {dynamicTime=1504244817602, dynamic_dex_dir_key=/data/user/0/com.example.freeline_exception/cache/temp/dex, dynamic_opt_key=/data/user/0/com.example.freeline_exception/cache/temp/opt}
09-01 01:46:59.170 19227-19227/com.example.freeline_exception I/Freeline: resMap: {}
09-01 01:46:59.171 19227-19227/com.example.freeline_exception I/Freeline: start to load hackload.dex...
09-01 01:46:59.171 19227-19227/com.example.freeline_exception I/Freeline.hackDex: /data/user/0/com.example.freeline_exception/cache/hack/hackload.dex dex length: 848
09-01 01:46:59.171 19227-19227/com.example.freeline_exception I/Freeline.hackDex: /data/user/0/com.example.freeline_exception/cache/hack/opt opt length: 4096
09-01 01:46:59.180 19227-19227/com.example.freeline_exception I/Freeline.hackDex: after opt, dex len:848; opt len:4096
09-01 01:46:59.180 19227-19227/com.example.freeline_exception I/Freeline: load hackload，dex size:848
09-01 01:46:59.180 19227-19227/com.example.freeline_exception I/Freeline: start to inject native lib...
09-01 01:46:59.181 19227-19227/com.example.freeline_exception I/Freeline.hackNative: native lib inject process start...
09-01 01:46:59.183 19227-19227/com.example.freeline_exception W/System: ClassLoader referenced unknown path:
09-01 01:46:59.184 19227-19227/com.example.freeline_exception I/Freeline.hackNative: inject native lib success [Ldalvik.system.DexPathList$Element;@f4c6f89
09-01 01:46:59.184 19227-19227/com.example.freeline_exception I/Freeline: freeline init server
09-01 01:46:59.190 19227-19227/com.example.freeline_exception D/FreelineApplication: realApplication#attach(Context)
09-01 01:46:59.191 19227-19227/com.example.freeline_exception D/FreelineApplication: realApplication#onCreate()
09-01 01:46:59.194 19227-19227/com.example.freeline_exception W/art: Incompatible structural change detected: Structural change of com.example.freeline_exception.Parent is hazardous (/data/app/com.example.freeline_exception-1/oat/x86/base.odex at compile time, /data/user/0/com.example.freeline_exception/cache/temp/opt/86a1cac5b4192c5f3d21af84ded67e3e/merged.dex at runtime): Virtual method count off: 2 vs 3
09-01 01:46:59.194 19227-19227/com.example.freeline_exception W/art: Lcom/example/freeline_exception/Parent; (Compile time):
09-01 01:46:59.194 19227-19227/com.example.freeline_exception W/art:  Static fields:
09-01 01:46:59.194 19227-19227/com.example.freeline_exception W/art:  Instance fields:
09-01 01:46:59.194 19227-19227/com.example.freeline_exception W/art:  Direct methods:
09-01 01:46:59.195 19227-19227/com.example.freeline_exception W/art:   <init>()V
09-01 01:46:59.195 19227-19227/com.example.freeline_exception W/art:  Virtual methods:
09-01 01:46:59.195 19227-19227/com.example.freeline_exception W/art:   aa()V
09-01 01:46:59.195 19227-19227/com.example.freeline_exception W/art:   bb()V
09-01 01:46:59.195 19227-19227/com.example.freeline_exception W/art: Lcom/example/freeline_exception/Parent; (Runtime):
09-01 01:46:59.195 19227-19227/com.example.freeline_exception W/art:  Static fields:
09-01 01:46:59.195 19227-19227/com.example.freeline_exception W/art:  Instance fields:
09-01 01:46:59.195 19227-19227/com.example.freeline_exception W/art:  Direct methods:
09-01 01:46:59.195 19227-19227/com.example.freeline_exception W/art:   <init>()V
09-01 01:46:59.195 19227-19227/com.example.freeline_exception W/art:  Virtual methods:
09-01 01:46:59.195 19227-19227/com.example.freeline_exception W/art:   aa()V
09-01 01:46:59.195 19227-19227/com.example.freeline_exception W/art:   bb()V
09-01 01:46:59.195 19227-19227/com.example.freeline_exception W/art:   cc()V
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art: Rejecting re-init on previously-failed class java.lang.Class<com.example.freeline_exception.Child>: java.lang.IncompatibleClassChangeError: Structural change of com.example.freeline_exception.Parent is hazardous (/data/app/com.example.freeline_exception-1/oat/x86/base.odex at compile time, /data/user/0/com.example.freeline_exception/cache/temp/opt/86a1cac5b4192c5f3d21af84ded67e3e/merged.dex at runtime): Virtual method count off: 2 vs 3
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art: Lcom/example/freeline_exception/Parent; (Compile time):
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:  Static fields:
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:  Instance fields:
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:  Direct methods:
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:   <init>()V
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:  Virtual methods:
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:   aa()V
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:   bb()V
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art: Lcom/example/freeline_exception/Parent; (Runtime):
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:  Static fields:
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:  Instance fields:
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:  Direct methods:
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:   <init>()V
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:  Virtual methods:
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:   aa()V
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:   bb()V
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:   cc()V
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:  (declaration of 'com.example.freeline_exception.Child' appears in /data/app/com.example.freeline_exception-1/base.apk)
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:     at java.lang.Object java.lang.Class.newInstance!() (Class.java:-2)
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:     at android.app.Activity android.app.Instrumentation.newActivity(java.lang.ClassLoader, java.lang.String, android.content.Intent) (Instrumentation.java:1078)
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2557)
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2726)
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1477)
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:     at void android.os.Looper.loop() (Looper.java:154)
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6119)
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:886)
09-01 01:46:59.195 19227-19227/com.example.freeline_exception I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:776)
09-01 01:46:59.221 19227-19227/com.example.freeline_exception W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-01 01:46:59.354 19227-19227/com.example.freeline_exception I/art: Rejecting re-init on previously-failed class java.lang.Class<com.example.freeline_exception.Child>: java.lang.IncompatibleClassChangeError: Structural change of com.example.freeline_exception.Parent is hazardous (/data/app/com.example.freeline_exception-1/oat/x86/base.odex at compile time, /data/user/0/com.example.freeline_exception/cache/temp/opt/86a1cac5b4192c5f3d21af84ded67e3e/merged.dex at runtime): Virtual method count off: 2 vs 3
09-01 01:46:59.357 19227-19227/com.example.freeline_exception I/art: Lcom/example/freeline_exception/Parent; (Compile time):
09-01 01:46:59.357 19227-19227/com.example.freeline_exception I/art:  Static fields:
09-01 01:46:59.357 19227-19227/com.example.freeline_exception I/art:  Instance fields:
09-01 01:46:59.357 19227-19227/com.example.freeline_exception I/art:  Direct methods:
09-01 01:46:59.357 19227-19227/com.example.freeline_exception I/art:   <init>()V
09-01 01:46:59.357 19227-19227/com.example.freeline_exception I/art:  Virtual methods:
09-01 01:46:59.357 19227-19227/com.example.freeline_exception I/art:   aa()V
09-01 01:46:59.357 19227-19227/com.example.freeline_exception I/art:   bb()V
09-01 01:46:59.359 19227-19227/com.example.freeline_exception I/art: Lcom/example/freeline_exception/Parent; (Runtime):
09-01 01:46:59.361 19227-19227/com.example.freeline_exception I/art:  Static fields:
09-01 01:46:59.361 19227-19227/com.example.freeline_exception I/art:  Instance fields:
09-01 01:46:59.361 19227-19227/com.example.freeline_exception I/art:  Direct methods:
09-01 01:46:59.361 19227-19227/com.example.freeline_exception I/art:   <init>()V
09-01 01:46:59.361 19227-19227/com.example.freeline_exception I/art:  Virtual methods:
09-01 01:46:59.361 19227-19227/com.example.freeline_exception I/art:   aa()V
09-01 01:46:59.361 19227-19227/com.example.freeline_exception I/art:   bb()V
09-01 01:46:59.361 19227-19227/com.example.freeline_exception I/art:   cc()V
09-01 01:46:59.361 19227-19227/com.example.freeline_exception I/art:  (declaration of 'com.example.freeline_exception.Child' appears in /data/app/com.example.freeline_exception-1/base.apk)
09-01 01:46:59.361 19227-19227/com.example.freeline_exception I/art:     at java.lang.Object java.lang.Class.newInstance!() (Class.java:-2)
09-01 01:46:59.361 19227-19227/com.example.freeline_exception I/art:     at android.app.Activity android.app.Instrumentation.newActivity(java.lang.ClassLoader, java.lang.String, android.content.Intent) (Instrumentation.java:1078)
09-01 01:46:59.361 19227-19227/com.example.freeline_exception I/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2557)
09-01 01:46:59.361 19227-19227/com.example.freeline_exception I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2726)
09-01 01:46:59.361 19227-19227/com.example.freeline_exception I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
09-01 01:46:59.361 19227-19227/com.example.freeline_exception I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1477)
09-01 01:46:59.361 19227-19227/com.example.freeline_exception I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
09-01 01:46:59.361 19227-19227/com.example.freeline_exception I/art:     at void android.os.Looper.loop() (Looper.java:154)
09-01 01:46:59.361 19227-19227/com.example.freeline_exception I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6119)
09-01 01:46:59.361 19227-19227/com.example.freeline_exception I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
09-01 01:46:59.361 19227-19227/com.example.freeline_exception I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:886)
09-01 01:46:59.361 19227-19227/com.example.freeline_exception I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:776)
09-01 01:46:59.363 19227-19227/com.example.freeline_exception D/AndroidRuntime: Shutting down VM
09-01 01:46:59.363 19227-19227/com.example.freeline_exception E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.example.freeline_exception, PID: 19227
                                                                                java.lang.IncompatibleClassChangeError: Structural change of com.example.freeline_exception.Parent is hazardous (/data/app/com.example.freeline_exception-1/oat/x86/base.odex at compile time, /data/user/0/com.example.freeline_exception/cache/temp/opt/86a1cac5b4192c5f3d21af84ded67e3e/merged.dex at runtime): Virtual method count off: 2 vs 3
                                                                                Lcom/example/freeline_exception/Parent; (Compile time):
                                                                                 Static fields:
                                                                                 Instance fields:
                                                                                 Direct methods:
                                                                                  <init>()V
                                                                                 Virtual methods:
                                                                                  aa()V
                                                                                  bb()V
                                                                                Lcom/example/freeline_exception/Parent; (Runtime):
                                                                                 Static fields:
                                                                                 Instance fields:
                                                                                 Direct methods:
                                                                                  <init>()V
                                                                                 Virtual methods:
                                                                                  aa()V
                                                                                  bb()V
                                                                                  cc()V
                                                                                 (declaration of 'com.example.freeline_exception.Child' appears in /data/app/com.example.freeline_exception-1/base.apk)
                                                                                    at java.lang.Class.newInstance(Native Method)
                                                                                    at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2557)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                                    at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by lijunhuawhu** [comment]
我也遇到了同样的问题
