### ISSUE TITLE
执行命令 gradlew.bat initFreeline -Pmirror 就报错了 

### ISSUE THREAD

**Issue by blackmamba123** [alibaba/freeline#88]
E:\project_soulution\trunk>gradlew.bat initFreeline -Pmirror
Parallel execution is an incubating feature.
find variant debug start hack process...                                                                      
variant release is not debug, skip hack process.
:initFreeline                
Freeline init process start...
[NOTE] Download freeline dependency from mirror...
Downloading lastest release from http://obr0ndq7a.bkt.clouddn.com/freeline/freeline-v0.6.0.zip
Please wait a minute...      
      [get] Getting: http://obr0ndq7a.bkt.clouddn.com/freeline/freeline-v0.6.0.zip
      [get] To: E:\project_soulution\trunk\freeline.zip.tmp
download success.            
:initFreeline FAILED         
               
FAILURE: Build failed with an exception.
               
* What went wrong:
Execution failed for task ':initFreeline'.
> org/apache/commons/io/FileUtils
               
* Try:         
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
               
BUILD FAILED   
               
Total time: 10.401 secs

**Comment by blackmamba123** [comment]
Execution failed for task ':initFreeline'.
> org/apache/commons/io/FileUtils
               
* Try:         
Run with --info or --debug option to get more log output.
               
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':initFreeline'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
        at com.antfortune.freeline.FreelineInitializer.initFreeline(FreelineInitializer.groovy:60)
        at com.antfortune.freeline.FreelineInitializer$initFreeline.call(Unknown Source)
        at com.antfortune.freeline.FreelinePlugin$_apply_closure1.doCall(FreelinePlugin.groovy:28)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more
               
               
BUILD FAILED

**Comment by lomanyong** [comment]
@blackmamba123 今晚给你一个小版本切换看看，0.6.0在编译上传时出了点问题导致了这个问题。

**Comment by lomanyong** [comment]
@blackmamba123  `classpath 'com.antfortune.freeline:gradle:0.6.0.1609052218'`使用这个版本的插件，经过测试已经解决这个问题了。
