### ISSUE TITLE
freeline 0.8.8版本不支持gradle3.0.0

### ISSUE THREAD

**Issue by leecx** [alibaba/freeline#916]
最近随着Android Studio3.0版本的正式发布，gradle 3.0.0版本也正式发布了。升级后，发现freeline不支持，很多在用的api在gradle3.0.0版本中都已经停用了或者改名字了。请问freeline什么时候支持到gradle3.0.0？

**Comment by leecx** [comment]
StackTrace: 
-> Caused by: java.lang.IllegalStateException: Resolving configuration 'annotationProcessor' directly is not allowed
-> 追查Freeline源码部分
-> 
  at com.antfortune.freeline.FreelinePlugin.findAptConfig(FreelinePlugin.groovy:644)
	at com.antfortune.freeline.FreelinePlugin$_apply_closure4$_closure13$_closure19.doCall(FreelinePlugin.groovy:176)
	at com.antfortune.freeline.FreelinePlugin$_apply_closure4$_closure13.doCall(FreelinePlugin.groovy:156)
	at com.antfortune.freeline.FreelinePlugin$_apply_closure4.doCall(FreelinePlugin.groovy:51)

**Comment by dhhAndroid** [comment]
@leecx 在项目的gradle.properties文件中加入 android.enableAapt2=false，就可以解决这个问题

**Comment by 471448446** [comment]
同问
