### ISSUE TITLE
run freeline error on windows

### ISSUE THREAD

**Issue by wlwenming** [alibaba/freeline#944]
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=False, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.3.3
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.8
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.8
[DEBUG] collecting project info, please wait a while...
[DEBUG] final apk not found, need a clean build.
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: F:\66xue-leci-android\app\build\freeline\freeline-assets\apktime
[DEBUG] new clean build flag value: 699000
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save app module file stat
[DEBUG] [read_project_info_task] read_project_info_task finish in 0.0s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 0.0s
[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 0.0s
[DEBUG] [install_apk_task] install_apk_task start to run after waiting 0.0s
[DEBUG] [generate_apt_files_task] generate_apt_files_task start to run after waiting 0.0s
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after waiting 0.0s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run after waiting 0.0s
[DEBUG] [append_file_stat_task] append_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.6s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 0.58s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "F:\66xue-leci-android\freeline_core\task.py", line 123, in execute
    self.task.execute()
  File "F:\66xue-leci-android\freeline_core\gradle_clean_build.py", line 74, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "F:\66xue-leci-android\freeline_core\utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "E:\Python27\lib\subprocess.py", line 672, in __init__
    errread, errwrite)
  File "E:\Python27\lib\subprocess.py", line 882, in _execute_child
    startupinfo)
WindowsError: [Error 2]

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 0.6s
[DEBUG] Total time: 0.8s
[DEBUG] --------------------------------------------------------

**Comment by wlwenming** [comment]
@zhuzhaoyuan @JacksonTian 帮忙看一下什么原因？非常感谢

**Comment by jessehev** [comment]
0.8.8版本遇到同样的问题，都没有人解决下吗
