### ISSUE TITLE
通过插件安装freeline出现AssertionError，导致无法正常使用。

### ISSUE THREAD

**Issue by Larrysea** [alibaba/freeline#962]
安装插件以后，点击Install freeline 出现插件错误。
错误具体信息如下：null
java.lang.AssertionError
	at org.xmlpull.v1.XmlPullParserFactory.<init>(XmlPullParserFactory.java:43)
	at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:221)
	at com.antfortune.freeline.idea.models.GradleDependencyEntity.parse(GradleDependencyEntity.java:79)
	at com.antfortune.freeline.idea.actions.UpdateAction$GetServerVersion.run(UpdateAction.java:189)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by JSnail** [comment]
同样遇到这个问题

**Comment by Jinni6012** [comment]
也遇到了同样的问题，请问有解决方案吗？

**Comment by ApolloXiao** [comment]
@Larrysea 怎么解决的呢

**Comment by Larrysea** [comment]
@ApolloXiao 并没有解决，已经放弃治疗了。

**Comment by ApolloXiao** [comment]
@Larrysea  好吧
