### ISSUE TITLE
 unexpected exception within task!

### ISSUE THREAD

**Issue by chanlk** [alibaba/freeline#970]
按照官方流程走，到最后一步的时候出现如下问题：
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "D:\ex\freeline_core\task.py", line 123, in execute
    self.task.execute()
  File "D:\ex\freeline_core\gradle_tools.py", line 233, in execute
    self._fill_cache_map(all_modules)
  File "D:\ex\freeline_core\gradle_tools.py", line 247, in _fill_cache_map
    md5 = get_md5(settings_path)
  File "D:\ex\freeline_core\utils.py", line 84, in get_md5
    target_file = open(fpath, 'rb')
IOError: [Errno 2] No such file or directory: 'D:\\ex\\settings.gradle'

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task

项目中没有settings.gradle文件，刚转到andriod开发，并不了解gradle这个构建工具，组里给我的app就是没有settings.gradle文件的，请问该如何解决？谢谢您！另外用的是windows系统的

**Comment by chanlk** [comment]
已解决
直接添加一个settings.gradle文件即可！
