### ISSUE TITLE
Android Studio3.1上freeline插件不能使用

### ISSUE THREAD

**Issue by devzld** [alibaba/freeline#972]
Android Studio3.1上freeline插件不能使用了

com/android/tools/idea/gradle/dsl/model/GradleBuildModel
java.lang.NoClassDefFoundError: com/android/tools/idea/gradle/dsl/model/GradleBuildModel
	at com.antfortune.freeline.idea.utils.FreelineUtil.getFreelineStatus(FreelineUtil.java:153)
	at com.antfortune.freeline.idea.utils.FreelineUtil.checkInstall(FreelineUtil.java:204)
	at com.antfortune.freeline.idea.actions.FreelineRunAction.actionPerformed(FreelineRunAction.java:26)
	at com.antfortune.freeline.idea.actions.BaseAction.actionPerformed(BaseAction.java:32)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:195)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:153)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:346)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:646)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.android.tools.idea.gradle.dsl.model.GradleBuildModel PluginClassLoader[com.apkfuns.plugin.freeline, 1.1.4] com.intellij.ide.plugins.cl.PluginClassLoader@373828fc
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more

**Comment by devzld** [comment]
com/android/tools/idea/gradle/dsl/model/GradleBuildModel
java.lang.NoClassDefFoundError: com/android/tools/idea/gradle/dsl/model/GradleBuildModel
	at com.antfortune.freeline.idea.utils.FreelineUtil.getFreelineStatus(FreelineUtil.java:153)
	at com.antfortune.freeline.idea.utils.FreelineUtil.checkInstall(FreelineUtil.java:204)
	at com.antfortune.freeline.idea.actions.FreelineRunAction.actionPerformed(FreelineRunAction.java:26)
	at com.antfortune.freeline.idea.actions.BaseAction.actionPerformed(BaseAction.java:32)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:195)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:153)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:346)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:646)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.android.tools.idea.gradle.dsl.model.GradleBuildModel PluginClassLoader[com.apkfuns.plugin.freeline, 1.1.4] com.intellij.ide.plugins.cl.PluginClassLoader@373828fc
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more

**Comment by tanranran** [comment]
+1

**Comment by oneapp1e** [comment]
+1

**Comment by biyeshengplay** [comment]
+1

**Comment by pencilso** [comment]
+10086

**Comment by bingxuebage** [comment]
+1024

**Comment by zhuxiaohao** [comment]
作者老不跟新,可 Android studio 老更新啊.大兄弟你不要拖更呀.

**Comment by wuhaiyang** [comment]
+1

**Comment by breakingsword** [comment]
+1

**Comment by songzhixiang** [comment]
+1

**Comment by aprz512** [comment]
+1

**Comment by huanbin** [comment]
+1

**Comment by zhuanghm** [comment]
+1

**Comment by liuxuesong001** [comment]
+1

**Comment by jxnc12yangb** [comment]
++1

**Comment by honglei92** [comment]
+10086

**Comment by wangyuan0217** [comment]
+65536
