### ISSUE TITLE
ImportError: No module named _curses

### ISSUE THREAD

**Issue by huliBruce** [alibaba/freeline#974]
Traceback (most recent call last):
  File "freeline.py", line 50, in <module>
    main()
  File "freeline.py", line 45, in main
    freeline = Freeline()
  File "freeline.py", line 13, in __init__
    self.dispatcher = Dispatcher()
  File "/Users/Documents/work/test/freeline/freeline_core/dispatcher.py", line 24, in __init__
    self._logger = Logger()
  File "/Users/Documents/work/test/freeline/freeline_core/logger.py", line 61, in __init__
    from cursor import Cursor
  File "/Users/Documents/work/test/freeline/freeline_core/cursor.py", line 3, in <module>
    from terminal import Terminal
  File "/Users/Documents/work/test/freeline/freeline_core/terminal.py", line 5, in <module>
    import curses
  File "/Users/Documents/work/android-tools-arm12b/lib/python2.7/curses/__init__.py", line 15, in <module>
    from _curses import *
ImportError: No module named _curses

**Comment by Yiny123** [comment]
this is because u r using the python 3.0+
use python 2.7 can solve
