### ISSUE TITLE
执行python freeline.py -h命令时，报错

### ISSUE THREAD

**Issue by Tobi1025** [alibaba/freeline#976]
Traceback (most recent call last):
File "freeline.py", line 7, in 
from freeline_core.dispatcher import Dispatcher
File "/Users/qiaojingfei/Desktop/\u5bb6\u653fapp/jz_app_android/freeline/freeline_core/init.py", line 1, in 
import build_commands
ModuleNotFoundError: No module named 'build_commands'

**Comment by dede1314** [comment]
这个应该是缺少文件。
