### ISSUE TITLE
build failed with script: gradlew.bat :app:assembleDebug -P freelineBuild=true --stacktrace

### ISSUE THREAD

**Issue by guozhiqiang123** [alibaba/freeline#984]
build failed with script: gradlew.bat :app:assembleDebug -P freelineBuild=true --stacktrace
build failed with script: gradlew.bat :app:assembleDebug -P freelineBuild=true --stacktrace
build failed with script: gradlew.bat :app:assembleDebug -P freelineBuild=true --stacktrace
报这个错误 导致编译不通过怎么办？

**Comment by june5753** [comment]
同问，等求解。
复现步骤：
根据提示先安装freeline环境
1.配置项目根目录的 build.gradle，加入 freeline-gradle 的依赖：

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.antfortune.freeline:gradle:0.8.8'
    }
}
2.然后在主 module 的 build.gradle 中，应用 freeline 插件的依赖：

apply plugin: 'com.antfortune.freeline'
android {
    ...
}
3.在命令行执行以下命令来下载 freeline 的 python 和二进制依赖。

Windows: gradlew initFreeline
这一步能成功
之后执行：python freeline.py -f
出现同样的错误，详情日志如下：
caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: AAPT2 error: check logs for details
        at com.android.builder.png.AaptProcess$NotifierProcessOutput.handleOutput(AaptProcess.java:443)
        at com.android.builder.png.AaptProcess$NotifierProcessOutput.err(AaptProcess.java:395)
        at com.android.builder.png.AaptProcess$ProcessOutputFacade.err(AaptProcess.java:312)
        at com.android.utils.GrabProcessOutput$1.run(GrabProcessOutput.java:104)


* Get more help at https://help.gradle.org

[ERROR] --------------------------------------------------------
[ERROR] build failed with script: gradlew.bat :app:assembleDebug -P freelineBuild=true --stacktrace

**Comment by weihuawei** [comment]
设置android.enableAapt2=false 就行了

**Comment by dede1314** [comment]
上面的错误是gradlew.bat :app:assembleDebug 编译不过的问题，freeline是使用这个命令来进行编译的。
如果gradlew.bat :app:assembleDebug 能正常运行，freeline就不会有问题
