### ISSUE TITLE
NoClassDefFoundError: com/android/tools/idea/gradle/dsl/model/GradleBuildModel

### ISSUE THREAD

**Issue by zomll** [alibaba/freeline#992]
大佬们，可知道这是咋了？

at com.antfortune.freeline.idea.utils.FreelineUtil.getFreelineStatus(FreelineUtil.java:153)
	at com.antfortune.freeline.idea.utils.FreelineUtil.checkInstall(FreelineUtil.java:204)
	at com.antfortune.freeline.idea.actions.FreelineRunAction.actionPerformed(FreelineRunAction.java:26)
	at com.antfortune.freeline.idea.actions.BaseAction.actionPerformed(BaseAction.java:32)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:195)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:153)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:346)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)

**Comment by siberiawolf89** [comment]
同样的问题，，请问楼主解决了么

**Comment by weihuawei** [comment]
同问，求解答

**Comment by MrRoshan** [comment]
#985

**Comment by honglei92** [comment]
同问 求解答
